import {test,expect,type Page} from '@playwright/test';
const user={id:'00000000-0000-4000-8000-000000000001',email:'ar@katathani.com',email_confirmed_at:'2026-09-01T00:00:00Z',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-01T00:00:00Z'};
async function setup(page:Page,{signedIn=false,error=false}={}){
 const calls:{path:string;method:string;body:Record<string,unknown>|null}[]=[];
 if(signedIn)await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic',refresh_token:'synthetic-refresh',expires_at:Math.floor(Date.now()/1000)+86400,token_type:'bearer',user:u})),user);
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;calls.push({path,method:route.request().method(),body:null});if(path==='/api/config')return route.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic',googleEnabled:true}});return route.fulfill({status:501,json:{error:'Unexpected data request during recovery'}});});
 await page.route('https://example.supabase.co/**',route=>{const req=route.request(),url=new URL(req.url());calls.push({path:url.pathname+url.search,method:req.method(),body:req.postData()?req.postDataJSON():null});if(error)return route.fulfill({status:429,json:{error_code:'over_email_send_rate_limit',msg:'PRIVATE PROVIDER DETAIL'}});if(url.pathname.endsWith('/token'))return route.fulfill({json:{access_token:'synthetic',refresh_token:'synthetic-refresh',token_type:'bearer',expires_in:3600,user}});if(url.pathname.endsWith('/user'))return route.fulfill({json:user});if(url.pathname.endsWith('/recover'))return route.fulfill({json:{}});return route.fulfill({status:501,json:{error:'Unexpected synthetic auth call'}});});return calls;
}
test('recovery link request uses PKCE and the fixed allowed account, never opens debtor data',async({page})=>{const calls=await setup(page);await page.goto('/?recover=1');await expect(page.getByRole('heading',{name:'Reset your web app password'})).toBeVisible();await expect(page.getByLabel('New web app password',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Send recovery link',exact:true}).click();await expect(page.getByRole('status')).toContainText('Open it in this browser');const sent=calls.find(c=>c.path.includes('/recover?'));expect(sent?.body).toMatchObject({email:'ar@katathani.com',code_challenge_method:'s256'});expect(String(sent?.body?.code_challenge).length).toBeGreaterThan(20);expect(sent?.path).toContain(encodeURIComponent('/?recover=1'));expect(new Set(calls.filter(c=>c.path.startsWith('/api/')).map(c=>c.path))).toEqual(new Set(['/api/config']));});
test('valid recovery session can update only the web password after confirmation',async({page})=>{const calls=await setup(page,{signedIn:true});await page.goto('/?recover=1');await page.getByLabel('New web app password',{exact:true}).fill('Synthetic-recovery-only-123');await page.getByLabel('Confirm new password',{exact:true}).fill('Synthetic-does-not-match');await page.getByRole('button',{name:'Update web app password'}).click();await expect(page.getByRole('alert')).toContainText('do not match');expect(calls.some(c=>c.method==='PUT')).toBe(false);await page.getByLabel('Confirm new password',{exact:true}).fill('Synthetic-recovery-only-123');await page.getByRole('button',{name:'Update web app password'}).click();await expect(page.getByRole('heading',{name:'Password updated',exact:true})).toBeVisible();expect(calls.filter(c=>c.method==='PUT')).toEqual([{path:'/auth/v1/user',method:'PUT',body:{password:'Synthetic-recovery-only-123',code_challenge:null,code_challenge_method:null}}]);await expect(page.getByLabel('New web app password',{exact:true})).toHaveCount(0);expect(new Set(calls.filter(c=>c.path.startsWith('/api/')).map(c=>c.path))).toEqual(new Set(['/api/config']));});
test('provider recovery error is useful and sanitized',async({page})=>{await setup(page,{error:true});await page.goto('/?recover=1');await page.getByRole('button',{name:'Send recovery link',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be requested');await expect(page.locator('body')).not.toContainText('PRIVATE PROVIDER DETAIL');});
test('small-screen login can reach recovery without a request being sent automatically',async({page})=>{await page.setViewportSize({width:390,height:844});const calls=await setup(page);await page.goto('/');await page.getByRole('button',{name:'Forgot web app password?'}).click();await expect(page.getByRole('heading',{name:'Reset your web app password'})).toBeVisible();expect(calls.some(c=>c.method==='POST')).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'evidence/password-recovery-390.png'});});

test('PKCE recovery callback exchanges the one-time code before showing the password form',async({page})=>{const calls=await setup(page);await page.addInitScript(()=>localStorage.setItem('sb-example-auth-token-code-verifier',JSON.stringify('synthetic-verifier/PASSWORD_RECOVERY')));await page.goto('/?recover=1&code=synthetic-recovery-code');await expect(page.getByLabel('New web app password',{exact:true})).toBeVisible();expect(calls.find(c=>c.path.includes('/token?grant_type=pkce'))?.body).toMatchObject({auth_code:'synthetic-recovery-code',code_verifier:'synthetic-verifier'});expect(calls.some(c=>c.method==='PUT')).toBe(false);expect(new Set(calls.filter(c=>c.path.startsWith('/api/')).map(c=>c.path))).toEqual(new Set(['/api/config']));});
