import {test,expect,type Page} from '@playwright/test';
const accountNames=['Azure Travel · Synthetic','Harbor Tours · Synthetic','Coral Travel · Synthetic','Palm Holidays · Synthetic','Bay Travel · Synthetic','Island Agency · Synthetic','Lagoon Travel · Synthetic','North Travel · Synthetic','Review Account · Synthetic'];
function rows(){return accountNames.map((name,index)=>({hotel:index%2?'TSK':'KAT',account_id:String(index+1),id:String(index+100),guest:'Synthetic Guest '+(index+1),invoice_no:'INV-'+(index+1),folio_no:'FOL-'+(index+1),open:[740000,510000,390000,310000,280000,190000,140000,95000,85000][index],transaction_date:'2026-08-01',collection_role:'standalone',collection_selectable:index!==8,verification_state:index===8?'unverified':'verified',account_name:name,account_type:index%2?'Corporate':'OTA',workflow:index===5?null:{revision:0,billing_required:index===0,credit_term:30,first_billing_date:null,last_reminder_stage:[null,'Follow 1','Final','Friendly',null,null,'Follow 2','Follow 3',null][index],last_reminder_date:[null,'2026-09-01','2026-09-09','2026-09-03',null,null,'2026-09-04','2026-09-01',null][index],due_date:index===4?'2026-09-25':index===0?null:'2026-09-09'}}));}
async function setup(page:Page,fail=false){const data=rows(),calls:string[]=[];const user={id:'synthetic-queue-user',email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-09T00:00:00Z'};
 await page.clock.setFixedTime(new Date('2026-09-10T05:00:00Z'));
 await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic-token',refresh_token:'synthetic-refresh',expires_at:Math.floor(Date.now()/1000)+86400,token_type:'bearer',user:u})),user);
 await page.route('https://example.supabase.co/**',r=>r.fulfill({json:{user}}));
 await page.route('**/api/**',async r=>{const q=r.request(),p=new URL(q.url()).pathname;calls.push(q.method()+' '+p);
 if(p==='/api/config')return r.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic'}});
 if(p==='/api/refresh')return r.fulfill({json:{jobs:[],running:false,hotels:[]}});
 if(p==='/api/portfolio')return r.fulfill({json:{status:'connected',accounts:data.map(d=>({id:d.account_id,hotel:d.hotel,name:d.account_name,type:d.account_type,open:d.open,items:1,over90:0})),refresh:{running:false,hotels:[]}}});
 if(p==='/api/collection-queue')return r.fulfill({status:fail?503:200,json:fail?{error:'unavailable'}:{rows:data,asOf:'2026-09-10'}});
 if(p==='/api/mail-reconciliation')return r.fulfill({json:{enabled:true,intervalMinutes:15,waiting:0,needsReview:0,last:{trigger:'scheduled',state:'complete',created_at:'2026-09-10T05:00:00Z',finished_at:'2026-09-10T05:00:02Z',checked:0,verified:0,needs_review:0,unavailable:0}}});
 if(p.startsWith('/api/accounts/'))return r.fulfill({json:{invoices:[]}});
 return r.fulfill({status:501,json:{error:'blocked_unmocked_test_api'}});
 });return calls;
}
for(const width of [1440,1280,390])test(`collection queue ${width}: correct stage labels, filters and scoped selection`,async({page})=>{const calls=await setup(page);await page.setViewportSize({width,height:width===1440?900:width===1280?800:844});await page.goto('/?collections=1');await expect(page.getByRole('heading',{name:'Billing & Collection Queue',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Harbor Tours · Synthetic',exact:true})).toBeVisible();await page.screenshot({path:`evidence/collection-queue-${width}.png`,fullPage:true});
 await page.getByLabel('Queue stage',{exact:true}).selectOption('Follow 2');await expect(page.locator('.queue-work tbody tr')).toHaveCount(1);await expect(page.locator('.queue-work tbody')).toContainText('Follow-up 2');await page.getByRole('button',{name:'Harbor Tours · Synthetic',exact:true}).click();await page.getByLabel('Queue select INV-2',{exact:true}).check();if(width===390)await page.screenshot({path:'evidence/collection-queue-390-drawer.png'});await page.getByRole('button',{name:'Prepare collection documents',exact:true}).click();await expect(page.getByRole('dialog').getByRole('combobox',{name:'Purpose',exact:true})).toHaveValue('collection');await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();if(width===390)await page.getByRole('button',{name:'Close queue details',exact:true}).click();expect(calls.some(c=>c.includes('/send')||c.includes('/gmail-draft')||c==='POST /api/documents')).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('latest sent filter and back navigation preserve queue context',async({page})=>{await setup(page);await page.goto('/?collections=1');await page.getByLabel('Queue latest sent stage',{exact:true}).selectOption('Follow 1');await expect(page.locator('.queue-work tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'Open account details',exact:true}).click();await expect(page.getByRole('heading',{name:'Harbor Tours · Synthetic',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to collections',exact:true}).click();await expect(page.getByLabel('Queue latest sent stage',{exact:true})).toHaveValue('Follow 1');await expect(page.locator('.queue-work tbody tr')).toHaveCount(1);});
test('queue API failure does not become zero work',async({page})=>{await setup(page,true);await page.goto('/?collections=1');await expect(page.getByRole('alert')).toContainText('Collection data is unavailable');await expect(page.locator('.queue-metrics strong').first()).toHaveText('—');await expect(page.getByText('No work matches these filters',{exact:true})).toHaveCount(0);});

test('Collection due card matches its drill-down count and excludes separate Urgent work',async({page})=>{await setup(page);await page.goto('/?collections=1');await page.getByRole('button',{name:/Collection due 3/}).click();await expect(page.locator('.queue-work tbody tr')).toHaveCount(3);await expect(page.locator('.queue-work tbody')).not.toContainText('Urgent');});
