import {test,expect} from '@playwright/test';
import {setupDashboard} from './fixtures/dashboard-period';
test('Dashboard uses an inclusive range and closing-date stock, with current Aging independent',async({page})=>{
 const c=await setupDashboard(page);await page.goto('/?dashboard=1');await expect(page.getByTestId('dashboard-closing-count')).toHaveText('2 invoices');await page.getByLabel('Date selection mode').selectOption('range');await page.getByLabel('From',{exact:true}).fill('2026-09-01');await page.getByLabel('Through',{exact:true}).fill('2026-09-11');await expect(page.getByTestId('dashboard-closing-count')).toHaveText('1 invoices');
 expect(c.calls.some(r=>r.path==='/api/reports/activity'&&r.query.get('from')==='2026-09-01'&&r.query.get('to')==='2026-09-11')).toBe(true);expect(c.calls.some(r=>r.path==='/api/dashboard/balances'&&r.query.get('asOf')==='2026-09-11')).toBe(true);
 await page.getByRole('button',{name:'Current Aging · KAT / TSK',exact:true}).click();await expect(page.getByRole('table',{name:'Current source aging comparison'})).toContainText('Agent');await expect(page.getByLabel('From',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Period analysis',exact:true}).click();await expect(page.getByLabel('From',{exact:true})).toHaveValue('2026-09-01');await expect(page.getByLabel('Through',{exact:true})).toHaveValue('2026-09-11');expect(c.errors).toEqual([]);
});
test('missing historic coverage never displays the current open balance',async({page})=>{await setupDashboard(page);await page.goto('/?dashboard=1&dashboardFrom=2026-08-01&dashboardTo=2026-08-31');await expect(page.getByText('No invoice snapshot was captured for this date.',{exact:false})).toBeVisible();await expect(page.getByTestId('dashboard-closing-count')).toHaveText('— invoices');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('7');});
test('invoice drill has all pages and retains period through Account Detail return',async({page})=>{
 const c=await setupDashboard(page,{large:true});await page.goto('/?dashboard=1&dashboardFrom=2026-09-01&dashboardTo=2026-09-12');await page.getByRole('button',{name:'View invoices',exact:true}).click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail.getByRole('table').locator('tbody tr')).toHaveCount(50);await detail.getByRole('button',{name:'Next',exact:true}).click();await expect(detail.getByRole('table').locator('tbody tr')).toHaveCount(12);await expect(detail).toContainText('SYN-60');await detail.getByRole('button',{name:'Open current account',exact:true}).first().click();await expect(page.locator('.account-page .breadcrumb')).toBeVisible();await page.locator('.account-page .breadcrumb').click();await expect(page.getByLabel('From',{exact:true})).toHaveValue('2026-09-01');await expect(detail).toContainText('Page 2');expect(c.errors).toEqual([]);
});
test('payment source failure remains unknown and source refresh retry keeps command identity',async({page})=>{
 const c=await setupDashboard(page,{failPayments:true,failRefreshOnce:true});await page.goto('/?dashboard=1&hotel=KAT');await expect(page.getByTestId('dashboard-paid-count')).toHaveText('—');await expect(page.getByTestId('dashboard-payment-credits')).toHaveText('—');await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect(page.getByText('The refresh request could not be confirmed.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect.poll(()=>c.calls.filter(r=>r.path==='/api/financial/refresh').length).toBe(2);const posts=c.calls.filter(r=>r.path==='/api/financial/refresh');expect(posts[0].body.commandId).toBe(posts[1].body.commandId);expect(posts[0].body).toMatchObject({from:'2026-09-12',to:'2026-09-12',hotel:'KAT'});
});
test('Reports contains only external billing and retired financial bookmark opens Dashboard detail',async({page})=>{
 await setupDashboard(page);await page.goto('/?reports=1');await expect(page.getByRole('heading',{name:'External billing activity'}).first()).toBeVisible();for(const name of ['Current receivables','Verified sent activity','OPERA financial history','AR history & timing'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
 await page.goto('/?financial=1&dashboardDay=2026-09-11');await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Dashboard invoice details'})).toContainText('OPERA payment records');await expect(page).not.toHaveURL(/financial=1/);
});
test('current Aging reload refreshes catalog and invoice evidence while keeping return context',async({page})=>{
 const c=await setupDashboard(page);await page.goto('/?dashboard=1&dashboardView=aging&dashboardFrom=2026-08-01&dashboardTo=2026-08-31');const table=page.getByRole('table',{name:'Current source aging comparison'});await table.getByRole('button',{name:'Open accounts in Agent',exact:true}).click();await table.getByRole('button',{name:'Azure Travel · Synthetic · KAT · 0–30',exact:true}).click();const invoices=page.getByRole('table',{name:'Current aging invoices'});await expect(invoices).toContainText('INV-kat-parent');const before=c.calls.filter(r=>r.path==='/api/accounts/KAT/kat-azure').length;await page.getByRole('button',{name:'Reload dashboard',exact:true}).click();await expect.poll(()=>c.calls.filter(r=>r.path==='/api/accounts/KAT/kat-azure').length).toBeGreaterThan(before);await expect(invoices).toContainText('INV-kat-parent');await invoices.getByRole('button',{name:'Open invoice INV-kat-parent',exact:true}).click();await page.locator('.account-page .breadcrumb').click();await expect(invoices).toContainText('INV-kat-parent');await expect(page.getByLabel('Invoice hotel')).toHaveValue('KAT');
});
for(const width of [1440,1280,390])test('period Dashboard layout '+width,async({page})=>{const c=await setupDashboard(page);await page.setViewportSize({width,height:width===1440?900:width===1280?800:844});await page.goto('/?dashboard=1&dashboardFrom=2026-09-01&dashboardTo=2026-09-12');await expect(page.getByTestId('dashboard-closing-count')).toHaveText('2 invoices');await expect(page.getByTestId('dashboard-paid-count')).toHaveText('1');expect(await page.locator('.dashboard-page').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await page.screenshot({path:'evidence/dashboard-period-'+width+'.png',fullPage:false,animations:'disabled'});expect(c.errors).toEqual([]);expect(c.unexpected).toEqual([]);});

test('changing global hotel resets the invoice detail page',async({page})=>{const c=await setupDashboard(page,{large:true});await page.goto('/?dashboard=1&dashboardDetail=balance&dashboardMetric=open&dashboardPage=1');const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail).toContainText('Page 2');await page.getByRole('button',{name:'TSK',exact:true}).click();await expect(detail).toContainText('Page 1');await expect(detail).toContainText('INV-tsk-old');expect(c.calls.filter(r=>r.path==='/api/dashboard/balances'&&r.query.get('hotel')==='TSK').every(r=>!r.query.has('page')||r.query.get('page')==='0')).toBe(true);});
test('unobserved invoice evidence and unclassified billing cannot become exact totals',async({page})=>{await setupDashboard(page,{invoiceGap:true,billingUnclassified:true});await page.goto('/?dashboard=1');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('—');await expect(page.getByTestId('dashboard-first-count')).toHaveText('—');await expect(page.getByTestId('dashboard-repeat-count')).toHaveText('—');await expect(page.getByTestId('dashboard-billing-unclassified-count')).toHaveText('1');await expect(page.getByText('Some actual billing sends cannot yet be classified',{exact:false})).toBeVisible();});
test('an unrelated invoice payment-mapping gap does not suppress source invoice entries',async({page})=>{await setupDashboard(page,{invoiceMappingGap:true});await page.goto('/?dashboard=1');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('7');});

test('an empty date remains invalid instead of silently substituting today',async({page})=>{const c=await setupDashboard(page);await page.goto('/?dashboard=1&dashboardFrom=2026-09-01&dashboardTo=2026-09-12');await expect(page.getByTestId('dashboard-closing-count')).toHaveText('2 invoices');await page.getByLabel('Through',{exact:true}).fill('');await expect(page.getByLabel('Through',{exact:true})).toHaveValue('');await expect(page.getByRole('alert')).toContainText('Choose valid dates');await expect(page.getByTestId('dashboard-closing-count')).toHaveCount(0);await page.getByRole('button',{name:'Current Aging · KAT / TSK',exact:true}).click();await expect(page.getByRole('table',{name:'Current source aging comparison'})).toBeVisible();expect(c.errors).toEqual([]);});

for(const width of [1440,1280])test('integrated current Aging comparison '+width,async({page})=>{const c=await setupDashboard(page);await page.setViewportSize({width,height:width===1440?900:800});await page.goto('/?dashboard=1&dashboardView=aging');const table=page.getByRole('table',{name:'Current source aging comparison'});await expect(table.locator('tbody tr')).toHaveCount(2);await page.screenshot({path:'evidence/dashboard-aging-'+width+'.png',animations:'disabled'});await table.getByRole('button',{name:'Open accounts in Agent',exact:true}).click();await expect(table.locator('tbody tr')).toHaveCount(2);await expect(table).toContainText('Azure Travel · Synthetic');await expect(table.getByRole('button',{name:'Azure Travel · Synthetic · KAT · 0–30',exact:true})).toBeVisible();await expect(table.getByRole('button',{name:'Azure Travel · Synthetic · TSK · 0–30',exact:true})).toBeVisible();expect(c.errors).toEqual([]);});
