import {test,expect,type Page} from '@playwright/test';
import {setupDashboard} from './fixtures/dashboard-period';

// Synthetic saved OPERA rows: Bill Date differs from the observation date; zero open balances remain included.
const invoice=(hotel:string,accountId:string,transactionId:string,transactionDate:string,originalAmount:string,accountType='Agent')=>({hotel,accountId,transactionId,transactionDate,invoiceNo:'SYN-'+transactionId,folioNo:'SYN-FOL-'+transactionId,accountName:'Synthetic '+accountId,accountType,originalAmount,openAmount:'25.00',entryClassification:'invoice',sourceStatus:'observed',lastObservedAt:'2026-09-14T01:00:00Z'});
const invoices=[{...invoice('KAT','kat-azure','kat-sept-12','2026-09-12','100.00'),openAmount:'0.00'},invoice('KAT','kat-azure','kat-sept-13','2026-09-13','200.00'),invoice('TSK','tsk-azure','tsk-sept-13','2026-09-13','300.00'),invoice('KAT','kat-cedar','corp-sept-13','2026-09-13','400.00','Corporate')];
async function setup(page:Page,rows=invoices){
 const result=await setupDashboard(page,{now:'2026-09-14T03:00:00Z'}),entryRequests:URLSearchParams[]=[],historyRequests:string[]=[];
 page.on('request',r=>{if(new URL(r.url()).pathname==='/api/financial/invoice_entries'||new URL(r.url()).pathname==='/api/financial/refresh')historyRequests.push(r.url());});
 const read=(q:URLSearchParams)=>{const matched=rows.filter(r=>r.transactionDate>=q.get('from')!&&r.transactionDate<=q.get('to')!&&(!q.get('hotel')||q.get('hotel')===r.hotel)&&(!q.get('type')||q.get('type')===r.accountType)&&(!q.get('account')||q.get('account')===r.accountId)),pageNumber=Number(q.get('page')??0),limit=Number(q.get('limit')??50);return {rows:matched.slice(pageNumber*limit,(pageNumber+1)*limit),total:matched.length,summary:{invoiceCount:matched.length,amount:matched.reduce((n,r)=>n+Number(r.originalAmount),0).toFixed(2),unknownAmounts:0,notObserved:0,unknownSourceDates:0},coverage:{complete:true,lastSuccessAt:'2026-09-14T01:00:00Z',lastAttemptStatus:'succeeded'}};};
 await page.route('**/api/dashboard/invoice-entries?*',route=>{const q=new URL(route.request().url()).searchParams;entryRequests.push(q);return route.fulfill({json:read(q)});});
 await page.route('**/api/dashboard/hotel-overview?*',route=>{const q=new URL(route.request().url()).searchParams;const scope=(hotel?:string)=>{const query=new URLSearchParams(q);if(hotel)query.set('hotel',hotel);const value=read(query);return {balances:null,activity:null,external:null,payments:null,paid:null,entries:{summary:value.summary,coverage:value.coverage}};};return route.fulfill({json:{from:q.get('from'),to:q.get('to'),total:scope(),hotels:[{hotel:'KAT',...scope('KAT')},{hotel:'TSK',...scope('TSK')}]}});});
 return {...result,entryRequests,historyRequests};
}

test('New invoices follows Portfolio Bill Dates for day and inclusive range, independent of observation date',async({page})=>{
 const c=await setup(page);await page.goto('/?dashboard=1&hotel=KAT&dashboardFrom=2026-09-12&dashboardTo=2026-09-12');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('1');await expect(page.getByText('OPERA Bill Date · Original invoice value',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:/New invoices/}).first().click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail).toContainText('SYN-kat-sept-12');await expect(detail).toContainText('Current open ฿0.00');await expect(detail).not.toContainText('SYN-kat-sept-13');
 await page.getByLabel('Date',{exact:true}).fill('2026-09-13');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('2');await page.getByRole('button',{name:/New invoices/}).first().click();await expect(detail).toContainText('SYN-kat-sept-13');await expect(detail).toContainText('SYN-corp-sept-13');await expect(detail).not.toContainText('SYN-kat-sept-12');
 await page.getByLabel('Date selection mode').selectOption('range');await page.getByLabel('From',{exact:true}).fill('2026-09-12');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('3');
 expect(c.entryRequests.some(q=>q.get('hotel')==='KAT'&&q.get('from')==='2026-09-12'&&q.get('to')==='2026-09-13')).toBe(true);expect(c.historyRequests).toEqual([]);expect(c.errors).toEqual([]);
});

test('New invoices comparison and detail preserve hotel, account type and account scope',async({page})=>{
 const c=await setup(page);await page.goto('/?dashboard=1&dashboardFrom=2026-09-13&dashboardTo=2026-09-13');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('3');await expect(page.getByTestId('activity-invoice_entries-KAT')).toContainText('2 invoices');await expect(page.getByTestId('activity-invoice_entries-TSK')).toContainText('1 invoices');
 await page.getByTestId('activity-invoice_entries-TSK').click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail).toContainText('SYN-tsk-sept-13');await expect(detail).not.toContainText('SYN-kat-sept-13');expect(c.entryRequests.at(-1)?.get('hotel')).toBe('TSK');
 await page.getByLabel('Period account type').selectOption('Agent');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('2');await page.getByLabel('Period account',{exact:true}).selectOption(JSON.stringify(['KAT','kat-azure']));await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('1');await page.getByRole('button',{name:/New invoices/}).first().click();await expect(detail).toContainText('SYN-kat-sept-13');await expect(detail).not.toContainText('SYN-corp-sept-13');expect(c.entryRequests.at(-1)?.get('account')).toBe('kat-azure');expect(c.entryRequests.at(-1)?.get('type')).toBe('Agent');expect(c.historyRequests).toEqual([]);expect(c.errors).toEqual([]);
});

test('New invoice detail paginates the Portfolio source without reading financial history',async({page})=>{
 const rows=Array.from({length:51},(_,i)=>invoice('KAT','kat-azure','page-'+String(i).padStart(2,'0'),'2026-09-13','10.00'));const c=await setup(page,rows);await page.goto('/?dashboard=1&hotel=KAT&dashboardFrom=2026-09-13&dashboardTo=2026-09-13');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('51');await page.getByRole('button',{name:/New invoices/}).first().click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail.locator('tbody tr')).toHaveCount(50);await detail.getByRole('button',{name:'Next',exact:true}).click();await expect(detail.locator('tbody tr')).toHaveCount(1);await expect(detail).toContainText('SYN-page-50');expect(c.entryRequests.at(-1)?.get('page')).toBe('1');expect(c.entryRequests.at(-1)?.get('limit')).toBe('50');expect(c.historyRequests).toEqual([]);
});

test('an invoice reaching zero open balance retains its Bill Date count and original amount after reload',async({page})=>{
 const row={...invoice('KAT','kat-azure','paid-after-bill','2026-09-13','100.00'),openAmount:'100.00'},c=await setup(page,[row]);
 await page.goto('/?dashboard=1&hotel=KAT&dashboardFrom=2026-09-13&dashboardTo=2026-09-13');const headline=page.getByRole('button',{name:/New invoices/}).first();await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('1');await expect(headline).toContainText('฿100.00');await headline.click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail).toContainText('Current open ฿100.00');
 row.openAmount='0.00';await page.getByRole('button',{name:'Reload dashboard',exact:true}).click();await expect(detail).toContainText('Current open ฿0.00');await expect(detail).toContainText('Original ฿100.00');await expect(detail.locator('tbody tr')).toHaveCount(1);await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('1');await expect(headline).toContainText('฿100.00');expect(c.historyRequests).toEqual([]);expect(c.errors).toEqual([]);
});

for(const width of [1280,390])test('Portfolio Bill Date caption and invoice detail remain readable at '+width,async({page})=>{
 const c=await setupDashboard(page);await page.setViewportSize({width,height:width===1280?800:844});await page.goto('/?dashboard=1');await expect(page.getByTestId('dashboard-invoice_entries-count')).toHaveText('7');const section=page.getByRole('region',{name:'Activity in selected period',exact:true});await section.evaluate(e=>e.scrollIntoView({block:'start'}));await page.screenshot({path:'evidence/period-portfolio-bill-date-'+width+'.png',animations:'disabled'});await section.getByRole('button',{name:/New invoices/}).first().click();const detail=page.getByRole('region',{name:'Dashboard invoice details'});await expect(detail).toContainText('Saved OPERA invoices filtered by Bill Date, including invoices with zero open balance');await expect(detail).toContainText('Original ฿500.00');expect(await page.locator('.dashboard-page').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);expect(c.unexpected).toEqual([]);expect(c.errors).toEqual([]);
});
