import {test,expect,type Page} from '@playwright/test';
const user={id:'00000000-0000-4000-8000-000000000001',email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-01T00:00:00Z'};
const recordId='00000000-0000-4000-8000-000000000010';
async function setup(page:Page,{lost=false}={}){const calls:{path:string;method:string;body:any}[]=[];let confirmations=0,voided=false,recordRevision=1;await page.clock.setFixedTime(new Date('2026-09-11T00:00:00Z'));await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic',refresh_token:'synthetic-refresh',expires_at:Math.floor(Date.now()/1000)+86400,token_type:'bearer',user:u})),user);await page.route('https://example.supabase.co/**',r=>r.fulfill({json:{user}}));const preview={action:'record',hotel:'KAT',accountId:'A',actualDate:'2026-09-09',channel:'system',reference:'Synthetic portal reference',note:'',amount:null,workflowEffect:'Set first billing only where not recorded',lines:[{invoiceId:'I-A',firstBilling:true,firstDateBefore:null,firstDateAfter:'2026-09-09',dueAfter:'2026-10-09'}]};
 await page.route('**/api/**',r=>{const req=r.request(),u=new URL(req.url()),path=u.pathname,body=req.postData()?req.postDataJSON():null;calls.push({path:path+u.search,method:req.method(),body});if(path==='/api/config')return r.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic'}});if(path==='/api/refresh')return r.fulfill({json:{jobs:[],running:false,hotels:[]}});if(path==='/api/portfolio')return r.fulfill({json:{accounts:[{hotel:'KAT',id:'A',name:'Synthetic Billing Account',type:'Agent',open:200,over90:0,items:2,verification_state:'verified'}],status:'connected'}});
 if(path==='/api/accounts/KAT/A')return r.fulfill({json:{invoices:['I-A','I-B'].map(id=>({id,hotel:'KAT',account_id:'A',guest:'Synthetic '+id,invoice_no:id,folio_no:'F-'+id,transaction_date:'2026-08-20',original:100,open:100,age:20,aging:'Up to 30',collection_role:'standalone',collection_selectable:true,verification_state:'verified',workflow:{revision:0,billing_required:true,credit_term:30,first_billing_date:null,last_reminder_stage:null,last_reminder_date:null,due_date:null}}))}});
 if(path==='/api/account-settings/KAT/A')return r.fulfill({json:{billing_method:'system',billing_portal:'https://portal.example.test/billing'}});
 if(path==='/api/external-billing/preview')return r.fulfill({json:{digest:'a'.repeat(64),preview:{...preview,...body.input,lines:preview.lines,workflowEffect:body.input.action==='record'?preview.workflowEffect:'Billing/due/reminder history remains unchanged'}}});
 if(path==='/api/external-billing/confirm'){confirmations++;if(!lost||confirmations>1){voided=body.input.action==='void';recordRevision++;}return lost&&confirmations===1?r.fulfill({status:503,json:{error:'billing_unavailable'}}):r.fulfill({json:{recordId,revision:2,replayed:confirmations>1}});}
 if(path.endsWith('/history')&&path.startsWith('/api/external-billing/'))return r.fulfill({json:{rows:[{revision:2,recorded_at:'2026-09-10T10:00:00Z',preview:{...preview,action:'correct',reason:'Corrected synthetic source reference'}}],total:1}});
 if(path==='/api/external-billing')return r.fulfill({json:{rows:[{id:recordId,hotel:'KAT',account_id:'A',account_name:'Synthetic Billing Account',revision:recordRevision,voided,created_at:'2026-09-09T10:00:00Z',details:preview}],total:1,summary:{records:voided?0:1,invoices:voided?0:1,firstBillingInvoices:voided?0:1,amount:voided?'0.00':null,unknownAmounts:voided?0:1}}});
 return r.fulfill({status:501,json:{error:'unmocked_synthetic_endpoint'}});
 });return calls;}
for(const [width,height]of [[1440,900],[1280,800],[390,844]])test(`external billing ${width}: review one selected invoice before saving`,async({page})=>{await page.setViewportSize({width,height});const calls=await setup(page);await page.goto('/?account=A&property=KAT');await page.getByRole('checkbox',{name:'Select I-A',exact:true}).check();await page.getByRole('button',{name:'Record external billing',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Record actual external billing',exact:true});await expect(dialog.getByRole('link',{name:'Open account billing portal'})).toHaveAttribute('href','https://portal.example.test/billing');await dialog.getByLabel('Actual billing date',{exact:true}).fill('2026-09-09');await dialog.getByLabel('Portal / email reference',{exact:true}).fill('Synthetic portal reference');await dialog.getByRole('button',{name:'Review billing record',exact:true}).click();await expect(dialog.getByText('Review before saving',{exact:true})).toBeVisible();expect(calls.some(c=>c.path.endsWith('/confirm'))).toBe(false);const body=calls.find(c=>c.path.endsWith('/preview'))!.body;expect(body.input.lines).toEqual([{invoiceId:'I-A',revision:0}]);expect(body.input.amount).toBe(null);await page.screenshot({path:`evidence/external-billing-${width}.png`});await dialog.getByRole('button',{name:'Confirm billing record',exact:true}).click();await expect(dialog).toHaveCount(0);expect(calls.filter(c=>c.method==='POST').every(c=>c.path==='/api/refresh'||c.path.startsWith('/api/external-billing/'))).toBe(true);});
test('an uncertain external billing result retries the exact reviewed command',async({page})=>{const calls=await setup(page,{lost:true});await page.goto('/?account=A&property=KAT');await page.getByRole('checkbox',{name:'Select I-A',exact:true}).check();await page.getByRole('button',{name:'Record external billing',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Record actual external billing',exact:true});await dialog.getByLabel('Portal / email reference',{exact:true}).fill('Synthetic reference');await dialog.getByRole('button',{name:'Review billing record',exact:true}).click();await dialog.getByRole('button',{name:'Confirm billing record',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('locked');await expect(dialog.getByLabel('Portal / email reference',{exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Close external billing'})).toBeDisabled();await dialog.getByRole('button',{name:'Retry same billing command',exact:true}).click();const saved=calls.filter(c=>c.path.endsWith('/confirm'));expect(saved).toHaveLength(2);expect(saved[0].body).toEqual(saved[1].body);});
test('external activity filters and correction history keep Gmail and invoice dates separate',async({page})=>{const calls=await setup(page);await page.goto('/?externalBilling=1');await expect(page.getByRole('heading',{name:'External billing activity',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Billing account type',exact:true}).selectOption('Agent');await expect.poll(()=>calls.some(c=>c.path.includes('/api/external-billing?')&&c.path.includes('type=Agent'))).toBe(true);await page.getByRole('button',{name:'View record changes'}).click();await expect(page.getByText('Corrected synthetic source reference',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Correct record',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Correct external billing record',exact:true});await dialog.getByLabel('Reason for this change',{exact:true}).fill('Fix the portal reference');await dialog.getByRole('button',{name:'Review billing record',exact:true}).click();await expect(dialog).toContainText('Billing/due/reminder history remains unchanged');expect(calls.filter(c=>c.path.endsWith('/preview')).at(-1)?.body.input.lines).toBeUndefined();});

test('void and restore remain reviewed activity changes without rewriting invoice dates',async({page})=>{const calls=await setup(page);await page.goto('/?externalBilling=1');await page.getByRole('button',{name:'Void record',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Void external billing record',exact:true});await dialog.getByLabel('Reason for this change',{exact:true}).fill('Synthetic duplicate record');await dialog.getByRole('button',{name:'Review billing record',exact:true}).click();await expect(dialog).toContainText('Billing/due/reminder history remains unchanged');await dialog.getByRole('button',{name:'Confirm billing record',exact:true}).click();await expect(page.getByText('0 active records',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Restore record',exact:true}).click();dialog=page.getByRole('dialog',{name:'Restore external billing record',exact:true});await dialog.getByLabel('Reason for this change',{exact:true}).fill('Synthetic evidence restored');await dialog.getByRole('button',{name:'Review billing record',exact:true}).click();await dialog.getByRole('button',{name:'Confirm billing record',exact:true}).click();await expect(page.getByText('1 active records',{exact:false})).toBeVisible();expect(calls.filter(c=>c.path.endsWith('/confirm')).map(c=>c.body.input.action)).toEqual(['void','restore']);expect(calls.some(c=>c.path.includes('invoice-history')&&c.method!=='GET')).toBe(false);});
