import {test,expect} from '@playwright/test';
import {setupDashboard} from './fixtures/dashboard-period';
test('a long period refresh uses bounded adjacent source requests',async({page})=>{const c=await setupDashboard(page);await page.goto('/?dashboard=1&hotel=KAT&dashboardFrom=2025-01-01&dashboardTo=2026-09-12');await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect(page.getByText('OPERA history requested for this period.',{exact:false})).toBeVisible();const calls=c.calls.filter(r=>r.path==='/api/financial/refresh');expect(calls.length).toBeGreaterThan(1);expect(calls[0].body.from).toBe('2025-01-01');expect(calls.at(-1)?.body.to).toBe('2026-09-12');for(const [i,r]of calls.entries()){expect(Date.parse(r.body.to)-Date.parse(r.body.from)).toBeLessThan(366*86400000);if(i)expect(Date.parse(r.body.from)-Date.parse(calls[i-1].body.to)).toBe(86400000);}});
test('multi-hotel partial retry never re-requests a completed hotel',async({page})=>{
 await setupDashboard(page);const sent:{hotel:string;commandId:string}[]=[];let failed=false;await page.route('**/api/financial/refresh',route=>{const body=route.request().postDataJSON();sent.push(body);if(body.hotel==='TSK'&&!failed){failed=true;return route.fulfill({status:503,json:{error:'synthetic_uncertain'}});}return route.fulfill({json:{status:body.hotel==='KAT'?'succeeded':'queued',created:true,hotel:body.hotel}});});await page.goto('/?dashboard=1');await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect(page.getByText('1 of 2 requests confirmed.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect(page.getByText('OPERA history requested for this period.',{exact:false})).toBeVisible();expect(sent.map(r=>r.hotel)).toEqual(['KAT','TSK','TSK']);expect(sent[1].commandId).toBe(sent[2].commandId);
});
test('a non-enabled 2xx receipt is not reported as successful refresh',async({page})=>{await setupDashboard(page);await page.route('**/api/financial/refresh',route=>route.fulfill({json:{created:false,status:'not_enabled'}}));await page.goto('/?dashboard=1&hotel=KAT');await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect(page.getByText('The refresh request could not be confirmed.',{exact:false})).toBeVisible();await expect(page.getByText('OPERA history requested for this period.',{exact:false})).toHaveCount(0);});

test('leaving a pending long-period request stops subsequent chunks',async({page})=>{
 await setupDashboard(page);const sent:any[]=[];let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/api/financial/refresh',async route=>{sent.push(route.request().postDataJSON());await held;try{await route.fulfill({json:{status:'queued',created:true}});}catch{}});
 await page.goto('/?dashboard=1&hotel=KAT&dashboardFrom=2025-01-01&dashboardTo=2026-09-12');await page.getByRole('button',{name:'Refresh OPERA for this period',exact:true}).click();await expect.poll(()=>sent.length).toBe(1);await page.getByLabel('From',{exact:true}).fill('2026-09-01');release();await page.waitForLoadState('networkidle');expect(sent).toHaveLength(1);
});

test('status polling follows older active jobs outside the latest run list',async({page})=>{
 await page.clock.install({time:new Date('2026-09-12T03:00:00Z')});const c=await setupDashboard(page);let statusReads=0,running=true;await page.route('**/api/financial/status',route=>{statusReads++;return route.fulfill({json:{enabled:true,running,runs:Array.from({length:10},(_,i)=>({hotel:'TSK',from:'2025-01-01',to:'2025-12-31',status:'succeeded',finishedAt:'2026-09-12T02:00:00Z',id:'synthetic-'+i}))}});});await page.goto('/?dashboard=1');await expect(page.getByText('OPERA is still reading source history.',{exact:false})).toBeVisible();const before=c.calls.filter(r=>r.path==='/api/dashboard/balances').length;await page.clock.runFor(16000);await expect.poll(()=>statusReads).toBeGreaterThan(1);running=false;await page.clock.runFor(16000);await expect.poll(()=>c.calls.filter(r=>r.path==='/api/dashboard/balances').length).toBeGreaterThan(before);
});
