import {test,expect,type Page} from '@playwright/test';
import {policyFixture} from './fixtures/collection-policy';
import {registerValues,type RegisterRow} from '../../src/register/model';
function invoice(index:number):RegisterRow{return {hotel:'KAT',account_id:'SYN-A',id:String(index),account_name:'Synthetic Travel Company',account_no:'SYN-001',account_type:'OTA',guest:index===1?'Alexandra Montgomery / Christopher Longsurname':'Synthetic guest '+index,invoice_no:index===1?'1234567890123':String(index),folio_no:'FOL-'+index,transaction_date:'2026-09-01',original:10000+index,open:10000+index,age:20,aging:'Up to 30',verification_state:'verified',collection_role:'standalone',collection_selectable:true,workflow:{revision:0,billing_required:true,credit_term:30,first_billing_date:null,due_date:null,last_reminder_stage:null,last_reminder_date:null},workflow_revision:0,tracking_revision:0,exception_revision:0,billing_required:true,credit_term:30,first_billing_date:null,due_date:null,last_reminder_stage:null,last_reminder_date:null,promised_date:null,tracking_status:'',owner_name:'',reported_received:null,note:'',edited_at:null,hidden:false};}
async function setup(page:Page,{conflict=false,ambiguous=false}={}){
 const rows=Array.from({length:57},(_,i)=>invoice(i+1)),writes:any[]=[],reads:string[]=[],receipts=new Map<string,unknown>();let first=true;
 const user={id:'synthetic-register-user',email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-01T00:00:00Z'};
 await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic-register-token',refresh_token:'synthetic',expires_at:Math.floor(Date.now()/1000)+3600,user:u})),user);await page.route('https://example.supabase.co/**',r=>r.fulfill({json:{user}}));
 await page.route('**/api/**',async r=>{const q=r.request(),url=new URL(q.url()),p=url.pathname;reads.push(q.method()+' '+p);
  if(p==='/api/config')return r.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic'}});
  if(p==='/api/collection-policy')return r.fulfill({json:policyFixture});
  if(p==='/api/refresh')return r.fulfill({json:{jobs:[],running:false,hotels:[]}});
  if(p==='/api/portfolio')return r.fulfill({json:{status:'connected',accounts:[{hotel:'KAT',id:'SYN-A',name:'Synthetic Travel Company',type:'OTA',open:600000,items:57,over90:0}],refresh:{running:false,hotels:[]}}});
  if(p==='/api/invoice-register'){
   let visible=rows.filter(row=>!url.searchParams.get('search')||JSON.stringify(row).toLowerCase().includes(url.searchParams.get('search')!.toLowerCase()));const hiddenTotal=visible.filter(row=>row.hidden).length;
   if(url.searchParams.get('visibility')!=='all')visible=visible.filter(row=>row.hidden===(url.searchParams.get('visibility')==='hidden'));
   const sort=url.searchParams.get('sort') as keyof RegisterRow,dir=url.searchParams.get('direction')==='desc'?-1:1;visible.sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),'en',{numeric:true})*dir);const page=Number(url.searchParams.get('page')??0);
   return r.fulfill({json:{rows:visible.slice(page*50,page*50+50),total:visible.length,hiddenTotal,summary:{invoices:visible.length,open:visible.reduce((s,x)=>s+x.open,0),unverified:0}}});
  }
  if(p==='/api/invoice-register/visibility'){const b=q.postDataJSON();writes.push(b);for(const scope of b.rows)rows.find(row=>row.id===scope.invoiceId)!.hidden=b.hidden;return r.fulfill({json:{changed:b.rows.length,hidden:b.hidden}});}
  if(p.endsWith('/history')&&p.startsWith('/api/invoice-register'))return r.fulfill({json:{rows:[],total:0}});
  if(p.startsWith('/api/invoice-register/KAT/SYN-A/')){
   const row=rows.find(row=>row.id===p.split('/').at(-1))!;if(q.method()==='GET')return r.fulfill({json:row});const b=q.postDataJSON();writes.push(b);
   if(conflict)return r.fulfill({status:409,json:{error:'register_revision_conflict'}});if(receipts.has(b.commandId))return r.fulfill({json:receipts.get(b.commandId)});
   const v=b.values;Object.assign(row,{billing_required:v.billingRequired,credit_term:v.creditTerm,first_billing_date:v.firstBillingDate,last_reminder_stage:v.lastReminderStage,last_reminder_date:v.lastReminderDate,promised_date:v.promisedDate,tracking_status:v.trackingStatus,owner_name:v.ownerName,reported_received:v.reportedReceived,note:v.note,tracking_revision:row.tracking_revision+1,workflow_revision:row.workflow_revision+1});row.workflow={...row.workflow!,revision:row.workflow_revision,billing_required:row.billing_required,credit_term:row.credit_term,first_billing_date:row.first_billing_date,last_reminder_stage:row.last_reminder_stage,last_reminder_date:row.last_reminder_date};const receipt={row:{...row}};receipts.set(b.commandId,receipt);if(ambiguous&&first){first=false;return r.abort();}return r.fulfill({json:receipt});
  }
  if(p==='/api/accounts/KAT/SYN-A')return r.fulfill({json:{invoices:rows.map(row=>({...row,workflow:row.workflow}))}});
  if(p==='/api/account-settings/KAT/SYN-A')return r.fulfill({json:{billing_method:'email'}});
  if(p.startsWith('/api/invoice-exceptions/'))return r.fulfill({status:503,json:{error:'synthetic_unavailable'}});
  return r.fulfill({status:501,json:{error:'unmocked_synthetic_api'}});
 });return {rows,writes,reads};
}
for(const width of [1440,1280,390])test(`invoice register ${width}: readable table, sorting, search and reversible hiding`,async({page})=>{
 const {writes}=await setup(page);await page.setViewportSize({width,height:900});await page.goto('/?reports=1');await expect(page.getByRole('heading',{name:'Invoice Register',exact:true})).toBeVisible();await expect(page.locator('.register-table tbody tr')).toHaveCount(50);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.register-table')).toContainText('1234567890123');
 if(width>800){const overflow=await page.locator('.register-table').evaluate(e=>[...e.querySelectorAll('th,td')].filter(c=>c.scrollWidth>c.clientWidth+1).map(c=>c.textContent));expect(overflow).toEqual([]);await page.getByRole('columnheader').getByRole('button',{name:'Open · THB',exact:true}).click();await expect(page.locator('.register-table th[aria-sort="ascending"]')).toContainText('Open');}
 await page.locator('.register-tools').scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/invoice-register-${width}.png`,fullPage:false});
 await page.getByLabel('Search invoice register').fill('1234567890123');await expect(page.locator('.register-table tbody tr')).toHaveCount(1);await page.getByLabel('Select invoice KAT 1234567890123',{exact:true}).check();await page.getByRole('button',{name:'Hide',exact:true}).click();await expect(page.locator('.register-table tbody tr')).toHaveCount(0);
 await page.getByLabel('Register row visibility').selectOption('hidden');await expect(page.locator('.register-table tbody tr')).toHaveCount(1);await page.getByLabel('Select invoice KAT 1234567890123',{exact:true}).check();await page.getByRole('button',{name:'Show',exact:true}).click();await page.getByLabel('Register row visibility').selectOption('visible');await expect(page.locator('.register-table tbody tr')).toHaveCount(1);expect(writes.map(w=>w.hidden)).toEqual([true,false]);
});
test('table edits update invoice workflow and invoice-side changes refresh the table',async({page})=>{
 const {rows,writes}=await setup(page);await page.goto('/?reports=1');await page.getByRole('button',{name:'Edit invoice KAT 1234567890123',exact:true}).click();await page.getByLabel('Credit term',{exact:true}).fill('45');await page.getByLabel('First billing date',{exact:true}).fill('2026-09-01');await page.getByRole('button',{name:'Follow-up',exact:true}).click();await page.getByLabel('Latest reminder',{exact:true}).selectOption('Follow 1');await page.getByLabel('Reminder date',{exact:true}).fill('2026-09-02');await page.getByRole('button',{name:'Notes & receipts',exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Synthetic AR');await page.getByLabel('Invoice note',{exact:true}).fill('Shared note');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('status')).toContainText('Linked invoice status updated');expect(writes[0].values).toMatchObject({creditTerm:45,lastReminderStage:'Follow 1',note:'Shared note'});
 await page.getByRole('button',{name:'1234567890123',exact:true}).click();await expect(page.locator('.detail-fields')).toContainText('Follow-up 1');await page.getByText('Tracking & payment notes',{exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Synthetic account AR');await page.getByRole('button',{name:'Save tracking',exact:true}).click();await expect(page.getByRole('status')).toContainText('Invoice Register is updated');
 await page.getByRole('button',{name:'Back to reports',exact:true}).click();await expect(page.locator('.register-table')).toContainText('Synthetic account AR');rows[0].note='Changed in invoice details';rows[0].last_reminder_stage='Follow 2';await page.evaluate(()=>window.dispatchEvent(new Event('ar-invoice-changed')));await expect(page.locator('.register-table')).toContainText('Changed in invoice details');
});
for(const ambiguous of [false,true])test(`register save ${ambiguous?'retries the same receipt':'preserves edits on a revision conflict'}`,async({page})=>{const {writes}=await setup(page,{conflict:!ambiguous,ambiguous});await page.goto('/?reports=1');await page.getByRole('button',{name:'Edit invoice KAT 1234567890123',exact:true}).click();await page.getByLabel('Credit term',{exact:true}).fill('45');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('alert')).toContainText(ambiguous?'could not be confirmed':'changed elsewhere');await expect(page.getByLabel('Credit term',{exact:true})).toHaveValue('45');if(ambiguous){await page.getByRole('button',{name:'Retry save',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');expect(writes[0].commandId).toBe(writes[1].commandId);}else{await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByLabel('Credit term',{exact:true})).toHaveValue('45');}});
test('register view uses the selected Khao Lak region',async({page})=>{const {reads}=await setup(page);await page.goto('/?reports=1&region=khao-lak');await expect(page.getByRole('heading',{name:'Invoice Register',exact:true})).toBeVisible();await expect.poll(()=>reads.filter(r=>r==='GET /api/invoice-register').length).toBeGreaterThan(0);});
test('clearing search immediately before switching regions keeps the cleared search',async({page})=>{await setup(page);await page.goto('/?reports=1');await page.getByLabel('Search invoice register').fill('Synthetic');await expect.poll(()=>new URL(page.url()).searchParams.get('regSearch')).toBe('Synthetic');await page.getByLabel('Search invoice register').fill('');await page.getByLabel('Region',{exact:true}).selectOption('khao-lak');await expect(page.getByLabel('Search invoice register')).toHaveValue('');});
