import {createHash} from 'node:crypto';
import {test,expect,type Page} from '@playwright/test';
import {policyFixture} from './fixtures/collection-policy';
import {registerValues,type RegisterRow} from '../../src/register/model';
function invoice(index:number):RegisterRow{return {hotel:'KAT',account_id:'SYN-A',id:String(index),account_name:'Synthetic Travel Company',account_no:'SYN-001',account_type:'OTA',guest:index===1?'Alexandra Montgomery / Christopher Longsurname':'Synthetic guest '+index,invoice_no:index===1?'1234567890123':String(index),folio_no:'FOL-'+index,transaction_date:'2026-09-01',original:10000+index,open:10000+index,age:20,aging:'Up to 30',verification_state:'verified',collection_role:'standalone',collection_selectable:true,workflow:{revision:0,billing_required:true,credit_term:30,first_billing_date:null,due_date:null,last_reminder_stage:null,last_reminder_date:null},workflow_revision:0,tracking_revision:0,exception_revision:0,billing_required:true,credit_term:30,first_billing_date:null,due_date:null,last_reminder_stage:null,last_reminder_date:null,promised_date:null,tracking_status:'',owner_name:'',reported_received:null,note:'',edited_at:null,hidden:false};}
async function setup(page:Page,{conflict=false,ambiguous=false,invalid=false,count=57,visibilityAmbiguous=false}={}){
 const rows=Array.from({length:count},(_,i)=>invoice(i+1)),writes:any[]=[],reads:string[]=[],receipts=new Map<string,unknown>();let first=true;
 const user={id:'synthetic-register-user',email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{providers:['google']},user_metadata:{},created_at:'2026-09-01T00:00:00Z'};
 await page.route('https://example.supabase.co/**',r=>r.fulfill({json:{access_token:'synthetic-register-token',refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user}}));
 await page.route('**/api/**',async r=>{const q=r.request(),url=new URL(q.url()),p=url.pathname;reads.push(q.method()+' '+p);
  if(p==='/api/access/me')return r.fulfill({json:{memberId:user.id,email:user.email,active:true,administrator:true,regions:['phuket','khao-lak'],revision:1}});
  if(p==='/api/config')return r.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic',googleEnabled:true}});
  if(p==='/api/collection-policy')return r.fulfill({json:policyFixture});
  if(p==='/api/refresh')return r.fulfill({json:{jobs:[],running:false,hotels:[]}});
  if(p==='/api/portfolio')return r.fulfill({json:{status:'connected',accounts:[{hotel:'KAT',id:'SYN-A',name:'Synthetic Travel Company',type:'OTA',open:600000,items:count,over90:0}],refresh:{running:false,hotels:[]}}});
  if(p==='/api/invoice-register'){
   let visible=rows.filter(row=>!url.searchParams.get('search')||JSON.stringify(row).toLowerCase().includes(url.searchParams.get('search')!.toLowerCase()));const hiddenTotal=visible.filter(row=>row.hidden).length;
   if(url.searchParams.get('visibility')!=='all')visible=visible.filter(row=>row.hidden===(url.searchParams.get('visibility')==='hidden'));
   const sort=url.searchParams.get('sort') as keyof RegisterRow,dir=url.searchParams.get('direction')==='desc'?-1:1;visible.sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),'en',{numeric:true})*dir);const page=Number(url.searchParams.get('page')??0),limit=Number(url.searchParams.get('limit')??50),snapshot=createHash('md5').update(JSON.stringify(visible)).digest('hex');
   return r.fulfill({json:{snapshot,rows:visible.slice(page*limit,page*limit+limit),total:visible.length,hiddenTotal,summary:{invoices:visible.length,open:visible.reduce((s,x)=>s+x.open,0),unverified:0}}});
  }
  if(p==='/api/invoice-register/visibility'){const b=q.postDataJSON();writes.push(b);if(receipts.has(b.commandId))return r.fulfill({json:receipts.get(b.commandId)});for(const scope of b.rows)rows.find(row=>row.id===scope.invoiceId)!.hidden=b.hidden;const result={changed:b.rows.length,hidden:b.hidden};receipts.set(b.commandId,result);if(visibilityAmbiguous&&writes.length===2)return r.abort();return r.fulfill({json:result});}
  if(p.endsWith('/history')&&p.startsWith('/api/invoice-register'))return r.fulfill({json:{rows:[],total:0}});
  if(p.startsWith('/api/invoice-register/KAT/SYN-A/')){
   const row=rows.find(row=>row.id===p.split('/').at(-1))!;if(q.method()==='GET')return r.fulfill({json:row});const b=q.postDataJSON();writes.push(b);
   if(invalid&&first){first=false;return r.fulfill({status:400,json:{error:'register_invalid'}});}if(conflict)return r.fulfill({status:409,json:{error:'register_revision_conflict'}});if(receipts.has(b.commandId))return r.fulfill({json:receipts.get(b.commandId)});
   const v=b.values;Object.assign(row,{billing_required:v.billingRequired,credit_term:v.creditTerm,first_billing_date:v.firstBillingDate,last_reminder_stage:v.lastReminderStage,last_reminder_date:v.lastReminderDate,promised_date:v.promisedDate,tracking_status:v.trackingStatus,owner_name:v.ownerName,reported_received:v.reportedReceived,note:v.note,tracking_revision:row.tracking_revision+1,workflow_revision:row.workflow_revision+1});row.workflow={...row.workflow!,revision:row.workflow_revision,billing_required:row.billing_required,credit_term:row.credit_term,first_billing_date:row.first_billing_date,last_reminder_stage:row.last_reminder_stage,last_reminder_date:row.last_reminder_date};const receipt={row:{...row}};receipts.set(b.commandId,receipt);if(ambiguous&&first){first=false;return r.abort();}return r.fulfill({json:receipt});
  }
  if(p==='/api/accounts/KAT/SYN-A')return r.fulfill({json:{invoices:rows.map(row=>({...row,workflow:row.workflow}))}});
  if(p==='/api/account-settings/KAT/SYN-A')return r.fulfill({json:{billing_method:'email'}});
  if(p.startsWith('/api/invoice-exceptions/'))return r.fulfill({status:503,json:{error:'synthetic_unavailable'}});
  return r.fulfill({status:501,json:{error:'unmocked_synthetic_api'}});
 });
 await page.goto('/');await expect(page.getByRole('button',{name:'Sign in with Google',exact:true})).toBeEnabled();
 await page.evaluate(()=>{sessionStorage.setItem('ar-google-tab-v1-oauth',String(Date.now()));const key=sessionStorage.getItem('ar-google-tab-v1')!;sessionStorage.setItem(key+'-code-verifier',JSON.stringify('synthetic-code-verifier'));});
 await page.goto('/?code=synthetic-code');await expect(page.getByRole('button',{name:'Reports',exact:true})).toBeVisible();
 return {rows,writes,reads};
}
for(const width of [1440,1280,390])test(`invoice register ${width}: readable table, sorting, search and reversible hiding`,async({page})=>{
 const {writes}=await setup(page);await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByRole('heading',{name:'Invoice Register',exact:true})).toBeVisible();await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();expect(await page.locator('.register-table tbody tr[data-invoice-row]').count()).toBeLessThan(40);await expect(page.locator('.register-table')).toHaveAttribute('aria-rowcount','58');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.register-table')).toContainText('1234567890123');
 if(width>800){const overflow=await page.locator('.register-table').evaluate(e=>[...e.querySelectorAll('th,td')].filter(c=>c.scrollWidth>c.clientWidth+1).map(c=>c.textContent));expect(overflow).toEqual([]);await page.getByRole('columnheader').getByRole('button',{name:'Open · THB',exact:true}).click();await expect(page.locator('.register-table th[aria-sort="ascending"]')).toContainText('Open');}
 await page.locator('.register-tools').scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/register-sheet-${width}.png`,fullPage:false});
 await page.getByLabel('Search invoice register').fill('1234567890123');await expect(page.locator('.register-table tbody tr[data-invoice-row]')).toHaveCount(1);await page.getByLabel('Select invoice KAT 1234567890123',{exact:true}).check();await page.getByRole('button',{name:'Hide',exact:true}).click();await expect(page.locator('.register-table tbody tr[data-invoice-row]')).toHaveCount(0);
 await page.getByLabel('Register row visibility').selectOption('hidden');await expect(page.locator('.register-table tbody tr[data-invoice-row]')).toHaveCount(1);await page.getByLabel('Select invoice KAT 1234567890123',{exact:true}).check();await page.getByRole('button',{name:'Show',exact:true}).click();await page.getByLabel('Register row visibility').selectOption('visible');await expect(page.locator('.register-table tbody tr[data-invoice-row]')).toHaveCount(1);expect(writes.map(w=>w.hidden)).toEqual([true,false]);
});
test('table edits update invoice workflow and invoice-side changes refresh the table',async({page})=>{
 const {rows,writes}=await setup(page);await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Edit invoice KAT 1234567890123',exact:true}).click();await page.getByLabel('Credit term',{exact:true}).fill('45');await page.getByLabel('First billing date',{exact:true}).fill('2026-09-01');await page.getByLabel('Latest reminder',{exact:true}).selectOption('Follow 1');await page.getByLabel('Reminder date',{exact:true}).fill('2026-09-02');await page.getByLabel('Owner',{exact:true}).fill('Synthetic AR');await page.getByLabel('Invoice note',{exact:true}).fill('Shared note');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('status')).toContainText('Linked invoice status updated');expect(writes[0].values).toMatchObject({creditTerm:45,lastReminderStage:'Follow 1',note:'Shared note'});
 await page.getByRole('button',{name:'1234567890123',exact:true}).click();await expect(page.locator('.detail-fields')).toContainText('Follow-up 1');await page.getByText('Tracking & payment notes',{exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Synthetic account AR');await page.getByRole('button',{name:'Save tracking',exact:true}).click();await expect(page.getByRole('status')).toContainText('Invoice Register is updated');
 await page.getByRole('button',{name:'Back to reports',exact:true}).click();await expect(page.locator('.register-table')).toContainText('Synthetic account AR');rows[0].note='Changed in invoice details';rows[0].last_reminder_stage='Follow 2';await page.evaluate(()=>window.dispatchEvent(new Event('ar-invoice-changed')));await expect(page.locator('.register-table')).toContainText('Changed in invoice details');
});
for(const ambiguous of [false,true])test(`register save ${ambiguous?'retries the same receipt':'preserves edits on a revision conflict'}`,async({page})=>{const {writes}=await setup(page,{conflict:!ambiguous,ambiguous});await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Edit invoice KAT 1234567890123',exact:true}).click();await page.getByLabel('Credit term',{exact:true}).fill('45');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('alert')).toContainText(ambiguous?'could not be confirmed':'changed elsewhere');await expect(page.getByLabel('Credit term',{exact:true})).toHaveValue('45');if(ambiguous){await page.getByRole('button',{name:'Retry save',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');expect(writes[0].commandId).toBe(writes[1].commandId);}else{await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByLabel('Credit term',{exact:true})).toHaveValue('45');}});
test('register view uses the selected Khao Lak region',async({page})=>{const {reads}=await setup(page);await page.getByRole('combobox',{name:'Region',exact:true}).selectOption('khao-lak');await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByRole('heading',{name:'Invoice Register',exact:true})).toBeVisible();await expect.poll(()=>reads.filter(r=>r==='GET /api/invoice-register').length).toBeGreaterThan(0);});
test('clearing search immediately before switching regions keeps the cleared search',async({page})=>{await setup(page);await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByLabel('Search invoice register').fill('Synthetic');await expect.poll(()=>new URL(page.url()).searchParams.get('regSearch')).toBe('Synthetic');await page.getByLabel('Search invoice register').fill('');await page.getByLabel('Region',{exact:true}).selectOption('khao-lak');await expect(page.getByLabel('Search invoice register')).toHaveValue('');});
test('a rejected value can be corrected in the same row without discarding edits',async({page})=>{const {writes}=await setup(page,{invalid:true});await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Edit invoice KAT 1234567890123',exact:true}).click();await page.getByLabel('Credit term',{exact:true}).fill('45');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Check the dates');await expect(page.getByLabel('Credit term',{exact:true})).toBeEnabled();await page.getByLabel('Credit term',{exact:true}).fill('35');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');expect(writes[0].commandId).not.toBe(writes[1].commandId);});
test('one sheet loads 1500 rows, pins invoice/account, and edits the last row without a page change',async({page})=>{
 const {writes}=await setup(page,{count:1500});await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();await expect(page.locator('.register-table')).toHaveAttribute('aria-rowcount','1501');expect(await page.locator('[data-invoice-row]').count()).toBeLessThan(45);
 const pane=page.getByRole('region',{name:'Invoice register sheet',exact:true}),cell=page.locator('[data-invoice-row]').first().locator('[data-pinned=account_name]');const before=await cell.boundingBox();await pane.evaluate(e=>{e.scrollLeft=1300;});await expect.poll(async()=>Math.round((await cell.boundingBox())!.x)).toBe(Math.round(before!.x));const topScroll=page.getByRole('region',{name:'Sheet horizontal scroll',exact:true});await expect.poll(()=>topScroll.evaluate(e=>e.scrollLeft)).toBe(1300);await topScroll.evaluate(e=>{e.scrollLeft=800;});await expect.poll(()=>pane.evaluate(e=>e.scrollLeft)).toBe(800);await topScroll.evaluate(e=>{e.scrollLeft=e.scrollWidth;});await expect.poll(()=>pane.evaluate(e=>e.scrollWidth-e.clientWidth-e.scrollLeft)).toBeLessThanOrEqual(1);await pane.evaluate(e=>{e.scrollLeft=300;});await expect.poll(()=>topScroll.evaluate(e=>e.scrollLeft)).toBe(300);
 await pane.evaluate(e=>{e.scrollTop=e.scrollHeight;});await expect(page.getByRole('button',{name:'Edit invoice KAT 1500',exact:true})).toBeVisible();expect(await page.locator('[data-invoice-row]').count()).toBeLessThan(45);
 await page.getByRole('button',{name:'Edit invoice KAT 1500',exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Last-row synthetic owner');await page.getByRole('button',{name:'Save row',exact:true}).click();await expect(page.getByRole('status')).toContainText('Invoice 1500 saved');expect(writes[0].values.ownerName).toBe('Last-row synthetic owner');await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();expect(await pane.evaluate(e=>e.scrollTop)).toBeGreaterThan(1000);
});
test('hiding a whole sheet retries only the unconfirmed batch and can restore every row',async({page})=>{
 const {writes}=await setup(page,{count:230,visibilityAmbiguous:true});await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();await page.getByLabel('Select all register rows',{exact:true}).check();await page.getByRole('button',{name:'Hide',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');await page.getByRole('button',{name:'Retry visibility',exact:true}).click();await expect(page.getByRole('status')).toHaveText('230 rows hidden from your register.');expect(writes.map(w=>w.rows.length)).toEqual([100,100,100,30]);expect(writes[1].commandId).toBe(writes[2].commandId);
 await page.getByLabel('Register row visibility').selectOption('hidden');await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();await expect(page.locator('.register-table')).toHaveAttribute('aria-rowcount','231');await page.getByLabel('Select all register rows',{exact:true}).check();await page.getByRole('button',{name:'Show',exact:true}).click();await expect(page.getByRole('status')).toHaveText('230 rows restored.');
});
test('a laptop sees invoice rows immediately below compact report controls',async({page})=>{await setup(page);await page.setViewportSize({width:1280,height:720});await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByText('All matching rows loaded',{exact:true})).toBeVisible();const box=await page.getByRole('region',{name:'Invoice register sheet',exact:true}).boundingBox();expect(box!.y+44+3*52).toBeLessThanOrEqual(720);await expect(page.getByRole('button',{name:'1234567890123',exact:true})).toBeInViewport();await page.screenshot({path:'evidence/register-sheet-laptop-720.png',fullPage:false});});

for(const width of [1440,1280,390])test(`sheet entry ${width}: Enter saves and moves down, Tab stays within the row`,async({page})=>{
 const {writes}=await setup(page,{count:70});await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'Reports',exact:true}).click();
 await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();
 await page.getByLabel('Owner',{exact:true}).fill('First owner');await page.getByLabel('Owner',{exact:true}).press('Tab');
 await expect(page.getByLabel('Reported received',{exact:true})).toBeFocused();expect(writes).toHaveLength(0);
 await page.getByLabel('Reported received',{exact:true}).fill('1500.50');await page.getByLabel('Reported received',{exact:true}).press('Enter');
 await expect(page.locator('tr.is-editing')).toContainText('2');await expect(page.getByLabel('Reported received',{exact:true})).toBeFocused();await expect.poll(()=>writes.length).toBe(1);
 expect(writes[0].values).toMatchObject({ownerName:'First owner',reportedReceived:'1500.50'});
 await page.getByLabel('Reported received',{exact:true}).fill('250');await page.getByLabel('Reported received',{exact:true}).press('Enter');await expect.poll(()=>writes.length).toBe(2);
 await page.getByLabel('Owner',{exact:true}).fill('Unsaved');await page.getByLabel('Owner',{exact:true}).press('Escape');await expect(page.getByLabel('Owner',{exact:true})).toHaveCount(0);expect(writes).toHaveLength(2);
 await page.getByRole('button',{name:'Notes & receipts',exact:true}).click();await page.screenshot({path:`.tmp/register-sheet/entry-${width}.png`,fullPage:false});
});
test('moving to another invoice cell saves once and focuses that exact destination',async({page})=>{
 const {writes}=await setup(page);await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Saved on move');
 await page.getByRole('button',{name:'Invoice note · KAT 2',exact:true}).click();await expect(page.getByLabel('Invoice note',{exact:true})).toBeFocused();await expect.poll(()=>writes.length).toBe(1);expect(writes[0].values.ownerName).toBe('Saved on move');
 await page.getByLabel('Invoice note',{exact:true}).press('Enter');await expect(page.getByLabel('Invoice note',{exact:true})).toBeFocused();expect(writes).toHaveLength(1);
});
test('a failed automatic save retains the row and retries the same command',async({page})=>{
 const {writes}=await setup(page,{ambiguous:true});await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Retained owner');await page.getByLabel('Owner',{exact:true}).press('Enter');
 await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByLabel('Owner',{exact:true})).toHaveValue('Retained owner');await expect(page.locator('tr.is-editing')).toContainText('1234567890123');
 await page.getByRole('button',{name:'Retry save',exact:true}).click();await expect(page.getByRole('status')).toContainText('Invoice 1234567890123 saved');expect(writes).toHaveLength(2);expect(writes[0].commandId).toBe(writes[1].commandId);
});

async function pasteCells(page:Page,value:string){await page.getByLabel('Owner',{exact:true}).evaluate((e,text)=>{const transfer=new DataTransfer();transfer.setData('text/plain',text);e.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));},value);}
test('pasted cells show exact invoice destinations before saving and link every row',async({page})=>{
 const {writes}=await setup(page);await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();
 await pasteCells(page,'Alice\t1,250.50\tFirst note\nBob\t0\tSecond note');const dialog=page.getByRole('dialog',{name:'Review pasted cells'});
 await expect(dialog).toContainText('2 invoice rows');await expect(dialog).toContainText('KAT · 1234567890123');await expect(dialog).toContainText('KAT · 2');expect(writes).toHaveLength(0);
 await page.screenshot({path:'.tmp/register-sheet/paste-review.png',fullPage:false});await dialog.getByRole('button',{name:'Save 2 rows',exact:true}).click();await expect(dialog).toHaveCount(0);
 expect(writes.map(w=>w.values)).toEqual([expect.objectContaining({ownerName:'Alice',reportedReceived:'1250.50',note:'First note'}),expect.objectContaining({ownerName:'Bob',reportedReceived:'0',note:'Second note'})]);
});
test('pasted batch stops on uncertainty and reuses the failed command before continuing',async({page})=>{
 const {writes}=await setup(page,{ambiguous:true});await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();await pasteCells(page,'Alice\nBob');const dialog=page.getByRole('dialog',{name:'Review pasted cells'});
 await dialog.getByRole('button',{name:'Save 2 rows',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('could not be confirmed');expect(writes).toHaveLength(1);
 await dialog.getByRole('button',{name:'Retry remaining rows',exact:true}).click();await expect(dialog).toHaveCount(0);expect(writes).toHaveLength(3);expect(writes[0].commandId).toBe(writes[1].commandId);expect(writes[2].commandId).not.toBe(writes[0].commandId);
});
test('paste cannot write OPERA columns or extend beyond existing invoices',async({page})=>{
 const {writes}=await setup(page,{count:1});await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();await pasteCells(page,'Alice\nBob');const dialog=page.getByRole('dialog',{name:'Review pasted cells'});await expect(dialog.getByRole('alert')).toContainText('beyond the loaded invoice rows');await expect(dialog.getByRole('button',{name:'Save 0 rows',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 await pasteCells(page,'Alice\t0\tNote\tReplacement guest');await expect(dialog.getByRole('alert')).toContainText('read-only OPERA');expect(writes).toHaveLength(0);
});

test('leaving the workspace with an unfinished row does not start a competing save',async({page})=>{
 const {writes}=await setup(page);await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Owner · KAT 1234567890123',exact:true}).click();await page.getByLabel('Owner',{exact:true}).fill('Unfinished owner');
 page.on('dialog',dialog=>dialog.dismiss());await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Aging',exact:true}).click();await expect(page.getByLabel('Owner',{exact:true})).toHaveValue('Unfinished owner');expect(writes).toHaveLength(0);
});
