import {test,expect,type Page} from '@playwright/test';
const id='00000000-0000-4000-8000-000000000001',user={id,email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-10T00:00:00Z'};
async function setup(page:Page){const calls:string[]=[];await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic',refresh_token:'synthetic',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:u})),user);await page.route('https://example.supabase.co/**',r=>r.fulfill({json:{user}}));await page.route('**/api/**',async route=>{const r=route.request(),u=new URL(r.url()),p=u.pathname;calls.push(r.method()+' '+p+u.search);
 if(p==='/api/config')return route.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic',writeHold:true}});
 if(p==='/api/collection-policy')return route.fulfill({status:503,json:{error:'policy_unavailable'}});
 if(p==='/api/portfolio')return route.fulfill({json:{status:'connected',accounts:[],refresh:{running:false,hotels:[]}}});
 if(p==='/api/refresh')return route.fulfill({json:{jobs:[],running:false,hotels:[]}});
 if(p==='/api/operations/queue')return route.fulfill({json:{total:51,writeHold:true,rows:[{kind:'email',id,hotel:'KAT',label:u.searchParams.get('page')==='1'?'Synthetic second-page work':'Synthetic unfinished handoff',state:'awaiting_evidence',updated_at:'2026-09-10T10:00:00Z',job_id:id,delivery_id:id,reason:'no_sent_evidence'}]}});
 if(p.endsWith('/check'))return route.fulfill({json:{state:'awaiting_evidence'}});
 if(p==='/api/operations/recovery-sent')return route.fulfill({json:{from:u.searchParams.get('from'),to:u.searchParams.get('to'),scanned:1,rows:[{deliveryId:id,gmailId:u.searchParams.has('pageToken')?'synthetic2':'synthetic1',sentAt:'2026-09-10T10:00:00Z',state:u.searchParams.has('pageToken')?'recorded':'missing_receipt'}],nextPageToken:u.searchParams.has('pageToken')?null:'synthetic-next',complete:u.searchParams.has('pageToken')}});
 return route.fulfill({status:501,json:{error:'unexpected_synthetic_request'}});
});return calls;}
test('work queue preserves unknown outcomes and never offers a resend shortcut',async({page})=>{const calls=await setup(page);await page.goto('/?operations=1');await expect(page.getByRole('heading',{name:'Operations & recovery',exact:true})).toBeVisible();await expect(page.getByText('Synthetic unfinished handoff')).toBeVisible();await expect(page.getByRole('button',{name:'Refresh OPERA',exact:true})).toBeDisabled();expect(calls.some(c=>c==='POST /api/refresh')).toBe(false);await page.getByRole('button',{name:'Check existing SENT',exact:true}).click();await expect(page.getByText('No complete SENT match was confirmed.',{exact:false})).toBeVisible();expect(calls.filter(c=>c.startsWith('POST'))).toEqual([`POST /api/email/deliveries/${id}/check`]);await page.getByRole('navigation',{name:'Operations pages'}).getByRole('button',{name:'Next'}).click();await expect(page.getByText('Synthetic second-page work')).toBeVisible();});
test('SENT audit is explicit and reads all pages without inventing a missing receipt',async({page})=>{const calls=await setup(page);await page.goto('/?operations=1');await expect(page.getByRole('heading',{name:'Post-backup SENT audit'})).toBeVisible();expect(calls.some(c=>c.includes('recovery-sent'))).toBe(false);await page.getByRole('button',{name:'Read SENT metadata',exact:true}).click();await expect(page.getByRole('heading',{name:'Missing database receipt'})).toBeVisible();await expect(page.getByText('More results available',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Read next page'}).click();await expect(page.getByRole('heading',{name:'Receipt recorded',exact:true})).toBeVisible();await expect(page.getByText('2 SENT messages scanned',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Read next page'})).toHaveCount(0);expect(calls.some(c=>c.startsWith('POST'))).toBe(false);});
for(const [width,height] of [[1440,900],[1280,800],[390,844]])test(`operations is usable at ${width}`,async({page})=>{await setup(page);await page.setViewportSize({width,height});await page.goto('/?operations=1');await expect(page.getByText('Synthetic unfinished handoff')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`evidence/operations-${width}.png`,fullPage:true});});
