import {test,expect,type Page} from '@playwright/test';
const user={id:'00000000-0000-4000-8000-000000000001',email:'ar@katathani.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-09-10T00:00:00Z'};
async function setup(page:Page,{unavailable=false}={}){
 const calls:string[]=[];let pending=true;
 await page.addInitScript(u=>localStorage.setItem('sb-example-auth-token',JSON.stringify({access_token:'synthetic-app-token',refresh_token:'synthetic-refresh',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:u})),user);
 await page.route('https://example.supabase.co/**',route=>route.fulfill({json:{user}}));
 await page.route('**/api/**',async route=>{const r=route.request(),u=new URL(r.url()),p=u.pathname;calls.push(r.method()+' '+p+u.search);
  if(p==='/api/config')return route.fulfill({json:{supabaseUrl:'https://example.supabase.co',publishableKey:'synthetic-key'}});
  if(p==='/api/collection-policy')return route.fulfill({json:{available:false}});
  if(p==='/api/refresh')return route.fulfill({json:{jobs:[],running:false,hotels:[]}});
  if(p==='/api/portfolio')return route.fulfill({json:{status:'connected',accounts:[],refresh:{running:false,hotels:[]}}});
  if(p==='/api/drive/status')return route.fulfill({json:{configured:true,connected:true,email:'ar@katathani.com',folder:null,cleanupDisabled:false,pickerConfigured:false}});
  if(p==='/api/operations/status')return unavailable?route.fulfill({status:503,json:{error:'budget_usage_unverified'}}):route.fulfill({json:{enabled:true,activatedAt:'2026-09-11T00:00:00Z',active:pending?1:0,unresolved:pending?1:0,chargedEgress:10485760,limits:{storedBytes:1073741824,egressBytes:2147483648,databaseBytes:268435456,safetyPercent:20},measurement:{periodStart:'2026-08-31T17:00:00Z',periodEnd:'2026-09-30T17:00:00Z',used:{storedBytes:12582912,databaseBytes:41943040},observedAt:{storedBytes:'2026-09-11T01:00:00Z',databaseBytes:'2026-09-11T01:00:00Z'}},pendingUploads:pending?[{id:'00000000-0000-4000-8000-000000000002',byteCount:1024,createdAt:'2026-09-11T00:30:00Z',originFinished:true}]:[]}});
  if(p.endsWith('/reconcile')){pending=false;return route.fulfill({json:{verified:true}});}
  if(p==='/api/operations/retention')return route.fulfill({json:{enabled:true,total:51,summary:{waiting:48,blocked:1,uncertain:1,deleted:1,deletedBytes:100},rows:[{id:u.searchParams.get('page')==='1'?'second-reference':'first-reference',store:'supabase',state:'waiting',reason:'retention_waiting',eligibleSince:'2026-09-11T00:00:00Z',dueAt:'2026-10-11T00:00:00Z',deletedAt:null,bytes:1024}]}});
  return route.fulfill({status:501,json:{error:'unexpected_synthetic_api'}});
 });return calls;
}
test('usage and retention show measured scope, reconcile exact upload, and paginate',async({page})=>{const calls=await setup(page);await page.goto('/?storage=1');await expect(page.getByRole('heading',{name:'Working files & usage'})).toBeVisible();await expect(page.getByText('12 MiB',{exact:true})).toBeVisible();await expect(page.getByText(/not the total Supabase bill/)).toBeVisible();await page.getByRole('button',{name:'Check uploaded file'}).click();await expect(page.getByText('The exact uploaded bytes were verified. No new upload was sent.')).toBeVisible();await expect(page.getByRole('button',{name:'Check uploaded file'})).toHaveCount(0);expect(calls.filter(c=>c.startsWith('POST')&&c!=='POST /api/refresh')).toEqual(['POST /api/operations/uploads/00000000-0000-4000-8000-000000000002/reconcile']);await page.getByRole('navigation',{name:'Retention pages'}).getByRole('button',{name:'Next'}).click();await expect(page.getByText('Reference second-r',{exact:false})).toBeVisible();expect(calls).toContain('GET /api/operations/retention?page=1');});
test('unknown usage never renders a fabricated zero',async({page})=>{await setup(page,{unavailable:true});await page.goto('/?storage=1');await expect(page.getByRole('alert')).toContainText('Storage controls are unavailable');await expect(page.getByText('0 MiB',{exact:true})).toHaveCount(0);});
for(const [width,height] of [[1440,900],[1280,800],[390,844]])test(`storage controls fit ${width}`,async({page})=>{await setup(page);await page.setViewportSize({width,height});await page.goto('/?storage=1');await expect(page.getByRole('heading',{name:'Completed-file retention'})).toBeVisible();await expect(page.getByText('Keeping files for one calendar month')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`evidence/storage-controls-${width}.png`,fullPage:true});});
