import {test,expect} from '@playwright/test';
import {auditWorkspace,auditLogin,auditRoute} from './fixtures/audit-workspace';
const rows=Array.from({length:122},(_,i)=>({id:'10000000-0000-4000-8000-'+String(i+1).padStart(12,'0'),rowKey:'SYNTH conflict row '+(i+1),field:i<60?'identity':i<120?['S','T','AA'][i%3]:i===120?'R':'U',reason:'concurrent_or_unmapped_edit',sheetValue:i<120?'30':'2026-10-04',webValue:null,revision:7,createdAt:'2026-10-06T09:00:00.123456Z'}));
for(const width of [1280,390])test(`held dates are reachable by category and pages ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await auditWorkspace(page);const commands:unknown[]=[],queries:URLSearchParams[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/reports/sheets',r=>r.fulfill({json:{rows:[{region:'phuket',url:'https://docs.google.com/spreadsheets/d/synthetic_phuket_sheet_12345/edit'}]}}));
 await page.route('**/api/reports/tracker?region=phuket',async r=>{if(r.request().method()==='POST'){commands.push(r.request().postDataJSON());return r.fulfill({json:{resolved:true}});}return r.fulfill({json:{connected:true,enabled:true,available:true,bootstrapConfirmed:true,revision:1,lastCheckedAt:null,pending:21,conflictCount:122,heldWrites:21,writebackAvailable:false,conflicts:rows.slice(0,50)}});});
 await page.route('**/api/reports/tracker-conflicts?*',async r=>{const q=new URL(r.request().url()).searchParams;queries.push(q);const category=q.get('category')!,filtered=category==='dates'?rows.slice(120):category==='identity'?rows.slice(0,60):category==='references'?rows.slice(60,120):rows;const offset=q.get('cursor')==='synthetic-page-2'?100:q.get('cursor')==='synthetic-page-1'?50:0;return r.fulfill({json:{region:'phuket',category,counts:{all:122,dates:2,references:60,identity:60,other:0},rows:filtered.slice(offset,offset+50),nextCursor:offset+50<filtered.length?'synthetic-page-'+(offset===0?1:2):null}});});
 await auditLogin(page);await auditRoute(page,'reports=1&reportsTab=sheets');const panel=page.locator('[aria-label="phuket tracker synchronization"]');await panel.getByRole('button',{name:'Review differences (122)'}).click();await expect(panel.getByText('SYNTH conflict row 1',{exact:true})).toBeVisible();await expect(panel.getByRole('combobox',{name:'Difference type'})).toContainText('Billing & follow-up dates (2)');
 await panel.getByRole('button',{name:'Next',exact:true}).click();await expect(panel.getByText('SYNTH conflict row 51',{exact:true})).toBeVisible();await panel.getByRole('button',{name:'Next',exact:true}).click();await expect(panel.getByText('SYNTH conflict row 121',{exact:true})).toBeVisible();expect(commands).toHaveLength(0);
 await panel.getByRole('button',{name:'Back',exact:true}).click();await expect(panel.getByText('SYNTH conflict row 51',{exact:true})).toBeVisible();
 await panel.getByRole('combobox',{name:'Difference type'}).selectOption('dates');await expect(panel.getByText('SYNTH conflict row 121',{exact:true})).toBeVisible();await expect(panel.locator('article')).toHaveCount(2);await expect(panel.locator('article').first()).toContainText('First billing date (R)');await expect(panel.locator('article').last()).toContainText('Follow-up 1 date (U)');await expect(panel.getByRole('button',{name:'Back',exact:true})).toBeDisabled();await expect(panel.getByRole('button',{name:'Next',exact:true})).toBeDisabled();expect(queries.at(-1)!.get('cursor')).toBeNull();
 await panel.getByRole('button',{name:'Keep AR value',exact:true}).first().click();expect(commands).toEqual([{action:'resolve',conflictId:rows[120].id,revision:7,choice:'keep_web'}]);await expect(panel.getByText('SYNTH conflict row 121',{exact:true})).toBeVisible();expect(queries.at(-1)!.get('cursor')).toBeNull();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await panel.screenshot({path:`.tmp/tracker-conflict-pages/held-dates-${width}.png`});
});
test('category changes discard late stale responses and failed page shows retry',async({page})=>{
 await auditWorkspace(page);await page.route('**/api/reports/sheets',r=>r.fulfill({json:{rows:[{region:'phuket',url:'https://docs.google.com/spreadsheets/d/synthetic_phuket_sheet_12345/edit'}]}}));await page.route('**/api/reports/tracker?region=phuket',r=>r.fulfill({json:{connected:true,enabled:true,available:true,bootstrapConfirmed:true,revision:1,lastCheckedAt:null,pending:0,conflictCount:122,conflicts:rows.slice(0,50)}}));let failDates=true,releaseReferences!:()=>void,referencesStarted!:()=>void;const referencesPending=new Promise<void>(r=>{referencesStarted=r;});
 await page.route('**/api/reports/tracker-conflicts?*',async r=>{const category=new URL(r.request().url()).searchParams.get('category')!;if(category==='references'){referencesStarted();await new Promise<void>(resolve=>{releaseReferences=resolve;});}if(category==='dates'&&failDates)return r.fulfill({status:503,json:{error:'synthetic_unavailable'}});await r.fulfill({json:{region:'phuket',category,counts:{all:122,dates:2,references:60,identity:60,other:0},rows:category==='dates'?rows.slice(120):category==='references'?rows.slice(60,110):rows.slice(0,50),nextCursor:category==='dates'?null:'synthetic-page-1'}}).catch(()=>{});});
 await auditLogin(page);await auditRoute(page,'reports=1&reportsTab=sheets');const panel=page.locator('[aria-label="phuket tracker synchronization"]');await panel.getByRole('button',{name:'Review differences (122)'}).click();await expect(panel.getByText('SYNTH conflict row 1',{exact:true})).toBeVisible();await panel.getByRole('combobox',{name:'Difference type'}).selectOption('references');await referencesPending;await panel.getByRole('combobox',{name:'Difference type'}).selectOption('dates');await expect(panel.getByRole('alert')).toContainText('Differences could not be loaded');releaseReferences();await expect(panel.locator('article')).toHaveCount(0);failDates=false;await panel.getByRole('button',{name:'Retry differences'}).click();await expect(panel.locator('article')).toHaveCount(2);await expect(panel.getByText('SYNTH conflict row 61',{exact:true})).toHaveCount(0);
});
