import {allowedEmail,boundedBytes,fileIdPattern,readJson,type Archive,type DriveFile} from './shared';
const root='https://www.googleapis.com/drive/v3';
export interface Metadata {id?:string;name?:string;mimeType?:string;trashed?:boolean;parents?:string[];size?:string;sha256Checksum?:string;appProperties?:Record<string,string>;webViewLink?:string;driveId?:string;owners?:{emailAddress?:string}[];capabilities?:{canAddChildren?:boolean;canTrash?:boolean}}
export async function google(url:string,token:string,init:RequestInit={}){const u=new URL(url);if(u.protocol!=='https:'||u.host!=='www.googleapis.com'||u.username||u.password||u.hash||!/^\/(?:drive\/v3\/|upload\/drive\/v3\/files$)/.test(u.pathname))throw Error('drive_unsafe_upload_url');return fetch(u,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),Authorization:'Bearer '+token},redirect:'manual',signal:init.signal?AbortSignal.any([init.signal,AbortSignal.timeout(90000)]):AbortSignal.timeout(90000)});}
export async function checkedJson(r:Response){if(!r.ok){await r.body?.cancel();throw Error(r.status===401?'drive_reconnect_required':'drive_unavailable');}return readJson(r);}
export async function identity(token:string){const value=await checkedJson(await google(root+'/about?fields=user(emailAddress)',token));const user=value.user as {emailAddress?:string}|undefined;if(user?.emailAddress?.toLowerCase()!==allowedEmail)throw Error('drive_identity_mismatch');return allowedEmail;}
export async function metadata(token:string,id:string):Promise<Metadata|null>{if(!fileIdPattern.test(id))throw Error('drive_invalid');const q=new URLSearchParams({supportsAllDrives:'true',fields:'id,name,mimeType,trashed,parents,size,sha256Checksum,appProperties,webViewLink,driveId,owners(emailAddress),capabilities(canAddChildren,canTrash)'});const r=await google(root+'/files/'+id+'?'+q,token);if(r.status===404){await r.body?.cancel();return null;}return await checkedJson(r) as Metadata;}
async function visibility(token:string,id:string):Promise<'public'|'restricted'|'unknown'>{
 let page='';let onlyOwner=true;const seen=new Set<string>();
 try{for(let i=0;i<100;i++){const q=new URLSearchParams({supportsAllDrives:'true',pageSize:'100',fields:'nextPageToken,permissions(type,role,emailAddress)'});if(page)q.set('pageToken',page);const v=await checkedJson(await google(root+'/files/'+id+'/permissions?'+q,token));if(!Array.isArray(v.permissions)||v.permissions.length===0)return 'unknown';
 for(const p of v.permissions as {type?:string;role?:string;emailAddress?:string}[]){if(p.type==='anyone'||p.type==='domain')return 'public';if(p.type!=='user'||p.role!=='owner'||p.emailAddress?.toLowerCase()!==allowedEmail)onlyOwner=false;}
 if(!v.nextPageToken)return onlyOwner?'restricted':'unknown';if(typeof v.nextPageToken!=='string'||seen.has(v.nextPageToken))return 'unknown';page=v.nextPageToken;seen.add(page);}
 }catch{return 'unknown';}return 'unknown';
}
export async function verifyFolder(token:string,id:string){const m=await metadata(token,id);if(!m||m.id!==id||m.mimeType!=='application/vnd.google-apps.folder'||m.trashed!==false||m.capabilities?.canAddChildren!==true)throw Error('drive_folder_unavailable');
 if(!m.driveId&&!m.owners?.some(o=>o.emailAddress?.toLowerCase()===allowedEmail))throw Error('drive_identity_mismatch');
 return {name:m.name??'Archive folder',driveId:m.driveId??null,visibility:await visibility(token,id)};
}
export async function generateId(token:string){const v=await checkedJson(await google(root+'/files/generateIds?count=1&space=drive&type=files',token));const id=Array.isArray(v.ids)?v.ids[0]:null;if(typeof id!=='string'||!fileIdPattern.test(id))throw Error('drive_unavailable');return id;}
export function properties(a:Archive,f:DriveFile){return {ar_owner:a.owner,ar_archive:a.id,ar_job:a.document_job_id??'synthetic',ar_revision:String(a.document_revision??0),ar_test:a.kind==='test'?'true':'false',ar_sha256:f.sha256,ar_ordinal:String(f.ordinal)};}
export function verifyMetadata(m:Metadata,a:Archive,f:DriveFile,allowTrashed=false){
 if(m.id!==f.drive_file_id||m.mimeType!=='application/pdf'||typeof m.trashed!=='boolean'||(!allowTrashed&&m.trashed!==false)||m.parents?.length!==1||m.parents[0]!==a.folder_id||m.size!==String(f.byte_count)||(!m.driveId&&!m.owners?.some(o=>o.emailAddress?.toLowerCase()===allowedEmail)))throw Error('drive_metadata_mismatch');
 for(const [k,v] of Object.entries(properties(a,f)))if(m.appProperties?.[k]!==v)throw Error('drive_metadata_mismatch');
 if(m.sha256Checksum?.toLowerCase()!==f.sha256)throw Error('drive_checksum_mismatch');
 let url:string|null=null;if(m.webViewLink){const u=new URL(m.webViewLink);if(u.protocol==='https:'&&u.hostname==='drive.google.com'&&!u.username&&!u.password)url=u.href;}return url;
}
export function trustedSession(value:string){let u:URL;try{u=new URL(value);}catch{throw Error('drive_unsafe_upload_url');}if(u.protocol!=='https:'||u.host!=='www.googleapis.com'||u.pathname!=='/upload/drive/v3/files'||u.username||u.password||u.hash||u.searchParams.get('uploadType')!=='resumable'||!u.searchParams.get('upload_id'))throw Error('drive_unsafe_upload_url');return u.href;}
export async function beginUpload(token:string,a:Archive,f:DriveFile){const r=await google('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&supportsAllDrives=true',token,{method:'POST',headers:{'Content-Type':'application/json','X-Upload-Content-Type':'application/pdf','X-Upload-Content-Length':String(f.byte_count)},body:JSON.stringify({id:f.drive_file_id,name:f.name,mimeType:'application/pdf',parents:[a.folder_id],appProperties:properties(a,f)})});
 if(r.status===409){await r.body?.cancel();return null;}if(!r.ok){await r.body?.cancel();throw Error('drive_unavailable');}const location=r.headers.get('Location');await r.body?.cancel();if(!location)throw Error('drive_unavailable');return trustedSession(location);
}
export async function uploadPosition(token:string,session:string,size:number){const r=await google(trustedSession(session),token,{method:'PUT',headers:{'Content-Range':`bytes */${size}`,'Content-Length':'0'},body:''});await r.body?.cancel();if(r.ok)return {complete:true,offset:size,expired:false};if(r.status===404||r.status===410)return {complete:false,offset:0,expired:true};if(r.status!==308)throw Error('drive_unavailable');const range=r.headers.get('Range');if(range&&!/^bytes=0-\d+$/.test(range))throw Error('drive_unavailable');const offset=range?Number(range.slice(8))+1:0;if(!Number.isSafeInteger(offset)||offset<0||offset>=size)throw Error('drive_unavailable');return {complete:false,offset,expired:false};}
export async function uploadStream(token:string,session:string,stream:ReadableStream<Uint8Array>,offset:number,size:number){
 const url=trustedSession(session),fixed=new FixedLengthStream(size-offset),abort=new AbortController();
 // Workers derives Content-Length from the body; a manually set header on a generic stream is ignored.
 const pump=stream.pipeTo(fixed.writable,{signal:abort.signal});
 const send=google(url,token,{method:'PUT',headers:{'Content-Type':'application/pdf','Content-Length':String(size-offset),'Content-Range':`bytes ${offset}-${size-1}/${size}`},body:fixed.readable,signal:abort.signal}).then(async r=>{await r.body?.cancel();if(!r.ok&&r.status!==409)throw Error(r.status===308?'drive_upload_pending':'drive_unavailable');});
 try{await Promise.all([pump,send]);}catch(e){abort.abort();await Promise.allSettled([pump,send]);throw e;}
}
export async function readTest(token:string,a:Archive,f:DriveFile){if(a.kind!=='test'||!f.drive_file_id)throw Error('drive_forbidden');const r=await google(root+'/files/'+f.drive_file_id+'?alt=media&supportsAllDrives=true',token);if(!r.ok){await r.body?.cancel();throw Error('drive_unavailable');}return boundedBytes(r,f.byte_count);}
export async function trashTest(token:string,a:Archive,f:DriveFile){if(a.kind!=='test'||!f.drive_file_id)throw Error('drive_forbidden');const before=await metadata(token,f.drive_file_id);if(!before)throw Error('drive_cleanup_failed');verifyMetadata(before,a,f,true);if(before.trashed===true)return;
 if(before.capabilities?.canTrash!==true)throw Error('drive_cleanup_failed');const r=await google(root+'/files/'+f.drive_file_id+'?supportsAllDrives=true&fields=id,trashed',token,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({trashed:true})});await checkedJson(r);const after=await metadata(token,f.drive_file_id);if(!after)throw Error('drive_cleanup_failed');verifyMetadata(after,a,f,true);if(after.trashed!==true)throw Error('drive_cleanup_failed');}
