import {readJson} from '../drive/shared';
import {trackerFields,trackerHotel,type TrackerField} from './model';
import {trackerHeaders,trackerDateValue} from './workbook';
import type {ProviderRow,ProviderSnapshot,ProviderWrite} from './service';
const TITLE='ลูกหนี้ เขาหลัก',ROOT='https://sheets.googleapis.com/v4/spreadsheets/';
const dates=new Set(['R','T','U','V','W','X']),allowed=new Set(['R','U','V','W']);
interface Cell {userEnteredValue?:{stringValue?:string;numberValue?:number;formulaValue?:string;boolValue?:boolean};effectiveValue?:{stringValue?:string;numberValue?:number;boolValue?:boolean;errorValue?:unknown};formattedValue?:string;textFormatRuns?:unknown[];chipRuns?:unknown[];userEnteredFormat?:{numberFormat?:{type?:string;pattern?:string}};effectiveFormat?:{numberFormat?:{type?:string;pattern?:string}}}
interface Sheet {properties:{sheetId:number;title:string};data?:{startRow?:number;startColumn?:number;rowData?:{values?:Cell[]}[]}[]}
const column=(name:string)=>[...name].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1;
async function request(token:string,file:string,suffix:string,init:RequestInit={}){if(!/^[A-Za-z0-9_-]{20,200}$/.test(file))throw Error('tracker_target_conflict');return fetch(ROOT+file+suffix,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),Authorization:'Bearer '+token},redirect:'manual',signal:AbortSignal.timeout(90000)});}
function raw(cell:Cell|undefined):string|null{if(!cell)return null;const v=cell.userEnteredValue?.formulaValue?cell.effectiveValue:cell.userEnteredValue??cell.effectiveValue;if(v===undefined)return null;if('errorValue'in v)throw Error('tracker_native_cell_invalid');if(typeof v.stringValue==='string')return v.stringValue;if(typeof v.numberValue==='number'&&Number.isFinite(v.numberValue))return String(v.numberValue);if(typeof v.boolValue==='boolean')return v.boolValue?'TRUE':'FALSE';throw Error('tracker_native_cell_invalid');}
function identityValue(cell:Cell|undefined):string {if(cell?.userEnteredValue?.formulaValue||typeof (cell?.userEnteredValue??cell?.effectiveValue)?.boolValue==='boolean')throw Error('tracker_native_identity_invalid');let value=raw(cell)?.trim()??'';const numeric=cell?.userEnteredValue?cell.userEnteredValue.numberValue:cell?.effectiveValue?.numberValue,format=cell?.userEnteredFormat?.numberFormat?.pattern??cell?.effectiveFormat?.numberFormat?.pattern;if(numeric!==undefined){if(!Number.isSafeInteger(numeric)||numeric<0||format&&!/^0{1,20}$/.test(format)&&format!=='General')throw Error('tracker_native_identity_invalid');if(format&&/^0{2,20}$/.test(format))value=value.padStart(format.length,'0');}return value;}
function blockedDate(cell:Cell|undefined){return !!cell?.userEnteredValue?.formulaValue||[cell?.textFormatRuns,cell?.chipRuns].some(r=>r!==undefined&&(!Array.isArray(r)||r.length>0));}
function date(value:string|null):string|null {const result=trackerDateValue(value??'',false);if(result&&(!/^\d{4}-\d{2}-\d{2}$/.test(result)||new Date(result+'T00:00:00Z').toISOString().slice(0,10)!==result))throw Error('tracker_native_date_invalid');return result;}
function parse(value:Record<string,unknown>,file:string){
 if(value.spreadsheetId!==file||!Array.isArray(value.sheets))throw Error('tracker_native_schema_invalid');
 const matches=(value.sheets as Sheet[]).filter(s=>s.properties?.title===TITLE);if(matches.length!==1)throw Error('tracker_native_schema_invalid');const sheet=matches[0],gid=sheet.properties.sheetId;if(!Number.isInteger(gid)||gid<0)throw Error('tracker_native_schema_invalid');
 const grid=new Map<number,Cell[]>();for(const data of sheet.data??[]){if((data.startColumn??0)!==0||!Array.isArray(data.rowData))throw Error('tracker_native_schema_invalid');const first=data.startRow??0;if(!Number.isInteger(first)||first<0)throw Error('tracker_native_schema_invalid');for(let i=0;i<data.rowData.length;i++){if(first+i>100001||grid.has(first+i))throw Error('tracker_native_schema_invalid');grid.set(first+i,data.rowData[i].values??[]);}}
 const headers=grid.get(1),fallback=!raw(headers?.[0])?grid.get(0)?.[0]:undefined;
 if(!headers||!Object.entries(trackerHeaders).every(([col,title])=>raw(col==='A'&&fallback?fallback:headers[column(col)])?.trim()===title)||Object.values(trackerHeaders).some(title=>headers.filter(c=>raw(c)?.trim()===title).length+(title==='Property'&&raw(fallback)?.trim()===title?1:0)!==1))throw Error('tracker_native_schema_invalid');
 const rows:ProviderRow[]=[],keys=new Set<string>(),identities=new Set<string>(),cells=new Map<string,Cell[]>();
 for(const [rowIndex,row]of grid){if(rowIndex<2)continue;const get=(col:string)=>row[column(col)];if(get('AG')?.userEnteredValue?.formulaValue)throw Error('tracker_native_identity_invalid');const key=raw(get('AG'))??'';if(!key)continue;const hotel=trackerHotel(identityValue(get('A')),'khao-lak');if(!hotel)continue;if(keys.has(key))throw Error('tracker_native_identity_ambiguous');keys.add(key);
  const issues:string[]=[];let accountNo='',invoiceNo='',folio:string|null=null,transactionDate:string|null=null;try{accountNo=identityValue(get('C'));invoiceNo=identityValue(get('E'));folio=identityValue(get('F'))||null;if(get('G')?.userEnteredValue?.formulaValue)throw Error('tracker_native_identity_invalid');transactionDate=date(raw(get('G')));}catch{issues.push('identity_invalid');}if(!accountNo)issues.push('account_missing');if(!invoiceNo)issues.push('invoice_missing');
  const identity=JSON.stringify([hotel,accountNo,invoiceNo,folio]);if(accountNo&&invoiceNo&&identities.has(identity))throw Error('tracker_native_identity_ambiguous');identities.add(identity);
  const fields:ProviderRow['fields']={},formulaFields:TrackerField[]=[];for(const field of trackerFields){const cell=get(field);if(cell?.userEnteredValue?.formulaValue)formulaFields.push(field);try{fields[field]=dates.has(field)?date(raw(cell)):raw(cell)||null;}catch{fields[field]=cell?.formattedValue??null;issues.push(field+'_invalid');}}
  rows.push({rowKey:key,hotel,accountNo,invoiceNo,folio,folioNo:folio,transactionDate,fields,locator:{sheetId:gid,sheetName:TITLE,rowIndex},issues,formulaFields,blockedWriteFields:(['R','U','V','W'] as const).filter(f=>blockedDate(get(f)))});cells.set(key,row);
 }
 return {rows,cells,gid};
}
export function trackerIdentityMatches(row:ProviderRow,identity:ProviderWrite['expectedIdentity']):boolean{return !!identity&&row.hotel===identity.hotel&&row.accountNo===identity.accountNo&&row.invoiceNo===identity.invoiceNo&&(row.folio??null)===(identity.folio??null)&&(row.transactionDate??null)===(identity.transactionDate??null);}
export async function readNativeTracker(token:string,file:string):Promise<ProviderSnapshot>{
 const query=new URLSearchParams({includeGridData:'true',ranges:`'${TITLE}'!A:AG`,fields:'spreadsheetId,sheets(properties(sheetId,title),data(startRow,startColumn,rowData(values(userEnteredValue,effectiveValue,formattedValue,userEnteredFormat(numberFormat),effectiveFormat(numberFormat),textFormatRuns,chipRuns))))'});
 const response=await request(token,file,'?'+query);if(!response.ok){await response.body?.cancel();throw Error(response.status===401||response.status===403||response.status===404?'tracker_authorization_required':'tracker_provider_unavailable');}
 const value=await readJson(response,16*1024*1024),parsed=parse(value,file),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value))))].map(b=>b.toString(16).padStart(2,'0')).join('');
 return {version:'native-observed:'+hash,rows:parsed.rows,schemaFingerprint:JSON.stringify([TITLE,parsed.gid,trackerHeaders]),capabilities:{conditionalWrite:'unverified',writeAssurance:'best-effort'}};
}
export async function writeNativeTrackerBatch(token:string,file:string,inputs:readonly ProviderWrite[]):Promise<{status:'written'|'conflict'|'uncertain';version?:string}>{
 if(!inputs.length||inputs.length>100||inputs.reduce((n,i)=>n+i.changes.length,0)>300)throw Error('tracker_batch_limit');
 const current=await readNativeTracker(token,file),requests:unknown[]=[],seen=new Map<string,string>();
 for(const input of inputs){const row=current.rows.find(r=>r.rowKey===input.rowKey);if(!row||!trackerIdentityMatches(row,input.expectedIdentity)||row.issues?.some(i=>!/^([A-Z]{1,2})_invalid$/.test(i))||!input.changes.length)return {status:'conflict'};
  for(const change of input.changes){if(!allowed.has(change.field)||typeof change.value!=='string')throw Error('tracker_patch_forbidden');let day:string|null;try{day=date(change.value);}catch{return {status:'conflict'};}if(!day||day!==change.value||row.blockedWriteFields?.includes(change.field as 'R'|'U'|'V'|'W')||row.issues?.includes(change.field+'_invalid')||(row.fields[change.field]??null)!==change.expected)return {status:'conflict'};const key=input.rowKey+':'+change.field,prior=seen.get(key);if(prior&&prior!==day)return {status:'conflict'};if(prior)continue;seen.set(key,day);const locator=row.locator as {sheetId:number;rowIndex:number};requests.push({updateCells:{start:{sheetId:locator.sheetId,rowIndex:locator.rowIndex,columnIndex:column(change.field)},rows:[{values:[{userEnteredValue:{numberValue:(Date.parse(day+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000}}]}],fields:'userEnteredValue'}});}
 }
 // One best-effort atomic request, without any conditional-write guarantee.
 try{const response=await request(token,file,':batchUpdate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests,includeSpreadsheetInResponse:false})});if(!response.ok){await response.body?.cancel();return {status:'uncertain'};}const result=await readJson(response);if(result.spreadsheetId!==file)return {status:'uncertain'};}catch{return {status:'uncertain'};}
 try{const after=await readNativeTracker(token,file);if(after.schemaFingerprint!==current.schemaFingerprint)return {status:'uncertain',version:after.version};for(const input of inputs){const row=after.rows.find(r=>r.rowKey===input.rowKey);if(!row||!trackerIdentityMatches(row,input.expectedIdentity)||input.changes.some(c=>row.formulaFields?.includes(c.field)||row.fields[c.field]!==c.value))return {status:'uncertain',version:after.version};}return {status:'written',version:after.version};}catch{return {status:'uncertain'};}
}
