import {useEffect,useState} from 'react';
import {REGION_IDS,regionLabel} from '../domain/hotels';
import {mailboxSender,type MailboxId} from '../domain/mailboxes';
import {connectedMailbox,type GmailState} from './mailbox-ui';
import '../operations/operations.css';
export default function GmailSettings({token,onDirtyChange}:{token:string;onDirtyChange:(value:boolean)=>void}){
 const [states,setStates]=useState<Partial<Record<MailboxId,GmailState>>>({}),[errors,setErrors]=useState<Partial<Record<MailboxId,string>>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState<MailboxId|null>(null),[revision,setRevision]=useState(0);
 useEffect(()=>{onDirtyChange(false);return()=>onDirtyChange(false);},[onDirtyChange]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setStates({});setErrors({});void Promise.all(REGION_IDS.map(async region=>{try{const r=await fetch(`/api/gmail/status?region=${region}`,{headers:{Authorization:'Bearer '+token},signal:controller.signal});if(!r.ok)throw Error();const state=await r.json() as GmailState;if(state.region!==region||state.expectedEmail!==mailboxSender(region))throw Error();if(!controller.signal.aborted)setStates(old=>({...old,[region]:state}));}catch{if(!controller.signal.aborted)setErrors(old=>({...old,[region]:'Connection status unavailable. Retry to check this mailbox.'}));}})).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,revision]);
 async function connect(region:MailboxId){if(busy)return;setBusy(region);setErrors(old=>({...old,[region]:undefined}));try{const r=await fetch('/api/gmail/connect',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({region})});if(!r.ok)throw Error();const result=await r.json() as {url:string},url=new URL(result.url);if(url.origin!=='https://accounts.google.com')throw Error();location.assign(url.href);}catch{setErrors(old=>({...old,[region]:'Gmail authorization could not start. Retry this mailbox connection.'}));setBusy(null);}}
 return <section className="page" aria-label="Gmail connections"><h1>Gmail connections</h1>{new URLSearchParams(location.search).get('gmail')==='failed'&&<p role="alert" className="error-message">Gmail authorization failed. Connect the expected mailbox shown below and select that Google account.</p>}{new URLSearchParams(location.search).get('gmail')==='connected'&&<p role="status">Gmail authorization returned. Check the mailbox status below.</p>}{REGION_IDS.map(region=>{const state=states[region],connected=connectedMailbox(state??null,region);return <section className="panel operations-section" key={region} aria-label={`${regionLabel(region)} Gmail connection`}><h2>{regionLabel(region)}</h2><p><strong>{mailboxSender(region)}</strong></p><p role="status">{loading&&!state&&!errors[region]?'Checking connection…':!state?'Status unavailable':connected?state.canRead?'Connected · sending and Sent verification authorized':'Connected · Sent verification authorization required':state.configured?'Not connected':'Gmail configuration is incomplete'}</p>{errors[region]&&<p role="alert" className="error-message">{errors[region]}</p>}<button className="primary-button" disabled={busy!==null||!state?.configured||connected&&!!state.canRead} onClick={()=>void connect(region)}>{busy===region?'Opening Google authorization…':connected?(state?.canRead?'Connected':'Authorize Sent verification'):'Connect Gmail'}</button></section>;})}<button disabled={busy!==null||loading} onClick={()=>setRevision(n=>n+1)}>Refresh mailbox status</button></section>;
}
