import {useRef,useState,useEffect} from 'react';
interface Candidate {gmailId:string;sentAt:string|null;eligible:boolean;reason:string|null;proof:string|null}
export default function SentMatchReview({token,deliveryId,onMatched,onClose}:{token:string;deliveryId:string;onMatched:()=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[rows,setRows]=useState<Candidate[]>([]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[chosen,setChosen]=useState<Candidate|null>(null),[confirmed,setConfirmed]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 async function read(page=''){setBusy(true);setError('');try{const r=await fetch(`/api/email/deliveries/${deliveryId}/candidates${page?'?pageToken='+encodeURIComponent(page):''}`,{headers:{Authorization:'Bearer '+token}});const v=await r.json() as {rows?:Candidate[];nextPageToken?:string|null};if(!r.ok||!v.rows)throw Error();setRows(old=>page?[...old,...v.rows!.filter(row=>!old.some(x=>x.gmailId===row.gmailId))]:v.rows!);setNext(v.nextPageToken??null);setLoaded(true);}catch{setError('Sent candidates could not be verified. No history was changed.');}finally{setBusy(false);}}
 async function link(){if(!chosen||!confirmed)return;setBusy(true);setError('');try{const r=await fetch(`/api/email/deliveries/${deliveryId}/reviewed-match`,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({gmailId:chosen.gmailId,proof:chosen.proof,reason,confirmed:true})});const v=await r.json() as {error?:string;state?:string};if(!r.ok||v.error||v.state!=='sent')throw Error();onMatched();}catch{setError('This match changed or could not update history safely. Review the existing result; do not resend.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="drive-confirm" aria-labelledby="sent-review-title" onCancel={onClose}><h2 id="sent-review-title">Review an existing sent message</h2><p>Use this when Gmail changed the message identifiers. Searching does not record sending. Only a message that passes the recipient, subject, body and complete attachment checks can be linked.</p><button disabled={busy} onClick={()=>void read()}>Find matching sent messages</button>{loaded&&!rows.length&&<p>No matching candidates found. A missing draft does not prove sending.</p>}<ul>{rows.map(row=><li key={row.gmailId}><p>{row.sentAt?new Date(row.sentAt).toLocaleString():''} · {row.eligible?'Content and attachments verified':'Needs review: '+row.reason}</p><a href={`https://mail.google.com/mail/u/?authuser=ar%40katathani.com#all/${row.gmailId}`} target="_blank" rel="noreferrer">Review in Gmail</a> <button disabled={busy||!row.eligible} onClick={()=>{setChosen(row);setConfirmed(false);}}>Select this sent message</button></li>)}</ul>{next&&<button disabled={busy} onClick={()=>void read(next)}>More candidates</button>}{chosen&&<><p>Selected message: {chosen.sentAt?new Date(chosen.sentAt).toLocaleString():chosen.gmailId}</p><label>Review note<textarea aria-label="Sent match review note" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/> I confirmed in Gmail that this is the message sent for this reviewed package.</label><button disabled={busy||!confirmed||reason.trim().length<5} onClick={()=>void link()}>Link verified sent message</button></>}{error&&<p role="alert" className="error-message">{error}</p>}<footer><button onClick={onClose} disabled={busy}>Close sent review</button></footer></dialog>;
}
