import SignatureTestSender from './SignatureTestSender';
import {useWorkspaceMember} from '../access/context';
import {regionHotels,hotelName,type HotelId} from '../domain/hotels';
import {useEffect,useRef,useState} from 'react';
import {signatureHtml,signatureWorkplace,parseSignatureProfile,type SignatureProfile} from './signature';
import './signature.css';
export async function readSignature(token:string,signal?:AbortSignal):Promise<SignatureProfile>{
 const response=await fetch('/api/access/signature',{headers:{Authorization:'Bearer '+token},signal});if(!response.ok)throw Error('Your email signature could not be loaded. Try again.');return parseSignatureProfile(await response.json());
}
export default function SignatureSettings({token,onDirtyChange}:{token:string;onDirtyChange?:(dirty:boolean)=>void}){
 const member=useWorkspaceMember();const regions=member?.regions??['phuket'];const hotels=regions.flatMap(r=>[...regionHotels(r)]);const [previewHotel,setPreviewHotel]=useState<HotelId>(hotels[0]);
 const [profile,setProfile]=useState<SignatureProfile|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[retry,setRetry]=useState(0),[testing,setTesting]=useState(false);
 const alive=useRef(true);useEffect(()=>{alive.current=true;const controller=new AbortController();setProfile(null);setError('');readSignature(token,controller.signal).then(value=>{if(!controller.signal.aborted)setProfile(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{alive.current=false;controller.abort();};},[token,retry]);
 useEffect(()=>{onDirtyChange?.(dirty||busy||testing);return()=>onDirtyChange?.(false);},[dirty,busy,testing,onDirtyChange]);
 const edit=(name:'name'|'title'|'workplace',value:string)=>{setProfile(p=>p?{...p,signature:{...p.signature,[name]:value}}:p);setDirty(true);setNotice('');};
 const save=async()=>{if(!profile||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/access/signature',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({...profile,signature:{...profile.signature,workplace:signatureWorkplace(hotels[0])}})});if(!r.ok)throw Error(r.status===409?'Your signature changed in another tab. Reload and review it before saving.':'Your signature could not be saved. Your edits are still here.');const value=parseSignatureProfile(await r.json());if(alive.current){setProfile(value);setDirty(false);setNotice('Email signature saved.');}}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}};
 return <section className="signature-settings" aria-label="My email signature"><header><h1>My email signature</h1><p>Personal details added below your message.</p></header>{error&&<p className="error-message" role="alert">{error}<button disabled={busy} onClick={()=>{if(!dirty||confirm('Discard unsaved signature edits?')){setDirty(false);setRetry(n=>n+1);}}}>Reload</button></p>}{!profile?!error&&<p role="status">Loading signature…</p>:<div className="signature-layout"><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||testing}><legend className="sr-only">Signature details</legend><label>Name<input value={profile.signature.name} maxLength={100} placeholder="Name as it should appear in emails" onChange={e=>edit('name',e.target.value)}/></label><label>Position<input value={profile.signature.title} maxLength={100} placeholder="Your job title" onChange={e=>edit('title',e.target.value)}/></label><label className="signature-toggle"><input type="checkbox" checked={profile.enabled} onChange={e=>{setProfile({...profile,enabled:e.target.checked});setDirty(true);}}/>Add my signature to emails</label><button className="primary-button" disabled={busy||!dirty}>{busy?'Saving…':'Save signature'}</button></fieldset>{notice&&<p role="status">{notice}</p>}</form><section className="signature-preview" aria-label="Signature preview"><h2>Preview</h2>{hotels.length>1&&<label>Hotel<select aria-label="Signature preview hotel" value={previewHotel} onChange={e=>setPreviewHotel(e.target.value as HotelId)}>{hotels.map(h=><option key={h} value={h}>{h} · {hotelName(h)}</option>)}</select></label>}{profile.enabled?<div dangerouslySetInnerHTML={{__html:signatureHtml({...profile.signature,workplace:signatureWorkplace(previewHotel)},true)}}/>:<p>Signature is turned off.</p>}</section></div>}{profile&&member?.administrator&&<SignatureTestSender token={token} disabled={dirty||busy} onBusyChange={setTesting}/>}</section>;
}
