import {describe,it,expect} from 'vitest';
import {agingCountFor,agingDetailsResult,agingInvoicesResult,agingPublicationMatches,agingStatusTarget,agingTargetPublicationMatches,agingCatalogRevision,isEmptyAgingRow} from '../src/dashboard/aging-invoice-data';
import {agingColumns,agingComparison,agingBucketKey} from '../src/dashboard/aging-model';
import type {Account,RefreshState} from '../src/domain/portfolio';
import type {AgingInvoicesResponse} from '../worker/dashboard/aging-model';
const bucket={label:'91–120',start:91,end:120,sequence:3,amount:100,debit:100,credit:0};
const at='2026-09-13T12:00:00Z';
const refresh:RefreshState={running:false,hotels:['KAT','TSK'].map(hotel=>({hotel,status:'succeeded',last_success_at:at}))};
const accounts:Account[]=(['KAT','TSK'] as const).map(hotel=>({hotel,id:hotel+'-A',account_no:'MATCH',name:hotel+' account',type:'OTA',open:100,over90:100,items:1,verification_state:'verified',agingBuckets:[bucket]}));
const rows=agingComparison(accounts,'All'),columns=agingColumns(accounts);
function response():AgingInvoicesResponse{return {asOfDate:'2026-09-13',publications:(['KAT','TSK'] as const).map(hotel=>({hotel,sourceAt:at})),accounts:accounts.map((a,i)=>({hotel:a.hotel as 'KAT'|'TSK',accountId:a.id,accountType:a.type,syncedAt:at,complete:true,unverified:0,buckets:[{key:null,count:i+2,amount:'100.00',creditAmount:'0.00',complete:true},{key:agingBucketKey(bucket),count:i+2,amount:'100.00',creditAmount:'0.00',complete:true}]})),summary:{complete:true,count:5,amount:'200.00',creditAmount:'0.00',billing:[{key:'billed',label:'Billed',count:5,amount:'200.00'}],followup:[],due:[],flags:[]},rows:[],total:5,complete:true};}
const detail=()=>({hotel:'KAT' as const,accountId:'KAT-A',accountName:'KAT account',accountType:'OTA',invoiceId:'I-1',invoiceNo:'INV-1',folioNo:'F-1',guest:'Synthetic guest',open:'100.00',age:100,billingStatus:'billed',latestStage:'Follow 2',latestStageLabel:'Follow-Up 2',dueStatus:'past_due',dueDate:'2026-08-01',held:false,needsReview:false});

describe('hide empty Aging accounts',()=>{
 const empty=()=>agingComparison(accounts.map(a=>({...a,open:0,items:0})),'All','OTA')[0];
 const zero=()=>{const r=response();r.accounts.forEach(a=>a.buckets.forEach(b=>{b.count=0;b.amount='0.00';}));return r;};
 it('hides only confirmed zero balances with no invoices',()=>{expect(isEmptyAgingRow(empty(),{state:'ready',data:zero()},refresh)).toBe(true);});
 it('keeps offsetting balances across hotels even when Total is zero',()=>{const row=agingComparison(accounts.map((a,i)=>({...a,open:i?-100:100,items:0})),'All','OTA')[0];expect(row.net.Total.amount).toBe(0);expect(isEmptyAgingRow(row,{state:'ready',data:zero()},refresh)).toBe(false);});
 it('keeps zero net with invoices and credit balances',()=>{const r=zero();r.accounts[0].buckets[0].count=2;expect(isEmptyAgingRow(empty(),{state:'ready',data:r},refresh)).toBe(false);const row=agingComparison(accounts.map(a=>({...a,open:-100,items:1})),'All','OTA')[0];expect(isEmptyAgingRow(row,{state:'ready',data:zero()},refresh)).toBe(false);expect(isEmptyAgingRow({...empty(),members:empty().members.map(a=>({...a,items:2}))},{state:'ready',data:zero()},refresh)).toBe(false);});
 it('keeps unavailable, incomplete and stale counts visible',()=>{expect(isEmptyAgingRow(empty(),{state:'loading'},refresh)).toBe(false);expect(isEmptyAgingRow(empty(),{state:'error'},refresh)).toBe(false);const r=zero();r.accounts[0].buckets[0].complete=false;expect(isEmptyAgingRow(empty(),{state:'ready',data:r},refresh)).toBe(false);r.accounts[0].buckets[0].complete=true;r.publications[0].sourceAt='2026-09-01T00:00:00Z';expect(isEmptyAgingRow(empty(),{state:'ready',data:r},refresh)).toBe(false);});
});
describe('current Aging invoice data',()=>{
 it('normalizes database JSON whitespace while preserving source bucket identity',()=>{const r=response();r.accounts[0].buckets[1].key=JSON.stringify(['91–120',91,120,3],null,1);const parsed=agingInvoicesResult(r);expect(parsed.accounts[0].buckets[1].key).toBe(agingBucketKey(bucket));expect(agingCountFor(rows[0],'Total',bucket,{state:'ready',data:parsed},refresh)).toMatchObject({count:5,state:'ready'});});
 it('rejects duplicate bucket identities even with different JSON whitespace',()=>{const r=response();r.accounts[0].buckets.push({...r.accounts[0].buckets[1],key:JSON.stringify(['91–120',91,120,3],null,1)});expect(()=>agingInvoicesResult(r)).toThrow();});
 it('rejects duplicate accounts, malformed counts and unsafe money',()=>{for(const mutate of [(r:AgingInvoicesResponse)=>r.accounts.push(r.accounts[0]),(r:AgingInvoicesResponse)=>r.accounts[0].buckets[0].count=-1,(r:AgingInvoicesResponse)=>r.accounts[0].buckets[0].amount='9e99']){const r=response();mutate(r);expect(()=>agingInvoicesResult(r)).toThrow();}});
 it('keeps a known hotel count when another hotel is incomplete, never guesses Total',()=>{const r=response();r.complete=false;r.accounts[1].buckets[1]={...r.accounts[1].buckets[1],complete:false,count:null};const source={state:'ready' as const,data:r};expect(agingCountFor(rows[0],'KAT',bucket,source,refresh).count).toBe(2);expect(agingCountFor(rows[0],'Total',bucket,source,refresh).count).toBeNull();});
 it('keeps verified net count independent of missing aging membership',()=>{const r=response();r.accounts[0].buckets[1]={...r.accounts[0].buckets[1],complete:false,count:null};expect(agingCountFor(rows[0],'KAT',undefined,{state:'ready',data:r},refresh).count).toBe(2);expect(agingCountFor(rows[0],'KAT',bucket,{state:'ready',data:r},refresh).count).toBeNull();});
 it('suppresses counts from a different publication or missing account',()=>{const r=response();r.publications[0].sourceAt='2026-09-12T12:00:00Z';expect(agingCountFor(rows[0],'KAT',bucket,{state:'ready',data:r},refresh).count).toBeNull();r.publications[0].sourceAt=at;r.accounts=r.accounts.filter(a=>a.hotel!=='KAT');expect(agingCountFor(rows[0],'Total',bucket,{state:'ready',data:r},refresh).count).toBeNull();});
 it('distinguishes absent, loading, unknown and verified zero',()=>{const kat=agingComparison(accounts,'KAT')[0];expect(agingCountFor(kat,'TSK',bucket,{state:'ready',data:response()},refresh).state).toBe('absent');expect(agingCountFor(rows[0],'KAT',bucket,{state:'loading'},refresh).state).toBe('loading');expect(agingCountFor(rows[0],'KAT',bucket,{state:'error'},refresh).state).toBe('unavailable');const r=response();r.accounts[0].buckets[1].count=0;expect(agingCountFor(rows[0],'KAT',bucket,{state:'ready',data:r},refresh)).toMatchObject({count:0,state:'ready'});});
 it('requires current catalog account verification and type agreement',()=>{const r=response();r.accounts[0].accountType='Changed';expect(agingCountFor(rows[0],'KAT',bucket,{state:'ready',data:r},refresh).count).toBeNull();const bad={...rows[0],members:rows[0].members.map(a=>({...a,verification_state:'unknown'}))};expect(agingCountFor(bad,'KAT',bucket,{state:'ready',data:response()},refresh).count).toBeNull();});
 it('requests exact matched member IDs and only their publications',()=>{const matched=agingComparison(accounts,'KAT','OTA')[0],target=agingStatusTarget(matched,'Total',bucket,false,columns);expect(new URLSearchParams(target.query).get('katAccount')).toBe('KAT-A');expect(target.hotels).toEqual(['KAT']);const r=response();r.publications=r.publications.filter(p=>p.hotel==='KAT');expect(agingPublicationMatches(r,refresh,target.hotels)).toBe(true);});
 it('keeps explicit multi-account groups exact and source amount keyed to the actual column',()=>{const members=[...accounts,{...accounts[0],id:'KAT-B',group:'shared'}].map(a=>({...a,group:'shared'}));const row=agingComparison(members,'All','OTA')[0],target=agingStatusTarget(row,'Total',bucket,false,agingColumns(members));expect(JSON.parse(new URLSearchParams(target.query).get('accounts')!)).toEqual([['KAT','KAT-A'],['TSK','TSK-A'],['KAT','KAT-B']]);expect(target.sourceAmount).toBe(300);});
 it('rejects foreign account, wrong bucket, wrong status and mismatched attention detail rows',()=>{const q=new URLSearchParams({hotel:'KAT',katAccount:'KAT-A',bucket:agingBucketKey(bucket),dimension:'followup',status:'Follow 2',flag:'held',limit:'25'});for(const mutate of [(r:ReturnType<typeof detail>)=>r.accountId='FOREIGN',(r:ReturnType<typeof detail>)=>r.age=40,(r:ReturnType<typeof detail>)=>r.latestStage='Follow 1',(r:ReturnType<typeof detail>)=>r.held=false]){const r=response(),row={...detail(),held:true};mutate(row);r.accounts=r.accounts.filter(a=>a.hotel==='KAT');r.rows=[row];expect(()=>agingDetailsResult(q)(r)).toThrow();}});
 it('accepts matching filtered rows without requiring the page to contain the full summary',()=>{const r=response();r.accounts=r.accounts.filter(a=>a.hotel==='KAT');r.rows=[detail()];expect(agingDetailsResult(new URLSearchParams({hotel:'KAT',katAccount:'KAT-A',dimension:'followup',status:'Follow 2',limit:'25'}))(r).summary.count).toBe(5);});
 it('detects account-only refreshes even when the hotel publication is unchanged',()=>{const catalog=accounts.map(a=>({...a,synced_at:at})),row=agingComparison(catalog,'All')[0],target=agingStatusTarget(row,'Total',bucket,true,columns),r=response();expect(agingTargetPublicationMatches(r,target,refresh)).toBe(true);const changed=catalog.map(a=>({...a,synced_at:'2026-09-13T12:05:00Z'})),next=agingComparison(changed,'All')[0];expect(agingCatalogRevision(changed)).not.toBe(agingCatalogRevision(catalog));expect(agingCountFor(next,'KAT',bucket,{state:'ready',data:r},refresh).count).toBeNull();expect(agingTargetPublicationMatches(r,agingStatusTarget(next,'Total',bucket,true,columns),refresh)).toBe(false);});
 it('rejects detail publication membership changes in a type scope',()=>{const target=agingStatusTarget(rows[0],'Total',bucket,true,columns),r=response();r.accounts=r.accounts.filter(a=>a.hotel==='KAT');expect(agingTargetPublicationMatches(r,target,refresh)).toBe(false);});
});

describe('signed Aging invoice details',()=>{
 const credit=()=>({...detail(),invoiceId:'C-1',open:'-50.00',billingStatus:'credit',latestStage:'credit',latestStageLabel:'Credit',dueStatus:'credit',dueDate:null});
 it('accepts signed credit rows in the same scoped detail response',()=>{const r=response();r.rows=[credit()];expect(agingInvoicesResult(r).rows[0].open).toBe('-50.00');expect(agingDetailsResult(new URLSearchParams({dimension:'billing',status:'credit'}))(r).rows).toHaveLength(1);});
 it('excludes zero and rejects a credit disguised as billing or follow-up work',()=>{for(const mutate of [(r:ReturnType<typeof credit>)=>r.open='0.00',(r:ReturnType<typeof credit>)=>r.billingStatus='unbilled',(r:ReturnType<typeof credit>)=>r.latestStage='Friendly',(r:ReturnType<typeof credit>)=>r.dueStatus='past_due']){const r=response(),row=credit();mutate(row);r.rows=[row];expect(()=>agingInvoicesResult(r)).toThrow();}});
 it('does not classify a positive balance as credit',()=>{const r=response();r.rows=[{...credit(),open:'50.00'}];expect(()=>agingInvoicesResult(r)).toThrow();});
 it('keeps the complete signed inventory count when its net amount is zero',()=>{const r=response();r.summary={...r.summary,count:2,amount:'0.00',creditAmount:'100.00'};r.rows=[detail(),{...credit(),open:'-100.00'}];expect(agingInvoicesResult(r).summary).toMatchObject({count:2,amount:'0.00'});});
});
