import {afterEach,expect,it,vi} from 'vitest';
import {externalBillingApi,parseExternalBilling} from '../worker/billing/api';
const id='00000000-0000-4000-8000-000000000001',env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const input={commandId:id,action:'record',hotel:'KAT',accountId:'SYN-A',actualDate:'2026-09-01',channel:'system',reference:'Synthetic receipt',note:'',amount:null,lines:[{invoiceId:'A',revision:0}]};
afterEach(()=>vi.unstubAllGlobals());
it('requires exact scope, source dates and unique revision-bound invoices',()=>{expect(parseExternalBilling(input)).toEqual(input);for(const patch of [{hotel:'OTHER'},{actualDate:'2026-02-30'},{amount:100},{lines:[{invoiceId:'A',revision:0.1}]},{lines:[{invoiceId:'A',revision:0},{invoiceId:'A',revision:0}]},{reference:''},{unexpected:true}])expect(()=>parseExternalBilling({...input,...patch})).toThrow('billing_invalid');});
it('corrections require their record revision/reason and cannot change linked invoices',()=>{const {lines,...fields}=input;void lines;const correction={...fields,action:'correct',recordId:id,revision:1,reason:'Correct source reference'};expect(parseExternalBilling(correction)).toEqual(correction);expect(()=>parseExternalBilling({...correction,lines:input.lines})).toThrow();expect(()=>parseExternalBilling({...correction,reason:''})).toThrow();});
it('preview and confirmed writes are separate and service errors remain sanitized',async()=>{const calls:string[]=[];vi.stubGlobal('fetch',async(url:string)=>{calls.push(url);return Response.json({preview:input,digest:'a'.repeat(64)});});const request=(path:string,body:unknown)=>new Request('https://app.test/api/external-billing/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});expect((await externalBillingApi(request('preview',{input}),env,id)).status).toBe(200);expect(calls[0]).toContain('ar_external_billing_preview');expect((await externalBillingApi(request('confirm',{input}),env,id)).status).toBe(400);expect(calls).toHaveLength(1);vi.stubGlobal('fetch',async()=>Response.json({error:'billing_revision_conflict'}));expect((await externalBillingApi(request('confirm',{input,digest:'a'.repeat(64)}),env,id)).status).toBe(409);});
it('cross-origin confirmation is rejected before database writes',async()=>{const f=vi.fn();vi.stubGlobal('fetch',f);expect((await externalBillingApi(new Request('https://app.test/api/external-billing/confirm',{method:'POST',headers:{Origin:'https://other.test','Content-Type':'application/json'},body:JSON.stringify({input,digest:'a'.repeat(64)})}),env,id)).status).toBe(403);expect(f).not.toHaveBeenCalled();});
