import {afterEach,expect,it,vi} from 'vitest';
import type {WorkflowStep} from 'cloudflare:workers';
import {requestFinancialHistory,runFinancialHistory} from '../worker/financial/refresh';
const actor='00000000-0000-4000-8000-000000000001',runId='00000000-0000-4000-8000-000000000002',commandId='00000000-0000-4000-8000-000000000003';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic',OPERA_BASE_URL:'https://synthetic.opera.invalid',OPERA_HOTEL_IDS:'KAT',OPERA_ENTERPRISE_ID:'synthetic',OPERA_CLIENT_ID:'synthetic',OPERA_CLIENT_SECRET:'synthetic',OPERA_APP_KEY:'synthetic',FINANCIAL_HISTORY_ENABLED:'true',FINANCIAL_HISTORY_DATE_FILTER_PROOF:'synthetic-proof'};
const money=(amount:string)=>({amount,currencyCode:'THB'});
function harness(options:{knownCommand?:boolean;historyFailure?:boolean;changedDiscovery?:boolean;batchFailure?:boolean;noMapping?:boolean;missingMappingMoney?:boolean}={}){
 const rpc:{name:string;args:Record<string,unknown>}[]=[],sources:string[]=[],stepOutputs:unknown[]=[],ids=['SYNTHETIC-A','SYNTHETIC-B'];let discoveries=0;const staged=new Set<number>();
 const run={id:runId,owner:actor,hotel:'KAT',from:'2026-08-11',to:'2026-09-10',status:'running',proof:'synthetic-proof',discovered:false,accounts:2,startedAt:'2026-09-10T10:00:00.000Z',initialImport:true};
 vi.stubGlobal('fetch',async(input:RequestInfo|URL,init:RequestInit={})=>{
  const request=input instanceof Request?input:new Request(input,init),url=new URL(request.url);
  if(url.origin===env.SUPABASE_URL){const args=JSON.parse(await request.text()),name=url.pathname.split('/').at(-1)!;rpc.push({name,args});
   if(name==='ar_financial_command_get')return Response.json(options.knownCommand?{id:runId,status:'succeeded',created:false,hotel:'KAT',from:run.from,to:run.to}:null);
   if(name==='ar_financial_request')return Response.json({id:runId,status:'queued',created:true,hotel:'KAT',from:args.p_from,to:args.p_to});
   if(name==='ar_financial_run_get')return Response.json(run);
   if(name==='ar_financial_claim'||name==='ar_financial_renew')return Response.json(true);
   if(name==='ar_financial_discovery_set')return Response.json({accounts:2});
   if(name==='ar_financial_account_get'){const index=Number(args.p_ordinal);return Response.json({ordinal:index,accountId:ids[index],staged:staged.has(index),counts:{invoices:1,payments:1,applications:1}});}
   if(name==='ar_financial_stage_batch'){if(options.batchFailure)return Response.json({error:'financial_batch_conflict'});return Response.json(true);}
   if(name==='ar_financial_account_done'){staged.add(ids.indexOf(String(args.p_account)));return Response.json(args.p_counts);}
   if(name==='ar_financial_publish')return Response.json({status:'succeeded',accounts:2,invoices:2,payments:2,applications:options.noMapping?0:2});
   if(name==='ar_financial_fail')return Response.json(true);
   throw Error('Unexpected synthetic RPC');
  }
  sources.push(url.pathname+url.search);
  if(url.pathname==='/oauth/v1/tokens')return Response.json({access_token:'synthetic',expires_in:3600});
  if(url.pathname.includes('/businessDate'))return Response.json({hotels:[{hotelId:'KAT',businessDate:'2026-09-10'}]});
  if(url.pathname==='/ars/v1/accounts'){discoveries++;return Response.json({accountsDetails:(options.changedDiscovery&&discoveries>1?ids.slice(0,1):ids).map(id=>({hotelId:'KAT',accountId:{id}})),offset:20,limit:20,totalResults:options.changedDiscovery&&discoveries>1?1:2,hasMore:false});}
  if(url.pathname.endsWith('/invoicePaymentDetails')){const parts=url.pathname.split('/'),account=decodeURIComponent(parts[parts.indexOf('accounts')+1]),payment=parts[parts.indexOf('transactions')+1]==='301';return Response.json({details:[{hotelId:'KAT',accountId:{id:account},...(payment?{payments:[{hotelId:'KAT',transactionNo:'301',transactionDate:'2026-09-01',amount:money('-0.30'),amountUsed:money(options.noMapping?'0.00':'-0.30'),balance:money(options.noMapping?'-0.30':'0.00'),transferredIn:false,transferredOut:false}]}:{invoices:[{hotelId:'KAT',transactionNo:'101',invoiceNo:'201',folioNo:'401',invoiceType:'Normal',transactionDate:'2026-08-20',originalAmount:money('0.30'),amount:options.missingMappingMoney?null:money('0.30'),payments:money(options.noMapping?'0.00':'0.30'),balance:money(options.noMapping?'0.30':'0.00'),compressed:false}]})}]});}
  const account=url.pathname.includes('/invoicePayments/')?decodeURIComponent(url.pathname.split('/').at(-1)!):url.pathname.includes('/invoiceAppliedPayments')?decodeURIComponent(url.pathname.split('/').at(-2)!):decodeURIComponent(url.pathname.split('/').at(-1)!);
  if(url.pathname.endsWith('/invoiceAppliedPayments'))return Response.json({details:options.noMapping?[]:[{hotelId:'KAT',transactionNo:'101',invoiceNo:'201',paymentTrxNo:'301',appliedAmount:money('0.30'),transactionDate:'2026-08-20'}]});
  if(url.pathname.includes('/invoicePayments/')){if(options.historyFailure&&account==='SYNTHETIC-B')return new Response('private unavailable',{status:503});return Response.json({details:[{hotelId:'KAT',accountId:{id:account},invoices:[{hotelId:'KAT',transactionNo:'101',invoiceNo:'201',folioNo:'401',invoiceType:'Normal',transactionDate:'2026-08-20',originalAmount:money('0.30'),amount:money('0.30'),payments:money(options.noMapping?'0.00':'0.30'),balance:money(options.noMapping?'0.30':'0.00'),compressed:false}],payments:[{hotelId:'KAT',transactionNo:'301',transactionDate:'2026-09-01',amount:money('-0.30'),amountUsed:money('-0.30'),balance:money('0.00'),transferredIn:false,transferredOut:false}]}],offset:20,limit:20,totalResults:2,hasMore:false});}
  return Response.json({accountDetails:{hotelId:'KAT',accountId:{id:account},accountName:'Synthetic account',type:'Synthetic type',accountNo:null}});
 });
 const step={do:async(_name:string,_config:unknown,callback:()=>Promise<unknown>)=>{const value=await callback();stepOutputs.push(value);return value;}} as Pick<WorkflowStep,'do'>;
 return {rpc,sources,stepOutputs,step};
}
afterEach(()=>vi.unstubAllGlobals());
it('keeps ingestion off without both activation and proof, before accessing services',async()=>{const h=harness();expect(await requestFinancialHistory({...env,FINANCIAL_HISTORY_ENABLED:undefined},actor,{commandId,hotel:'KAT',reason:'manual'})).toMatchObject({status:'not_enabled',created:false});expect(await requestFinancialHistory({...env,FINANCIAL_HISTORY_DATE_FILTER_PROOF:undefined},actor,{commandId,hotel:'KAT',reason:'manual'})).toMatchObject({status:'not_enabled'});expect(h.rpc).toHaveLength(0);expect(h.sources).toHaveLength(0);});
it('replays a known command without recalculating its window or reading OPERA',async()=>{const h=harness({knownCommand:true});expect(await requestFinancialHistory(env,actor,{commandId,hotel:'KAT',reason:'manual'})).toMatchObject({id:runId,status:'succeeded',created:false});expect(h.sources).toHaveLength(0);expect(h.rpc.map(r=>r.name)).toEqual(['ar_financial_command_get']);});
it('resolves the default31-day window from hotel Business Date and preserves explicit source-date backfill',async()=>{const h=harness();const r=await requestFinancialHistory(env,actor,{commandId,hotel:'KAT',reason:'manual'});expect(r).toMatchObject({from:'2026-08-11',to:'2026-09-10'});expect(h.rpc.at(-1)).toMatchObject({name:'ar_financial_request',args:{p_from:'2026-08-11',p_to:'2026-09-10',p_proof:'synthetic-proof'}});const h2=harness();await requestFinancialHistory(env,actor,{commandId,hotel:'KAT',reason:'backfill',from:'2026-01-01',to:'2026-01-31'});expect(h2.sources).toHaveLength(0);expect(h2.rpc.at(-1)?.args.p_from).toBe('2026-01-01');});
it('stages every Account and unseen zero invoice with original dates, then publishes only after complete rediscovery',async()=>{const h=harness();const result=await runFinancialHistory(env,{actor,runId},h.step);expect(result).toMatchObject({status:'succeeded',accounts:2,invoices:2,payments:2,applications:2});const batches=h.rpc.filter(r=>r.name==='ar_financial_stage_batch');expect(new Set(batches.map(r=>r.args.p_account))).toEqual(new Set(['SYNTHETIC-A','SYNTHETIC-B']));expect(batches.find(r=>r.args.p_kind==='invoice')?.args.p_rows).toMatchObject([{transactionDate:'2026-08-20',openAmount:'0.00',originalAmount:'0.30'}]);expect(batches.find(r=>r.args.p_kind==='payment')?.args.p_rows).toMatchObject([{amount:'-0.30',classification:'unknown',reversal:'unknown'}]);expect(batches.find(r=>r.args.p_kind==='application')?.args.p_rows).toMatchObject([{applicationDate:null,applicationEventId:null}]);expect(h.rpc.at(-1)?.name).toBe('ar_financial_publish');expect(h.rpc.at(-1)?.args.p_accounts).toEqual(['SYNTHETIC-A','SYNTHETIC-B']);expect(JSON.stringify(h.stepOutputs)).not.toMatch(/SYNTHETIC-A|SYNTHETIC-B|0.30|Synthetic account/);});
it('a later Account failure marks this run failed without publishing any partial dataset',async()=>{const h=harness({historyFailure:true});const result=await runFinancialHistory(env,{actor,runId},h.step);expect(result.status).toBe('failed');expect(h.rpc.some(r=>r.name==='ar_financial_publish')).toBe(false);expect(h.rpc.at(-1)?.name).toBe('ar_financial_fail');expect(JSON.stringify(result)).not.toContain('private unavailable');});
it('changed discovery or a conflicting batch cannot publish',async()=>{for(const options of [{changedDiscovery:true},{batchFailure:true}]){const h=harness(options);expect((await runFinancialHistory(env,{actor,runId},h.step)).status).toBe('failed');expect(h.rpc.some(r=>r.name==='ar_financial_publish')).toBe(false);}});
it('empty current mapping remains a checked observation, never a dated zero application',async()=>{const h=harness({noMapping:true});await runFinancialHistory(env,{actor,runId},h.step);const accounts=h.rpc.filter(r=>r.name==='ar_financial_account_done');expect(accounts[0].args.p_counts).toEqual({invoices:1,payments:1,applications:0});expect(accounts[0].args.p_mapping_invoices).toEqual(['101']);});
it('rejects changed range shape, invalid actor, and unsafe window configuration before service work',async()=>{const h=harness();for(const input of [{commandId,hotel:'KAT',reason:'backfill',from:'2026-01-01'},{commandId,hotel:'KAT',reason:'backfill',from:'2026-02-30',to:'2026-03-01'}])await expect(requestFinancialHistory(env,actor,input as Parameters<typeof requestFinancialHistory>[2])).rejects.toThrow();await expect(requestFinancialHistory(env,'',{commandId,hotel:'KAT',reason:'manual'})).rejects.toThrow();await expect(requestFinancialHistory({...env,FINANCIAL_HISTORY_WINDOW_DAYS:'0'},actor,{commandId,hotel:'KAT',reason:'manual'})).rejects.toThrow();expect(h.rpc).toHaveLength(0);expect(h.sources).toHaveLength(0);});

it('unavailable application details do not discard independently verified invoice and payment history',async()=>{const h=harness({missingMappingMoney:true});const result=await runFinancialHistory(env,{actor,runId},h.step);expect(result.status).toBe('succeeded');const saved=h.rpc.filter(r=>r.name==='ar_financial_account_done');expect(saved).toHaveLength(2);expect(saved[0].args.p_mapping_invoices).toEqual([]);expect(saved[0].args.p_coverage).toMatchObject({mappingVerified:0,mappingFailures:[{invoiceId:'101',code:'financial_mapping_missing_current'}]});expect(h.rpc.filter(r=>r.name==='ar_financial_stage_batch'&&r.args.p_kind==='application')).toHaveLength(0);});
