import {describe,expect,it} from 'vitest';
import {OperaReader} from '../worker/opera/client';
import {parseFinancialMoney,readFinancialHistory,readFinancialTransactionDetail,readAppliedPaymentMapping,type FinancialHistoryQuery} from '../worker/opera/financial-history';

const scope={hotel:'KAT' as const,accountId:'synthetic-account'};
const query:FinancialHistoryQuery={...scope,start:'2026-09-01',end:'2026-09-10'};
const observedAt='2026-09-10T10:00:00.000Z';
const money=(amount:number|string)=>({amount,currencyCode:'THB'});
const invoice=(transactionNo:number|string=101,extra:Record<string,unknown>={})=>({hotelId:'KAT',transactionNo,invoiceNo:'501',folioNo:'601',invoiceType:'Normal',transactionDate:'2026-09-09',originalAmount:money('100.10'),amount:money('100.10'),payments:money('100.10'),balance:money('0.00'),compressed:false,...extra});
const payment=(transactionNo:number|string=201,extra:Record<string,unknown>={})=>({hotelId:'KAT',transactionNo,transactionCode:'9000',transactionDate:'2026-09-10',postingDate:'2026-09-10',amount:money('-100.10'),amountUsed:money('-70.10'),balance:money('-30.00'),transferredIn:false,transferredOut:false,...extra});
const page=(invoices:unknown[]=[],payments:unknown[]=[],extra:Record<string,unknown>={})=>({details:invoices.length||payments.length?[{hotelId:'KAT',accountId:{id:scope.accountId},invoices,payments}]:[],hasMore:false,totalResults:invoices.length+payments.length,offset:20,limit:20,...extra});
function harness(respond:(url:URL)=>unknown|Response|Promise<unknown|Response>){const calls:Request[]=[];let tokens=0;const reader=new OperaReader({origin:'https://synthetic.example.invalid',appKey:'synthetic',hotelId:'KAT'},async()=>{tokens++;return 'synthetic';},async request=>{calls.push(request);const value=await respond(new URL(request.url));return value instanceof Response?value:Response.json(value);});return {reader,calls,tokenCount:()=>tokens};}

describe('fixed read-only financial routes',()=>{
 it('builds bounded zero-inclusive history with explicit kinds and stable ordering',async()=>{const h=harness(()=>page());await readFinancialHistory(h.reader,query,{observedAt});const u=new URL(h.calls[0].url);expect(u.pathname).toBe('/ars/v1/invoicePayments/accounts/synthetic-account');expect(Object.fromEntries(u.searchParams)).toMatchObject({hotelIds:'KAT',start:'2026-09-01',end:'2026-09-10',inclZeroBalance:'true',inclDetails:'true',orderBy:'TransactionDate',sortOrder:'Asc',offset:'0',limit:'20'});expect(u.searchParams.getAll('fetchInstructions')).toEqual(['Invoices','Payments']);expect(u.searchParams.has('unBilled')).toBe(false);expect(h.calls[0].method).toBe('GET');expect(h.calls[0].redirect).toBe('manual');});
 it('uses exact current detail/mapping routes and never the deprecated invoices route',async()=>{const h=harness(u=>u.pathname.endsWith('invoicePaymentDetails')?page([invoice()]):{details:[{...invoice(),paymentTrxNo:201,appliedAmount:money('70.10')}]});await readFinancialTransactionDetail(h.reader,{...scope,kind:'invoice',transactionId:'101'},{observedAt});await readAppliedPaymentMapping(h.reader,{...scope,invoiceTransactionId:'101',invoiceNo:'501'},{observedAt});expect(h.calls.map(r=>new URL(r.url).pathname)).toEqual(['/ars/v1/hotels/KAT/accounts/synthetic-account/transactions/101/invoicePaymentDetails','/ars/v1/hotels/KAT/transactions/101/accounts/synthetic-account/invoiceAppliedPayments']);expect(new URL(h.calls[1].url).searchParams.get('invoiceNo')).toBe('501');expect(h.calls.every(r=>r.method==='GET'&&r.redirect==='manual')).toBe(true);});
 it.each([{hotel:'TSK'},{accountId:'../outside'},{accountId:' x'},{start:'2026-02-30'},{start:'2026-09-11'},{end:'2026-09-10\n'},{start:'2024-01-01'},{kinds:[]},{kinds:['invoice','invoice']},{kinds:['receipt']}])('rejects invalid scope/range/kinds without obtaining credentials %j',async patch=>{const h=harness(()=>page());await expect(readFinancialHistory(h.reader,{...query,...patch} as FinancialHistoryQuery)).rejects.toMatchObject({code:'invalid_request'});expect(h.tokenCount()).toBe(0);});
 it('rejects malformed direct client calls before a token lookup',()=>{const h=harness(()=>page());expect(()=>h.reader.financialHistoryPage({...query,hotel:'TSK',kinds:['invoice']},0,20)).toThrow('invalid_request');expect(()=>h.reader.financialTransactionDetail({...scope,transactionId:'1/../other'})).toThrow('invalid_request');expect(()=>h.reader.appliedInvoicePayments({...scope,invoiceTransactionId:'1',invoiceNo:'1&other=2'})).toThrow('invalid_request');expect(h.tokenCount()).toBe(0);});
 it('rejects impossible observation timestamps before service access',async()=>{const h=harness(()=>page());await expect(readFinancialHistory(h.reader,query,{observedAt:'2026-02-30T10:00:00Z'})).rejects.toMatchObject({code:'invalid_request'});expect(h.calls).toHaveLength(0);});
});

describe('exact financial money',()=>{
 it.each([[money('9007199254740993.99'),'9007199254740993.99'],[money('-100.10'),'-100.10'],[money(0.29),'0.29'],[money(0),'0.00'],[null,null],[undefined,null]])('preserves exact values or explicit unknown %j',(value,want)=>expect(parseFinancialMoney(value)).toBe(want));
 it.each([{amount:1,currencyCode:'USD'},{amount:'1.001',currencyCode:'THB'},{amount:'1e2',currencyCode:'THB'},{amount:' 1',currencyCode:'THB'},{amount:90071992547409.92,currencyCode:'THB'},{amount:Infinity,currencyCode:'THB'},{amount:NaN,currencyCode:'THB'},{amount:'1.00'},{amount:true,currencyCode:'THB'},'1.00'])('rejects foreign, lossy or ambiguous source money %j',value=>expect(()=>parseFinancialMoney(value)).toThrow());
 it('accepts omitted per-field currency only with verified enclosing THB evidence',()=>{expect(parseFinancialMoney({amount:'1.20'},'THB')).toBe('1.20');expect(()=>parseFinancialMoney({amount:1,currencyCode:'USD'},'THB')).toThrow();});
 it('rejects numbers whose binary spacing can collapse distinct source satang',()=>{const alreadyRounded=JSON.parse('90071992547409.91');expect(()=>parseFinancialMoney(money(alreadyRounded))).toThrow();expect(parseFinancialMoney(money('90071992547409.91'))).toBe('90071992547409.91');});
});

describe('privacy-minimal source facts',()=>{
 it('retains an unseen zero invoice while keeping receipt classifications unknown',async()=>{const h=harness(()=>page([invoice()],[payment(201,{remark:'Reverse Posting',reference:'private reference',paymentCard:{cardNumber:'synthetic-private'},cashierInfo:{name:'Synthetic cashier'},guestName:'Private guest',email:'private@example.invalid'})]));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.invoices[0]).toMatchObject({transactionId:'101',openAmount:'0.00',originalAmount:'100.10',cumulativePayments:'100.10',transactionDate:'2026-09-09',invoiceType:'Normal'});expect(r.payments[0]).toMatchObject({transactionId:'201',amount:'-100.10',appliedAmount:'-70.10',unallocatedAmount:'-30.00',classification:'unknown',reversal:'unknown',transfer:'none_reported'});expect(JSON.stringify(r)).not.toMatch(/private reference|synthetic-private|Synthetic cashier|Private guest|private@example/);expect(r.coverage).toMatchObject({pagination:'complete',dateSemantics:'unverified',financialClassification:'unverified',completeForFinancialPeriod:false,observedAt,pages:1,members:2,roots:2});});
 it('preserves missing monetary/date facts as unknown without a fake zero or received day',async()=>{const h=harness(()=>page([],[payment(201,{amount:null,amountUsed:undefined,balance:null,transactionDate:undefined,postingDate:undefined})]));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.payments[0]).toMatchObject({amount:null,appliedAmount:null,unallocatedAmount:null,transactionDate:null,postingDate:null});expect(r.coverage).toMatchObject({missingTransactionDates:1,unknownPrimaryAmounts:1});});
 it('keeps out-of-range source dates visible as an unverified filter result',async()=>{const h=harness(()=>page([invoice(101,{transactionDate:'2026-08-01'})]));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.invoices).toHaveLength(1);expect(r.coverage.outsideRequestedTransactionDates).toBe(1);expect(r.coverage.completeForFinancialPeriod).toBe(false);});
 it('captures transfer evidence without manufacturing a receipt or reversal',async()=>{const h=harness(()=>page([],[payment(201,{transferredIn:true}),payment(202,{transferredOut:true}),payment(203,{transferredIn:undefined,transferredOut:undefined})]));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.payments.map(p=>p.transfer)).toEqual(['in','out','unknown']);expect(r.payments.every(p=>p.classification==='unknown'&&p.reversal==='unknown')).toBe(true);});
 it('preserves an opening-balance representation separately from a normal invoice',async()=>{const h=harness(()=>page([invoice(-1,{invoiceType:'OldBalance',invoiceNo:0})]));expect((await readFinancialHistory(h.reader,query,{observedAt})).invoices[0]).toMatchObject({transactionId:'-1',invoiceType:'OldBalance',entryClassification:'opening_balance'});});
 it.each([{hotelId:'TSK'},{transactionNo:1.1},{transactionNo:'001'},{transactionDate:'2026-02-30'},{compressed:'false'},{transferredIn:'true'}])('fails closed for malformed source identity/date/flags %j',async extra=>{const h=harness(()=>page([invoice(101,extra)]));await expect(readFinancialHistory(h.reader,query,{observedAt})).rejects.toMatchObject({code:'invalid_response'});});
 it('requires exact enclosing Account identity and rejects hidden provider warnings',async()=>{for(const value of [{...page([invoice()]),details:[{hotelId:'KAT',accountId:{id:'other'},invoices:[invoice()]}]},{...page([invoice()]),warnings:[{shortText:'private warning'}]}]){const h=harness(()=>value);await expect(readFinancialHistory(h.reader,query,{observedAt})).rejects.toMatchObject({code:'invalid_response'});}});
 it('allows currency omissions only under a verified group summary',async()=>{const h=harness(()=>({...page([invoice()]),details:[{hotelId:'KAT',accountId:{id:scope.accountId},summary:{total:money('0.00')},invoices:[invoice(101,{balance:{amount:0}})]}]}));expect((await readFinancialHistory(h.reader,query,{observedAt})).invoices[0].openAmount).toBe('0.00');});
});

describe('complete pagination and operational budgets',()=>{
 it('collects every page with the environment next-offset convention, preserving cross-kind identities',async()=>{const h=harness(u=>u.searchParams.get('offset')==='0'?page([invoice(101)],[],{hasMore:true,totalResults:2}):page([],[payment(101)],{offset:40,totalResults:2}));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(h.calls.map(c=>new URL(c.url).searchParams.get('offset'))).toEqual(['0','20']);expect(r.coverage).toMatchObject({pages:2,roots:2,members:2,reportedRoots:2});expect(r.invoices[0].transactionId).toBe(r.payments[0].transactionId);});
 it('counts explicit compressed children as expanded members, not extra paging roots',async()=>{const h=harness(()=>page([invoice(101,{compressed:true,invoiceNo:500}),invoice(102,{compressed:false,parentInvoiceNo:500,invoiceNo:501})],[],{totalResults:1}));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.coverage).toMatchObject({members:2,roots:1,reportedRoots:1});expect(r.invoices.map(i=>i.collectionRole)).toEqual(['parent','child']);});
 it('rejects duplicate transaction identities even if financial amounts match',async()=>{const h=harness(u=>page([invoice(101)],[],{offset:u.searchParams.get('offset')==='0'?20:40,hasMore:u.searchParams.get('offset')==='0',totalResults:2}));await expect(readFinancialHistory(h.reader,query,{observedAt})).rejects.toMatchObject({code:'duplicate_member'});});
 it.each([{totalResults:2},{totalResults:0},{offset:0},{hasMore:true,details:[]},{totalResults:undefined}])('rejects incomplete or contradictory paging metadata %j',async extra=>{const h=harness(()=>page([invoice()],[],extra));await expect(readFinancialHistory(h.reader,query,{observedAt})).rejects.toThrow();});
 it('never returns partial success after later-page transport failure',async()=>{const h=harness(u=>u.searchParams.get('offset')==='0'?page([invoice()],[],{hasMore:true,totalResults:2}):new Response('private error',{status:503}));await expect(readFinancialHistory(h.reader,query,{observedAt})).rejects.toMatchObject({code:'provider_unavailable'});});
 it('fails explicitly at page and member budgets without a silently truncated dataset',async()=>{let h=harness(()=>page([invoice()],[],{hasMore:true,totalResults:2}));await expect(readFinancialHistory(h.reader,query,{observedAt,maxPages:1})).rejects.toMatchObject({code:'response_too_large',stage:'financial_history_page_budget'});expect(h.calls).toHaveLength(1);h=harness(()=>page([invoice(101),invoice(102)]));await expect(readFinancialHistory(h.reader,query,{observedAt,maxRows:1})).rejects.toMatchObject({code:'response_too_large',stage:'financial_history_row_budget'});});
 it('accepts an explicitly empty terminal page without interpreting any existing invoice as zero',async()=>{const h=harness(()=>page([],[],{offset:0,totalResults:0}));const r=await readFinancialHistory(h.reader,query,{observedAt});expect(r.invoices).toEqual([]);expect(r.payments).toEqual([]);expect(r.coverage).toMatchObject({members:0,reportedRoots:0,completeForFinancialPeriod:false});});
});

describe('detail and mapping are observations, not dated application events',()=>{
 it('finds only the requested kind and exact transaction while stripping companion data',async()=>{const h=harness(()=>page([invoice(101)],[payment(101)]));const r=await readFinancialTransactionDetail(h.reader,{...scope,kind:'payment',transactionId:'101'},{observedAt});expect(r.status).toBe('found');expect(r.transaction).toMatchObject({kind:'payment',transactionId:'101',amount:'-100.10'});expect(r).not.toHaveProperty('invoices');});
 it('returns missing explicitly and never a synthetic zero record',async()=>{const h=harness(()=>page([],[payment(201)]));expect(await readFinancialTransactionDetail(h.reader,{...scope,kind:'invoice',transactionId:'101'},{observedAt})).toMatchObject({status:'missing',transaction:null});});
 it('reads a single child detail without imposing paginated-history parent expansion',async()=>{const h=harness(()=>page([invoice(101,{parentInvoiceNo:500})]));const r=await readFinancialTransactionDetail(h.reader,{...scope,kind:'invoice',transactionId:'101'},{observedAt});expect(r.transaction).toMatchObject({transactionId:'101',collectionRole:'child',parentInvoiceNo:'500'});});
 it('returns mapping amounts with no invented event ID or application date',async()=>{const h=harness(()=>({details:[{...invoice(),paymentTrxNo:201,appliedAmount:money('70.10'),postingDate:'2026-09-08',reference:'private',paymentCard:{cardNumber:'private'}}]}));const r=await readAppliedPaymentMapping(h.reader,{...scope,invoiceTransactionId:'101',invoiceNo:'501'},{observedAt});expect(r.links[0]).toMatchObject({hotel:'KAT',accountId:scope.accountId,invoiceTransactionId:'101',paymentTransactionId:'201',appliedAmount:'70.10',invoiceTransactionDate:'2026-09-09',invoicePostingDate:'2026-09-08',applicationDate:null,applicationEventId:null});expect(r.coverage).toMatchObject({pagination:'not_exposed',completeness:'unverified',dateSemantics:'invoice_dates_only',observedAt});expect(JSON.stringify(r)).not.toContain('private');});
 it.each([{hotelId:'TSK'},{transactionNo:102},{paymentTrxNo:undefined},{paymentTrxNo:1.5},{invoiceNo:999}])('rejects ambiguous or cross-scope mapping rows %j',async extra=>{const h=harness(()=>({details:[{...invoice(),paymentTrxNo:201,appliedAmount:money('70.10'),...extra}]}));await expect(readAppliedPaymentMapping(h.reader,{...scope,invoiceTransactionId:'101',invoiceNo:'501'},{observedAt})).rejects.toMatchObject({code:'invalid_response'});});
 it('does not merge ambiguous duplicate invoice/payment pairs',async()=>{const row={...invoice(),paymentTrxNo:201,appliedAmount:money('70.10')},h=harness(()=>({details:[row,row]}));await expect(readAppliedPaymentMapping(h.reader,{...scope,invoiceTransactionId:'101'},{observedAt})).rejects.toMatchObject({code:'duplicate_member'});});
 it('never calls an empty mapping proof of no historical applications',async()=>{const h=harness(()=>({details:[]}));const r=await readAppliedPaymentMapping(h.reader,{...scope,invoiceTransactionId:'101'},{observedAt});expect(r.links).toEqual([]);expect(r.coverage.completeness).toBe('unverified');});
});
