import {afterEach,expect,it,vi} from 'vitest';
import {runFinancialDiagnostic} from '../worker/opera/financial-diagnostic';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic-private-key',OPERA_BASE_URL:'https://synthetic.opera.invalid',OPERA_HOTEL_IDS:'KAT,TSK',OPERA_CLIENT_ID:'synthetic-client',OPERA_CLIENT_SECRET:'synthetic-client-secret',OPERA_APP_KEY:'synthetic-app',OPERA_ENTERPRISE_ID:'synthetic-enterprise'};
const account='PRIVATE-SYNTHETIC-ACCOUNT',transaction='123456789',paymentId='987654321',money=(amount:string)=>({amount,currencyCode:'THB'});
const invoice={hotelId:'KAT',transactionNo:transaction,invoiceNo:'1234',folioNo:'5678',transactionDate:'2026-09-09',postingDate:'2026-09-09',invoiceType:'Normal',originalAmount:money('10000.00'),amount:money('10000.00'),payments:money('1000.00'),balance:money('9000.00'),compressed:false,guestName:'PRIVATE GUEST'};
const payment={hotelId:'KAT',transactionNo:paymentId,transactionDate:'2026-09-10',postingDate:'2026-09-10',amount:money('-1000.00'),amountUsed:money('-1000.00'),balance:money('0.00'),transferredIn:false,transferredOut:false,paymentCard:{cardNumber:'PRIVATE CARD'}};
type Overrides={candidates?:unknown;changeTen?:boolean;historyError?:boolean;mappingError?:boolean;mappingRaw?:unknown;emptyMapping?:boolean;emptyWindow?:boolean;missingDate?:boolean;secondAccount?:boolean;candidateStatus?:number};
function setup(overrides:Overrides={}){
 const calls:{url:URL;method:string;body:string|null}[]=[];
 vi.stubGlobal('fetch',async(input:RequestInfo|URL,init:RequestInit={})=>{
  const request=input instanceof Request?input:new Request(input,init),url=new URL(request.url),body=request.method==='GET'?null:await request.text();calls.push({url,method:request.method,body});
  if(url.origin===env.SUPABASE_URL){expect(url.pathname).toBe('/rest/v1/rpc/ar_financial_diagnostic_candidates');return Response.json(overrides.candidates??{hotel:'KAT',accounts:[{accountId:account,invoiceTransactionId:transaction,invoiceNo:'1234'},...(overrides.secondAccount?[{accountId:'OTHER-PRIVATE-ACCOUNT',invoiceTransactionId:null,invoiceNo:null}]:[])]},{status:overrides.candidateStatus??200});}
  if(url.pathname==='/oauth/v1/tokens')return Response.json({access_token:'synthetic-private-token',expires_in:3600});
  if(url.pathname==='/bof/v1/hotels/KAT/businessDate')return Response.json({hotels:[{hotelId:'KAT',businessDate:'2026-09-10'}]});
  if(url.pathname.endsWith('/invoiceAppliedPayments'))return overrides.mappingError?new Response('PRIVATE ERROR',{status:503}):Response.json(overrides.mappingRaw??{details:overrides.emptyMapping?[]:[{...invoice,paymentTrxNo:paymentId,appliedAmount:money('1000.00')}]});
  if(url.pathname.endsWith('/invoicePaymentDetails'))return Response.json({details:[{hotelId:'KAT',accountId:{id:account},...(url.pathname.includes('/transactions/'+paymentId+'/')?{payments:[payment]}:{invoices:[invoice]})}]});
  if(url.pathname.startsWith('/ars/v1/invoicePayments/accounts/')){
   if(overrides.historyError)return new Response('PRIVATE ERROR',{status:503});
   const source=overrides.missingDate?{...payment,transactionDate:undefined}:payment,start=url.searchParams.get('start')!,end=url.searchParams.get('end')!,limit=Number(url.searchParams.get('limit'));
   if(overrides.emptyWindow)return Response.json({details:[],offset:limit,limit,totalResults:0,hasMore:false});
   const invoices=invoice.transactionDate>=start&&invoice.transactionDate<=end?[{...invoice,...(overrides.changeTen&&limit===10?{transactionNo:'999999'}:{})}]:[];
   const payments=!source.transactionDate||source.transactionDate>=start&&source.transactionDate<=end?[source]:[];
   return Response.json({details:[{hotelId:'KAT',accountId:{id:decodeURIComponent(url.pathname.split('/').at(-1)!)},invoices,payments}],offset:limit,limit,totalResults:invoices.length+payments.length,hasMore:false});
  }
  throw Error('Unexpected synthetic endpoint');
 });return calls;
}
afterEach(()=>vi.unstubAllGlobals());
it('runs bounded read-only comparisons and emits no identities, amounts, cards or credentials',async()=>{const calls=setup();const result=await runFinancialDiagnostic(env,'KAT');expect(result).toMatchObject({hotel:'KAT',status:'checked',accountsChecked:1,windowDays:7,readChecksPassed:true,financialPeriodCoverageVerified:false,applicationDatesVerified:false});expect(result.samples[0]).toMatchObject({sameMembership:true,sameValues:true,invoices:1,payments:1,detail:{status:'found'},mapping:{status:'read',links:1,applicationDatesPresent:0}});const text=JSON.stringify(result);for(const privateValue of [account,transaction,paymentId,'10000.00','9000.00','PRIVATE GUEST','PRIVATE CARD','synthetic-private-token','synthetic-private-key'])expect(text).not.toContain(privateValue);const history=calls.filter(c=>c.url.pathname.includes('/invoicePayments/accounts/'));expect(history.map(c=>[c.url.searchParams.get('start'),c.url.searchParams.get('end'),c.url.searchParams.get('limit')])).toEqual([['2026-09-04','2026-09-10','20'],['2026-09-04','2026-09-10','10'],['2026-09-09','2026-09-09','20'],['2026-09-10','2026-09-10','20']]);expect(calls.filter(c=>c.url.origin===env.OPERA_BASE_URL&&!c.url.pathname.includes('/oauth/')).every(c=>c.method==='GET')).toBe(true);expect(calls.filter(c=>c.url.origin===env.SUPABASE_URL)).toHaveLength(1);});
it('detects changing history membership instead of reporting read checks passed',async()=>{setup({changeTen:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.readChecksPassed).toBe(false);expect(result.samples[0].sameMembership).toBe(false);expect(result.financialPeriodCoverageVerified).toBe(false);});
it('reports missing source dates without fabricating date-filter proof',async()=>{setup({missingDate:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.readChecksPassed).toBe(false);expect(result.samples[0].dateFields.payment.transactionDate).toMatchObject({present:0,withinWindow:0});});
it('contains provider failures as categorical sample results without private text',async()=>{setup({historyError:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.readChecksPassed).toBe(false);expect(result.samples[0]).toMatchObject({status:'unavailable',error:{stage:'history_20',code:'provider_unavailable'}});expect(JSON.stringify(result)).not.toContain('PRIVATE');});
it('does not turn unavailable mapping into zero verified applications',async()=>{setup({mappingError:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.samples[0].mapping).toMatchObject({status:'unavailable',links:null});expect(result.readChecksPassed).toBe(false);});
it('marks empty mapping as a current observation with historical completeness still unverified',async()=>{setup({emptyMapping:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.samples[0].mapping).toMatchObject({status:'read',links:0,complete:false,applicationDatesPresent:0});expect(result.applicationDatesVerified).toBe(false);});
it('does not report date-read proof from only empty history responses',async()=>{setup({emptyWindow:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result).toMatchObject({status:'checked',readChecksPassed:false,financialPeriodCoverageVerified:false});expect(result.samples[0]).toMatchObject({invoices:0,payments:0});});
it('never silently truncates an excessive or cross-hotel candidate response',async()=>{for(const candidates of [{hotel:'TSK',accounts:[]},{hotel:'KAT',accounts:Array.from({length:3},()=>({accountId:account,invoiceTransactionId:null,invoiceNo:null}))},{hotel:'KAT',accounts:[{accountId:account,invoiceTransactionId:null,invoiceNo:null},{accountId:account,invoiceTransactionId:null,invoiceNo:null}]}]){const calls=setup({candidates});const result=await runFinancialDiagnostic(env,'KAT');expect(result).toMatchObject({status:'unavailable',accountsChecked:0,readChecksPassed:false,error:{stage:'candidates',code:'invalid_response'}});expect(calls).toHaveLength(1);}});
it('reports no candidates explicitly and does not call OPERA',async()=>{const calls=setup({candidates:{hotel:'KAT',accounts:[]}});expect(await runFinancialDiagnostic(env,'KAT')).toMatchObject({status:'no_candidates',accountsChecked:0,readChecksPassed:false});expect(calls).toHaveLength(1);});
it('checks both selected accounts without exposing their identities',async()=>{setup({secondAccount:true});const result=await runFinancialDiagnostic(env,'KAT');expect(result.accountsChecked).toBe(2);expect(result.samples[1].mapping.status).toBe('no_candidate');expect(JSON.stringify(result)).not.toContain('OTHER-PRIVATE-ACCOUNT');});
it('rejects invalid hotel and candidate limits before service access',async()=>{const calls=setup();await expect(runFinancialDiagnostic(env,'OTHER' as 'KAT')).rejects.toMatchObject({code:'invalid_request'});await expect(runFinancialDiagnostic(env,'KAT',{maxAccounts:3 as 2})).rejects.toMatchObject({code:'invalid_request'});expect(calls).toHaveLength(0);});
it('reports allowlisted mapping field types and a static parse stage from a single response',async()=>{
 const calls=setup({mappingRaw:{details:[{...invoice,transactionNo:'111111111',paymentTrxNo:paymentId,appliedAmount:{amount:1000},['PRIVATE UNKNOWN KEY']:'PRIVATE VALUE',paymentCard:{cardNumber:'PRIVATE CARD'}}]}});
 const r=await runFinancialDiagnostic(env,'KAT');expect(r.samples[0].mapping).toMatchObject({status:'unavailable',parseStage:'financial_mapping_identity',shape:{type:'object',fields:{details:{type:'array',count:1,sample:{type:'object',fields:{hotelId:{type:'string'},transactionNo:{type:'string'},appliedAmount:{type:'object',fields:{amount:{type:'number'}}}}}}}},identityChecks:{sampled:1,hotelMatches:1,invoiceTransactionMatches:0,paymentIdentityPresent:1}});
 const output=JSON.stringify(r);expect(output).not.toMatch(/111111111|987654321|123456789|PRIVATE|10000.00|synthetic-private/);expect(calls.filter(c=>c.url.pathname.endsWith('/invoiceAppliedPayments'))).toHaveLength(1);
});
it('distinguishes mapping currency failure without printing the source currency or amount',async()=>{setup({mappingRaw:{details:[{...invoice,paymentTrxNo:paymentId,appliedAmount:{amount:1000}}]}});const r=await runFinancialDiagnostic(env,'KAT');expect(r.samples[0].mapping).toMatchObject({parseStage:'financial_currency',shape:{fields:{details:{sample:{fields:{appliedAmount:{fields:{amount:{type:'number'}}}}}}}}});expect(JSON.stringify(r.samples[0].mapping)).not.toContain('1000');});
it('corroborates slim mapping transaction IDs through independent scoped payment detail without accepting them yet',async()=>{
 const calls=setup({mappingRaw:{details:[{transactionNo:Number(paymentId),originalAmount:money('-1000.00'),appliedAmount:money('1000.00'),postingDate:'2026-09-10'}]}});
 const result=await runFinancialDiagnostic(env,'KAT');expect(result.samples[0].mapping).toMatchObject({status:'unavailable',parseStage:'financial_hotel_scope',corroboration:{sampled:1,candidateIds:1,idsInWindow:1,paymentDetailsFound:1,originalAmountMatches:1,postingDateMatches:1,paymentTransactionDateMatches:1,sourceInvoiceConfirmed:true,acceptedAsMapping:false,errors:0}});
 expect(calls.filter(c=>c.url.pathname.includes('/transactions/'+paymentId+'/invoicePaymentDetails'))).toHaveLength(1);expect(JSON.stringify(result)).not.toMatch(/987654321|123456789|1000.00|PRIVATE/);
});
it('does not infer payment identity or normalize away mismatching original amounts/dates',async()=>{
 setup({mappingRaw:{details:[{transactionNo:Number(paymentId),originalAmount:money('1000.00'),appliedAmount:money('1000.00'),postingDate:'2026-09-09'}]}});
 const result=await runFinancialDiagnostic(env,'KAT');expect(result.samples[0].mapping).toMatchObject({corroboration:{paymentDetailsFound:1,originalAmountMatches:0,postingDateMatches:0,paymentTransactionDateMatches:0,acceptedAsMapping:false}});
});
