import {describe,it,expect} from 'vitest';
import {pdfFilename,deliveryFilenames,defaultPdfFilename} from '../src/pdf/filenames';
import {deliveryGroups,restoreProject} from '../src/pdf/model';
import type {PdfProject,PdfSourceDocument} from '../src/pdf/types';
const sources:PdfSourceDocument[]=['a','b'].map(id=>({id,invoiceId:id,name:`Invoice ${id}.pdf`,kind:'invoice',bytes:new Uint8Array()}));
const project:PdfProject={version:1,content:'invoices',delivery:'separate',pages:sources.map(s=>({id:s.id,sourceId:s.id,sourcePage:1,width:600,height:800,layers:[]}))};
describe('preparation filenames',()=>{
 it('preserves Thai and adds exactly one extension',()=>{expect(pdfFilename('ใบแจ้งหนี้ 123')).toBe('ใบแจ้งหนี้ 123.pdf');expect(pdfFilename('Invoice.PDF')).toBe('Invoice.PDF');});
 it('rejects unsafe, ambiguous, reserved and oversized names',()=>{for(const name of ['', '.pdf','../bill.pdf','folder/bill.pdf','folder\\bill.pdf','a\n.pdf','a\0.pdf','bill.pdf.pdf','CON.pdf','LPT1.pdf','a?.pdf','a .pdf','a'.repeat(197)])expect(()=>pdfFilename(name)).toThrow();});
 it('keeps defaults and rejects case insensitive output collisions',()=>{const groups=deliveryGroups(project,sources);expect(deliveryFilenames(project,groups)).toEqual(['01-Invoice a.pdf','02-Invoice b.pdf']);expect(()=>deliveryFilenames({...project,outputNames:{[groups[0].id]:'Bill.pdf',[groups[1].id]:'bill.pdf'}},groups)).toThrow('different filename');});
 it('generates valid defaults from provider punctuation without relaxing chosen names',()=>{for(const name of ['Invoice123..45','../folder\\report','Invoice.pdf.pdf','Invoice. ','..','CON','..pdf','a'.repeat(99)+'.pdf','ใบแจ้งหนี้..123'])expect(()=>pdfFilename(defaultPdfFilename({id:'test',name},0))).not.toThrow();expect(defaultPdfFilename({id:'test',name:'Invoice123..45'},0)).toBe('01-Invoice123.45.pdf');expect(defaultPdfFilename({id:'test',name:'Invoice-A'},1)).toBe('02-Invoice-A.pdf');expect(()=>deliveryFilenames({...project,outputNames:{[deliveryGroups(project,sources)[0].id]:'Invoice..123.pdf'}},deliveryGroups(project,sources))).toThrow('without paths');});
 it('rejects a custom/default collision after group deletion without rewriting custom names',()=>{const catalog=[...sources,{...sources[1],id:'c',invoiceId:'c',name:'Invoice c.pdf'}],original={...project,pages:[...project.pages,{...project.pages[1],id:'c',sourceId:'c'}]},groups=deliveryGroups(original,catalog),named={...original,outputNames:{[groups[1].id]:'02-Invoice c.pdf'}};expect(deliveryFilenames(named,groups)).toEqual(['01-Invoice a.pdf','02-Invoice c.pdf','03-Invoice c.pdf']);expect(()=>deliveryFilenames(named,deliveryGroups({...named,pages:named.pages.filter(p=>p.sourceId!=='a')},catalog))).toThrow('different filename');expect(named.outputNames[groups[1].id]).toBe('02-Invoice c.pdf');});
 it('binds names to source identity through deletions, display renames and mode roundtrips',()=>{const groups=deliveryGroups(project,sources),named={...project,outputNames:{[groups[1].id]:'Selected.pdf'},sourceNames:{a:'Scan.pdf'}};const remaining=deliveryGroups({...named,pages:named.pages.filter(p=>p.sourceId==='b')},sources);expect(deliveryFilenames(named,remaining)).toEqual(['Selected.pdf']);expect(deliveryFilenames(named,deliveryGroups(named,sources.map(s=>({...s,name:'changed.pdf'}))))[1]).toBe('Selected.pdf');expect(deliveryFilenames({...named,delivery:'combined'},deliveryGroups({...named,delivery:'combined'},sources))).toEqual(['01-Documents.pdf']);expect(deliveryFilenames(named,deliveryGroups(named,sources))[1]).toBe('Selected.pdf');});
 it('roundtrips names and rejects untrusted persisted names',()=>{const groups=deliveryGroups(project,sources),named={...project,outputNames:{[groups[0].id]:'Reviewed.pdf'},sourceNames:{a:'Imported scan.pdf'}};expect(restoreProject(JSON.parse(JSON.stringify(named)),project,sources)).toEqual(named);expect(()=>restoreProject({...named,sourceNames:{unknown:'Scan.pdf'}},project,sources)).toThrow();expect(()=>restoreProject({...named,outputNames:{[groups[0].id]:'../bad.pdf'}},project,sources)).toThrow();});
});
