import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {deliverMessage} from '../worker/email/delivery';
const m=vi.hoisted(()=>({prepare:vi.fn(),token:vi.fn()}));
vi.mock('../worker/email/oauth',()=>({gmailCanRead:async()=>true,gmailToken:m.token}));
vi.mock('../worker/email/gmail-draft',()=>({prepareMail:m.prepare,readMailFile:vi.fn(),draftBudget:()=>10000}));
const actor='00000000-0000-4000-8000-000000000001',draftId='00000000-0000-4000-8000-000000000002';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const policy={version:2,rounds:[{key:'Friendly',label:'Friendly',anchor:'due',offsetDays:-7,terminal:false,active:true},{key:'round_personal',label:'Personal follow-up',anchor:'previous_sent',offsetDays:5,terminal:true,active:true}]};
function setup(existing=false){const calls:{path:string;body:Record<string,unknown>}[]=[];vi.stubGlobal('fetch',async(path:string,init:RequestInit={})=>{const body=JSON.parse(String(init.body??'{}'));calls.push({path,body});if(path.endsWith('/ar_mail_for_draft'))return Response.json(existing?{id:draftId,state:'sent',mode:'send',sent_at:'2026-09-01'}:null);if(path.endsWith('/ar_email_get'))return Response.json({id:draftId,revision:1,purpose:'collection',package_changed:false,recipients:{to:['recipient@example.test'],cc:[],bcc:[]},subject:'Synthetic',body:'Synthetic',exports:[]});if(path.endsWith('/ar_collection_policy_get'))return Response.json(policy);if(path.endsWith('/ar_mail_claim'))return Response.json({id:draftId,state:'pending',mode:'send',claimed:false});throw Error('unexpected provider work');});return calls;}
beforeEach(()=>{m.token.mockResolvedValue('synthetic');m.prepare.mockResolvedValue({raw:'synthetic',expected:{recipients:{to:['recipient@example.test'],cc:[],bcc:[]},subject:'Synthetic',body:'Synthetic',files:[]}});});
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();});
it('rejects a changed reviewed policy before file preparation or Gmail work',async()=>{const calls=setup();await expect(deliverMessage(env,actor,draftId,1,'send','round_personal',1)).rejects.toThrow('email_policy_revision_conflict');expect(m.prepare).not.toHaveBeenCalled();expect(m.token).not.toHaveBeenCalled();expect(calls.some(c=>c.path.endsWith('/ar_mail_claim'))).toBe(false);});
it('pins the reviewed version and registered custom key in the atomic claim',async()=>{const calls=setup();await expect(deliverMessage(env,actor,draftId,1,'send','round_personal',2)).resolves.toMatchObject({state:'pending'});expect(calls.find(c=>c.path.endsWith('/ar_mail_claim'))?.body).toMatchObject({p_stage:'round_personal',p_expected:{policyVersion:2}});expect(calls.every(c=>c.path.startsWith(env.SUPABASE_URL))).toBe(true);});
it('an existing confirmed delivery stays readable without reinterpretation by a new policy',async()=>{const calls=setup(true);expect(await deliverMessage(env,actor,draftId,1,'send','Final',1)).toMatchObject({state:'sent',recorded:true});expect(calls).toHaveLength(1);expect(m.prepare).not.toHaveBeenCalled();});
