import {it,expect} from 'vitest';
import {parseSheetText,planSheetPaste,normalizeReceived} from '../src/register/paste';
import type {RegisterRow} from '../src/register/model';
const row:RegisterRow={hotel:'KAT',account_id:'a',id:'1',account_name:'Synthetic',account_no:null,account_type:'OTA',guest:'Guest',invoice_no:'101',folio_no:'201',transaction_date:'2026-09-01',original:100,open:100,age:1,aging:'Up to 30',verification_state:'verified',collection_role:'standalone',collection_selectable:true,workflow:null,workflow_revision:0,tracking_revision:0,exception_revision:0,billing_required:true,credit_term:30,first_billing_date:null,due_date:null,last_reminder_stage:null,last_reminder_date:null,promised_date:null,tracking_status:'',owner_name:'Original owner',reported_received:null,note:'Keep this note',edited_at:null,hidden:false};
it('reads quoted multiline notes, tabs, escaped quotes and Windows clipboard rows',()=>{expect(parseSheetText('Alice\t"Line 1\nLine 2"\r\nBob\t"A ""quote"""\r\n')).toEqual([['Alice','Line 1\nLine 2'],['Bob','A "quote"']]);});
it.each(['"unfinished','A\tB\nC','x'.repeat(100001),Array(101).fill('x').join('\n')])('rejects malformed or oversized pasted ranges',text=>expect(()=>parseSheetText(text)).toThrow());
it('normalizes dates and amounts but preserves all untouched fields',()=>{const entries=planSheetPaste('26/09/2026',[row],0,[{label:'Billing date',field:'firstBillingDate'}],'2026-09-26',[]);expect(entries[0].values).toMatchObject({firstBillingDate:'2026-09-26',ownerName:'Original owner',note:'Keep this note'});expect(planSheetPaste('1,250.50',[row],0,[{label:'Received',field:'reportedReceived'}],'2026-09-26',[])[0].values.reportedReceived).toBe('1250.50');});
it.each(['31/02/2026','27/09/2026','0000-01-01'])('rejects invalid or future actual dates: %s',text=>expect(()=>planSheetPaste(text,[row],0,[{label:'Billing',field:'firstBillingDate'}],'2026-09-26',[])).toThrow());
it('rejects read-only targets and incomplete reminder pairs',()=>{expect(()=>planSheetPaste('0',[row],0,[{label:'OPERA balance'}],'2026-09-26',[])).toThrow('read-only');expect(()=>planSheetPaste('Follow 1',[row],0,[{label:'Reminder',field:'lastReminderStage'}],'2026-09-26',[{key:'Follow 1',label:'Follow-up 1'}])).toThrow('Date sent');});

it('shares strict amount parsing between single-cell entry and pasted ranges',()=>{expect(normalizeReceived(' 1,250.50 ')).toBe('1250.50');expect(normalizeReceived('')).toBeNull();expect(normalizeReceived('0')).toBe('0');expect(()=>normalizeReceived('12,50')).toThrow();});
