import {afterEach,expect,it,vi} from 'vitest';
import {PDFDocument,PDFName} from 'pdf-lib';
import {remittanceFileRequest,remittanceLimits,remittanceFileRpc,checkedRemittanceRecord,checkedRemittanceRow} from '../worker/remittance/files';
import {syntheticPdf} from '../worker/drive/archive';
import {hash} from '../worker/email/crypto';
import type {RemittanceRecord,RemittanceFile} from '../src/remittance/model';

const actor='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002',fileId='00000000-0000-4000-8000-000000000003',command='00000000-0000-4000-8000-000000000004';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const key=`remittances/${id}/${fileId}`;
const bytes=syntheticPdf();
function record(files:RemittanceFile[]=[]):RemittanceRecord{return {id,revision:1,state:'active',hotel:'KAT',accountId:'synthetic',accountName:'Synthetic',accountType:'TA',accountNo:null,receivedDate:'2026-09-10',reference:'Synthetic notice',sourceNote:'',notes:'',reportedAmount:null,allocatedAmount:'0.00',unallocatedAmount:null,invoiceCount:0,fileCount:files.filter(f=>f.state==='ready').length,pendingFiles:files.filter(f=>f.state==='pending').length,lines:[],files,linkedOpen:null,knownLinkedOpen:'0.00',unverifiedLines:0,resolution:'needs_review',createdAt:'2026-09-10T00:00:00Z',updatedAt:'2026-09-10T00:00:00Z',voidReason:null};}
async function file(state:RemittanceFile['state']='pending'){return {id:fileId,name:'Proof.pdf',mime:'application/pdf',byteCount:bytes.length,sha256:await hash(bytes),state,error:null,createdAt:'2026-09-10T00:00:00Z',storageKey:key};}
function upload(content:Uint8Array=bytes,name='Proof.pdf',extraHeaders:Record<string,string>={}){return new Request(`https://app.test/api/remittances/${id}/files/${fileId}?revision=1&name=${encodeURIComponent(name)}`,{method:'POST',headers:{'Content-Type':'application/pdf',...extraHeaders},body:new Uint8Array(content).buffer});}
function action(method='DELETE',changes:Record<string,unknown>={}){return new Request(`https://app.test/api/remittances/${id}/files/${fileId}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:command,revision:1,reason:'Correct evidence',confirmed:true,...changes})});}
type Setup={state?:RemittanceFile['state'];fileOverrides?:Partial<RemittanceFile>;writeStatus?:number;lostWrite?:boolean;lostFinish?:boolean;wrongBytes?:boolean;missingBytes?:boolean;badKey?:string;beginError?:string;readRedirect?:boolean;writeRedirect?:boolean;readLength?:number;readHeaderLength?:number;readStatus?:number};
async function setup(options:Setup={}){
 const metadata={...await file(options.state),...options.fileOverrides},calls:{url:string;method:string;body:Record<string,unknown>|null}[]=[];
 let completed=false,savedAction:string|null=null;
 vi.stubGlobal('fetch',async(input:RequestInfo|URL,init:RequestInit={})=>{
  const url=String(input),method=init.method??'GET';const body=url.includes('/rpc/')?JSON.parse(String(init.body)):null;calls.push({url,method,body});
  expect(new URL(url).origin).toBe(env.SUPABASE_URL);expect(init.redirect).toBe('manual');expect(new Headers(init.headers).get('apikey')).toBe('synthetic');expect(new Headers(init.headers).get('Authorization')).toBeNull();
  if(url.endsWith('/ar_remittance_file_begin')){expect(body.p_actor).toBe(actor);if(options.beginError)return Response.json({error:options.beginError});return Response.json({file:{...metadata,state:completed?'ready':metadata.state,storageKey:options.badKey??key},record:record([{...metadata,state:completed?'ready':metadata.state}])});}
  if(url.endsWith('/ar_remittance_file_get'))return Response.json({...metadata,storageKey:options.badKey??key});
  if(url.endsWith('/ar_remittance_command_get'))return Response.json(savedAction===null?{complete:false}:{complete:true,recordId:id,revision:2});
  if(url.endsWith('/ar_remittance_file_finish')){completed=true;if(options.lostFinish){options.lostFinish=false;throw Error('upstream body synthetic secret');}return Response.json({...record([{...metadata,state:'ready'}]),revision:2});}
  if(url.endsWith('/ar_remittance_file_status')){const fingerprint=JSON.stringify({recordId:body.p_id,fileId:body.p_file_id,commandId:body.p_command,revision:body.p_revision,restore:body.p_restore,reason:body.p_reason});if(savedAction!==null&&savedAction!==fingerprint)return Response.json({error:'remittance_command_conflict'});savedAction=fingerprint;return Response.json({...record([{...metadata,state:body.p_restore?'ready':'removed'}]),revision:2});}
  if(url.includes('/object/authenticated/')){if(options.readRedirect)return new Response(null,{status:302,headers:{Location:'https://evil.test/private'}});if(options.missingBytes||options.readStatus)return new Response(null,{status:options.readStatus??404});const body=options.readLength===undefined?new Uint8Array(options.wrongBytes?new Uint8Array(bytes.length).fill(65):bytes):new Uint8Array(options.readLength);return new Response(body.buffer,{headers:options.readHeaderLength===undefined?{}:{'Content-Length':String(options.readHeaderLength)}});}
  if(url.includes('/storage/')&&method==='POST'){expect(new Headers(init.headers).get('x-upsert')).toBe('false');if(options.lostWrite){options.lostWrite=false;throw Error('uncertain');}if(options.writeRedirect)return new Response(null,{status:307,headers:{Location:'https://evil.test'}});return new Response(null,{status:options.writeStatus??200});}
  throw Error('unexpected synthetic request');
 });return {calls,metadata};
}
afterEach(()=>vi.unstubAllGlobals());

it('reserves inspected immutable metadata before a private write and checksum read-back before finish',async()=>{
 const {calls}=await setup();expect(await remittanceFileRequest(upload(),env,actor,id,fileId)).toMatchObject({revision:2,files:[{state:'ready'}]});
 expect(calls.map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_file_begin',fileId,fileId,'ar_remittance_file_finish']);
 expect(calls[0].body).toMatchObject({p_id:id,p_revision:1,p_file:{id:fileId,name:'Proof.pdf',byteCount:bytes.length,sha256:await hash(bytes),inspection:{version:1,pages:1}},p_limits:{maxFileBytes:10*1048576,maxFiles:50,maxTotalFileBytes:100*1048576}});
});
it.each([400,409])('reconciles duplicate storage %s only after reading exact reserved bytes',async writeStatus=>{const {calls}=await setup({writeStatus});expect(await remittanceFileRequest(upload(),env,actor,id,fileId)).toMatchObject({revision:2});expect(calls.at(-1)?.url).toContain('file_finish');});
it('keeps an uncertain upload reservation retryable with the same ID',async()=>{const {calls}=await setup({lostWrite:true,writeStatus:409});await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_upload_pending');expect(calls.some(c=>c.url.endsWith('file_finish'))).toBe(false);expect(await remittanceFileRequest(upload(),env,actor,id,fileId)).toMatchObject({revision:2});expect(calls.filter(c=>c.url.endsWith('file_begin')).every(c=>c.body?.p_file&&((c.body.p_file as {id:string}).id===fileId))).toBe(true);});
it('replays a lost finish without another storage write and still verifies retained bytes',async()=>{const {calls}=await setup({lostFinish:true});await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_unavailable');expect(await remittanceFileRequest(upload(),env,actor,id,fileId)).toMatchObject({files:[{state:'ready'}]});expect(calls.filter(c=>c.method==='POST'&&c.url.includes('/storage/'))).toHaveLength(1);expect(calls.filter(c=>c.url.includes('/object/authenticated/'))).toHaveLength(2);});
it('rejects immutable metadata conflicts and removed file IDs before storage',async()=>{for(const options of [{beginError:'remittance_file_conflict'},{state:'removed' as const}]){const {calls}=await setup(options);await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_file_conflict');expect(calls).toHaveLength(1);}});
it('rejects wrong owner before any storage read',async()=>{const {calls}=await setup({beginError:'remittance_forbidden'});await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_forbidden');expect(calls).toHaveLength(1);});
it('rejects unsafe returned keys and any redirects without following them',async()=>{for(const badKey of ['https://evil.test/private',`remittances/${fileId}/${id}`,`${key}/../other`,`${key}?secret=1`]){const {calls}=await setup({badKey});await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_file_invalid');expect(calls).toHaveLength(1);}for(const options of [{readRedirect:true},{writeRedirect:true}]){const {calls}=await setup(options);await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_storage_unavailable');expect(calls.some(c=>c.url.endsWith('file_finish'))).toBe(false);}});
it('never finishes changed or missing stored bytes, including conflict responses',async()=>{for(const options of [{wrongBytes:true},{missingBytes:true,writeStatus:400}]){const {calls}=await setup(options);await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow(options.wrongBytes?'remittance_checksum_mismatch':'remittance_file_bytes_missing');expect(calls.some(c=>c.url.endsWith('file_finish'))).toBe(false);}});
it('rejects active PDFs, disguised HTML, mismatched MIME and unsafe names before reservation',async()=>{const pdf=await PDFDocument.create();pdf.addPage();pdf.catalog.set(PDFName.of('OpenAction'),pdf.context.obj({S:'JavaScript',JS:'synthetic'}));const {calls}=await setup();for(const request of [upload(await pdf.save()),upload(new TextEncoder().encode('<html/>')),upload(bytes,'Proof.pdf',{'Content-Type':'image/png'}),upload(bytes,'bad\r\n.pdf')])await expect(remittanceFileRequest(request,env,actor,id,fileId)).rejects.toThrow(/remittance_file_/);expect(calls).toHaveLength(0);});
it('enforces declared and streamed request limits before reservation',async()=>{const {calls}=await setup();await expect(remittanceFileRequest(upload(bytes,'Proof.pdf',{'Content-Length':String(bytes.length+1)}),{...env,REMITTANCE_MAX_FILE_BYTES:String(bytes.length)},actor,id,fileId)).rejects.toThrow('remittance_file_too_large');await expect(remittanceFileRequest(upload(),{...env,REMITTANCE_MAX_FILE_BYTES:String(bytes.length-1)},actor,id,fileId)).rejects.toThrow('remittance_file_too_large');expect(calls).toHaveLength(0);expect(await remittanceFileRequest(upload(),{...env,REMITTANCE_MAX_FILE_BYTES:String(bytes.length)},actor,id,fileId)).toMatchObject({revision:2});});
it('exposes explicit defaults and accepts ceilings but rejects invalid or excessive resource configuration',()=>{expect(remittanceLimits({})).toEqual({maxFileBytes:10*1048576,maxFiles:50,maxTotalFileBytes:100*1048576});expect(remittanceLimits({REMITTANCE_MAX_FILE_BYTES:String(20*1048576),REMITTANCE_MAX_FILES:'200',REMITTANCE_MAX_TOTAL_FILE_BYTES:String(512*1048576)})).toEqual({maxFileBytes:20*1048576,maxFiles:200,maxTotalFileBytes:512*1048576});for(const [name,value]of [['REMITTANCE_MAX_FILE_BYTES',String(20*1048576+1)],['REMITTANCE_MAX_FILES','201'],['REMITTANCE_MAX_TOTAL_FILE_BYTES',String(512*1048576+1)],['REMITTANCE_MAX_FILES','0'],['REMITTANCE_MAX_FILES','1.5'],['REMITTANCE_MAX_FILES','1e2']])expect(()=>remittanceLimits({[name]:value})).toThrow('remittance_not_configured');});
it('downloads only ready evidence with owner lookup, exact hash and attachment-only headers',async()=>{await setup({state:'ready'});const result=await remittanceFileRequest(new Request(`https://app.test/api/remittances/${id}/files/${fileId}`),env,actor,id,fileId);expect(result).toBeInstanceOf(Response);const response=result as Response;expect(response.headers.get('Content-Disposition')).toContain('attachment;');expect(response.headers.get('X-Content-Type-Options')).toBe('nosniff');expect(response.headers.get('Cache-Control')).toBe('no-store');expect(new Uint8Array(await response.arrayBuffer())).toEqual(bytes);for(const state of ['pending','removed'] as const){const {calls}=await setup({state});await expect(remittanceFileRequest(new Request('https://app.test'),env,actor,id,fileId)).rejects.toThrow('remittance_file_not_ready');expect(calls).toHaveLength(1);}});
it('soft-removes without deleting storage and restores only after retained bytes verify',async()=>{let f=await setup({state:'pending'});expect(await remittanceFileRequest(action(),env,actor,id,fileId)).toMatchObject({files:[{state:'removed'}]});expect(f.calls).toHaveLength(1);expect(f.calls[0].body).toMatchObject({p_restore:false,p_command:command,p_reason:'Correct evidence'});f=await setup({state:'removed'});expect(await remittanceFileRequest(action('POST'),env,actor,id,fileId,true)).toMatchObject({files:[{state:'ready'}]});expect(f.calls.map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_command_get','ar_remittance_file_get',fileId,'ar_remittance_file_status']);expect(f.calls.at(-1)?.body).toMatchObject({p_restore:true,p_revision:1});expect(f.calls.some(c=>c.method==='DELETE')).toBe(false);});
it('reports a new upload is needed to restore a removed incomplete file with missing bytes',async()=>{const {calls}=await setup({state:'removed',missingBytes:true});await expect(remittanceFileRequest(action('POST'),env,actor,id,fileId,true)).rejects.toThrow('remittance_file_reupload_required');expect(calls.some(c=>c.url.endsWith('file_status'))).toBe(false);});
it('contains provider errors and forbids invalid service configuration before any request',async()=>{const {calls}=await setup();for(const SUPABASE_URL of ['http://example.supabase.co','https://name:password@example.supabase.co','https://example.supabase.co/path','https://example.supabase.co?other=1'])await expect(remittanceFileRequest(upload(),{...env,SUPABASE_URL},actor,id,fileId)).rejects.toThrow('remittance_not_configured');expect(calls).toHaveLength(0);vi.stubGlobal('fetch',async()=>Response.json({error:'synthetic upstream detail'}));await expect(remittanceFileRpc(env,'ar_remittance_get',{p_actor:actor,p_id:id})).rejects.toThrow(/^remittance_unavailable$/);});
it('independently detects reservation metadata conflicts even if RPC returns success',async()=>{for(const fileOverrides of [{name:'Other.pdf'},{sha256:'f'.repeat(64)},{byteCount:bytes.length+1}]){const {calls}=await setup({fileOverrides});await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_file_conflict');expect(calls).toHaveLength(1);}});
it('rejects truncated, oversized and falsely declared stored response lengths before finish',async()=>{for(const options of [{readLength:bytes.length-1},{readLength:bytes.length+1},{readHeaderLength:bytes.length+1}]){const {calls}=await setup(options);await expect(remittanceFileRequest(upload(),env,actor,id,fileId)).rejects.toThrow('remittance_checksum_mismatch');expect(calls.some(c=>c.url.endsWith('file_finish'))).toBe(false);}});
it('never treats malformed detail as an empty record and strips private keys or upstream errors',async()=>{const metadata=await file(),value={...record([metadata]),providerSecret:'synthetic hidden detail'};expect(checkedRemittanceRecord(value)).not.toHaveProperty('providerSecret');expect(checkedRemittanceRecord(value).files[0]).not.toHaveProperty('storageKey');expect(checkedRemittanceRecord({...value,files:[{...metadata,error:'synthetic hidden detail'}]}).files[0].error).toBe('remittance_file_unavailable');expect(checkedRemittanceRow(value)).not.toHaveProperty('lines');for(const malformed of [{...value,lines:undefined},{...value,revision:0},{...value,knownLinkedOpen:0},{...value,pendingFiles:undefined},{...value,files:[{...metadata,sha256:'invalid'}]}])expect(()=>checkedRemittanceRecord(malformed)).toThrow(/remittance_/);});
it('bounds RPC response bytes and fails instead of silently truncating large option lists',async()=>{vi.stubGlobal('fetch',async()=>new Response('{}',{headers:{'Content-Length':String(32*1048576+1)}}));await expect(remittanceFileRpc(env,'ar_remittance_options',{p_actor:actor})).rejects.toThrow('remittance_response_too_large');});
it('replays a completed restore command without storage reads even when Storage is now unavailable',async()=>{const options:Setup={state:'removed'};const {calls}=await setup(options);expect(await remittanceFileRequest(action('POST'),env,actor,id,fileId,true)).toMatchObject({revision:2,files:[{state:'ready'}]});const beforeRetry=calls.length;options.readStatus=503;expect(await remittanceFileRequest(action('POST'),env,actor,id,fileId,true)).toMatchObject({revision:2,files:[{state:'ready'}]});expect(calls.slice(beforeRetry).map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_command_get','ar_remittance_file_status']);expect(calls.filter(c=>c.url.includes('/storage/'))).toHaveLength(1);});
it('sends completed restore retries through exact command validation and rejects changed details',async()=>{const options:Setup={state:'removed'};const {calls}=await setup(options);await remittanceFileRequest(action('POST'),env,actor,id,fileId,true);options.readStatus=503;const beforeRetry=calls.length;await expect(remittanceFileRequest(action('POST',{reason:'A different reason'}),env,actor,id,fileId,true)).rejects.toThrow('remittance_command_conflict');expect(calls.slice(beforeRetry).map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_command_get','ar_remittance_file_status']);});
it('still requires storage proof when the restore command outcome is unknown',async()=>{const {calls}=await setup({state:'removed',readStatus:503});await expect(remittanceFileRequest(action('POST'),env,actor,id,fileId,true)).rejects.toThrow('remittance_storage_unavailable');expect(calls.map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_command_get','ar_remittance_file_get',fileId]);});
