import {afterEach,expect,it,vi} from 'vitest';
import {runRemittanceDiagnostic} from '../worker/remittance/diagnostic';
import {syntheticPdf} from '../worker/drive/archive';
import {hash} from '../worker/email/crypto';
const actor='00000000-0000-4000-8000-000000000001',command='00000000-0000-4000-8000-000000000004';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const key=`remittance-diagnostics/${actor}/${command}`,bytes=syntheticPdf();
type Options={database?:unknown;badKey?:string;badReceipt?:boolean;verified?:boolean;lostUpload?:boolean;wrongBytes?:boolean;writeStatus?:number;finish?:unknown};
async function setup(options:Options={}){
 const sha256=await hash(bytes),calls:{url:string;method:string;body:Record<string,unknown>|null}[]=[];
 vi.stubGlobal('fetch',async(input:RequestInfo|URL,init:RequestInit={})=>{const url=String(input),method=init.method??'GET',body=url.includes('/rpc/')?JSON.parse(String(init.body)):null;calls.push({url,method,body});
  expect(new URL(url).origin).toBe(env.SUPABASE_URL);expect(init.redirect).toBe('manual');
  if(url.endsWith('/ar_remittance_diagnostic_check'))return Response.json(options.database??{passed:true,rolledBack:true,checks:12});
  if(url.endsWith('/ar_remittance_diagnostic_begin')){expect(body).toEqual({p_actor:actor,p_command:command,p_file:{name:'Remittance-connection-test.pdf',mime:'application/pdf',byteCount:bytes.length,sha256}});return Response.json({storageKey:options.badKey??key,verified:options.verified??false,byteCount:bytes.length,sha256:options.badReceipt?'f'.repeat(64):sha256});}
  if(url.endsWith('/ar_remittance_diagnostic_finish'))return Response.json(options.finish??{passed:true,byteCount:bytes.length,sha256,retained:true});
  if(url.includes('/object/authenticated/'))return new Response(new Uint8Array(options.wrongBytes?new Uint8Array(bytes.length).fill(65):bytes).buffer);
  if(url.includes('/storage/')&&method==='POST'){expect(new Headers(init.headers).get('x-upsert')).toBe('false');expect(new Uint8Array(init.body as ArrayBuffer)).toEqual(bytes);if(options.lostUpload){options.lostUpload=false;throw Error('uncertain');}return new Response(null,{status:options.writeStatus??200});}
  throw Error('unexpected synthetic request');
 });return {calls,sha256};
}
afterEach(()=>vi.unstubAllGlobals());
it('runs rolled-back database proof and retains only an isolated private synthetic receipt',async()=>{const {calls,sha256}=await setup();expect(await runRemittanceDiagnostic(env,actor,command)).toEqual({database:{passed:true,rolledBack:true,checks:12},storage:{passed:true,byteCount:bytes.length,sha256,retained:true},businessRecordsChanged:false});expect(calls.map(c=>c.url.split('/').at(-1))).toEqual(['ar_remittance_diagnostic_check','ar_remittance_diagnostic_begin',command,command,'ar_remittance_diagnostic_finish']);expect(calls.every(c=>!c.url.includes('/ar_remittance_save')&&!c.url.includes('google')&&c.method!=='DELETE')).toBe(true);});
it('retries uncertain upload with the same isolated path and verifies duplicate bytes before finish',async()=>{const {calls}=await setup({lostUpload:true,writeStatus:400});await expect(runRemittanceDiagnostic(env,actor,command)).rejects.toThrow('remittance_upload_pending');expect(calls.some(c=>c.url.endsWith('diagnostic_finish'))).toBe(false);expect(await runRemittanceDiagnostic(env,actor,command)).toMatchObject({storage:{passed:true}});expect(calls.filter(c=>c.url.includes('/storage/')&&c.method==='POST').map(c=>c.url)).toEqual([`${env.SUPABASE_URL}/storage/v1/object/ar-working-files/${key}`,`${env.SUPABASE_URL}/storage/v1/object/ar-working-files/${key}`]);});
it('verifies an already-recorded receipt without rewriting bytes',async()=>{const {calls}=await setup({verified:true});expect(await runRemittanceDiagnostic(env,actor,command)).toMatchObject({storage:{passed:true}});expect(calls.filter(c=>c.url.includes('/storage/')&&c.method==='POST')).toHaveLength(0);expect(calls.some(c=>c.url.includes('/object/authenticated/'))).toBe(true);});
it('does not create a file if rollback proof is false or malformed',async()=>{for(const database of [{passed:false,rolledBack:true,checks:12},{passed:true,rolledBack:false,checks:12},{passed:true,rolledBack:true,checks:0},{passed:true,rolledBack:true,checks:'12'}]){const {calls}=await setup({database});await expect(runRemittanceDiagnostic(env,actor,command)).rejects.toThrow('remittance_diagnostic_failed');expect(calls).toHaveLength(1);}});
it('rejects cross-owner or non-diagnostic paths and conflicting diagnostic metadata before storage',async()=>{for(const options of [{badKey:`remittance-diagnostics/${command}/${command}`},{badKey:`remittances/${actor}/${command}`},{badKey:'https://evil.test/private'},{badReceipt:true}]){const {calls}=await setup(options);await expect(runRemittanceDiagnostic(env,actor,command)).rejects.toThrow('remittance_diagnostic_failed');expect(calls).toHaveLength(2);}});
it('never records successful diagnostic proof if checksum or final receipt is wrong',async()=>{const {calls}=await setup({wrongBytes:true});await expect(runRemittanceDiagnostic(env,actor,command)).rejects.toThrow('remittance_checksum_mismatch');expect(calls.some(c=>c.url.endsWith('diagnostic_finish'))).toBe(false);for(const finish of [{passed:true,byteCount:bytes.length,sha256:await hash(bytes),retained:false},{passed:true,byteCount:bytes.length+1,sha256:await hash(bytes),retained:true}]){await setup({finish});await expect(runRemittanceDiagnostic(env,actor,command)).rejects.toThrow('remittance_diagnostic_failed');}});
it('rejects invalid actor and command identities without provider access',async()=>{const {calls}=await setup();await expect(runRemittanceDiagnostic(env,'',command)).rejects.toThrow('remittance_forbidden');await expect(runRemittanceDiagnostic(env,actor,'https://evil.test')).rejects.toThrow('remittance_id_invalid');expect(calls).toHaveLength(0);});
