import {afterEach,describe,expect,it,vi} from 'vitest';
import {remittanceApi} from '../worker/remittance/api';
import type {RemittanceRecord} from '../src/remittance/model';
import {syntheticPdf} from '../worker/drive/archive';
import {hash} from '../worker/email/crypto';

const actor='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002',commandId='00000000-0000-4000-8000-000000000003',fileId='00000000-0000-4000-8000-000000000004';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const input={commandId,revision:0,confirmed:true,hotel:'KAT',accountId:'synthetic-account',receivedDate:'2026-01-01',reference:'Synthetic notice',sourceNote:'',notes:'',reportedAmount:'30000',lines:[{invoiceId:'synthetic-1',reportedAmount:null}],changeReason:''};
const record:RemittanceRecord={id,revision:1,state:'active',hotel:'KAT',accountId:'synthetic-account',accountName:'Synthetic account',accountType:'Travel Agent',accountNo:null,receivedDate:'2026-01-01',reference:'Synthetic notice',sourceNote:'',notes:'',reportedAmount:'30000.00',allocatedAmount:'0.00',unallocatedAmount:'30000.00',invoiceCount:1,fileCount:0,pendingFiles:0,lines:[{invoiceId:'synthetic-1',reportedAmount:null,invoiceNo:'INV-SYNTHETIC',folioNo:'',guest:'Synthetic guest',currentOpen:'50000.00',currentStatus:'open',sourceVerifiedAt:'2026-09-10T01:00:00Z'}],files:[],linkedOpen:'50000.00',knownLinkedOpen:'50000.00',unverifiedLines:0,resolution:'awaiting_opera',createdAt:'2026-09-10T01:00:00Z',updatedAt:'2026-09-10T01:00:00Z',voidReason:null};
const summary={documents:1,invoices:1,reportedAmount:'30000.00',knownReportedAmount:'30000.00',unspecifiedAmounts:0,linkedOpen:'50000.00',knownLinkedOpen:'50000.00',unverifiedInvoices:0};
function request(path='',method='GET',body?:unknown,headers?:HeadersInit){return new Request('https://app.test/api/remittances'+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...Object.fromEntries(new Headers(headers))},...(body!==undefined?{body:JSON.stringify(body)}:{})});}
afterEach(()=>{vi.unstubAllGlobals();vi.useRealTimers();});

describe('authenticated remittance API boundary',()=>{
 it('requires a verified actor on every read and mutation before service access',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);for(const [path,method,body] of [['','GET',undefined],['/options','GET',undefined],[`/${id}`,'PUT',input],[`/${id}/files/${fileId}`,'GET',undefined],['/diagnostic','POST',{commandId,confirmed:true}]] as const)expect((await remittanceApi(request(path,method,body),env,'')).status).toBe(401);expect((await remittanceApi(request(),env,'not-a-uuid')).status).toBe(401);expect(fetcher).not.toHaveBeenCalled();});
 it('rejects foreign, opaque and browser cross-site mutation origins',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);for(const headers of [new Headers({Origin:'https://evil.test'}),new Headers({Origin:'null'}),new Headers({'Sec-Fetch-Site':'cross-site'})])expect((await remittanceApi(request(`/${id}`,'PUT',input,headers),env,actor)).status).toBe(403);expect(fetcher).not.toHaveBeenCalled();});
 it('rejects malformed identities, extra path segments and unsupported methods',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);for(const path of ['/not-a-uuid',`/${id}/files/not-a-uuid`,'/commands/not-a-uuid','/%ZZ'])expect((await remittanceApi(request(path),env,actor)).status).toBe(400);expect((await remittanceApi(request(`/${id}/extra/path`),env,actor)).status).toBe(404);expect((await remittanceApi(request(`/${id}`,'DELETE'),env,actor)).status).toBe(405);expect((await remittanceApi(request('/options','PUT',input),env,actor)).status).toBe(405);expect(fetcher).not.toHaveBeenCalled();});
 it('does not accept an unconfirmed save, status, evidence removal or diagnostic',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);for(const [path,method,body] of [[`/${id}`,'PUT',{...input,confirmed:false}],[`/${id}/status`,'POST',{commandId,revision:1,status:'voided',reason:'Duplicate',confirmed:false}],[`/${id}/files/${fileId}`,'DELETE',{commandId,revision:1,reason:'Wrong file',confirmed:false}],['/diagnostic','POST',{commandId,confirmed:false}]] as const)expect((await remittanceApi(request(path,method,body),env,actor)).status).toBe(400);expect(fetcher).not.toHaveBeenCalled();});
 it('fails explicitly on the JSON request guard instead of truncating',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const r=await remittanceApi(request(`/${id}`,'PUT',{...input,notes:'x'.repeat(1024*1024)}),env,actor);expect(r.status).toBe(413);expect(await r.json()).toMatchObject({error:'remittance_request_too_large'});expect(fetcher).not.toHaveBeenCalled();});
});

describe('RPC contract and faithful results',()=>{
 it('saves normalized strings with the exact actor, identity and command',async()=>{let sent:Record<string,unknown>={};let target='';vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{target=url;sent=JSON.parse(String(init.body));expect(init.redirect).toBe('manual');return Response.json(record);});const r=await remittanceApi(request(`/${id}`,'PUT',input,{Origin:'https://app.test'}),env,actor);expect(r.status).toBe(200);expect(target).toBe('https://synthetic.supabase.co/rest/v1/rpc/ar_remittance_save');expect(sent).toEqual({p_actor:actor,p_id:id,p_input:{...input,reportedAmount:'30000.00'}});expect(await r.json()).toEqual(record);expect(r.headers.get('Cache-Control')).toBe('no-store');});
 it('does not reinterpret an exact command retry after later edits advanced the record',async()=>{vi.stubGlobal('fetch',async()=>Response.json(record));const r=await remittanceApi(request(`/${id}`,'PUT',{...input,revision:4,changeReason:'Correction'}),env,actor);expect(r.status).toBe(200);expect((await r.json() as RemittanceRecord).revision).toBe(1);});
 it('sends consistent scoped pagination and filter totals without deriving them from current page rows',async()=>{let sent:Record<string,unknown>={};vi.stubGlobal('fetch',async(_url:string,init:RequestInit)=>{sent=JSON.parse(String(init.body));return Response.json({rows:[record],total:30001,summary:{...summary,documents:30001}});});const r=await remittanceApi(request('?view=activity&hotel=KAT&accountId=synthetic-account&type=Travel%20Agent&search=SYN&from=2026-09-01&to=2026-09-10&page=300&limit=100'),env,actor);expect(r.status).toBe(200);expect(sent).toEqual({p_actor:actor,p_filters:{view:'activity',hotel:'KAT',accountId:'synthetic-account',type:'Travel Agent',search:'SYN',from:'2026-09-01',to:'2026-09-10',includeVoided:false,offset:30000,limit:100}});expect(await r.json()).toMatchObject({total:30001,summary:{documents:30001}});});
 it('returns all account options with configured evidence limits',async()=>{const accounts=Array.from({length:700},(_,i)=>({hotel:'KAT',accountId:`synthetic-${i}`,name:`Synthetic account ${i}`,type:'Agent',accountNo:null,verified:true}));vi.stubGlobal('fetch',async()=>Response.json({accounts}));const r=await remittanceApi(request('/options'),{...env,REMITTANCE_MAX_FILE_BYTES:'5242880',REMITTANCE_MAX_FILES:'80',REMITTANCE_MAX_TOTAL_FILE_BYTES:'104857600'},actor);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({accounts,config:{maxFileBytes:5242880,maxFiles:80,maxTotalFileBytes:104857600}});});
 it('preserves historical account type choices without duplicating account identities',async()=>{const accounts=[{hotel:'KAT',accountId:'synthetic-1',name:'Synthetic account',type:'Current type',accountNo:null,verified:true}];vi.stubGlobal('fetch',async()=>Response.json({accounts,accountTypes:['Current type','Historical type']}));const r=await remittanceApi(request('/options'),env,actor);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({accounts,accountTypes:['Current type','Historical type']});});
 it('forwards exact invoice identity scope and does not substitute missing balances',async()=>{let sent:Record<string,unknown>={};const rows=[{invoiceId:'synthetic-1',invoiceNo:'SYN',folioNo:'',guest:'Synthetic',transactionDate:'2026-09-01',currentOpen:null,verified:false,eligible:false,reason:'source_unverified'}];vi.stubGlobal('fetch',async(_url:string,init:RequestInit)=>{sent=JSON.parse(String(init.body));return Response.json({rows,total:1001});});const r=await remittanceApi(request('/invoices?hotel=TSK&accountId=synthetic%3Aexact&search=INV&page=5&limit=100'),env,actor);expect(r.status).toBe(200);expect(sent).toEqual({p_actor:actor,p_hotel:'TSK',p_account:'synthetic:exact',p_search:'INV',p_offset:500,p_limit:100});expect(await r.json()).toEqual({rows,total:1001});});
 it('maps status and history to their agreed atomic RPCs',async()=>{const calls:{url:string;args:unknown}[]=[];vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{calls.push({url,args:JSON.parse(String(init.body))});return Response.json(url.endsWith('ar_remittance_history')?{rows:[],total:25}:record);});expect((await remittanceApi(request(`/${id}/status`,'POST',{commandId,revision:1,status:'voided',reason:'Duplicate record',confirmed:true}),env,actor)).status).toBe(200);expect((await remittanceApi(request(`/${id}/history?page=1&limit=20`),env,actor)).status).toBe(200);expect(calls).toEqual([{url:'https://synthetic.supabase.co/rest/v1/rpc/ar_remittance_set_status',args:{p_actor:actor,p_id:id,p_command:commandId,p_revision:1,p_status:'voided',p_reason:'Duplicate record'}},{url:'https://synthetic.supabase.co/rest/v1/rpc/ar_remittance_history',args:{p_actor:actor,p_id:id,p_offset:20,p_limit:20}}]);});
 it('treats absent command receipts as unknown outcomes and missing records as missing',async()=>{vi.stubGlobal('fetch',async()=>Response.json(null));const command=await remittanceApi(request(`/commands/${commandId}`),env,actor);expect(command.status).toBe(200);expect(await command.json()).toEqual({complete:false});expect((await remittanceApi(request(`/${id}`),env,actor)).status).toBe(404);});
 it.each([['remittance_forbidden',403],['remittance_revision_conflict',409],['remittance_scope_immutable',409],['remittance_pending_upload',409],['remittance_command_conflict',409],['remittance_allocation_overflow',400],['remittance_source_unverified',409],['remittance_missing',404]])('exposes a safe actionable error %s',async(error,status)=>{vi.stubGlobal('fetch',async()=>Response.json({error,detail:'synthetic-private-detail'}));const r=await remittanceApi(request(`/${id}`,'PUT',input),env,actor);expect(r.status).toBe(status);const result=await r.json() as {error:string;message:string};expect(result.error).toBe(error);expect(result.message.length).toBeGreaterThan(10);expect(JSON.stringify(result)).not.toContain('synthetic-private-detail');});
 it('never turns transport errors, redirect or malformed totals into empty successful results',async()=>{for(const response of [new Response('private upstream failure',{status:500}),new Response(null,{status:302,headers:{Location:'https://evil.test'}}),Response.json(null),Response.json({rows:[],total:0}),Response.json({rows:[],total:0,summary:{...summary,reportedAmount:30000}})]){vi.stubGlobal('fetch',async()=>response);const r=await remittanceApi(request(),env,actor);expect(r.status).toBe(503);expect(await r.text()).not.toContain('private upstream failure');}});
 it('does not expose unknown SQL errors or echoed provider data',async()=>{vi.stubGlobal('fetch',async()=>Response.json({error:'syntax error containing synthetic account',details:'private'}));const r=await remittanceApi(request(),env,actor);expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:'remittance_unavailable'});});
 it('treats malformed completed command receipts as unavailable, not a client input error',async()=>{for(const value of [{complete:true,recordId:'invalid',revision:1},{complete:true,recordId:id,revision:0},{complete:true,recordId:id}]){vi.stubGlobal('fetch',async()=>Response.json(value));const r=await remittanceApi(request(`/commands/${commandId}`),env,actor);expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:'remittance_unavailable'});}});
});

describe('private evidence and diagnostic route seams',()=>{
 it('routes download to owner metadata and checksum proof, returning private bytes',async()=>{const bytes=syntheticPdf();const file={id:fileId,name:'synthetic.pdf',mime:'application/pdf',byteCount:bytes.length,sha256:await hash(bytes),state:'ready',error:null,createdAt:'2026-09-10T01:00:00Z',storageKey:`remittances/${id}/${fileId}`};const calls:string[]=[];vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{calls.push(url);if(url.endsWith('ar_remittance_file_get')){expect(JSON.parse(String(init.body))).toEqual({p_actor:actor,p_id:id,p_file_id:fileId});return Response.json(file);}if(url.endsWith(`object/authenticated/ar-working-files/${file.storageKey}`))return new Response(new Uint8Array(bytes).buffer);throw Error('Unexpected synthetic endpoint');});const r=await remittanceApi(request(`/${id}/files/${fileId}`),env,actor);expect(r.status).toBe(200);expect(r.headers.get('Content-Type')).toBe('application/pdf');expect(r.headers.get('Cache-Control')).toBe('no-store');expect(await hash(new Uint8Array(await r.arrayBuffer()))).toBe(file.sha256);expect(calls).toHaveLength(2);});
 it('routes recoverable removal and restore with exact command and revision, retaining storage bytes',async()=>{
  const bytes=syntheticPdf(),restoreCommandId='00000000-0000-4000-8000-000000000005';
  const file={id:fileId,name:'synthetic.pdf',mime:'application/pdf',byteCount:bytes.length,sha256:await hash(bytes),state:'removed',error:null,createdAt:'2026-09-10T01:00:00Z',storageKey:`remittances/${id}/${fileId}`};
  const commands:Record<string,unknown>[]=[];const methods:string[]=[];const paths:string[]=[];
  vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{
   methods.push(init.method??'GET');paths.push(url.split('/').at(-1)!);
   if(url.endsWith('ar_remittance_command_get')){expect(JSON.parse(String(init.body))).toEqual({p_actor:actor,p_command:restoreCommandId});return Response.json({complete:false});}
   if(url.endsWith('ar_remittance_file_get'))return Response.json(file);
   if(url.includes('/object/authenticated/'))return new Response(new Uint8Array(bytes).buffer);
   if(url.endsWith('ar_remittance_file_status')){const command=JSON.parse(String(init.body));commands.push(command);return Response.json({...record,revision:command.p_revision+1});}
   throw Error('Unexpected synthetic endpoint');
  });
  expect((await remittanceApi(request(`/${id}/files/${fileId}`,'DELETE',{commandId,revision:1,reason:'Correct evidence',confirmed:true}),env,actor)).status).toBe(200);
  expect((await remittanceApi(request(`/${id}/files/${fileId}/restore`,'POST',{commandId:restoreCommandId,revision:2,reason:'Correct evidence',confirmed:true}),env,actor)).status).toBe(200);
  expect(commands.map(command=>({actor:command.p_actor,id:command.p_id,fileId:command.p_file_id,commandId:command.p_command,revision:command.p_revision,restore:command.p_restore}))).toEqual([{actor,id,fileId,commandId,revision:1,restore:false},{actor,id,fileId,commandId:restoreCommandId,revision:2,restore:true}]);
  expect(paths).toEqual(['ar_remittance_file_status','ar_remittance_command_get','ar_remittance_file_get',fileId,'ar_remittance_file_status']);expect(methods).not.toContain('DELETE');
 });
 it('dispatches a confirmed diagnostic to the isolated routines and stops if rollback proof fails',async()=>{const calls:string[]=[];vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{calls.push(url);expect(JSON.parse(String(init.body))).toEqual({p_actor:actor});return Response.json({passed:true,rolledBack:false,checks:4});});const r=await remittanceApi(request('/diagnostic','POST',{commandId,confirmed:true}),env,actor);expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:'remittance_diagnostic_failed'});expect(calls).toEqual(['https://synthetic.supabase.co/rest/v1/rpc/ar_remittance_diagnostic_check']);});
});
