import {describe,expect,it} from 'vitest';
import {amountToSatang,parseAmount,parseRemittanceInput,parseRemittanceStatus,parseRemittanceFileAction,parseRemittanceDiagnostic,parseRemittanceFilters,parseRemittanceInvoiceQuery,parseRemittancePage,parseRemittanceId,readRemittanceJson,satangToAmount} from '../worker/remittance/validation';
import {formatAmount,parseAmountInput} from '../src/remittance/money';

const commandId='00000000-0000-4000-8000-000000000001';
const now=new Date('2026-09-09T17:00:00Z');
const input=()=>({commandId,revision:0,confirmed:true,hotel:'KAT',accountId:'synthetic-account',receivedDate:'2026-09-10',reference:' Synthetic notice ',sourceNote:'',notes:'',reportedAmount:'0.30',lines:[{invoiceId:'synthetic-1',reportedAmount:'0.1'},{invoiceId:'synthetic-2',reportedAmount:'0.20'}],changeReason:''});

describe('exact remittance amounts',()=>{
 it.each([[null,null],['0','0.00'],['1.2','1.20'],['9007199254740993.99','9007199254740993.99']])('preserves unknown or exact satang %s',(value,want)=>expect(parseAmount(value)).toBe(want));
 it.each([undefined,0,0.3,'',' ',' 1','1 ','1.00\n','1.00\r','1.00\r\n','-1','-0.00','+1','1e2','1,000','00.10','.5','1.','1.001','NaN','Infinity'])('rejects ambiguous or lossy amount %s',value=>expect(()=>parseAmount(value)).toThrow('remittance_amount_invalid'));
 it('performs arithmetic beyond floating point integer precision',()=>{expect(amountToSatang('9007199254740993.99')).toBe(900719925474099399n);expect(satangToAmount(900719925474099399n)).toBe('9007199254740993.99');});
 it('formats signed OPERA balances and large aggregate totals without losing satang',()=>{expect(formatAmount('-9007199254740993.99')).toBe('-฿9,007,199,254,740,993.99');expect(formatAmount('9999999999999999999999.03')).toBe('฿9,999,999,999,999,999,999,999.03');expect(formatAmount(null)).toBe('Not specified');expect(formatAmount('0.00')).toBe('฿0.00');});
 it('keeps blank form input unknown while rejecting amounts beyond the database precision',()=>{expect(parseAmountInput(' ')).toBeNull();expect(parseAmountInput(' 0.10 ')).toBe('0.10');expect(parseAmount('9999999999999999.99')).toBe('9999999999999999.99');expect(()=>parseAmount('10000000000000000.00')).toThrow('remittance_amount_invalid');});
 it.each(['-1.00\n','123.40\r','10.00\r\n'])('rejects noncanonical source amounts during formatting %j',value=>{expect(()=>amountToSatang(value)).toThrow('remittance_amount_invalid');expect(()=>formatAmount(value)).toThrow('remittance_amount_invalid');});
 it('accepts exact allocation equality and normalizes independently supplied strings',()=>expect(parseRemittanceInput(input(),now)).toMatchObject({reference:'Synthetic notice',reportedAmount:'0.30',lines:[{invoiceId:'synthetic-1',reportedAmount:'0.10'},{invoiceId:'synthetic-2',reportedAmount:'0.20'}]}));
 it('rejects even one satang beyond a known reported total',()=>expect(()=>parseRemittanceInput({...input(),reportedAmount:'0.29'},now)).toThrow('remittance_allocation_exceeded'));
 it('keeps unknown total and allocations unknown instead of inferring payment',()=>expect(parseRemittanceInput({...input(),reportedAmount:null,lines:[{invoiceId:'synthetic-1',reportedAmount:null}]},now)).toMatchObject({reportedAmount:null,lines:[{invoiceId:'synthetic-1',reportedAmount:null}]}));
});

describe('remittance identity and review validation',()=>{
 it.each(['2026-02-29','2026-04-31','2026-13-01','2026-9-10','2026-09-11','0000-01-01'])('rejects impossible, noncalendar or future received date %s',receivedDate=>expect(()=>parseRemittanceInput({...input(),receivedDate},now)).toThrow('remittance_date_invalid'));
 it('uses the Thai day at UTC rollover and accepts a real leap day',()=>{expect(parseRemittanceInput(input(),now).receivedDate).toBe('2026-09-10');expect(()=>parseRemittanceInput(input(),new Date('2026-09-09T16:59:59Z'))).toThrow('remittance_date_invalid');expect(parseRemittanceInput({...input(),receivedDate:'2024-02-29'},now).receivedDate).toBe('2024-02-29');});
 it.each([{hotel:'kat'},{hotel:'All'},{accountId:''},{accountId:' synthetic-account'},{accountId:'account\u0000x'}])('rejects altered account scope %j',patch=>expect(()=>parseRemittanceInput({...input(),...patch},now)).toThrow('remittance_scope_invalid'));
 it('rejects duplicate exact invoice identities',()=>expect(()=>parseRemittanceInput({...input(),lines:[{invoiceId:'same',reportedAmount:null},{invoiceId:'same',reportedAmount:null}]},now)).toThrow('remittance_duplicate_invoice'));
 it('keeps invoice identities distinct by case and does not fuzzy match',()=>expect(parseRemittanceInput({...input(),lines:[{invoiceId:'Exact',reportedAmount:null},{invoiceId:'exact',reportedAmount:null}]},now).lines).toHaveLength(2));
 it.each([{lines:[]},{lines:[{invoiceId:'',reportedAmount:null}]},{lines:[{invoiceId:' padded',reportedAmount:null}]},{lines:[{invoiceId:'x'.repeat(201),reportedAmount:null}]}])('requires exact invoice identities',({lines})=>expect(()=>parseRemittanceInput({...input(),lines},now)).toThrow('remittance_lines_invalid'));
 it('fails explicitly beyond the operational line guard without truncating',()=>expect(()=>parseRemittanceInput({...input(),lines:Array.from({length:5001},(_,i)=>({invoiceId:`synthetic-${i}`,reportedAmount:null}))},now)).toThrow('remittance_too_many_lines'));
 it.each([{revision:-1},{revision:1.2},{revision:'0'},{revision:2147483648},{commandId:'bad'},{confirmed:false},{confirmed:'true'},{reference:' '},{reference:'notice\u0000'}])('rejects incomplete write review %j',patch=>expect(()=>parseRemittanceInput({...input(),...patch},now)).toThrow());
 it('requires an explicit reason for a correction',()=>{expect(()=>parseRemittanceInput({...input(),revision:1},now)).toThrow('remittance_reason_required');expect(parseRemittanceInput({...input(),revision:1,changeReason:' Corrected reference '},now).changeReason).toBe('Corrected reference');});
 it('does not accept client balances or alternative scopes inside lines',()=>expect(()=>parseRemittanceInput({...input(),lines:[{invoiceId:'synthetic-1',reportedAmount:null,hotel:'TSK',currentOpen:'0.00'}]},now)).toThrow('remittance_lines_invalid'));
 it('rejects unrecognized mutation fields',()=>expect(()=>parseRemittanceInput({...input(),state:'voided'},now)).toThrow('remittance_invalid'));
 it('requires status commands to be confirmed, scoped to a saved revision and reasoned',()=>{expect(parseRemittanceStatus({commandId,revision:1,status:'voided',reason:' Duplicate record ',confirmed:true})).toEqual({commandId,revision:1,status:'voided',reason:'Duplicate record',confirmed:true});for(const patch of [{revision:0},{status:'deleted'},{reason:''},{commandId:'bad'},{confirmed:false}])expect(()=>parseRemittanceStatus({commandId,revision:1,status:'active',reason:'Restored evidence',confirmed:true,...patch})).toThrow();});
 it('requires review metadata for evidence changes and diagnostics',()=>{expect(parseRemittanceFileAction({commandId,revision:1,reason:'Wrong file',confirmed:true}).revision).toBe(1);expect(()=>parseRemittanceFileAction({commandId,revision:1,reason:'',confirmed:true})).toThrow('remittance_reason_required');expect(parseRemittanceDiagnostic({commandId,confirmed:true})).toEqual({commandId,confirmed:true});expect(()=>parseRemittanceDiagnostic({commandId,confirmed:false})).toThrow('remittance_confirmation_required');});
 it.each(['\n','\r','\r\n'])('rejects trailing line breaks on IDs and calendar dates %j',suffix=>{expect(()=>parseRemittanceId(commandId+suffix)).toThrow('remittance_id_invalid');expect(()=>parseRemittanceInput({...input(),receivedDate:'2026-09-10'+suffix},now)).toThrow('remittance_date_invalid');});
});

describe('query and request boundaries',()=>{
 it('applies dates only to activity and keeps filters and page offsets exact',()=>{expect(parseRemittanceFilters(new URLSearchParams('view=activity&hotel=KAT&accountId=synthetic&type=Travel%20Agent&from=2026-09-01&to=2026-09-10&page=3&limit=50'))).toEqual({view:'activity',hotel:'KAT',accountId:'synthetic',type:'Travel Agent',search:'',from:'2026-09-01',to:'2026-09-10',includeVoided:false,offset:150,limit:50});expect(parseRemittanceFilters(new URLSearchParams('view=pending&from=2026-09-01&to=2026-09-10')).from).toBeNull();});
 it.each(['view=activity','view=activity&from=2026-09-10&to=2026-09-01','view=unknown','hotel=All','accountId=one','includeVoided=yes','page=-1','limit=0','limit=10001','page=999999999999999999','page=1&page=2','page=1%0A','limit=50%0D','extra=1'])('rejects invalid or ambiguous list query %s',query=>expect(()=>parseRemittanceFilters(new URLSearchParams(query))).toThrow('remittance_query_invalid'));
 it('requires explicit hotel/account for invoice options',()=>{expect(parseRemittanceInvoiceQuery(new URLSearchParams('hotel=TSK&accountId=synthetic&page=2&limit=100'))).toEqual({hotel:'TSK',accountId:'synthetic',search:'',offset:200,limit:100});expect(()=>parseRemittanceInvoiceQuery(new URLSearchParams('accountId=synthetic'))).toThrow('remittance_query_invalid');});
 it('retains pagination beyond an initial result page instead of a silent portfolio cap',()=>expect(parseRemittancePage(new URLSearchParams('page=300&limit=100'))).toEqual({offset:30000,limit:100}));
 it('requires JSON and rejects malformed content without reflecting it',async()=>{for(const [body,type] of [['{broken','application/json'],['{}','text/plain'],['[]','application/json']])await expect(readRemittanceJson(new Request('https://app.test',{method:'PUT',headers:{'Content-Type':type},body}))).rejects.toThrow('remittance_invalid');});
 it('rejects a request larger than 1 MiB even without a content length header',async()=>{const request=new Request('https://app.test',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:'x'.repeat(1024*1024)})});await expect(readRemittanceJson(request)).rejects.toThrow('remittance_request_too_large');});
});
