import {afterEach,expect,it,vi} from 'vitest';
import {calendarMonthAfterThai,retentionDecision,retentionConfig,enrollRetention,runRetentionItem,type RetentionSnapshot,type RetentionItem,type RetentionProvider,type RetentionTarget,type RetentionInspection} from '../worker/operations/retention';
const actor='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002',objectId='00000000-0000-4000-8000-000000000003',claim='00000000-0000-4000-8000-000000000004';
const now=Date.parse('2026-09-10T14:00:00Z'),env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'synthetic',RETENTION_ENABLED:'true'};
const snapshot=():RetentionSnapshot=>({owned:true,knownReferences:true,minimumEligibleAt:'2026-07-01T00:00:00Z',eligibleSince:'2026-08-10T14:00:00Z',pendingDocuments:false,pendingMail:false,links:[{hotel:'KAT',accountId:'synthetic',invoiceId:'A',open:'0.00',verified:true,collectionRole:'standalone',verifiedAt:'2026-09-10T13:45:00Z',zeroSince:'2026-07-01T00:00:00Z',held:false,disputed:false,needsReview:false}]});
const item=(state:RetentionItem['state']='claimed'):RetentionItem=>({id,revision:1,state,reason:null,eligibleSince:'2026-08-10T14:00:00Z',dueAt:'2026-09-10T14:00:00Z',claimId:claim,target:{store:'supabase',objectId,bucket:'ar-working-files',key:`remittances/${id}/${objectId}`,updatedAt:'2026-07-01T00:00:00Z',etag:'synthetic',byteCount:622,sha256:'a'.repeat(64),owner:actor}});
afterEach(()=>vi.unstubAllGlobals());

it('uses one Thai calendar month, including month ends and leap years, not 30 days',()=>{expect(calendarMonthAfterThai('2026-01-31T16:30:00Z')).toBe('2026-02-28T16:30:00.000Z');expect(calendarMonthAfterThai('2028-01-31T16:30:00Z')).toBe('2028-02-29T16:30:00.000Z');expect(calendarMonthAfterThai('2026-08-31T18:00:00Z')).toBe('2026-09-30T18:00:00.000Z');});
it('starts eligibility at the actual first observation of completion without inventing an older creation/completion time',()=>{const s=snapshot();s.eligibleSince=null;const result=retentionDecision(s,now);expect(result).toMatchObject({complete:true,due:false,eligibleSince:'2026-09-10T14:00:00.000Z',dueAt:'2026-10-10T14:00:00.000Z'});expect(retentionDecision(snapshot(),now)).toMatchObject({complete:true,due:true});});
it('requires all shared invoice references to be verified zero and blocks unknown or missing identities',()=>{for(const changes of [{owned:false},{knownReferences:false},{links:[]}])expect(retentionDecision({...snapshot(),...changes},now)).toMatchObject({complete:false,eligibleSince:null});const s=snapshot();s.links.push({...s.links[0],invoiceId:'B',open:'1.00'});expect(retentionDecision(s,now)).toMatchObject({complete:false,reason:'retention_source_open'});s.links[1].open=null;expect(retentionDecision(s,now)).toMatchObject({complete:false,reason:'retention_source_unknown'});});
it('blocks future, child/unverified, held, disputed and review-needed sources without treating them as zero',()=>{for(const change of [{verified:false},{collectionRole:'child'},{verifiedAt:'2026-09-10T14:01:00Z'},{zeroSince:null},{held:true},{disputed:true},{needsReview:true}]){const s=snapshot();s.links[0]={...s.links[0],...change};expect(retentionDecision(s,now)).toMatchObject({complete:false,eligibleSince:null});}});
it('defers stale-only zero snapshots without restarting the month, but still resets for other incomplete links',()=>{const s=snapshot();s.links[0].verifiedAt='2026-09-10T13:29:59Z';expect(retentionDecision(s,now)).toMatchObject({complete:false,due:false,reason:'retention_source_stale',eligibleSince:'2026-08-10T14:00:00.000Z'});s.links.push({...s.links[0],invoiceId:'B',open:null});expect(retentionDecision(s,now)).toMatchObject({complete:false,eligibleSince:null,reason:'retention_source_unknown'});});
it('resets the month clock for pending mail/documents or a newly changed completion floor',()=>{for(const changes of [{pendingDocuments:true},{pendingMail:true}])expect(retentionDecision({...snapshot(),...changes},now)).toMatchObject({complete:false,eligibleSince:null});const s=snapshot();s.minimumEligibleAt='2026-09-01T00:00:00Z';expect(retentionDecision(s,now)).toMatchObject({complete:true,due:false,eligibleSince:'2026-09-10T14:00:00.000Z'});});
it('uses the configured 30-minute source guard and rejects invalid resource settings',()=>{expect(retentionConfig({})).toEqual({sourceMaxAgeSeconds:1800,maxConcurrent:2,leaseSeconds:300});for(const config of [{RETENTION_SOURCE_MAX_AGE_SECONDS:'90000'},{RETENTION_MAX_CONCURRENT:'0'},{RETENTION_LEASE_SECONDS:'1'}])expect(()=>retentionConfig(config)).toThrow('retention_not_configured');});
it('enrolls only a known internal object ID, never a caller-supplied URL or Storage key',async()=>{const fetcher=vi.fn(async(_url:string,init:RequestInit)=>{expect(JSON.parse(String(init.body))).toEqual({p_actor:actor,p_store:'supabase',p_object_id:objectId,p_source_max_age:1800});return Response.json({...item('waiting'),claimId:null});});vi.stubGlobal('fetch',fetcher);expect(await enrollRetention(env,actor,'supabase',objectId)).toMatchObject({state:'waiting'});await expect(enrollRetention(env,actor,'supabase','https://evil.test/file')).rejects.toThrow('retention_invalid');expect(fetcher).toHaveBeenCalledTimes(1);});

type Setup={mode?:'delete'|'reconcile'|'wait'|'busy'|'complete';arm?:boolean;claimTarget?:unknown};
function setup(options:Setup={}){const calls:string[]=[];vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{expect(init.redirect).toBe('manual');expect(new URL(url).origin).toBe(env.SUPABASE_URL);const body=JSON.parse(String(init.body));const name=url.split('/').at(-1)!;calls.push(name);if(name==='ar_retention_claim')return Response.json({mode:options.mode??'delete',item:{...item(options.mode==='complete'?'deleted':'claimed'),target:options.claimTarget??item().target}});if(name==='ar_retention_arm')return Response.json({proceed:options.arm??true,item:item()});if(name==='ar_retention_observe')return Response.json(item(body.p_outcome==='absent'?'deleted':body.p_outcome==='identity_mismatch'?'blocked':body.p_outcome==='present'?'waiting':'uncertain'));throw Error('unexpected synthetic RPC');});return calls;}
function providers(states:('present'|'absent'|'unknown'|'mismatch')[],throws=false){let reads=0;const removed=vi.fn(async(_target:RetentionTarget)=>{if(throws)throw Error('private provider failure');});const provider:RetentionProvider={inspect:vi.fn(async(_target:RetentionTarget):Promise<RetentionInspection>=>{const state=states[Math.min(reads++,states.length-1)];return state==='present'||state==='mismatch'?{state:'present',identityVerified:state==='present'}:{state};}),remove:removed};return {provider,removed,all:{supabase:provider,drive:provider}};}
it('does nothing when disabled or unauthorized, even when provider adapters exist',async()=>{const p=providers(['present']);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(runRetentionItem({...env,RETENTION_ENABLED:'false'},actor,id,claim,p.all)).rejects.toThrow('retention_not_enabled');await expect(runRetentionItem(env,'',id,claim,p.all)).rejects.toThrow('retention_forbidden');expect(fetcher).not.toHaveBeenCalled();expect(p.removed).not.toHaveBeenCalled();});
it.each(['wait','busy','complete'] as const)('never calls providers for a %s claim',async mode=>{setup({mode});const p=providers(['present']);await runRetentionItem(env,actor,id,claim,p.all);expect(p.provider.inspect).not.toHaveBeenCalled();expect(p.removed).not.toHaveBeenCalled();});
it('inspects exact ownership, rechecks/arms immediately before deletion and records a tombstone only after absence',async()=>{const calls=setup(),p=providers(['present','absent']);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'deleted'});expect(calls).toEqual(['ar_retention_claim','ar_retention_arm','ar_retention_observe']);expect(p.removed).toHaveBeenCalledTimes(1);expect(p.removed.mock.calls[0][0]).toEqual(item().target);});
it('blocks changed provider identity and a reopened/pending source observed at final arm',async()=>{setup();let p=providers(['mismatch']);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'blocked'});expect(p.removed).not.toHaveBeenCalled();setup({arm:false});p=providers(['present']);await runRetentionItem(env,actor,id,claim,p.all);expect(p.removed).not.toHaveBeenCalled();});
it('preserves uncertain deletion until readback rather than assuming a timeout or accepted response means gone',async()=>{setup();let p=providers(['present','unknown'],true);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'uncertain'});expect(p.removed).toHaveBeenCalledTimes(1);setup();p=providers(['present','present']);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'uncertain'});});
it('reconciles an uncertain claim read-only and never repeats DELETE in that same pass',async()=>{setup({mode:'reconcile'});let p=providers(['absent']);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'deleted'});expect(p.removed).not.toHaveBeenCalled();setup({mode:'reconcile'});p=providers(['present']);expect(await runRetentionItem(env,actor,id,claim,p.all)).toMatchObject({state:'waiting'});expect(p.removed).not.toHaveBeenCalled();});
it('keeps two stores independent: a deleted Storage object never implies a Drive file was deleted',async()=>{setup();const storage=providers(['present','absent']),drive=providers(['unknown']);expect(await runRetentionItem(env,actor,id,claim,{supabase:storage.provider,drive:drive.provider})).toMatchObject({state:'deleted'});expect(drive.provider.inspect).not.toHaveBeenCalled();expect(drive.removed).not.toHaveBeenCalled();});
it('rejects wrong owner/unsafe target identity before provider access',async()=>{for(const target of [{...item().target,owner:objectId},{...item().target,key:'https://evil.test/file'},{...item().target,bucket:'public'}]){setup({claimTarget:target});const p=providers(['present']);await expect(runRetentionItem(env,actor,id,claim,p.all)).rejects.toThrow('retention_invalid_response');expect(p.provider.inspect).not.toHaveBeenCalled();}});
it('contains upstream errors and rejects redirected credentialed RPCs without follow-up',async()=>{const p=providers(['present']);vi.stubGlobal('fetch',async()=>new Response(null,{status:302,headers:{Location:'https://evil.test'}}));await expect(runRetentionItem(env,actor,id,claim,p.all)).rejects.toThrow('retention_unavailable');expect(p.removed).not.toHaveBeenCalled();});
