import {afterEach,expect,it,vi} from 'vitest';
import {accountWorkspaceApi} from '../worker/accounts/workspace';
import {handleApi} from '../worker/index';
import {previewSavedDraftThread} from '../worker/email/threads';
vi.mock('../worker/email/oauth',()=>({gmailCanRead:async()=>true,gmailToken:async()=>'synthetic-provider-token'}));
const actor='00000000-0000-4000-8000-000000000001',draftId='00000000-0000-4000-8000-000000000002',jobId='00000000-0000-4000-8000-000000000003';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const recipients={to:['customer@example.test'],cc:[],bcc:[]};
const scope={hotel:'KAT' as const,accountId:'A',draftId};
const choice={threadId:'saved-thread',parentMessageId:'m0',rfcMessageId:'<parent0@example.test>',references:['<parent0@example.test>'],subject:'Saved subject',matchedRecipients:recipients.to,parentDate:'2026-09-10T00:00:00.000Z'};
const saved=()=>({id:draftId,owner:actor,document_job_id:jobId,document_revision:1,revision:3,hotel:'KAT',account_id:'A',account_name:'Synthetic account',invoice_ids:['A1'],purpose:'billing',recipients,subject:'Saved subject',body:'Original saved message',package_changed:true,thread:choice,exports:[],attachments:[],providerSecret:'Do not expose this'});
function thread(count=1,historyId='100'){return {id:'saved-thread',historyId,messages:Array.from({length:count},(_,i)=>({id:'m'+i,threadId:'saved-thread',labelIds:['INBOX'],internalDate:String(Date.parse('2026-09-10T00:00:00Z')+i*1000),snippet:'Saved conversation '+i,payload:{headers:[{name:'From',value:'customer@example.test'},{name:'To',value:'ar@katathani.com'},{name:'Subject',value:'Saved subject'},{name:'Message-ID',value:`<parent${i}@example.test>`}],body:{data:'PRIVATE BODY'}}}))};}
function request(suffix='',query=''){return new Request(`https://app.test/api/account-workspace/KAT/A/email/${draftId}${suffix}${query}`);}
afterEach(()=>vi.unstubAllGlobals());
it('reads the exact saved message after the current document becomes unreviewed without opening or creating a draft',async()=>{
 const calls:string[]=[];vi.stubGlobal('fetch',async(url:string,init:RequestInit)=>{calls.push(url);const body=JSON.parse(String(init.body));if(url.endsWith('ar_email_get')){expect(body).toEqual({p_actor:actor,p_id:draftId});return Response.json(saved());}if(url.endsWith('ar_mail_for_draft')){expect(body).toEqual({p_actor:actor,p_draft:draftId,p_revision:3});return Response.json({id:'00000000-0000-4000-8000-000000000004',owner:actor,draft_id:draftId,revision:3,state:'awaiting_evidence',mode:'send',sent_at:null});}if(url.endsWith('ar_gmail_attempt_get'))return Response.json(null);throw Error('Unexpected');});
 const r=await accountWorkspaceApi(request(),env,actor);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({id:draftId,documentJobId:jobId,documentRevision:1,draftRevision:3,packageChanged:true,subject:'Saved subject',body:'Original saved message',hasThread:true,delivery:{state:'awaiting_evidence',mode:'send',recorded:false}});expect(calls.every(url=>!url.includes('ar_email_open')&&!url.includes('googleapis'))).toBe(true);
});
it('requires actor, exact draft identity, Hotel and Account before any Gmail read',async()=>{
 for(const extra of [{owner:'other'},{id:jobId},{hotel:'TSK'},{account_id:'OTHER'}]){const calls:string[]=[];vi.stubGlobal('fetch',async(url:string)=>{calls.push(url);return Response.json({...saved(),...extra});});expect((await accountWorkspaceApi(request('/thread','?revision=3'),env,actor)).status).toBe(403);expect(calls).toHaveLength(1);}
 const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);expect((await accountWorkspaceApi(request(),env,'')).status).toBe(401);expect((await handleApi(request('/thread','?revision=3'),env)).status).toBe(401);expect(fetcher).not.toHaveBeenCalled();
});
it('does not accept mutations or an arbitrary thread selector on saved review routes',async()=>{const f=vi.fn();vi.stubGlobal('fetch',f);for(const method of ['POST','PUT','DELETE'])expect((await accountWorkspaceApi(new Request(request(),{method}),env,actor)).status).toBe(405);for(const query of ['?revision=3&threadId=other','?revision=3&offset=50','?revision=3&offset=0&offset=50'])expect((await accountWorkspaceApi(request('/thread',query),env,actor)).status).toBe(400);expect(f).not.toHaveBeenCalled();});
it('reads only the saved thread choice even if the document package changed',async()=>{const urls:URL[]=[];vi.stubGlobal('fetch',async(url:string)=>{if(url.endsWith('ar_email_get'))return Response.json(saved());urls.push(new URL(url));return Response.json(thread());});const preview=await previewSavedDraftThread(env,actor,scope,3);expect(preview.messages).toHaveLength(1);expect(preview.thread.threadId).toBe('saved-thread');expect(urls).toHaveLength(1);expect(urls[0].pathname).toBe('/gmail/v1/users/me/threads/saved-thread');expect(urls[0].searchParams.get('format')).toBe('metadata');expect(JSON.stringify(preview)).not.toContain('PRIVATE BODY');});
it('retains revision and Gmail history fences on next and previous pages',async()=>{let historyId='100';vi.stubGlobal('fetch',async(url:string)=>Response.json(url.endsWith('ar_email_get')?saved():thread(51,historyId)));const first=await previewSavedDraftThread(env,actor,scope,3);expect(first.nextMessageOffset).toBe(50);expect((await previewSavedDraftThread(env,actor,scope,3,50,first.historyId)).messages).toHaveLength(1);historyId='101';await expect(previewSavedDraftThread(env,actor,scope,3,0,'100')).rejects.toThrow('email_thread_changed');await expect(previewSavedDraftThread(env,actor,scope,2)).rejects.toThrow('email_revision_conflict');});
it('retains recipient and parent relation checks on a saved conversation',async()=>{for(const unrelated of [true,false]){vi.stubGlobal('fetch',async(url:string)=>{if(url.endsWith('ar_email_get'))return Response.json(saved());const value=thread();if(unrelated)value.messages[0].payload.headers[0].value='other@example.test';else value.messages[0].payload.headers[3].value='<changed@example.test>';return Response.json(value);});await expect(previewSavedDraftThread(env,actor,scope,3)).rejects.toThrow(unrelated?'email_thread_unrelated':'email_thread_changed');}});
it('strips internal saved-draft and delivery fields instead of leaking provider state',async()=>{vi.stubGlobal('fetch',async(url:string)=>Response.json(url.endsWith('ar_email_get')?saved():null));const r=await accountWorkspaceApi(request(),env,actor);const body=await r.text();expect(r.status).toBe(200);expect(body).not.toMatch(/providerSecret|Do not expose|storage_key|owner|rfcMessageId/);});
