import {expect,it} from 'vitest';
import {verifySentEvidence,type ExpectedMail} from '../worker/email/sent-evidence';
import {hash,url64} from '../worker/email/crypto';
const bytes=new TextEncoder().encode('synthetic PDF bytes');
async function fixture(){const expected:ExpectedMail={messageId:'<synthetic@example.test>',recipients:{to:['recipient@example.test'],cc:[],bcc:[]},subject:'Synthetic subject',body:'Hello\nTest',files:[{name:'test.pdf',sha256:await hash(bytes),byte_count:bytes.length}]};
const message={id:'abc123',labelIds:['SENT'],internalDate:String(Date.parse('2026-09-09T16:30:00Z')),payload:{mimeType:'multipart/mixed',headers:[{name:'Message-ID',value:expected.messageId},{name:'From',value:'AR <ar@katathani.com>'},{name:'To',value:'recipient@example.test'},{name:'Subject',value:expected.subject}],parts:[{mimeType:'text/plain',body:{data:url64(new TextEncoder().encode('Hello\r\nTest'))}},{mimeType:'application/pdf',filename:'test.pdf',body:{size:bytes.length,attachmentId:'attachment1'}}]}};return {expected,message};}
it('requires SENT label and uses Gmail timestamp',async()=>{const {expected,message}=await fixture();expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'verified',sentAt:'2026-09-09T16:30:00.000Z'});message.labelIds=['DRAFT'];expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'not_sent'});});
it('does not count changed recipients or missing/changed attachments',async()=>{const {expected,message}=await fixture();message.payload.headers[2].value='other@example.test';expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});message.payload.headers[2].value='recipient@example.test';expect(await verifySentEvidence(message,expected,async()=>new Uint8Array([1]))).toMatchObject({status:'review_required'});message.payload.parts.pop();expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});});
it('does not accept another Message-ID or a future timestamp',async()=>{const {expected,message}=await fixture();message.payload.headers[0].value='<unrelated@example.test>';expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});message.payload.headers[0].value=expected.messageId;message.internalDate=String(Date.now()+3600000);expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});});


it('rejects an extra recipient-visible representation and contradictory draft label',async()=>{const {expected,message}=await fixture();message.payload.parts.push({mimeType:'text/html',body:{data:url64(new TextEncoder().encode('<p>Changed content</p>'))}});expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});message.payload.parts.pop();message.labelIds=['SENT','DRAFT'];expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'not_sent'});});

it('accepts Gmail-rewritten RFC ID only with exact backend receipt ID or preserved correlation',async()=>{const {expected,message}=await fixture();message.payload.headers[0].value='<rewritten@mail.gmail.com>';expect(await verifySentEvidence(message,{...expected,gmailId:'abc123'},async()=>bytes)).toMatchObject({status:'verified'});expect(await verifySentEvidence(message,{...expected,gmailId:'other'},async()=>bytes)).toMatchObject({status:'review_required'});});

it('does not let matching RFC correlation override a different immutable receipt',async()=>{const {expected,message}=await fixture();expect(await verifySentEvidence(message,{...expected,gmailId:'different-receipt'},async()=>bytes)).toMatchObject({status:'review_required'});});

it('moving an already sent message to Trash does not undo independently verified sending',async()=>{const {expected,message}=await fixture();message.labelIds=['SENT','TRASH'];expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'verified'});message.labelIds=['TRASH'];expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'not_sent'});});

it('allows Gmail line wrapping without accepting changed words, amounts or paragraph boundaries',async()=>{const {expected,message}=await fixture();expected.body='Please review the synthetic invoice amount THB 1000.\n\nNo payment is requested.';message.payload.parts[0].body.data=url64(new TextEncoder().encode('Please review the synthetic\ninvoice amount THB 1000.\n\nNo payment is requested.'));expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'verified'});message.payload.parts[0].body.data=url64(new TextEncoder().encode('Please review the synthetic invoice amount THB 2000.\n\nNo payment is requested.'));expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required',reason:'message_body'});message.payload.parts[0].body.data=url64(new TextEncoder().encode('Please review the synthetic invoice amount THB 1000. No payment is requested.'));expect(await verifySentEvidence(message,expected,async()=>bytes)).toMatchObject({status:'review_required'});});
