import {afterEach,expect,it,vi} from 'vitest';
vi.mock('../worker/email/oauth',()=>({gmailCanRead:async()=>true,gmailToken:async()=> 'synthetic'}));
import {sentCandidates,reviewSentMatch} from '../worker/email/sent-review';
const actor='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002',env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
const expected={messageId:`<${id}@ar-workspace.ar-c82.workers.dev>`,subject:'Synthetic reviewed match',body:'Synthetic body',recipients:{to:['test@example.invalid'],cc:[],bcc:[]},files:[]};
afterEach(()=>vi.unstubAllGlobals());
function harness(){const calls:string[]=[];let changed=false;const created=Date.now()-10000,sent=Date.now()-5000;vi.stubGlobal('fetch',async(input:RequestInfo|URL)=>{const u=new URL(String(input));calls.push(u.pathname);if(u.pathname.endsWith('ar_mail_get'))return Response.json({id,owner:actor,mode:'draft',state:'created',created_at:new Date(created).toISOString(),snapshot:{expected}});if(u.pathname.endsWith('/profile'))return Response.json({emailAddress:'ar@katathani.com'});if(u.pathname.endsWith('/messages'))return Response.json({messages:[{id:'syntheticSent'}]});if(u.pathname.endsWith('/syntheticSent'))return Response.json({id:'syntheticSent',labelIds:['SENT'],internalDate:String(sent),payload:{mimeType:'text/plain',headers:[{name:'From',value:'ar@katathani.com'},{name:'To',value:'test@example.invalid'},{name:'Subject',value:expected.subject},{name:'Message-ID',value:'<changed@google.test>'}],body:{data:btoa(changed?'Changed body':expected.body)}}});if(u.pathname.endsWith('ar_mail_reviewed_sent'))return Response.json({state:'sent',recorded:true});throw Error('Unexpected synthetic call');});return {calls,change:()=>{changed=true;}};}
it('searches and verifies candidates without recording history or sending mail',async()=>{const h=harness(),r=await sentCandidates(env,actor,id);expect(r.rows[0]).toMatchObject({eligible:true,gmailId:'syntheticSent'});expect(r.recordsHistory).toBe(false);expect(h.calls).not.toContain('/rest/v1/rpc/ar_mail_reviewed_sent');expect(h.calls.some(p=>p.endsWith('/send'))).toBe(false);});
it('requires explicit acknowledgement and a reason before linking a freshly reverified candidate',async()=>{const h=harness(),r=await sentCandidates(env,actor,id),candidate=r.rows[0];await expect(reviewSentMatch(env,actor,id,{gmailId:candidate.gmailId,proof:candidate.proof!,reason:'Reviewed original sent message',confirmed:false})).rejects.toThrow('email_invalid');expect(await reviewSentMatch(env,actor,id,{gmailId:candidate.gmailId,proof:candidate.proof!,reason:'Reviewed original sent message',confirmed:true})).toMatchObject({state:'sent'});expect(h.calls.filter(p=>p.endsWith('ar_mail_reviewed_sent'))).toHaveLength(1);});
it('rejects stale content or tampered proof before history changes',async()=>{const h=harness(),r=await sentCandidates(env,actor,id),candidate=r.rows[0];h.change();await expect(reviewSentMatch(env,actor,id,{gmailId:candidate.gmailId,proof:candidate.proof!,reason:'Reviewed source message',confirmed:true})).rejects.toThrow('email_sent_match_changed');expect(h.calls).not.toContain('/rest/v1/rpc/ar_mail_reviewed_sent');});
