import {afterEach,expect,it,vi} from 'vitest';
import {readManagedStorage,writeManagedStorage,StorageWriteNotDispatched} from '../worker/operations/storage';
const owner='00000000-0000-4000-8000-000000000001',key='jobs/00000000-0000-4000-8000-000000000002/originals/00000000-0000-4000-8000-000000000003.pdf';
const env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic',OPERATIONS_BUDGET_ENABLED:'true'};
const bytes=new TextEncoder().encode('synthetic bytes');
function setup({deny=false,lost=false}={}){const calls:{name:string;method:string;body:any}[]=[];let registered=false,verified=false,lostOnce=lost;vi.stubGlobal('fetch',async(input:RequestInfo|URL,init:RequestInit={})=>{const u=new URL(String(input)),name=u.pathname.split('/').at(-1)!,method=init.method??'GET',body=u.pathname.includes('/rpc/')?JSON.parse(String(init.body)):null;calls.push({name,method,body});if(name==='ar_financial_service_actor')return Response.json(owner);if(name==='ar_storage_write_begin'){if(deny)return Response.json({error:'budget_storage_exceeded'});const proceed=!registered;registered=true;return Response.json({id:body.p_id,proceed,verified});}if(name==='ar_storage_write_finish'){if(body.p_verified)verified=true;return Response.json({verified});}if(name==='ar_storage_read_budget'){if(deny)return Response.json({error:'budget_egress_exceeded'});return Response.json({byteCount:bytes.length});}if(u.pathname.includes('/storage/')){expect(init.redirect).toBe('manual');if(method==='POST'){expect(new Headers(init.headers).get('x-upsert')).toBe('false');if(lostOnce){lostOnce=false;throw Error('synthetic uncertain transport');}return new Response(null,{status:200});}return new Response(bytes,{headers:{'Content-Length':String(bytes.length)}});}throw Error('Unexpected synthetic call');});return calls;}
afterEach(()=>vi.unstubAllGlobals());
it('reserves before a write and confirms only the acknowledged object, with immutable replay',async()=>{const calls=setup();await writeManagedStorage(env,key,bytes,'application/pdf');await writeManagedStorage(env,key,bytes,'application/pdf');expect(calls.filter(c=>c.method==='POST'&&c.name.endsWith('.pdf'))).toHaveLength(1);expect(calls.findIndex(c=>c.name==='ar_storage_write_begin')).toBeLessThan(calls.findIndex(c=>c.name.endsWith('.pdf')));expect(calls.find(c=>c.name==='ar_storage_write_finish'&&c.body.p_verified)).toBeTruthy();});
it('an uncertain upload is reconciled by exact bytes without another POST',async()=>{const calls=setup({lost:true});await expect(writeManagedStorage(env,key,bytes,'application/pdf')).rejects.toThrow('synthetic uncertain transport');await writeManagedStorage(env,key,bytes,'application/pdf');expect(calls.filter(c=>c.method==='POST'&&c.name.endsWith('.pdf'))).toHaveLength(1);expect(calls.filter(c=>c.name==='ar_storage_read_budget')).toHaveLength(1);expect(calls.filter(c=>c.name==='ar_storage_write_begin').map(c=>c.body.p_id)).toEqual([calls[1].body.p_id,calls[1].body.p_id]);});
it('a quota denial stops transfers before contacting Storage',async()=>{const calls=setup({deny:true});await expect(writeManagedStorage(env,key,bytes,'application/pdf')).rejects.toThrow('budget_storage_exceeded');await expect(readManagedStorage(env,key,bytes.length)).rejects.toThrow('budget_egress_exceeded');expect(calls.some(c=>c.name.endsWith('.pdf'))).toBe(false);});
it('each read is separately precharged and remains byte bounded',async()=>{const calls=setup();for(let n=0;n<2;n++)expect(new Uint8Array(await(await readManagedStorage(env,key,bytes.length)).arrayBuffer())).toEqual(bytes);const charges=calls.filter(c=>c.name==='ar_storage_read_budget');expect(charges).toHaveLength(2);expect(charges[0].body.p_id).not.toBe(charges[1].body.p_id);});
it('rejects traversal and arbitrary URLs before any credentialed request',async()=>{const f=vi.fn();vi.stubGlobal('fetch',f);for(const bad of ['https://unapproved.test/file','jobs/00000000-0000-4000-8000-000000000002/../secret','jobs/00000000-0000-4000-8000-000000000002/%2e%2e/file'])await expect(readManagedStorage(env,bad,100)).rejects.toThrow('storage_path_invalid');expect(f).not.toHaveBeenCalled();});

it('marks only failures before provider dispatch as safe intent cancellation',async()=>{
 setup({deny:true});await expect(writeManagedStorage(env,key,bytes,'application/pdf')).rejects.toBeInstanceOf(StorageWriteNotDispatched);
 setup({lost:true});try{await writeManagedStorage(env,key,bytes,'application/pdf');throw Error('expected transport failure');}catch(error){expect(error).not.toBeInstanceOf(StorageWriteNotDispatched);expect(error).toHaveProperty('message','synthetic uncertain transport');}
});
