import {crc32,deflateSync} from 'node:zlib';
import {afterEach,expect,it,vi} from 'vitest';
import {PDFDocument,PDFName,PDFString} from 'pdf-lib';
import {inspectSupplemental} from '../worker/email/supplemental-validation';
const png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==','base64'));
it('accepts a static PDF and reports its exact content hash',async()=>{const pdf=await PDFDocument.create();pdf.addPage();const bytes=await pdf.save();const result=await inspectSupplemental(bytes,'ตัวอย่าง.pdf','application/pdf');expect(result).toMatchObject({mime:'application/pdf',pages:1,byte_count:bytes.length});expect(result.sha256).toMatch(/^[a-f0-9]{64}$/);});
it('rejects PDF scripts, embedded files and forms even in compressed objects',async()=>{for(const key of ['OpenAction','EmbeddedFiles','AcroForm']){const pdf=await PDFDocument.create();pdf.addPage();pdf.catalog.set(PDFName.of(key),pdf.context.obj({S:'JavaScript',JS:PDFString.of('synthetic') }));await expect(inspectSupplemental(await pdf.save({useObjectStreams:true}),'test.pdf','application/pdf')).rejects.toThrow('attachment_active_pdf');}});
it('rejects disguised/unsupported files and filename header injection',async()=>{await expect(inspectSupplemental(new TextEncoder().encode('<html>sample</html>'),'receipt.pdf','application/pdf')).rejects.toThrow('attachment_invalid');await expect(inspectSupplemental(png,'receipt.xlsx','image/png')).rejects.toThrow('attachment_unsupported');await expect(inspectSupplemental(png,'receipt\r\n.png','image/png')).rejects.toThrow('attachment_name_invalid');});
it('parses PNG image data and enforces decoded pixel budget before parsing',async()=>{expect(await inspectSupplemental(png,'receipt.png','image/png')).toMatchObject({mime:'image/png',width:1,height:1});const huge=png.slice();new DataView(huge.buffer).setUint32(16,100000);await expect(inspectSupplemental(huge,'huge.png','image/png')).rejects.toThrow('attachment_image_too_large');});

afterEach(()=>vi.unstubAllGlobals());
function chunk(name:string,data:Uint8Array){const type=Buffer.from(name),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length,0);type.copy(out,4);Buffer.from(data).copy(out,8);out.writeUInt32BE(crc32(out.subarray(4,-4)),out.length-4);return out;}
it('rejects duplicate or illegal IHDR before starting decompression',async()=>{const decoder=vi.fn();vi.stubGlobal('DecompressionStream',decoder);const duplicate=Buffer.concat([png.subarray(0,33),png.subarray(8,33),png.subarray(33)]);await expect(inspectSupplemental(duplicate,'duplicate.png','image/png')).rejects.toThrow('attachment_invalid_image');for(const [offset,value]of [[24,255],[25,9],[26,1],[27,1],[28,3]]){const invalid=Buffer.from(png);invalid[offset]=value;invalid.writeUInt32BE(crc32(invalid.subarray(12,29)),29);await expect(inspectSupplemental(invalid,'invalid.png','image/png')).rejects.toThrow('attachment_invalid_image');}expect(decoder).not.toHaveBeenCalled();});
it('rejects inflated data larger than its declared raster and bad CRCs',async()=>{const bomb=Buffer.concat([png.subarray(0,33),chunk('IDAT',deflateSync(Buffer.alloc(100000))),chunk('IEND',new Uint8Array())]);await expect(inspectSupplemental(bomb,'oversized.png','image/png')).rejects.toThrow('attachment_invalid_image');const invalid=png.slice();invalid[45]^=1;await expect(inspectSupplemental(invalid,'crc.png','image/png')).rejects.toThrow('attachment_invalid_image');});

it('accepts a JPEG header with the supported dimensions',async()=>{const bytes=Uint8Array.from(Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAC0AUADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD2yiiimc4UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//2Q==','base64'));expect(await inspectSupplemental(bytes,'receipt.jpg','image/jpeg')).toMatchObject({mime:'image/jpeg',width:320,height:180});});
