import {afterEach,expect,it,vi} from 'vitest';
import {PDFDocument} from 'pdf-lib';
import {supplementalRequest} from '../worker/email/supplemental';
import {hash} from '../worker/email/crypto';
import {handleApi} from '../worker/index';
const draftId='00000000-0000-4000-8000-000000000001',fileId='00000000-0000-4000-8000-000000000002',jobId='00000000-0000-4000-8000-000000000003';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'synthetic'};
afterEach(()=>vi.unstubAllGlobals());
async function fixture(){const pdf=await PDFDocument.create();pdf.addPage();const bytes=await pdf.save();return {bytes,draft:{id:draftId,document_job_id:jobId,revision:1,package_changed:false,exports:[],attachments:[]},file:{id:fileId,name:'test.pdf',mime:'application/pdf',storage_key:`jobs/${jobId}/email/${draftId}/${fileId}`,byte_count:bytes.length,sha256:await hash(bytes)}};}
function request(bytes:Uint8Array){return new Request(`https://app.test/api/email/${draftId}/attachments/${fileId}?revision=1&name=test.pdf`,{method:'POST',headers:{'Content-Type':'application/pdf'},body:new Uint8Array(bytes).buffer});}
it('an identical upload replay returns the receipt without writing storage again',async()=>{const {bytes,draft,file}=await fixture();const calls:string[]=[];vi.stubGlobal('fetch',async(url:string)=>{calls.push(url);return Response.json(url.endsWith('/ar_email_get')?{...draft,revision:2,attachments:[file]}:{...file,removed:false});});const result=await supplementalRequest(request(bytes),env,'actor',draftId,fileId);expect(result).toMatchObject({revision:2});expect(calls).toHaveLength(2);expect(calls.every(s=>s.includes('/rest/v1/rpc/'))).toBe(true);});
it('recovers a storage-success/metadata-loss retry only after hashing existing bytes',async()=>{const {bytes,draft}=await fixture();let writes=0,records=0;vi.stubGlobal('fetch',async(url:string)=>{if(url.endsWith('/ar_email_get'))return Response.json(draft);if(url.endsWith('/ar_email_attachment_record'))return Response.json(null);if(url.endsWith('/ar_mail_unresolved'))return Response.json(false);if(url.endsWith('/ar_gmail_attempt_get'))return Response.json(null);if(url.includes('/object/authenticated/'))return new Response(new Uint8Array(bytes).buffer);if(url.includes('/storage/')){writes++;return Response.json({error:'Duplicate'},{status:400});}if(url.endsWith('/ar_email_attachment_add_v2')){records++;return Response.json({...draft,revision:2});}throw Error('Unexpected request');});expect(await supplementalRequest(request(bytes),env,'actor',draftId,fileId)).toMatchObject({revision:2});expect(writes).toBe(1);expect(records).toBe(1);});
it('does not write an attachment for another owner or an unresolved handoff',async()=>{vi.stubGlobal('fetch',async()=>Response.json(null));await expect(supplementalRequest(request(new Uint8Array([1])),env,'other',draftId,fileId)).rejects.toThrow('email_missing');const {bytes,draft}=await fixture();const calls:string[]=[];vi.stubGlobal('fetch',async(url:string)=>{calls.push(url);return Response.json(url.endsWith('/ar_email_get')?draft:url.endsWith('/ar_mail_unresolved')?true:null);});await expect(supplementalRequest(request(bytes),env,'actor',draftId,fileId)).rejects.toThrow('email_handoff_pending');expect(calls.some(s=>s.includes('/storage/'))).toBe(false);});
it('protects upload, preview and remove routes before any service access',async()=>{const f=vi.fn();vi.stubGlobal('fetch',f);for(const method of ['POST','GET','DELETE'])expect((await handleApi(new Request(`https://app.test/api/email/${draftId}/attachments/${fileId}`,{method}),{})).status).toBe(401);expect(f).not.toHaveBeenCalled();});
