import {afterEach,expect,it,vi} from 'vitest';
import {trackerHeaders} from '../worker/tracker-sync/workbook';
import {writeTrackerBatch} from '../worker/tracker-sync/provider';
import {readNativeTracker} from '../worker/tracker-sync/native';
import type {TrackerEnv,ProviderWrite} from '../worker/tracker-sync/service';
vi.mock('../worker/drive/oauth',()=>({driveToken:vi.fn(async()=> 'synthetic-token')}));
vi.mock('../worker/drive/provider',async original=>({...await original<typeof import('../worker/drive/provider')>(),identity:vi.fn(async()=> 'ar@katathani.com')}));
const file='synthetic_native_original_123456',owner='synthetic-owner';
const env:TrackerEnv={REPORT_SHEET_KHAOLAK_ID:file,TRACKER_NATIVE_BEST_EFFORT_ENABLED:'true'};
type Cell={userEnteredValue?:{stringValue?:string;numberValue?:number;formulaValue?:string;boolValue?:boolean};effectiveValue?:{stringValue?:string;numberValue?:number};textFormatRuns?:unknown[];chipRuns?:unknown[];userEnteredFormat?:{numberFormat:{type:string;pattern:string}}};
const col=(v:string)=>[...v].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1;
function grid(){const headers:Cell[]=Array.from({length:33},()=>({}));for(const [k,v]of Object.entries(trackerHeaders))headers[col(k)]={userEnteredValue:{stringValue:v}};const row=(key:string,invoice:string)=>{const cells:Cell[]=Array.from({length:33},()=>({}));for(const [k,v]of Object.entries({A:'SAN',C:'0002',E:invoice,F:'F'+invoice,G:'2026-09-01',AG:key}))cells[col(k)]={userEnteredValue:{stringValue:v}};for(const k of ['R','U','V','W'])cells[col(k)].userEnteredFormat={numberFormat:{type:'DATE',pattern:'dd/mm/yyyy'}};cells[col('T')]={userEnteredValue:{formulaValue:'=R3+S3'}};cells[col('AA')]={userEnteredValue:{formulaValue:'=H3-Z3'}};return {values:cells};};return {spreadsheetId:file,sheets:[{properties:{sheetId:9,title:'ลูกหนี้ เขาหลัก',gridProperties:{rowCount:100,columnCount:33}},data:[{startRow:0,startColumn:0,rowData:[{values:[]},{values:headers},row('key-A','00001'),row('key-B','00002')]}]}]};}
function fake(options:{lost?:boolean;move?:boolean;formula?:boolean;changeIdentity?:boolean;newGid?:boolean}={}){let value=grid();if(options.move){const rows=value.sheets[0].data[0].rowData;[rows[2],rows[3]]=[rows[3],rows[2]];value.sheets[0].properties.sheetId=77;}if(options.formula)value.sheets[0].data[0].rowData[2].values[col('R')].userEnteredValue={formulaValue:'=TODAY()'};const posts:Record<string,unknown>[]=[];const fetcher=vi.fn(async(input:RequestInfo|URL,init:RequestInit={})=>{const url=String(input);if(url.includes('sheets.googleapis.com')){if(init.method==='POST'){const body=JSON.parse(String(init.body));posts.push(body);for(const request of body.requests){const u=request.updateCells;value.sheets[0].data[0].rowData[u.start.rowIndex].values[u.start.columnIndex].userEnteredValue=u.rows[0].values[0].userEnteredValue;}if(options.changeIdentity)value.sheets[0].data[0].rowData[2].values[col('E')].userEnteredValue={stringValue:'OTHER'};if(options.newGid)value.sheets[0].properties.sheetId=88;if(options.lost)throw Error('synthetic response lost');return Response.json({spreadsheetId:file,replies:[]});}return Response.json(value);}return Response.json({id:file,name:'Master_SAN_AR_Tracker',mimeType:'application/vnd.google-apps.spreadsheet',trashed:false,version:'1',modifiedTime:'2026-10-07T00:00:00Z',capabilities:{canDownload:true,canEdit:true,canModifyContent:true}});});vi.stubGlobal('fetch',fetcher);return {posts,value,fetcher};}
const input=():ProviderWrite=>({version:'observed',rowKey:'key-A',expectedIdentity:{hotel:'TSAN',accountNo:'0002',invoiceNo:'00001',folio:'F00001',transactionDate:'2026-09-01'},locator:{sheetId:123,row:40},changes:[{field:'R',expected:null,value:'2026-09-02'},{field:'U',expected:null,value:'2026-09-03'},{field:'V',expected:null,value:'2026-09-04'},{field:'W',expected:null,value:'2026-09-05'}]});
afterEach(()=>vi.unstubAllGlobals());
it('publishes only numeric date values at freshly matched identity, preserving all other cell metadata',async()=>{const state=fake(),before=structuredClone(state.value);expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'written'});expect(state.posts).toHaveLength(1);const requests=state.posts[0].requests as {updateCells:{start:{sheetId:number;rowIndex:number;columnIndex:number};fields:string;rows:{values:{userEnteredValue:{numberValue:number}}[]}[]}}[];expect(requests.map(r=>[r.updateCells.start,r.updateCells.fields])).toEqual([17,20,21,22].map(columnIndex=>[{sheetId:9,rowIndex:2,columnIndex},'userEnteredValue']));for(const r of requests){expect(Number.isInteger(r.updateCells.rows[0].values[0].userEnteredValue.numberValue)).toBe(true);before.sheets[0].data[0].rowData[2].values[r.updateCells.start.columnIndex].userEnteredValue=r.updateCells.rows[0].values[0].userEnteredValue;}expect(state.value).toEqual(before);});
it('is disabled by default and formulas/identity mismatches never publish',async()=>{const state=fake();expect(await writeTrackerBatch({...env,TRACKER_NATIVE_BEST_EFFORT_ENABLED:undefined},owner,'khao-lak',file,[input()])).toEqual({status:'conflict'});expect(state.posts).toHaveLength(0);const formula=fake({formula:true});expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'conflict'});expect(formula.posts).toHaveLength(0);const wrong=input();wrong.expectedIdentity.invoiceNo='1';const identity=fake();expect(await writeTrackerBatch(env,owner,'khao-lak',file,[wrong])).toMatchObject({status:'conflict'});expect(identity.posts).toHaveLength(0);});
it.each([{lost:true},{changeIdentity:true}])('response loss or changed readback identity is uncertain with exactly one POST: %j',async option=>{const state=fake(option);expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'uncertain'});expect(state.posts).toHaveLength(1);});
it('accepts observed merged Property A1 header and resolves moved key under a new gid',async()=>{const state=fake({move:true}),rows=state.value.sheets[0].data[0].rowData;rows[0].values=[rows[1].values[0]];rows[1].values[0]={};expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'written'});expect(state.posts[0]).toMatchObject({requests:Array.from({length:4},()=>({updateCells:{start:{sheetId:77,rowIndex:3}}}))});});
it('holds duplicate canonical rows even when posting dates and AG differ',async()=>{const state=fake(),rows=state.value.sheets[0].data[0].rowData;rows[3].values[col('E')]=structuredClone(rows[2].values[col('E')]);rows[3].values[col('F')]=structuredClone(rows[2].values[col('F')]);rows[3].values[col('G')]={userEnteredValue:{stringValue:'2026-09-02'}};await expect(writeTrackerBatch(env,owner,'khao-lak',file,[input()])).rejects.toThrow('tracker_native_identity_ambiguous');expect(state.posts).toHaveLength(0);});
it('text identifiers never gain zero padding from a numeric format',async()=>{const state=fake(),cell=state.value.sheets[0].data[0].rowData[2].values[col('E')];cell.userEnteredValue={stringValue:'1'};cell.userEnteredFormat={numberFormat:{type:'NUMBER',pattern:'00000'}};const p=input();p.expectedIdentity.invoiceNo='1';expect(await writeTrackerBatch(env,owner,'khao-lak',file,[p])).toMatchObject({status:'written'});});
it.each(['textFormatRuns','chipRuns'] as const)('holds targeted %s metadata that value writes would erase',async property=>{const state=fake();state.value.sheets[0].data[0].rowData[2].values[col('R')][property]=[{}];expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'conflict'});expect(state.posts).toHaveLength(0);});
it('changed gid after publication is uncertain without another POST',async()=>{const state=fake({newGid:true});expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'uncertain'});expect(state.posts).toHaveLength(1);});
it('matches normal numeric posting dates without treating date formatting as an identifier mask',async()=>{const state=fake(),cell=state.value.sheets[0].data[0].rowData[2].values[col('G')];cell.userEnteredValue={numberValue:(Date.UTC(2026,8,1)-Date.UTC(1899,11,30))/86400000};cell.userEnteredFormat={numberFormat:{type:'DATE',pattern:'dd/mm/yyyy'}};expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'written'});});
it.each([false,true])('boolean %s is nonblank invalid date content and is never overwritten',async boolValue=>{const state=fake();state.value.sheets[0].data[0].rowData[2].values[col('R')].userEnteredValue={boolValue};expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'conflict'});expect(state.posts).toHaveLength(0);});
it('boolean identity cannot be accepted as a string identifier',async()=>{const state=fake();state.value.sheets[0].data[0].rowData[2].values[col('E')].userEnteredValue={boolValue:false};const p=input();p.expectedIdentity.invoiceNo='FALSE';expect(await writeTrackerBatch(env,owner,'khao-lak',file,[p])).toMatchObject({status:'conflict'});expect(state.posts).toHaveLength(0);});
it.each([{}, {numberValue:Number.NaN}])('unrecognized/nonfinite date values are never coerced to an expected blank',async value=>{const state=fake();state.value.sheets[0].data[0].rowData[2].values[col('R')].userEnteredValue=value;expect(await writeTrackerBatch(env,owner,'khao-lak',file,[input()])).toMatchObject({status:'conflict'});expect(state.posts).toHaveLength(0);});
it('retains nondate boolean source values verbatim',async()=>{const state=fake(),cells=state.value.sheets[0].data[0].rowData[2].values;cells[col('Y')].userEnteredValue={boolValue:false};cells[col('AB')].userEnteredValue={boolValue:true};const snapshot=await readNativeTracker('synthetic-token',file);expect(snapshot.rows[0].fields).toMatchObject({Y:'FALSE',AB:'TRUE'});expect(state.posts).toHaveLength(0);});
