import {afterEach,describe,expect,it,vi} from 'vitest';
import {trackerConflictsApi} from '../worker/tracker-sync/conflicts-api';
import {validConflictPage} from '../src/domain/tracker-conflicts';
const actor='00000000-0000-4000-8000-000000000001',env={SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SECRET_KEY:'synthetic-cursor-signing-key'};
afterEach(()=>vi.unstubAllGlobals());
const id=(n:number)=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const rows=Array.from({length:50},(_,n)=>({id:id(n+1),rowKey:'SYNTH-'+n,field:'identity',reason:'unmatched',sheetValue:null,webValue:null,revision:2,createdAt:'2026-10-06T09:00:00.123456Z'}));
const page={region:'phuket',category:'all',counts:{all:53,dates:2,references:0,identity:51,other:0},rows,next:{createdAt:rows[49].createdAt,id:rows[49].id}};
const request=(q='region=phuket',method='GET')=>new Request('https://app.test/api/reports/tracker-conflicts?'+q,{method});
describe('bounded context-bound tracker conflict pages',()=>{
 it('signs next cursor and preserves exact PostgreSQL microseconds and UUID ties',async()=>{const calls:Record<string,unknown>[]=[];vi.stubGlobal('fetch',vi.fn(async(_url,init)=>{const body=JSON.parse(init.body);calls.push(body);return Response.json(calls.length===1?page:{...page,rows:[{...rows[0],id:id(51)}],next:null});}));const first=await (await trackerConflictsApi(request(),env,actor)).json() as {nextCursor:string};expect(first.nextCursor).toMatch(/^[A-Za-z0-9_-]+\.[a-f0-9]{64}$/);expect((await trackerConflictsApi(request('region=phuket&cursor='+first.nextCursor),env,actor)).status).toBe(200);expect(calls[1].p_after_created_at).toBe('2026-10-06T09:00:00.123456Z');expect(calls[1].p_after_id).toBe(id(50));expect(calls[1].p_actor).toBe(actor);});
 it('rejects cursor tampering, cross-region, category and actor changes before RPC',async()=>{const fetch=vi.fn(async()=>Response.json(page));vi.stubGlobal('fetch',fetch);const first=await (await trackerConflictsApi(request(),env,actor)).json() as {nextCursor:string};const cursor=first.nextCursor;for(const q of ['region=phuket&cursor='+cursor.slice(0,-1)+(cursor.endsWith('a')?'b':'a'),'region=khao-lak&cursor='+cursor,'region=phuket&category=dates&cursor='+cursor])expect((await trackerConflictsApi(request(q),env,actor)).status).toBe(400);expect((await trackerConflictsApi(request('region=phuket&cursor='+cursor),env,id(2))).status).toBe(400);expect(fetch).toHaveBeenCalledTimes(1);});
 it.each(['region=phuket&region=phuket','region=phuket&category=dates&category=dates','region=phuket&cursor=&cursor=x','region=phuket&limit=999','region=unknown','region=phuket&category=anything','region=phuket&cursor='+'x'.repeat(801)])('rejects ambiguous/unbounded query %s',async q=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);expect((await trackerConflictsApi(request(q),env,actor)).status).toBe(400);expect(fetch).not.toHaveBeenCalled();});
 it('requires GET/auth actor and current regional access independently of cursor',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);expect((await trackerConflictsApi(request(),env,'')).status).toBe(401);expect((await trackerConflictsApi(request('region=phuket','POST'),env,actor)).status).toBe(405);expect((await trackerConflictsApi(request('region=khao-lak'),{...env,REQUEST_ACCESS:{regions:['phuket']} as never},actor)).status).toBe(403);expect(fetch).not.toHaveBeenCalled();});
 it('uses verified request actor rather than shared owner and preserves SQL denial',async()=>{const fetch=vi.fn(async(_url:unknown,_init:RequestInit)=>Response.json({error:'tracker_forbidden'}));vi.stubGlobal('fetch',fetch);expect((await trackerConflictsApi(request(),{...env,REQUEST_ACTOR:id(2)},actor)).status).toBe(403);expect(JSON.parse(String(fetch.mock.calls[0][1].body)).p_actor).toBe(id(2));});
 it.each([{...page,rows:[rows[1],rows[0]],next:null},{...page,rows:[rows[0],rows[0]],next:null},{...page,rows:[{...rows[0],createdAt:'2026-10-06T09:00:00.123Z'}],next:null},{...page,region:'khao-lak'},{...page,next:{createdAt:rows[49].createdAt,id:id(49)}}])('rejects unordered, duplicate, rounded or wrong-scope provider output',async response=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json(response)));expect((await trackerConflictsApi(request(),env,actor)).status).toBe(503);});
 it('date filtering exposes late dates without accepting identity/reference rows as dates',async()=>{const dates={...page,category:'dates',rows:[{...rows[0],id:id(52),field:'R'},{...rows[0],id:id(53),field:'U'}],next:null};vi.stubGlobal('fetch',vi.fn(async()=>Response.json(dates)));const response=await trackerConflictsApi(request('region=phuket&category=dates'),env,actor);expect(response.status).toBe(200);expect(validConflictPage(await response.json(),'phuket','dates')).toBe(true);vi.stubGlobal('fetch',vi.fn(async()=>Response.json({...dates,rows:[rows[0]]})));expect((await trackerConflictsApi(request('region=phuket&category=dates'),env,actor)).status).toBe(503);});
});
