import {hotelName,type HotelId} from '../domain/hotels';
import type {CSSProperties} from 'react';
import {amount,number} from './period-data';
import type {ComparisonAccount,ComparisonRow,ComparisonSort,ComparisonSortKey} from './account-comparison';
import './account-comparison.css';

export function AccountComparison({rows,hotels,sort,onSort,onOpen,visible=Number.POSITIVE_INFINITY,aged=false,unit='invoices',amountLabel='Open amount',label}:{rows:ComparisonRow[];hotels:readonly HotelId[];sort:ComparisonSort;onSort:(sort:ComparisonSort)=>void;onOpen:(account:ComparisonAccount)=>void;visible?:number;aged?:boolean;unit?:string;amountLabel?:string;label:string}){
 const selectedHotel=hotels.includes(sort.hotel)?sort.hotel:hotels[0];
 const choices:[ComparisonSortKey,string][]=[['account','Account name'],['amount',amountLabel],['count',unit==='records'?'Records':'Invoices'],['oldest','Oldest invoice'],['number','Account number'],['type','Account type'],...(aged?[['unbilled','Not billed'] as [ComparisonSortKey,string]]:[])];
 const accounts=rows.reduce((n,row)=>n+Object.keys(row.cells).length,0);
 return <div className="dashboard-account-comparison" role="region" aria-label={label}>
  <div className="dashboard-comparison-controls"><label>Sort by<select aria-label="Account comparison sort" value={sort.key} onChange={event=>onSort({...sort,key:event.target.value as ComparisonSortKey,descending:!['account','number','type'].includes(event.target.value)})}>{choices.map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label><label>Sort values for<select aria-label="Account comparison sort hotel" value={selectedHotel} disabled={sort.key==='account'} onChange={event=>onSort({...sort,hotel:event.target.value as HotelId})}>{hotels.map(hotel=><option value={hotel} key={hotel}>{hotel} · {hotelName(hotel)}</option>)}</select></label><button aria-label="Change account comparison sort direction" onClick={()=>onSort({...sort,descending:!sort.descending})}>{sort.descending?'Descending':'Ascending'}</button><span>{number(rows.length)} comparison {rows.length===1?'row':'rows'} · {number(accounts)} {accounts===1?'account':'accounts'}</span></div>
  <p className="dashboard-comparison-basis">{amountLabel} · THB · Hotel ledgers shown separately.</p>
  {rows.some(row=>row.independent)&&<p className="dashboard-comparison-note">Accounts with repeated or missing names are shown as separate ledgers.</p>}
  <div className="dashboard-comparison-scroll" tabIndex={0} role="region" aria-label={label+' table'}><table style={{'--comparison-hotel-count':hotels.length} as CSSProperties}><colgroup><col className="dashboard-comparison-account-col"/>{hotels.map(hotel=><col key={hotel} className="dashboard-comparison-hotel-col"/>)}</colgroup><thead><tr><th scope="col">Account</th>{hotels.map(hotel=><th scope="col" key={hotel} data-hotel={hotel}>{hotel}<small>{hotelName(hotel)}</small></th>)}</tr></thead><tbody>{rows.slice(0,visible).map(row=><tr key={row.key} data-dashboard-comparison-row="true"><th scope="row"><strong>{row.name}</strong>{row.independent&&Object.values(row.cells).map(cell=><small key={cell!.hotel}>{cell!.hotel} · {cell!.accountNo??cell!.accountId} · Separate ledger</small>)}</th>{hotels.map(hotel=>{const account=row.cells[hotel];return <td key={hotel} data-hotel={hotel}>{account?<button data-dashboard-account="true" aria-label={'Open '+account.accountName+' · '+hotel+' · Account '+(account.accountNo??account.accountId)} onClick={()=>onOpen(account)}><strong>{account.amount===null?'Unavailable':amount(account.amount)}</strong><span>{number(account.count)} {unit}</span><small>{account.accountNo??account.accountId} · {account.accountType}</small>{account.oldest!=null&&<small>Oldest {account.oldest} days</small>}{aged&&account.unbilled!==undefined&&<small>Not billed {number(account.unbilled)} · {account.unbilledAmount==null?'Unavailable':amount(account.unbilledAmount)}</small>}</button>:<span className="dashboard-comparison-missing" aria-label={'No matching Account in '+hotel+' within this scope'}>—</span>}</td>;})}</tr>)}</tbody></table></div>
 </div>;
}
