import {useSource} from './data';
import {scopeQuery,type DashboardScope,validPeriod} from './model';
import {balancesResult,balanceLabels,amount,number,percent,stamp} from './period-data';
import {useCollectionPolicy} from '../collection/PolicyContext';
export interface PeriodDetail {kind:'balance'|'sent'|'invoice_entries'|'payments'|'payment_invoices';metric?:string;stage?:string}
export function PeriodBalances({scope,token,revision,onDetail}:{scope:DashboardScope;token:string;revision:number;onDetail:(detail:PeriodDetail)=>void}){
 const q=scopeQuery(scope);q.set('asOf',scope.to);q.set('limit','1');const source=useSource(validPeriod(scope)?'/api/dashboard/balances?'+q:null,token,revision,balancesResult),data=source.data;
 const {policy}=useCollectionPolicy(),known=source.state==='ready'&&data?.complete,base=data?.metrics.find(m=>m.key==='open');
 const stages=[...new Map([...(policy?.rounds.filter(r=>r.active).map(r=>({key:r.key,label:r.label,count:0,amount:'0.00'}))??[]),...(data?.stages??[])].map(s=>[s.key,s])).values()];
 return <section className="dashboard-period-balances" aria-label="Outstanding at period end">
  <header className="dashboard-section-heading"><div><h2>Outstanding at period end · {scope.to}</h2><p>Open invoices from all entry dates · balances at the recorded time</p></div><span>{data?.mode==='current'?'Current saved state':data?.mode==='snapshot'?'Captured daily state':'Snapshot unavailable'}<small>{stamp(data?.capturedAt)} · Source {stamp(data?.sourceAt)}</small></span></header>
  {!known&&<p className="dashboard-notice" role="status">{source.state==='error'?'The closing-date balances could not be loaded. Reload to try again.':source.state==='loading'?'Loading closing-date balances…':data?.mode==='unavailable'?'No invoice snapshot was captured for this date. Current balances have not been substituted.':'Some source records are not verified. Confirmed totals remain unavailable.'}{data?.missingHotels.length?' · '+data.missingHotels.join(' / '):''}</p>}
  <div className="dashboard-closing-total"><span>All outstanding invoices</span><strong data-testid="dashboard-closing-count">{number(known?base?.count:null)} invoices</strong><b data-testid="dashboard-closing-amount">{amount(known?base?.amount:null)}</b><button disabled={!data||data.mode==='unavailable'} onClick={()=>onDetail({kind:'balance',metric:'open'})}>View invoices</button></div>
  <div className="dashboard-status-columns">
   <div className="dashboard-surface"><h3>Billing & Due date</h3><div className="dashboard-table-scroll" tabIndex={0} role="region" aria-label="Closing-date billing status"><table><thead><tr><th>Status</th><th>Invoices</th><th>Open amount</th><th>% of open</th></tr></thead><tbody>{Object.entries(balanceLabels).filter(([key])=>key!=='open').map(([key,label])=>{const row=data?.metrics.find(r=>r.key===key);return <tr key={key}><th><button className="dashboard-text-link" disabled={!data||data.mode==='unavailable'} onClick={()=>onDetail({kind:'balance',metric:key})}>{label}</button></th><td>{number(known?row?.count:null)}</td><td>{amount(known?row?.amount:null)}</td><td>{known?percent(row?.amount,base?.amount):'—'}</td></tr>;})}</tbody></table></div></div>
   <div className="dashboard-surface"><h3>Latest Follow-Up stage</h3><p>Each outstanding invoice appears in its latest recorded stage.</p><div className="dashboard-table-scroll" tabIndex={0} role="region" aria-label="Closing-date follow-up stages"><table><thead><tr><th>Stage</th><th>Invoices</th><th>Open amount</th><th>% of open</th></tr></thead><tbody>{stages.map(row=><tr key={row.key}><th><button className="dashboard-text-link" disabled={!data||data.mode==='unavailable'} onClick={()=>onDetail({kind:'balance',stage:row.key})}>{row.label}</button></th><td>{number(known?row.count:null)}</td><td>{amount(known?row.amount:null)}</td><td>{known?percent(row.amount,base?.amount):'—'}</td></tr>)}{!stages.length&&<tr><td colSpan={4}>Stage information is unavailable.</td></tr>}</tbody></table></div></div>
  </div><p className="dashboard-footnote">Percentages use the closing-date open amount in this scope. Due date and age groups overlap; they are not added together. Required and Not Required billing are kept separate.</p>
 </section>;
}
