import {isHotelId} from '../domain/hotels';
import {useEffect,useRef,useState} from 'react';
import {useDetailRows,sortDetailRows,detailIdentity,type DetailSortKey} from './detail-data';
import {SortButton} from '../table-sort';
import {accountIdentity,scopeQuery,type DashboardScope,validPeriod} from './model';
import {amount,number,balanceLabels,rangeLabel} from './period-data';
import type {PeriodDetail} from './PeriodBalances';
const text=(value:unknown)=>typeof value==='string'||typeof value==='number'?String(value):'—';
export function PeriodDetailPanel({scope,detail,token,revision,onClose,onOpenInvoice}:{scope:DashboardScope;detail:PeriodDetail;token:string;revision:number;onClose:()=>void;onOpenInvoice:(hotel:string,accountId:string,invoiceId?:string)=>void}){
 const displayedHotel=accountIdentity(scope.account)?.[0]??scope.hotel;
 const query=scopeQuery(scope,detail.kind!=='balance');
 let endpoint='';if(detail.kind==='balance'){endpoint='/api/dashboard/balances';query.set('asOf',scope.to);if(detail.stage)query.set('stage',detail.stage);else query.set('metric',detail.metric??'open');}
 else if(detail.kind==='invoice_entries')endpoint='/api/dashboard/invoice-entries';else if(detail.kind==='payment_invoices')endpoint='/api/dashboard/payment-invoices';else if(detail.kind==='sent'){endpoint='/api/reports/activity';if(detail.stage)query.set('kind',detail.stage);}else endpoint='/api/financial/'+detail.kind;
 const [retry,setRetry]=useState(0),[sort,setSort]=useState<{key:DetailSortKey;descending:boolean}>({key:'amount',descending:true}),[visible,setVisible]=useState(200);
 const path=validPeriod(scope)?endpoint+'?'+query:null;
 const source=useDetailRows(path,detail.kind,token,revision+retry);
 const changeSort=(key:DetailSortKey)=>{setSort(old=>({key,descending:old.key===key?!old.descending:['amount','original'].includes(key)}));setVisible(200);};
 const heading=(key:DetailSortKey,label:string)=><SortButton label={label} active={sort.key===key} descending={sort.descending} onClick={()=>changeSort(key)}/>;
 const direction=(...keys:DetailSortKey[])=>keys.includes(sort.key)?sort.descending?'descending':'ascending':'none';
 const more=useRef<HTMLDivElement>(null);
 useEffect(()=>{setVisible(200);},[path,revision,retry]);
 useEffect(()=>{const el=more.current;if(!el)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setVisible(n=>n+200);},{rootMargin:'600px'});observer.observe(el);return()=>observer.disconnect();},[visible,source.data]);
 const host=useRef<HTMLElement>(null);useEffect(()=>{host.current?.scrollIntoView({block:'start',behavior:'instant'});},[detail.kind,detail.metric,detail.stage,scope.hotel]);
 const title=detail.kind==='balance'?(detail.stage??balanceLabels[detail.metric??'open']):detail.kind==='sent'?(detail.stage??'All verified sends'):detail.kind==='invoice_entries'?'New invoices':detail.kind==='payment_invoices'?'Invoices with OPERA payments':'OPERA payment records';
 const allRows=sortDetailRows(source.data?.rows??[],detail.kind,sort.key,sort.descending),rows=allRows.slice(0,visible);
 return <section ref={host} className="dashboard-surface dashboard-detail-panel" aria-label="Dashboard invoice details"><header><div><h2>{title}</h2><p>{displayedHotel==='All'?'All hotels':displayedHotel} · {detail.kind==='balance'?'Open as of '+scope.to:rangeLabel(scope.from,scope.to)}</p></div><button onClick={onClose}>Close details</button></header>
  {detail.kind==='invoice_entries'&&<p className="dashboard-footnote">Saved OPERA invoices filtered by Bill Date, including invoices with zero open balance. Amounts show original invoice value.</p>}
  {source.state==='error'?<p role="alert">The full list could not be verified. Retry loading the records. <button onClick={()=>setRetry(n=>n+1)}>Retry details</button></p>:source.state==='loading'?<p role="status">Loading invoice details…{source.total!==undefined?` ${source.loaded} / ${source.total}`:''}</p>:!source.data?.complete&&<p className="dashboard-notice">Source coverage is incomplete. These are the available records for this selection.</p>}
  <div className="dashboard-table-scroll" tabIndex={0} role="region" aria-label="Detailed Dashboard records"><table><thead><tr><th scope="col" aria-sort={direction('account','hotel')}>{heading('account','Account')}<span className="table-sort-secondary">{heading('hotel','Hotel')}</span></th><th scope="col" aria-sort={direction('invoice','folio')}>{heading('invoice',detail.kind==='payments'?'Payment':'Invoice')}{detail.kind!=='payments'&&<span className="table-sort-secondary">{heading('folio','Folio')}</span>}</th><th scope="col" aria-sort={direction('guest','date')}>{detail.kind==='balance'?<>{heading('guest','Guest')}<span className="table-sort-secondary">{heading('date','Entry date')}</span></>:detail.kind==='payment_invoices'?'Payment evidence':heading('date',detail.kind==='sent'?'Sent date':'Date')}</th><th scope="col" aria-sort={direction('amount','original')}>{heading('amount',detail.kind==='balance'?'Open · THB':detail.kind==='sent'?'Amount at send':detail.kind==='payments'?'Posted · THB':detail.kind==='payment_invoices'?'Currently allocated':'Original · THB')}{['balance','invoice_entries','payments'].includes(detail.kind)&&<span className="table-sort-secondary">{heading('original',detail.kind==='balance'?'Original':detail.kind==='payments'?'Allocated':'Current open')}</span>}</th>{detail.kind==='balance'&&<><th scope="col" aria-sort={direction('billing','due')}>{heading('billing','Billing')}<span className="table-sort-secondary">{heading('due','Due date')}</span></th><th scope="col" aria-sort={direction('latest')}>{heading('latest','Latest Follow-Up')}</th></>}<th scope="col">Account details</th></tr></thead><tbody>{rows.map(row=>{
   const hotel=text(row.hotel),accountId=text(row.accountId??row.account_id),invoiceId=text(row.invoiceId??row.invoice_id??row.transactionId??row.id),hasInvoice=detail.kind!=='payments'&&invoiceId!=='—';
   return <tr key={detailIdentity(row,detail.kind)}><td><b>{text(row.accountName??row.account_name)}</b><small>{hotel} · {text(row.accountType??row.account_type)}</small></td><td>{detail.kind==='payments'?text(row.transactionId):text(row.invoiceNo??row.invoice_no)}<small>{detail.kind==='payments'?text(row.transactionDate):'Folio '+text(row.folioNo??row.folio_no)}</small></td><td>{detail.kind==='balance'?<>{text(row.guest)}<small>{text(row.transactionDate)} · Age {text(row.age)} days</small></>:detail.kind==='sent'?<>{text(row.sent_date??row.sent_at)}<small>{text(row.stage_label??row.kind)}</small></>:detail.kind==='payment_invoices'?<>{number(row.paymentCount)} linked payments<small>{row.verified===true?'Mapping verified':'Needs verification'}</small></>:<>{text(row.transactionDate)}<small>{row.sourceStatus==='not_observed'?'Needs source verification':text(row.entryClassification??row.transfer)}</small></>}</td><td>{detail.kind==='balance'?<><b>Open {amount(row.open)}</b><small>Original {amount(row.original)}</small></>:detail.kind==='sent'?amount(row.amount):detail.kind==='payment_invoices'?amount(row.amount):detail.kind==='payments'?<><b>Posted {amount(row.amount)}</b><small>Allocated {amount(row.appliedAmount)}</small><small>Unallocated {amount(row.unallocatedAmount)}</small></>:<><b>Original {amount(row.originalAmount)}</b><small>Current open {amount(row.openAmount)}</small></>}</td>{detail.kind==='balance'&&<><td>{row.billingRequired===false?'Not required':row.billingRequired===null?'Setup needed':row.firstBillingDate?'Billed '+text(row.firstBillingDate):'Not billed'}<small>Due date {text(row.dueDate)}</small></td><td>{text(row.latestStageLabel??row.latestStage)}<small>{text(row.latestSentAt)}</small></td></>}<td><button className="dashboard-text-link" disabled={!isHotelId(hotel)||accountId==='—'} onClick={()=>onOpenInvoice(hotel,accountId,hasInvoice?invoiceId:undefined)}>Open current account</button></td></tr>;
  })}</tbody></table></div>{source.state==='ready'&&!rows.length&&<p className="dashboard-empty">No invoice records match this selection.</p>}
  {source.state==='ready'&&<footer className="dashboard-detail-pagination"><span>{number(source.data?.total)} records</span></footer>}
  {rows.length<allRows.length&&<div ref={more} role="status" className="dashboard-detail-more">Showing {rows.length} of {allRows.length} records · scroll to continue</div>}
 </section>;
}
