import {useEffect,useRef,useState} from 'react';
import {Download,FileText,Upload} from 'lucide-react';
import type {RemittanceConfig,RemittanceFile,RemittanceRecord} from './model';
import {json,RemittanceError,request} from './ui';
export default function RemittanceEvidence({record,token,config,onChange,onPending}:{record:RemittanceRecord;token:string;config:RemittanceConfig;onChange:(r:RemittanceRecord)=>void;onPending:(v:boolean)=>void}){
 const [pending,setPending]=useState<{id:string;file:File;revision:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[action,setAction]=useState<{file:RemittanceFile;restore:boolean;commandId:string;revision:number}|null>(null),[reason,setReason]=useState(''),[unknown,setUnknown]=useState(false);
 const tokenRef=useRef(token);tokenRef.current=token;const live=useRef(true),input=useRef<HTMLInputElement>(null),frozenReason=useRef('');
 useEffect(()=>{live.current=true;return()=>{live.current=false;onPending(false);};},[]);
 useEffect(()=>{onPending(!!pending||busy||!!action);},[pending,busy,action,onPending]);
 async function upload(candidate:{id:string;file:File;revision:number}){if(busy)return;setPending(candidate);setBusy(true);setError('');try{const query=new URLSearchParams({revision:String(candidate.revision),name:candidate.file.name});const result=await request<RemittanceRecord>(`/api/remittances/${record.id}/files/${candidate.id}?${query}`,tokenRef.current,{method:'POST',headers:{'Content-Type':candidate.file.type||'application/octet-stream'},body:candidate.file});if(live.current){onChange(result);setPending(null);}}catch(e){if(live.current){setError(e instanceof Error?e.message:'Evidence upload unavailable. Retry this file with its original ID.');try{const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(live.current)onChange(current);}catch{/* Retain local bytes and command for a retry. */}}}finally{if(live.current)setBusy(false);if(input.current)input.current.value='';}}
 async function download(file:RemittanceFile){setBusy(true);setError('');try{const response=await fetch(`/api/remittances/${record.id}/files/${file.id}`,{headers:{Authorization:`Bearer ${tokenRef.current}`},redirect:'error'});if(!response.ok)throw Error('Verified evidence download is unavailable. Reload the notice and retry.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){if(live.current)setError(e instanceof Error?e.message:'Download unavailable.');}finally{if(live.current)setBusy(false);}}
 async function discard(){if(!pending)return;setBusy(true);setError('');try{const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(!live.current)return;onChange(current);const saved=current.files.find(f=>f.id===pending.id&&f.state!=='removed');if(saved){setAction({file:saved,restore:false,commandId:crypto.randomUUID(),revision:current.revision});setReason('');}else setPending(null);}catch(e){if(live.current)setError(e instanceof Error?e.message:'Evidence status must be checked before removing this selection.');}finally{if(live.current)setBusy(false);}}
 async function fileStatus(){if(!action||busy||!reason.trim())return;setBusy(true);setError('');if(!unknown)frozenReason.current=reason.trim();try{const body={commandId:action.commandId,revision:action.revision,reason:frozenReason.current,confirmed:true};const result=await request<RemittanceRecord>(`/api/remittances/${record.id}/files/${action.file.id}${action.restore?'/restore':''}`,tokenRef.current,json(body,action.restore?'POST':'DELETE'));if(live.current){onChange(result);if(pending?.id===action.file.id)setPending(null);setAction(null);setUnknown(false);}}catch(e){if(live.current){setError(e instanceof Error?e.message:'Evidence change unavailable.');setUnknown(e instanceof RemittanceError&&e.uncertain);}}finally{if(live.current)setBusy(false);}}
 async function checkAction(){if(!action)return;setBusy(true);try{const result=await request<{complete:boolean}>('/api/remittances/commands/'+action.commandId,tokenRef.current);if(result.complete){const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(live.current){onChange(current);if(pending?.id===action.file.id)setPending(null);setAction(null);setUnknown(false);}}else if(live.current)setError('The original command is not confirmed. Retry the same evidence change; no new command has been created.');}catch(e){if(live.current)setError(e instanceof Error?e.message:'Original command unavailable.');}finally{if(live.current)setBusy(false);}}
 const pendingFiles=record.files.some(f=>f.state==='pending');
 return <section className="remittance-evidence"><div className="remittance-section-heading"><div><h3>Supporting evidence</h3><p>Private, verified downloads. Removing a link retains its file.</p></div><button disabled={busy||!!pending||!!action||record.state==='voided'||pendingFiles} onClick={()=>input.current?.click()}><Upload size={15}/>Add evidence</button></div><input className="sr-only" ref={input} type="file" accept=".pdf,.png,.jpg,.jpeg" aria-label="Upload remittance evidence" disabled={busy||!!pending||!!action||record.state==='voided'||pendingFiles} onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>config.maxFileBytes){setError(`This file exceeds the ${(config.maxFileBytes/1048576).toFixed(0)} MiB limit. Choose a smaller file.`);e.target.value='';return;}void upload({id:crypto.randomUUID(),file,revision:record.revision});}}/>
 <p className="remittance-note">Static PDF, PNG or JPEG · {(config.maxFileBytes/1048576).toFixed(0)} MiB per file · {config.maxFiles} active files · {(config.maxTotalFileBytes/1048576).toFixed(0)} MiB retained/reserved per notice. Removing a link frees an active-file slot; it does not free the retained-byte quota.</p>{record.files.length?<ul className="remittance-files">{record.files.map(file=><li key={file.id}><FileText size={19}/><div><strong>{file.name}</strong><small>{(file.byteCount/1024).toFixed(1)} KiB · {file.state}{file.error?' · Verification needs attention':''}</small></div>{file.state==='ready'&&<button aria-label={`Download ${file.name}`} disabled={busy||!!action} onClick={()=>download(file)}><Download size={14}/>Download</button>}<button aria-label={`${file.state==='removed'?'Restore':'Remove'} evidence ${file.name}`} disabled={busy||!!action||record.state==='voided'||!!pending&&pending.id!==file.id} onClick={()=>{setAction({file,restore:file.state==='removed',commandId:crypto.randomUUID(),revision:record.revision});setReason('');setUnknown(false);setError('');}}>{file.state==='removed'?'Restore':'Remove link'}</button></li>)}</ul>:<p className="remittance-empty">No supporting evidence attached.</p>}
 {pending&&<div className="remittance-upload-pending" role="status"><strong>{pending.file.name}</strong><p>{busy?'Uploading and verifying private bytes…':'Upload outcome is pending. Keep this file selected to retry the same upload.'}</p><button disabled={busy||!!action} onClick={()=>upload(pending)}>Retry evidence upload</button><button disabled={busy||!!action} onClick={discard}>Remove pending selection</button></div>}
 {action&&<div className="remittance-review-inline"><h4>{action.restore?'Restore evidence link':'Remove evidence link'}</h4><p>{action.file.name} · {action.restore?'Retained bytes will be verified before the link is restored.':'The record keeps a recoverable history; the stored bytes are retained.'}</p><label>Reason<textarea aria-label="Evidence change reason" rows={2} value={reason} disabled={busy||unknown} onChange={e=>setReason(e.target.value)}/></label><div>{unknown?<button disabled={busy} onClick={checkAction}>Check original evidence command</button>:<button disabled={busy} onClick={()=>setAction(null)}>Cancel evidence change</button>}<button disabled={busy||!reason.trim()} onClick={fileStatus}>{unknown?'Retry same evidence change':action.restore?'Confirm restore evidence':'Confirm remove evidence'}</button></div></div>}{error&&<p role="alert" className="remittance-error">{error}</p>}</section>;
}
