import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ExternalLink,History,RefreshCw} from 'lucide-react';
import type {RemittanceConfig,RemittanceHistory,RemittanceRecord} from './model';
import RemittanceEvidence from './RemittanceEvidence';
import {amount,dateLabel,json,Pager,RemittanceError,request} from './ui';
export const resolutionLabel=(r:RemittanceRecord['resolution'])=>({awaiting_opera:'Awaiting OPERA',linked_zero:'Linked balances zero',needs_review:'Source needs review',voided:'Voided'})[r];
export default function RemittanceDetail({record,token,config,onChange,onEdit,onClose,onOpenAccount,onBusyChange}:{record:RemittanceRecord;token:string;config:RemittanceConfig;onChange:(r:RemittanceRecord)=>void;onEdit:()=>void;onClose:()=>void;onOpenAccount?:()=>void;onBusyChange:(busy:boolean)=>void}){
 const [history,setHistory]=useState<RemittanceHistory|null>(null),[historyPage,setHistoryPage]=useState(0),[showHistory,setShowHistory]=useState(false),[historyError,setHistoryError]=useState(''),[retry,setRetry]=useState(0),[filePending,setFilePending]=useState(false),[status,setStatus]=useState<{target:'active'|'voided';command:string;revision:number}|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false);
 const tokenRef=useRef(token);tokenRef.current=token;const head=useRef<HTMLHeadingElement>(null),live=useRef(true),frozenReason=useRef('');
 useEffect(()=>{live.current=true;head.current?.focus();head.current?.scrollIntoView({block:'start'});return()=>{live.current=false;onBusyChange(false);};},[]);
 useEffect(()=>{onBusyChange(busy||filePending||!!status);},[busy,filePending,status,onBusyChange]);
 useEffect(()=>{if(!showHistory)return;const controller=new AbortController();setHistory(null);setHistoryError('');request<RemittanceHistory>(`/api/remittances/${record.id}/history?page=${historyPage}&limit=20`,token,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setHistory(v);}).catch(e=>{if(!controller.signal.aborted)setHistoryError(e instanceof Error?e.message:'History unavailable.');});return()=>controller.abort();},[token,record.id,record.revision,showHistory,historyPage,retry]);
 const pending=filePending||record.files.some(f=>f.state==='pending');
 async function applyStatus(){if(!status||busy||!reason.trim())return;setBusy(true);setError('');let statusSaved=false;if(!uncertain)frozenReason.current=reason.trim();try{await request<RemittanceRecord>(`/api/remittances/${record.id}/status`,tokenRef.current,json({commandId:status.command,revision:status.revision,status:status.target,reason:frozenReason.current,confirmed:true}));statusSaved=true;const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(live.current){onChange(current);setStatus(null);setUncertain(false);setShowHistory(true);}}catch(e){if(live.current){setError(e instanceof Error?e.message:'Status result could not be confirmed.');setUncertain(statusSaved||!(e instanceof RemittanceError)||e.uncertain);}}finally{if(live.current)setBusy(false);}}
 async function check(){if(!status)return;setBusy(true);try{const result=await request<{complete:boolean}>('/api/remittances/commands/'+status.command,tokenRef.current);if(result.complete){const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(live.current){onChange(current);setStatus(null);setUncertain(false);}}else if(live.current)setError('No completed status result is available. Keep the same command and retry; this is not proof of failure.');}catch(e){if(live.current)setError(e instanceof Error?e.message:'Status check unavailable.');}finally{if(live.current)setBusy(false);}}
 async function reload(){setBusy(true);setError('');try{const current=await request<RemittanceRecord>('/api/remittances/'+record.id,tokenRef.current);if(live.current)onChange(current);}catch(e){if(live.current)setError(e instanceof Error?e.message:'Notice unavailable.');}finally{if(live.current)setBusy(false);}}
 return <section className="remittance-detail panel"><header className="remittance-section-heading"><div><h2 ref={head} tabIndex={-1}>{record.reference}</h2><p>{record.hotel} · {record.accountName} · Account {record.accountNo??record.accountId}</p></div><button disabled={busy||pending||!!status} onClick={onClose}><ArrowLeft size={15}/>Back to records</button></header><div className="remittance-detail-actions"><span className={`remittance-state ${record.resolution}`}>{resolutionLabel(record.resolution)}</span><span>Revision {record.revision} · Received {dateLabel(record.receivedDate)}</span><button disabled={busy||pending||!!status} onClick={reload}><RefreshCw size={14}/>Reload notice</button><button disabled={busy||pending||!!status||record.state==='voided'} onClick={onEdit}>Correct notice</button><button disabled={busy||pending||!!status} onClick={()=>{setStatus({target:record.state==='voided'?'active':'voided',command:crypto.randomUUID(),revision:record.revision});setReason('');setUncertain(false);setError('');}}>{record.state==='voided'?'Restore notice':'Void notice'}</button>{onOpenAccount&&<button disabled={busy||pending||!!status} onClick={onOpenAccount}>Open current account <ExternalLink size={13}/></button>}</div>
 {pending&&<p className="remittance-warning">An evidence upload is pending. Retry or remove it before correcting or changing this notice’s status.</p>}{record.resolution==='linked_zero'&&<p className="remittance-zero-note">Every linked saved OPERA balance is verified zero. This describes source balances only; it does not prove cash received or that this notice settled the invoices.</p>}{record.resolution==='needs_review'&&<p className="remittance-warning">Some linked invoice balances are missing or unverified. They remain linked and have not been treated as zero.</p>}
 <div className="remittance-detail-totals"><div><span>Reported notice total</span><strong>{amount(record.reportedAmount)}</strong></div><div><span>Known allocations</span><strong>{amount(record.allocatedAmount)}</strong></div><div><span>Unallocated reported</span><strong>{amount(record.unallocatedAmount)}</strong></div><div><span>Linked OPERA open</span><strong>{amount(record.linkedOpen,'Unknown')}</strong>{record.unverifiedLines>0&&<small>{record.unverifiedLines} unverified · Known {amount(record.knownLinkedOpen)}</small>}</div></div>
 <dl className="remittance-record-notes"><div><dt>Source note</dt><dd>{record.sourceNote||'Not specified'}</dd></div><div><dt>Notes</dt><dd>{record.notes||'None'}</dd></div>{record.voidReason&&<div><dt>Void / restore reason</dt><dd>{record.voidReason}</dd></div>}</dl>
 <h3 className="remittance-subheading">{record.lines.length} linked invoices</h3><p className="remittance-scroll-hint">Scroll across for reported allocations and verified source balances.</p><div className="remittance-scroll" role="region" aria-label="Linked remittance invoice details" tabIndex={0}><table className="remittance-linked-lines"><thead><tr><th>Invoice No.</th><th>Folio No.</th><th>Guest</th><th>Reported allocation</th><th>Saved OPERA open</th><th>Source verified</th></tr></thead><tbody>{record.lines.map(line=><tr key={line.invoiceId}><td>{line.invoiceNo}</td><td>{line.folioNo}</td><td>{line.guest}</td><td className="remittance-number">{amount(line.reportedAmount)}</td><td className="remittance-number">{amount(line.currentOpen,'Unknown')}<small>{line.currentStatus==='zero'?'Verified zero':line.currentStatus==='open'?'Verified open':line.currentStatus==='missing'?'Missing source identity':'Not verified'}</small></td><td>{dateLabel(line.sourceVerifiedAt)}</td></tr>)}</tbody></table></div>
 <RemittanceEvidence record={record} token={token} config={config} onChange={onChange} onPending={setFilePending}/>
 {status&&<section className="remittance-review-inline" aria-label="Review notice status"><h3>{status.target==='voided'?'Void this notice':'Restore this notice'}</h3><p>{record.reference} · {record.hotel} · {record.accountName}. Evidence and history are retained. OPERA and cash balances are unchanged.</p><label>Reason<textarea aria-label="Notice status reason" rows={2} value={reason} disabled={busy||uncertain} onChange={e=>setReason(e.target.value)}/></label><div>{uncertain?<button disabled={busy} onClick={check}>Check original status command</button>:<button disabled={busy} onClick={()=>setStatus(null)}>Cancel status change</button>}<button disabled={busy||!reason.trim()} onClick={applyStatus}>{uncertain?'Retry same status change':status.target==='voided'?'Confirm void notice':'Confirm restore notice'}</button></div></section>}{error&&<p role="alert" className="remittance-error">{error}</p>}
 <section className="remittance-history"><button onClick={()=>setShowHistory(v=>!v)} aria-expanded={showHistory}><History size={15}/>{showHistory?'Hide history':'View correction history'}</button>{showHistory&&<>{historyError?<p role="alert" className="remittance-error">{historyError}<button onClick={()=>setRetry(n=>n+1)}>Retry history</button></p>:!history?<p role="status">Loading version history…</p>:<><ol>{history.rows.map(row=><li key={row.revision}><div><strong>Revision {row.revision} · {row.action.replaceAll('_',' ')}</strong><span>{dateLabel(row.recordedAt)}</span></div><p>{row.reason||'Initial record'}</p><details><summary>View saved version</summary><HistorySnapshot value={row.snapshot}/></details></li>)}</ol><Pager page={historyPage} total={history.total} limit={20} label="remittance history" onChange={setHistoryPage}/></>}</>}</section></section>;
}
function HistorySnapshot({value}:{value:unknown}){if(!value||typeof value!=='object')return <p>Version details unavailable.</p>;const v=value as Partial<RemittanceRecord>;return <div className="remittance-history-snapshot"><p>{typeof v.reference==='string'?v.reference:'Reference unavailable'} · Received {typeof v.receivedDate==='string'?dateLabel(v.receivedDate):'Unavailable'}</p><p>Reported {typeof v.reportedAmount==='string'||v.reportedAmount===null?amount(v.reportedAmount):'Not specified'}</p><p>{typeof v.notes==='string'?v.notes:''}</p>{Array.isArray(v.lines)&&<ul>{v.lines.map((l,i)=><li key={i}>{String(l.invoiceNo??l.invoiceId??'Unknown invoice')} · {typeof l.reportedAmount==='string'?amount(l.reportedAmount):'Not specified'}</li>)}</ul>}</div>;}
