import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Plus,RefreshCw,Search,ShieldCheck} from 'lucide-react';
import type {Account} from '../domain/portfolio';
import type {RemittanceDiagnostic,RemittanceList,RemittanceOptions,RemittanceRecord} from './model';
import RemittanceEditor from './RemittanceEditor';
import RemittanceDetail,{resolutionLabel} from './RemittanceDetail';
import {amount,json,Pager,request,today,dateLabel} from './ui';
import './remittance.css';
export interface RemittanceContext {hotel:string;view:'pending'|'activity'|'all';type:string;account:string;search:string;from:string;to:string;includeVoided:boolean;page:number;selectedId?:string}
interface Props {token:string;hotel:string;accounts:Account[];scope?:string;initialContext?:RemittanceContext;onContextChange:(c:RemittanceContext)=>void;onOpenAccount:(a:Account)=>void;onBusyChange:(dirty:boolean)=>void;onBack?:()=>void;diagnostic?:boolean}
export default function Remittances({token,hotel,accounts,scope,initialContext,onContextChange,onOpenAccount,onBusyChange,onBack,diagnostic=false}:Props){
 const [filters,setFilters]=useState<RemittanceContext>(()=>initialContext??{hotel,view:'pending',type:'',account:scope??'',search:'',from:today().slice(0,8)+'01',to:today(),includeVoided:false,page:0});
 const [options,setOptions]=useState<RemittanceOptions|null>(null),[optionsError,setOptionsError]=useState(''),[list,setList]=useState<RemittanceList|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selected,setSelected]=useState<RemittanceRecord|null>(null),[selectedId,setSelectedId]=useState(initialContext?.selectedId??''),[detailError,setDetailError]=useState(''),[editing,setEditing]=useState<'new'|'edit'|null>(null),[changed,setChanged]=useState(false),[loadingDetail,setLoadingDetail]=useState(false),[notice,setNotice]=useState('');
 const [diagnosticId]=useState(()=>crypto.randomUUID()),[diagnosticBusy,setDiagnosticBusy]=useState(false),[diagnosticResult,setDiagnosticResult]=useState<RemittanceDiagnostic|null>(null),[diagnosticError,setDiagnosticError]=useState('');
 const refs=useRef({onContextChange,onBusyChange});refs.current={onContextChange,onBusyChange};const previousHotel=useRef(hotel),tokenRef=useRef(token);tokenRef.current=token;
 useEffect(()=>{if(previousHotel.current===hotel)return;previousHotel.current=hotel;setFilters(f=>({...f,hotel,account:'',page:0}));setSelectedId('');setSelected(null);},[hotel]);
 useEffect(()=>{refs.current.onContextChange({...filters,selectedId:selectedId||undefined});},[filters,selectedId]);
 useEffect(()=>{refs.current.onBusyChange(changed);const warn=(e:BeforeUnloadEvent)=>{if(changed){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[changed]);
 useEffect(()=>()=>refs.current.onBusyChange(false),[]);
 useEffect(()=>{const controller=new AbortController();setOptionsError('');request<RemittanceOptions>('/api/remittances/options',token,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setOptions(v);}).catch(e=>{if(!controller.signal.aborted)setOptionsError(e instanceof Error?e.message:'Account options unavailable.');});return()=>controller.abort();},[token,retry]);
 const invalidDates=filters.view==='activity'&&(!filters.from||!filters.to||filters.from>filters.to);
 useEffect(()=>{const controller=new AbortController();setError('');setList(null);if(invalidDates)return()=>controller.abort();const query=new URLSearchParams({view:filters.view,search:filters.search,page:String(filters.page),limit:'50',includeVoided:String(filters.includeVoided)});if(filters.hotel!=='All')query.set('hotel',filters.hotel);if(filters.type)query.set('type',filters.type);if(filters.account){const [h,id]=JSON.parse(filters.account);query.set('hotel',h);query.set('accountId',id);}if(filters.view==='activity'){query.set('from',filters.from);query.set('to',filters.to);}request<RemittanceList>('/api/remittances?'+query,token,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setList(v);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Remittance data unavailable.');});return()=>controller.abort();},[token,filters,retry,invalidDates]);
 useEffect(()=>{if(!selectedId||editing)return;const controller=new AbortController();setLoadingDetail(true);setDetailError('');request<RemittanceRecord>('/api/remittances/'+selectedId,token,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setSelected(v);}).catch(e=>{if(!controller.signal.aborted)setDetailError(e instanceof Error?e.message:'Notice unavailable.');}).finally(()=>{if(!controller.signal.aborted)setLoadingDetail(false);});return()=>controller.abort();},[token,selectedId,retry,editing]);
 function filter(next:Partial<RemittanceContext>){setFilters(v=>({...v,...next,page:next.page??0}));setSelected(null);setSelectedId('');}
 function saved(r:RemittanceRecord){setSelected(r);setSelectedId(r.id);setEditing(null);setChanged(false);setNotice('Remittance record saved. Financial balances and collection timing were not changed.');setRetry(n=>n+1);}
 async function runDiagnostic(){setDiagnosticBusy(true);setDiagnosticError('');try{setDiagnosticResult(await request<RemittanceDiagnostic>('/api/remittances/diagnostic',tokenRef.current,json({commandId:diagnosticId,confirmed:true})));}catch(e){setDiagnosticError(e instanceof Error?e.message:'The synthetic test is unconfirmed. Retry the same diagnostic command.');}finally{setDiagnosticBusy(false);}}
 const allOptions=options?.accounts??[],accountOptions=allOptions.filter(a=>filters.hotel==='All'||a.hotel===filters.hotel),summary=list?.summary;
 const selectedAccount=selected?accounts.find(a=>a.hotel===selected.hotel&&a.id===selected.accountId):null;
 return <main className="page remittance-page">{onBack&&!editing&&!selectedId&&<button className="breadcrumb" onClick={onBack}><ArrowLeft size={13}/>Back to account</button>}<header className="remittance-title"><div><h1>Remittances</h1><p>Received notices, exact invoice links and supporting evidence.</p></div>{!editing&&!selectedId&&<div><button onClick={()=>setRetry(n=>n+1)}><RefreshCw size={14}/>Reload records</button><button className="primary-button" disabled={!options||!!optionsError} onClick={()=>{setEditing('new');setNotice('');}}><Plus size={16}/>Record remittance</button></div>}</header>
 {editing&&options?<RemittanceEditor key={editing==='new'?'new':selected!.id} token={token} accounts={options.accounts} record={editing==='edit'?selected??undefined:undefined} scope={filters.account||scope} onSaved={saved} onDirty={setChanged} onClose={()=>{if(window.confirm('Leave this form without saving the retained edits?')){setEditing(null);setChanged(false);}}}/>:selectedId?<>{loadingDetail&&!selected?<p role="status" className="remittance-empty">Loading this notice and its exact invoice links…</p>:selected&&options?<RemittanceDetail key={selected.id} record={selected} token={token} config={options.config} onChange={r=>{setSelected(r);setNotice('Notice updated. Its history is retained.');setRetry(n=>n+1);}} onEdit={()=>{setEditing('edit');setNotice('');}} onClose={()=>{setSelectedId('');setSelected(null);setChanged(false);}} onOpenAccount={selectedAccount?()=>onOpenAccount(selectedAccount):undefined} onBusyChange={setChanged}/>:null}{detailError&&<p role="alert" className="remittance-error">{detailError}<button onClick={()=>setRetry(n=>n+1)}>Retry notice</button><button onClick={()=>{setSelectedId('');setSelected(null);}}>Back to records</button></p>}</>:<>
 <nav className="remittance-tabs" aria-label="Remittance view">{([{key:'pending',label:'Pending'},{key:'activity',label:'Received activity'},{key:'all',label:'All records'}] as const).map(v=><button key={v.key} aria-pressed={filters.view===v.key} onClick={()=>filter({view:v.key,includeVoided:false})}>{v.label}</button>)}<span>{filters.view==='pending'?'All received dates · Open or unknown linked balances':filters.view==='activity'?'Received dates · Thailand':'Active records, including linked zero balances'}</span></nav>
 <div className="remittance-filters"><label>Account type<select aria-label="Remittance account type filter" value={filters.type} onChange={e=>filter({type:e.target.value,account:''})}><option value="">All account types</option>{[...new Set(options?.accountTypes??allOptions.map(a=>a.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Account<select aria-label="Remittance account filter" value={filters.account} onChange={e=>filter({account:e.target.value})}><option value="">All accounts</option>{accountOptions.map(a=><option key={JSON.stringify([a.hotel,a.accountId])} value={JSON.stringify([a.hotel,a.accountId])}>{a.hotel} · {a.name}</option>)}</select></label><label>Record reference<span className="remittance-search"><Search size={14}/><input aria-label="Search remittance references" value={filters.search} placeholder="Find a reference" onChange={e=>filter({search:e.target.value})}/></span></label>{filters.view==='activity'&&<><label>From · Thai date<input aria-label="Remittance from date" type="date" value={filters.from} onChange={e=>filter({from:e.target.value})}/></label><label>Through · Thai date<input aria-label="Remittance through date" type="date" value={filters.to} onChange={e=>filter({to:e.target.value})}/></label></>}{filters.view==='all'&&<label className="remittance-checkbox"><input type="checkbox" checked={filters.includeVoided} onChange={e=>filter({includeVoided:e.target.checked})}/>Include voided notices</label>}<button onClick={()=>filter({type:'',account:'',search:'',includeVoided:false})}>Clear filters</button></div>
 {optionsError&&<p role="alert" className="remittance-error">{optionsError} Account choices are unavailable.<button onClick={()=>setRetry(n=>n+1)}>Retry account options</button></p>}{invalidDates&&<p role="alert" className="remittance-error">Choose a received-date range with the start on or before the end.</p>}{error&&<p role="alert" className="remittance-error">{error} No zero totals have been inferred.</p>}
 <section className="remittance-summary" data-testid="remittance-summary" aria-label="Remittance summary"><div className="remittance-summary-accent"><span>Active notices</span><strong>{summary?.documents??'—'}</strong><small>Each notice counted once</small></div><div><span>Unique linked invoices</span><strong>{summary?.invoices??'—'}</strong><small>Deduplicated across notices</small></div><div><span>Reported notice amount</span><strong>{summary?amount(summary.reportedAmount,'Partly unspecified'):'—'}</strong><small>{summary?.unspecifiedAmounts?`${summary.unspecifiedAmounts} unspecified · Known ${amount(summary.knownReportedAmount)}`:'Reported total counted once per notice'}</small></div><div><span>Unique OPERA open</span><strong>{summary?amount(summary.linkedOpen,'Unknown'):'—'}</strong><small>{summary?.unverifiedInvoices?`${summary.unverifiedInvoices} unverified · Known ${amount(summary.knownLinkedOpen)}`:'Saved verified balances · each invoice once'}</small></div></section><p className="remittance-note">Summary excludes voided notices. Reported amounts describe notices; OPERA open describes unique invoices. Neither is a cash-collected figure.</p>
 <section className="panel remittance-records"><header className="remittance-section-heading"><h2>{filters.view==='pending'?'Notices with open or unknown balances':filters.view==='activity'?'Notices received in this period':'Remittance records'}</h2><span>{list?`${list.total} notices`:'Waiting for source data'}</span></header><p className="remittance-scroll-hint">Scroll across for invoice counts, amounts and state.</p><div className="remittance-scroll" role="region" aria-label="Remittance records table" tabIndex={0}><table><thead><tr><th>Received · Thailand</th><th>Reference / Account</th><th>Linked invoices</th><th>Reported amount</th><th>Linked OPERA open</th><th>State</th></tr></thead><tbody>{list?.rows.map(row=><tr key={row.id}><td>{dateLabel(row.receivedDate)}</td><td><button className="remittance-reference" aria-label={`Open ${row.reference}`} onClick={()=>{setSelected(null);setSelectedId(row.id);setNotice('');}}>{row.reference}</button><small>{row.hotel} · {row.accountName} · {row.accountType}</small></td><td>{row.invoiceCount}</td><td className="remittance-number">{amount(row.reportedAmount)}</td><td className="remittance-number">{amount(row.linkedOpen,'Unknown')}</td><td><span className={`remittance-state ${row.resolution}`}>{resolutionLabel(row.resolution)}</span>{row.pendingFiles>0&&<small>{row.pendingFiles} pending evidence</small>}</td></tr>)}</tbody></table></div>{!list?<p role="status" className="remittance-empty">{error?'Remittance source data is unavailable.':invalidDates?'A valid received-date range is required.':'Loading saved remittance records…'}</p>:!list.rows.length?<div className="remittance-empty"><h3>No notices match this view</h3><p>{filters.view==='pending'?'No active notices have open or unknown linked balances under these filters.':'Try a different account, reference or received-date range.'}</p></div>:null}{list&&<Pager page={filters.page} total={list.total} label="remittance" onChange={p=>filter({page:p})}/>}</section>
 {diagnostic&&<section className="remittance-diagnostic panel"><ShieldCheck size={19}/><div><h2>Synthetic connection test</h2><p>Checks isolated database commands and one private synthetic PDF. No customer account is selected and no test notice remains.</p><button disabled={diagnosticBusy||!!diagnosticResult} onClick={runDiagnostic}>{diagnosticBusy?'Checking…':diagnosticError?'Retry same diagnostic':'Run synthetic connection test'}</button>{diagnosticResult&&<p role="status">Database: {diagnosticResult.database.passed&&diagnosticResult.database.rolledBack?'passed and rolled back':'needs review'} · Storage: {diagnosticResult.storage.passed?'verified':'needs review'} · Business records changed: {diagnosticResult.businessRecordsChanged?'yes — needs review':'no'}</p>}{diagnosticError&&<p role="alert">{diagnosticError}</p>}</div></section>}
 </>}{notice&&<p className="remittance-feedback" role="status">{notice}</p>}</main>;
}
