import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,Search} from 'lucide-react';
import type {RemittanceAccount,RemittanceInput,RemittanceInvoiceList,RemittanceInvoiceOption,RemittanceRecord} from './model';
import {amountToSatang,parseAmountInput,satangToAmount} from './money';
import {amount,dateLabel,json,Pager,RemittanceError,request,today} from './ui';
interface Selected extends RemittanceInvoiceOption {allocation:string}
export default function RemittanceEditor({token,accounts,record,scope,onSaved,onClose,onDirty}:{token:string;accounts:RemittanceAccount[];record?:RemittanceRecord;scope?:string;onSaved:(record:RemittanceRecord)=>void;onClose:()=>void;onDirty:(dirty:boolean)=>void}){
 const [id]=useState(()=>record?.id??crypto.randomUUID()),[revision,setRevision]=useState(record?.revision??0),[command,setCommand]=useState(()=>crypto.randomUUID());
 const [account,setAccount]=useState(record?JSON.stringify([record.hotel,record.accountId]):scope??''),[received,setReceived]=useState(record?.receivedDate??today()),[reference,setReference]=useState(record?.reference??''),[source,setSource]=useState(record?.sourceNote??''),[notes,setNotes]=useState(record?.notes??''),[total,setTotal]=useState(record?.reportedAmount??''),[reason,setReason]=useState('');
 const [selected,setSelected]=useState<Map<string,Selected>>(()=>new Map(record?.lines.map(l=>[l.invoiceId,{...l,allocation:l.reportedAmount??'',verified:l.currentStatus==='open'||l.currentStatus==='zero',eligible:true,reason:null,transactionDate:''}])??[]));
 const [search,setSearch]=useState(''),[page,setPage]=useState(0),[rows,setRows]=useState<RemittanceInvoiceList|null>(null),[readError,setReadError]=useState(''),[retry,setRetry]=useState(0),[review,setReview]=useState(false),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false),[latest,setLatest]=useState<RemittanceRecord|null>(null),[conflict,setConflict]=useState(false);
 const tokenRef=useRef(token);tokenRef.current=token;const live=useRef(true),frozen=useRef<RemittanceInput|null>(null),head=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{live.current=true;onDirty(true);return()=>{live.current=false;onDirty(false);};},[]);
 const chosen=accounts.find(a=>JSON.stringify([a.hotel,a.accountId])===account);
 useEffect(()=>{const controller=new AbortController();setRows(null);setReadError('');if(!account)return()=>controller.abort();const [hotel,accountId]=JSON.parse(account) as string[];const query=new URLSearchParams({hotel,accountId,search,page:String(page),limit:'50'});request<RemittanceInvoiceList>('/api/remittances/invoices?'+query,token,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setRows(v);}).catch(e=>{if(!controller.signal.aborted)setReadError(e instanceof Error?e.message:'Invoice list unavailable.');});return()=>controller.abort();},[token,account,search,page,retry]);
 useEffect(()=>{head.current?.focus();},[review]);
 let parsedTotal:string|null=null,allocated=0n,validation='';try{parsedTotal=parseAmountInput(total);for(const line of selected.values()){const v=parseAmountInput(line.allocation);if(v!==null)allocated+=amountToSatang(v);}if(parsedTotal!==null&&allocated>amountToSatang(parsedTotal))validation='Known invoice allocations cannot exceed the reported total.';}catch{validation='Use a nonnegative THB amount with no commas and no more than two decimal places.';}
 const remaining=parsedTotal===null?null:satangToAmount(amountToSatang(parsedTotal)-allocated);
 const change=()=>{setAck(false);setError('');setConflict(false);};
 function build():RemittanceInput{if(!chosen&&!record)throw Error('Choose the exact hotel and account.');if(!reference.trim())throw Error('Enter a human-readable record reference.');if(!/^\d{4}-\d{2}-\d{2}$/.test(received)||received>today()||new Date(received+'T00:00:00Z').toISOString().slice(0,10)!==received)throw Error('Choose a valid received date through today in Thailand.');if(!selected.size)throw Error('Link at least one exact invoice.');if(record&&!reason.trim())throw Error('Explain this correction before reviewing it.');if(validation)throw Error(validation);const [hotel,accountId]=JSON.parse(account);return {commandId:command,revision,confirmed:true,hotel,accountId,receivedDate:received,reference:reference.trim(),sourceNote:source.trim(),notes:notes.trim(),reportedAmount:parseAmountInput(total),lines:[...selected.values()].map(l=>({invoiceId:l.invoiceId,reportedAmount:parseAmountInput(l.allocation)})),changeReason:reason.trim()};}
 async function currentAfterSave(saved:RemittanceRecord){try{const current=await request<RemittanceRecord>('/api/remittances/'+id,tokenRef.current);if(live.current)onSaved(current);}catch{if(live.current)onSaved(saved);}}
 async function save(){if(busy||!ack)return;setBusy(true);setError('');try{const body=frozen.current??build();frozen.current=body;const saved=await request<RemittanceRecord>('/api/remittances/'+id,tokenRef.current,json(body,'PUT'));if(live.current){setUncertain(false);await currentAfterSave(saved);}}catch(e){if(live.current){setError(e instanceof Error?e.message:'Save unavailable.');const unknown=e instanceof RemittanceError&&e.uncertain;setUncertain(unknown);setConflict(e instanceof RemittanceError&&e.code==='remittance_revision_conflict');if(!unknown)frozen.current=null;}}finally{if(live.current)setBusy(false);}}
 async function check(){setBusy(true);setError('');try{const result=await request<{complete:boolean;recordId?:string}>('/api/remittances/commands/'+command,tokenRef.current);if(result.complete&&result.recordId){const saved=await request<RemittanceRecord>('/api/remittances/'+result.recordId,tokenRef.current);if(live.current)onSaved(saved);}else if(live.current)setError('No completed result is available yet. This does not prove failure. Retry the same command; its ID and reviewed details are retained.');}catch(e){if(live.current)setError(e instanceof Error?e.message:'Original command unavailable.');}finally{if(live.current)setBusy(false);}}
 return <section className="remittance-editor panel" aria-label="Remittance editor"><header className="remittance-section-heading"><div><h2 ref={head} tabIndex={-1}>{review?'Review remittance':record?'Correct remittance':'Record remittance'}</h2><p>{record?'The hotel and account stay fixed. Corrections retain version history.':'One notice belongs to one hotel and one account.'}</p></div><button disabled={busy||uncertain} onClick={onClose}><ArrowLeft size={15}/>Back to records</button></header>
 {!review?<><div className="remittance-form-grid"><label>Account<select aria-label="Remittance account" value={account} disabled={!!record||busy} onChange={e=>{setAccount(e.target.value);setSelected(new Map());setPage(0);change();}}><option value="">Choose Hotel + Account</option>{accounts.map(a=><option key={JSON.stringify([a.hotel,a.accountId])} value={JSON.stringify([a.hotel,a.accountId])}>{a.hotel} · {a.name} · {a.accountNo??a.accountId}</option>)}</select>{record&&<small>{record.hotel} · {record.accountName} · {record.accountNo??record.accountId}</small>}</label><label>Received date · Thailand<input aria-label="Received date" type="date" max={today()} value={received} onChange={e=>{setReceived(e.target.value);change();}}/></label><label>Record reference<input aria-label="Record reference" maxLength={200} value={reference} onChange={e=>{setReference(e.target.value);change();}} placeholder="Customer or internal reference"/></label><label>Reported total · THB<input aria-label="Reported total · THB" inputMode="decimal" value={total} onChange={e=>{setTotal(e.target.value);change();}} placeholder="Leave blank if not specified"/></label><label className="remittance-wide">Source note<input aria-label="Source note" maxLength={4000} value={source} onChange={e=>{setSource(e.target.value);change();}} placeholder="Where this notice was received"/></label><label className="remittance-wide">Notes<textarea aria-label="Remittance notes" maxLength={4000} value={notes} onChange={e=>{setNotes(e.target.value);change();}} rows={3}/></label>{record&&<label className="remittance-wide">Correction reason<textarea aria-label="Correction reason" value={reason} maxLength={1000} onChange={e=>{setReason(e.target.value);change();}} rows={2}/></label>}</div>
 <section className="remittance-invoice-picker"><div className="remittance-section-heading"><div><h3>Link exact invoices</h3><p>Invoice number, folio and guest are separate identifiers. Zero-balance verified invoices can be linked.</p></div><label className="remittance-search"><Search size={14}/><input aria-label="Search remittance invoices" placeholder="Invoice / folio / guest" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div>{!account?<p className="remittance-empty">Choose an account to load its invoices.</p>:readError?<p role="alert" className="remittance-error">{readError}<button onClick={()=>setRetry(n=>n+1)}>Retry invoice list</button></p>:!rows?<p role="status" className="remittance-empty">Loading verified invoice identities…</p>:<><div className="remittance-scroll"><table><thead><tr><th>Link</th><th>Invoice No.</th><th>Folio No.</th><th>Guest</th><th>Saved OPERA open</th></tr></thead><tbody>{rows.rows.map(row=><tr key={row.invoiceId}><td><input type="checkbox" aria-label={`Link ${row.invoiceNo}`} checked={selected.has(row.invoiceId)} disabled={!row.eligible&&!selected.has(row.invoiceId)} onChange={e=>{setSelected(old=>{const next=new Map(old);e.target.checked?next.set(row.invoiceId,{...row,allocation:''}):next.delete(row.invoiceId);return next;});change();}}/></td><td>{row.invoiceNo}<small>{!row.eligible?row.reason:null}</small></td><td>{row.folioNo}</td><td>{row.guest}</td><td className="remittance-number">{amount(row.currentOpen,'Unverified')}</td></tr>)}</tbody></table></div>{!rows.rows.length&&<p className="remittance-empty">No invoices match this account and search.</p>}<Pager page={page} total={rows.total} label="invoice selection" onChange={setPage}/></>}</section>
 {!!selected.size&&<section className="remittance-allocations"><h3>{selected.size} selected invoices · optional reported allocations</h3><p className="remittance-note">Leave each allocation blank unless the notice specifies it. Blank amounts are unknown.</p>{[...selected.values()].map(line=><div key={line.invoiceId}><span><strong>{line.invoiceNo}</strong><small>Folio {line.folioNo} · {line.guest}</small></span><input aria-label={`Reported allocation ${line.invoiceNo}`} inputMode="decimal" placeholder="Not specified" value={line.allocation} onChange={e=>{setSelected(old=>new Map(old).set(line.invoiceId,{...line,allocation:e.target.value}));change();}}/><button aria-label={`Unlink ${line.invoiceNo}`} onClick={()=>{setSelected(old=>{const n=new Map(old);n.delete(line.invoiceId);return n;});change();}}>Unlink</button></div>)}</section>}
 </>:<div className="remittance-review"><dl><div><dt>Account</dt><dd>{record?.hotel??chosen?.hotel} · {record?.accountName??chosen?.name}<small>{record?.accountNo??chosen?.accountNo??record?.accountId??chosen?.accountId}</small></dd></div><div><dt>Received · Thailand</dt><dd>{dateLabel(received)}</dd></div><div><dt>Record reference</dt><dd>{reference}</dd></div><div><dt>Reported total</dt><dd>{amount(parsedTotal)}</dd></div><div><dt>Source</dt><dd>{source||'Not specified'}</dd></div><div><dt>Notes</dt><dd>{notes||'None'}</dd></div>{record&&<div><dt>Correction reason</dt><dd>{reason}</dd></div>}</dl><div className="remittance-scroll"><table><thead><tr><th>Invoice No.</th><th>Folio No.</th><th>Guest</th><th>Reported allocation</th></tr></thead><tbody>{[...selected.values()].map(line=><tr key={line.invoiceId}><td>{line.invoiceNo}</td><td>{line.folioNo}</td><td>{line.guest}</td><td className="remittance-number">{amount(parseAmountInput(line.allocation))}</td></tr>)}</tbody></table></div><p className="remittance-note">This records a notice only. OPERA balances, billing dates, collection stages and cash receipts remain unchanged.</p><label className="remittance-checkbox"><input type="checkbox" checked={ack} disabled={busy||uncertain} onChange={e=>setAck(e.target.checked)}/>I reviewed the account, received date, amounts and invoice links.</label></div>}
 <div className="remittance-allocation-summary"><span>Known allocations <strong>{amount(satangToAmount(allocated))}</strong></span><span>Unallocated reported amount <strong>{validation?'Check amounts':amount(remaining)}</strong></span></div>{validation&&!review&&<p role="alert" className="remittance-error">{validation}</p>}{error&&<p role="alert" className="remittance-error">{error}</p>}{conflict&&<button disabled={busy} onClick={async()=>{setBusy(true);try{setLatest(await request<RemittanceRecord>('/api/remittances/'+id,tokenRef.current));}catch(e){setError(e instanceof Error?e.message:'Current record unavailable.');}finally{setBusy(false);}}}>Load latest saved version</button>}{latest&&<div className="remittance-conflict"><h3>Saved revision {latest.revision}</h3><p>{latest.reference} · Received {dateLabel(latest.receivedDate)} · Reported {amount(latest.reportedAmount)}</p><p><strong>Saved source note:</strong> {latest.sourceNote||'Not specified'}</p><p><strong>Saved notes:</strong> {latest.notes||'None'}</p><p>Saved invoice links: {latest.lines.length}. Your retained form has {selected.size} links and will replace the saved fields and links after you review it.</p><div className="remittance-scroll" role="region" aria-label="Latest saved invoice links" tabIndex={0}><table><thead><tr><th>Invoice / exact identity</th><th>Folio No.</th><th>Saved allocation</th></tr></thead><tbody>{latest.lines.map(line=><tr key={line.invoiceId}><td><strong>{line.invoiceNo||'Invoice number not recorded'}</strong><small>{line.invoiceId}</small></td><td>{line.folioNo||'Not recorded'}</td><td className="remittance-number">{amount(line.reportedAmount)}</td></tr>)}</tbody></table></div><button disabled={busy||latest.state==='voided'||latest.files.some(f=>f.state==='pending')} onClick={()=>{setRevision(latest.revision);setCommand(crypto.randomUUID());setLatest(null);setConflict(false);setReview(false);setAck(false);setError('Your edits are retained against the latest revision. Review every field before saving.');}}>Keep my edits against revision {latest.revision}</button></div>}
 <footer className="remittance-editor-footer">{uncertain?<><button disabled={busy} onClick={check}>Check original command</button><button disabled={busy} onClick={save}>Retry same save</button></>:review?<><button disabled={busy} onClick={()=>{setReview(false);setAck(false);}}>Back to editing</button><button className="primary-button" disabled={!ack||busy||conflict} onClick={save}><Check size={15}/>{busy?'Saving…':'Confirm save remittance'}</button></>:<button className="primary-button" disabled={!!validation} onClick={()=>{try{build();setError('');setReview(true);setAck(false);}catch(e){setError(e instanceof Error?e.message:'Review your fields.');}}}>Review remittance</button>}</footer></section>;
}
