import {useEffect,useState} from 'react';
interface RetentionState {enabled:boolean;total?:number;summary?:{waiting:number;blocked:number;uncertain:number;deleted:number;deletedBytes:number};rows?:{id:string;store:string;state:string;reason:string|null;eligibleSince:string|null;dueAt:string|null;deletedAt:string|null;bytes:number}[]}
const reasons:Record<string,string>={retention_source_open:'Invoice balance is still open',retention_source_unknown:'OPERA balance needs verification',retention_source_stale:'Waiting for a fresh OPERA check',retention_pending_documents:'Document work is still pending',retention_pending_mail:'Email work is still pending',retention_held:'Invoice is held or needs review',retention_waiting:'Keeping files for one calendar month',retention_due:'Eligible at the next cleanup check',retention_outcome_unknown:'Deletion result needs verification',retention_identity_mismatch:'File identity has changed',retention_no_links:'Invoice links need review',retention_observed_absent:'File bytes deleted; history retained'};
const date=(v:string|null)=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Bangkok'}).format(new Date(v)):'—';
export default function RetentionStatus({token}:{token:string}){
 const [page,setPage]=useState(0),[reload,setReload]=useState(0),[data,setData]=useState<RetentionState|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');void(async()=>{try{const r=await fetch('/api/operations/retention?page='+page,{headers:{Authorization:'Bearer '+token},signal:controller.signal});const v:unknown=await r.json();if(!r.ok||!v||typeof v!=='object'||!('enabled'in v)||typeof v.enabled!=='boolean')throw Error();if(!controller.signal.aborted)setData(v as RetentionState);}catch{if(!controller.signal.aborted)setError('File-retention status is unavailable. No deletion result has been assumed.');}})();return()=>controller.abort();},[token,page,reload]);
 return <section className="panel storage-controls" aria-labelledby="retention-title"><header><div><h2 id="retention-title">Completed-file retention</h2><p>Keep files for one calendar month after all linked invoices are verified as zero in OPERA and document/email work is complete.</p></div><button onClick={()=>setReload(n=>n+1)}>Check status</button></header>{error&&<p role="alert" className="error-message">{error}</p>}{!data&&!error&&<p role="status">Loading retention status…</p>}{data?.enabled===false&&<p>Automatic cleanup is awaiting activation.</p>}{data?.enabled&&<><p className="information-note">Checks run after a full OPERA refresh. Reopened invoices, pending work, holds and uncertain source data prevent deletion. Only app-owned file bytes in Supabase and Drive are removed; billing, sending and invoice history stay available.</p><p>{data.summary?.waiting} waiting · {data.summary?.blocked} protected or waiting for verification · {data.summary?.uncertain} results to verify · {data.summary?.deleted} files deleted</p>{!data.rows?.length?<p>No tracked files on this page.</p>:<ul className="storage-pending">{data.rows.map(row=><li key={row.id}><span><strong>{row.store==='supabase'?'Supabase working file':'Drive archive'}</strong><small>{reasons[row.reason??'']??'File requires a verified cleanup decision'}</small><small>Reference {row.id.slice(0,8)} · {(row.bytes/1048576).toFixed(2)} MiB</small></span><span>{row.state==='deleted'?'Deleted '+date(row.deletedAt):row.dueAt?'Keep through '+date(row.dueAt):'Protected'}<small>Completed {date(row.eligibleSince)}</small></span></li>)}</ul>}<nav aria-label="Retention pages"><button disabled={page===0} onClick={()=>setPage(n=>n-1)}>Previous</button><span> Page {page+1} · {data.total} files </span><button disabled={(page+1)*50>=(data.total??0)} onClick={()=>setPage(n=>n+1)}>Next</button></nav></>}</section>;
}
