import {useCallback,useEffect,useRef,useState} from 'react';
import './storage-operations.css';
interface Status {enabled:boolean;activatedAt?:string;blocked?:boolean;active?:number;unresolved?:number;chargedEgress?:number;limits?:{storedBytes:number;egressBytes:number;databaseBytes:number;safetyPercent:number};measurement?:{periodStart:string;periodEnd:string;used:{storedBytes:number|null;databaseBytes:number|null};observedAt:{storedBytes:string|null;databaseBytes:string|null}};pendingUploads?:{id:string;byteCount:number;createdAt:string;originFinished:boolean}[]}
function statusResponse(v:unknown):Status{if(!v||typeof v!=='object'||!('enabled'in v)||typeof v.enabled!=='boolean')throw Error('operations_unavailable');return v as Status;}
function errorCode(v:unknown){return v&&typeof v==='object'&&'error'in v&&typeof v.error==='string'?v.error:'operations_unavailable';}
const amount=(v:number|null|undefined)=>v==null?'Unavailable':new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(v<1048576?v/1024:v/1048576)+(v<1048576?' KiB':' MiB');
const stamp=(s:string|undefined|null)=>s?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'}).format(new Date(s))+' ICT':'Unavailable';
function message(code:string){return ({budget_storage_exceeded:'Working-file storage has reached the app allowance. Eligible files must be cleaned up before new uploads.',budget_egress_exceeded:'Managed file downloads have reached this month’s app allowance.',budget_database_exceeded:'The database has reached the app allowance. New writes are paused for review.',budget_concurrency_exceeded:'Other uploads are still in progress. Check unconfirmed uploads before starting more.',storage_object_unavailable:'The uploaded object could not be verified. Its reservation is retained; no duplicate upload was started.',storage_upload_uncertain:'The upload is still unconfirmed. No duplicate upload was started.',storage_object_changed:'Stored bytes differ from the original receipt. The file needs review.'} as Record<string,string>)[code]??'Storage controls are unavailable. Retry to check the actual status.';}
export default function StorageOperations({token}:{token:string}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const current=useRef(token);current.current=token;
 const load=useCallback(async(signal?:AbortSignal)=>{setBusy(true);setError('');try{const r=await fetch('/api/operations/status',{headers:{Authorization:'Bearer '+token},signal});const v=await r.json();if(!r.ok)throw Error(errorCode(v));if(current.current===token&&!signal?.aborted)setStatus(statusResponse(v));}catch(e){if(current.current===token&&!signal?.aborted)setError(message(e instanceof Error?e.message:''));}finally{if(current.current===token&&!signal?.aborted)setBusy(false);}},[token]);
 useEffect(()=>{const controller=new AbortController();setStatus(null);setNotice('');void load(controller.signal);return()=>controller.abort();},[load]);
 async function reconcile(id:string){setBusy(true);setError('');setNotice('');try{const r=await fetch(`/api/operations/uploads/${id}/reconcile`,{method:'POST',headers:{Authorization:'Bearer '+token}});const v=await r.json();if(!r.ok)throw Error(errorCode(v));if(current.current===token){setNotice('The exact uploaded bytes were verified. No new upload was sent.');await load();}}catch(e){if(current.current===token)setError(message(e instanceof Error?e.message:''));}finally{if(current.current===token)setBusy(false);}}
 const m=status?.measurement,l=status?.limits;
 return <section className="panel storage-controls" aria-labelledby="storage-controls-title"><header><div><h2 id="storage-controls-title">Working files & usage</h2><p>Private Supabase files and the app’s transfer allowance.</p></div><button disabled={busy} onClick={()=>void load()}>{busy?'Checking…':'Check usage'}</button></header>{error&&<p className="error-message" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!status&&!error&&<p role="status">Loading storage controls…</p>}{status?.enabled===false&&<p>Usage controls are awaiting activation. No usage is assumed to be zero.</p>}{status?.enabled&&<>{status.blocked&&<p className="error-message">New file operations are paused for a usage review.</p>}<div className="storage-meters">{[{label:'Stored working files',used:m?.used.storedBytes,cap:l?.storedBytes,note:'Measured '+stamp(m?.observedAt.storedBytes)},{label:'Managed file transfers',used:status.chargedEgress,cap:l?.egressBytes,note:'App month ends '+stamp(m?.periodEnd)},{label:'Logical database',used:m?.used.databaseBytes,cap:l?.databaseBytes,note:'Measured '+stamp(m?.observedAt.databaseBytes)}].map(item=><div key={item.label}><h3>{item.label}</h3><strong>{amount(item.used)}</strong><span> / {amount(item.cap)}</span><small>{item.note}</small></div>)}</div><p className="information-note">{l?.safetyPercent}% of each allowance is reserved as headroom. Transfers are conservatively counted from {stamp(status.activatedAt)}. Authentication, non-file API traffic and earlier usage are outside this meter; these figures are not the total Supabase bill.</p><p>{status.active} active upload reservations · {status.unresolved} unconfirmed uploads</p>{!!status.pendingUploads?.length&&<><h3>Unconfirmed uploads</h3><p>Check the stored file against its original receipt. Checking never sends another upload or discards its reserved space.</p><ul className="storage-pending">{status.pendingUploads.map(row=><li key={row.id}><span>{stamp(row.createdAt)} · {amount(row.byteCount)}<small>Reference {row.id.slice(0,8)}</small></span><button disabled={busy} onClick={()=>void reconcile(row.id)}>Check uploaded file</button></li>)}</ul></>}</>}</section>;
}
