import type {RefreshEnv} from '../refresh/backend';
import {boundedBody} from '../email/shared';
import {checkedException,exceptionId,exceptionPage,exceptionScope,parseExceptionCommand,type ExceptionScope,type ExceptionHistory} from './exceptions';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const errors:Record<string,number>={exception_invalid:400,exception_reason_required:400,exception_forbidden:403,exception_missing:404,exception_revision_conflict:409,exception_command_conflict:409,exception_state_conflict:409,exception_source_unverified:409,exception_request_too_large:413,exception_unavailable:503,unauthorized:401,forbidden:403,not_found:404,method_not_allowed:405};
async function input(request:Request){if(request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')throw Error('exception_invalid');try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedBody(request,65536)));}catch(e){throw Error(e instanceof Error&&e.message==='email_too_large'?'exception_request_too_large':'exception_invalid');}}
async function rpc(env:RefreshEnv,name:string,args:Record<string,unknown>){if(!env.SUPABASE_URL||!env.SUPABASE_SECRET_KEY)throw Error('exception_unavailable');const base=new URL(env.SUPABASE_URL);if(base.protocol!=='https:'||base.username||base.password||base.pathname!=='/'||base.search||base.hash)throw Error('exception_unavailable');const response=await fetch(`${base.origin}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(args),redirect:'manual',signal:AbortSignal.timeout(20000)});if(!response.ok){await response.body?.cancel();throw Error('exception_unavailable');}const value=JSON.parse(new TextDecoder().decode(await boundedBody(response,8*1024*1024)));if(value&&typeof value==='object'&&typeof value.error==='string')throw Error(Object.hasOwn(errors,value.error)?value.error:'exception_unavailable');return value as unknown;}
const object=(v:unknown)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('exception_unavailable');return v as Record<string,unknown>;};
const nonnegative=(v:unknown)=>{if(!Number.isSafeInteger(v)||Number(v)<0)throw Error('exception_unavailable');return Number(v);};
function history(value:unknown,scope:ExceptionScope):ExceptionHistory{const v=object(value);if(!Array.isArray(v.rows))throw Error('exception_unavailable');return {total:nonnegative(v.total),rows:v.rows.map(item=>{const r=object(item);if(typeof r.action!=='string'||typeof r.reason!=='string'||typeof r.recordedAt!=='string')throw Error('exception_unavailable');let transition=null;if(r.transition!==null){const t=object(r.transition);if(typeof t.fromOpen!=='string'||typeof t.toOpen!=='string'||![t.fromOpen,t.toOpen].every(s=>/^-?(0|[1-9][0-9]*)\.[0-9]{2}$/.test(s)))throw Error('exception_unavailable');transition={fromOpen:t.fromOpen,toOpen:t.toOpen};}return {revision:nonnegative(r.revision),action:r.action,reason:r.reason,recordedAt:r.recordedAt,snapshot:checkedException(r.snapshot,scope),transition};})};}
/** Root Worker validates the allowlisted session first; SQL independently checks p_actor. */
export async function invoiceExceptionsApi(request:Request,env:RefreshEnv,actor:string):Promise<Response>{try{
 try{actor=exceptionId(actor);}catch{throw Error('unauthorized');}const url=new URL(request.url),origin=request.headers.get('Origin');if(request.method!=='GET'&&(origin!==null&&origin!==url.origin||request.headers.get('Sec-Fetch-Site')==='cross-site'))throw Error('forbidden');
 if(!url.pathname.startsWith('/api/invoice-exceptions/'))throw Error('not_found');let parts:string[];try{parts=url.pathname.slice('/api/invoice-exceptions/'.length).split('/').map(decodeURIComponent);}catch{throw Error('exception_invalid');}
 if(parts.length===2&&parts[0]==='commands'){if(request.method!=='GET')throw Error('method_not_allowed');if(url.searchParams.size)throw Error('exception_invalid');const result=object(await rpc(env,'ar_invoice_exception_command_get',{p_actor:actor,p_command:exceptionId(parts[1])}));if(result.complete===false)return json({complete:false});if(result.complete!==true)throw Error('exception_unavailable');let scope:ExceptionScope;try{scope=exceptionScope(result.hotel,result.accountId,result.invoiceId);}catch{throw Error('exception_unavailable');}return json({complete:true,...scope,revision:nonnegative(result.revision)});}
 if(parts.length!==3&&!(parts.length===4&&parts[3]==='history'))throw Error('not_found');const scope=exceptionScope(parts[0],parts[1],parts[2]),args={p_actor:actor,p_hotel:scope.hotel,p_account_id:scope.accountId,p_invoice_id:scope.invoiceId};
 if(parts.length===4){if(request.method!=='GET')throw Error('method_not_allowed');const q=exceptionPage(url.searchParams);return json(history(await rpc(env,'ar_invoice_exception_history',{...args,p_offset:q.offset,p_limit:q.limit}),scope));}
 if(!['GET','POST'].includes(request.method))throw Error('method_not_allowed');if(url.searchParams.size)throw Error('exception_invalid');const result=await rpc(env,request.method==='GET'?'ar_invoice_exception_get':'ar_invoice_exception_command',{...args,...(request.method==='POST'?{p_input:parseExceptionCommand(await input(request))}:{})});if(result===null)throw Error('exception_missing');return json(checkedException(result,scope));
 }catch(e){const code=e instanceof Error&&Object.hasOwn(errors,e.message)?e.message:'exception_unavailable';return json({error:code},errors[code]);}}
