import {acceptanceRpc} from '../acceptance/routing';
import type {RefreshEnv} from '../refresh/backend';
import {boundedBody} from '../email/shared';
import {exceptionId,exceptionPage} from './exceptions';
import {parseCollectionPolicy,parsePolicyCommand,stageSnapshot,type CollectionPolicy,type StageSnapshot} from '../../src/domain/collection-policy';
const errors:Record<string,number>={policy_invalid:400,policy_forbidden:403,policy_missing:404,policy_revision_conflict:409,policy_command_conflict:409,policy_retirement_required:409,policy_unavailable:503,policy_request_too_large:413,unauthorized:401,forbidden:403,not_found:404,method_not_allowed:405};
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const unavailable=():never=>{throw Error('policy_unavailable');};
const object=(v:unknown)=>{if(!v||typeof v!=='object'||Array.isArray(v))return unavailable();return v as Record<string,unknown>;};
const count=(v:unknown,min=0)=>{if(!Number.isSafeInteger(v)||Number(v)<min)return unavailable();return Number(v);};
async function rpc(env:RefreshEnv,name:string,args:Record<string,unknown>){const routed=acceptanceRpc(env,name,args);if(!env.SUPABASE_URL||!env.SUPABASE_SECRET_KEY)return unavailable();const base=new URL(env.SUPABASE_URL);if(base.protocol!=='https:'||base.username||base.password||base.pathname!=='/'||base.search||base.hash)return unavailable();const r=await fetch(`${base.origin}/rest/v1/rpc/${routed.name}`,{method:'POST',headers:{apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(routed.args),redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok){await r.body?.cancel();return unavailable();}const v=JSON.parse(new TextDecoder().decode(await boundedBody(r,8*1024*1024)));if(v&&typeof v==='object'&&typeof v.error==='string')throw Error(Object.hasOwn(errors,v.error)?v.error:'policy_unavailable');return v as unknown;}
function checked(v:unknown):CollectionPolicy{try{return parseCollectionPolicy(v);}catch{return unavailable();}}
export async function readCollectionPolicy(env:RefreshEnv,actor:string,version:number|null=null):Promise<CollectionPolicy>{return checked(await rpc(env,'ar_collection_policy_get',{p_actor:exceptionId(actor),p_version:version}));}
/** Preflight only. Atomic SQL claim repeats version/stage validation under the policy-head lock. */
export async function readPolicyForHandoff(env:RefreshEnv,actor:string,stage:string,reviewedVersion?:number):Promise<StageSnapshot>{const policy=await readCollectionPolicy(env,actor);if(reviewedVersion!==policy.version&&!(reviewedVersion===undefined&&policy.version===1))throw Error('email_policy_revision_conflict');try{return stageSnapshot(policy,stage);}catch{throw Error('email_stage_required');}}
export async function collectionPolicyApi(request:Request,env:RefreshEnv,actor:string){try{
 try{actor=exceptionId(actor);}catch{throw Error('unauthorized');}const u=new URL(request.url),origin=request.headers.get('Origin');if(request.method!=='GET'&&(origin!==null&&origin!==u.origin||request.headers.get('Sec-Fetch-Site')==='cross-site'))throw Error('forbidden');
 if(u.pathname==='/api/collection-policy'){
  if(!['GET','PUT'].includes(request.method))throw Error('method_not_allowed');
  if(request.method==='GET'){let version:number|null=null;for(const k of u.searchParams.keys())if(k!=='version'||u.searchParams.getAll(k).length!==1)throw Error('policy_invalid');if(u.searchParams.has('version')){const raw=u.searchParams.get('version')!;if(!/^[1-9][0-9]*$/.test(raw)||!Number.isSafeInteger(Number(raw))||Number(raw)>2147483647)throw Error('policy_invalid');version=Number(raw);}return json(await readCollectionPolicy(env,actor,version));}
  if(u.searchParams.size||request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json')throw Error('policy_invalid');let v:unknown;try{v=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedBody(request,65536)));}catch(e){throw Error(e instanceof Error&&e.message==='email_too_large'?'policy_request_too_large':'policy_invalid');}return json(checked(await rpc(env,'ar_collection_policy_save',{p_actor:actor,p_input:parsePolicyCommand(v)})));
 }
 if(u.pathname==='/api/collection-policy/history'){if(request.method!=='GET')throw Error('method_not_allowed');let q:{offset:number;limit:number};try{q=exceptionPage(u.searchParams);}catch{throw Error('policy_invalid');}const v=object(await rpc(env,'ar_collection_policy_history',{p_actor:actor,p_offset:q.offset,p_limit:q.limit}));if(!Array.isArray(v.rows))return unavailable();return json({total:count(v.total),rows:v.rows.map(item=>{const r=object(item);if(typeof r.reason!=='string'||typeof r.recordedAt!=='string')return unavailable();return {...checked({version:r.version,rounds:r.rounds}),reason:r.reason,recordedAt:r.recordedAt};})});}
 const command=/^\/api\/collection-policy\/commands\/([^/]+)$/.exec(u.pathname);if(command){if(request.method!=='GET')throw Error('method_not_allowed');if(u.searchParams.size)throw Error('policy_invalid');let id:string;try{id=exceptionId(command[1]);}catch{throw Error('policy_invalid');}const v=object(await rpc(env,'ar_collection_policy_command_get',{p_actor:actor,p_command:id}));if(v.complete===false)return json({complete:false});if(v.complete!==true)return unavailable();return json({complete:true,version:count(v.version,1)});}
 throw Error('not_found');
 }catch(e){const code=e instanceof Error&&Object.hasOwn(errors,e.message)?e.message:'policy_unavailable';return json({error:code},errors[code]);}}
