import {useEffect,useRef,useState} from 'react';
import {calendarAdd,thaiToday} from '../domain/collection';
import {formatAmount} from '../remittance/money';
import type {FinancialReport,FinancialView,FinancialAccountOption,FinancialInvoiceReportRow,FinancialPaymentReportRow,FinancialApplicationReportRow,FinancialCoverageRow} from '../../worker/financial/model';
import './financial-reports.css';
type View=Exclude<FinancialView,'options'>;
type Run={id:string;hotel:string;from:string;to:string;status:string;finishedAt:string|null;error:string|null;accounts:number};
const labels:Record<View,string>={invoice_entries:'Invoice entries',payments:'OPERA payments',applications:'Invoice applications',coverage:'Coverage'};
const amount=(value:string|null|undefined)=>value==null?'—':formatAmount(value);
const stamp=(value:string|null|undefined)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'}):'Not recorded';
export interface FinancialReportContext {view:View;from:string;to:string;type:string;account:string}
export default function FinancialReports({token,hotel,onBack,initialContext}:{token:string;hotel:string;onBack:()=>void;initialContext?:FinancialReportContext}){
 const [view,setView]=useState<View>(initialContext?.view??'payments'),[from,setFrom]=useState(initialContext?.from??calendarAdd(thaiToday(),-30)),[to,setTo]=useState(initialContext?.to??thaiToday()),[type,setType]=useState(initialContext?.type??''),[account,setAccount]=useState(initialContext?.account??''),[page,setPage]=useState(0),[revision,setRevision]=useState(0);
 const [options,setOptions]=useState<FinancialAccountOption[]>([]),[data,setData]=useState<FinancialReport|null>(null),[status,setStatus]=useState<{enabled:boolean;running:boolean;runs:Run[]}|null>(null),[error,setError]=useState(''),[optionsError,setOptionsError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const auth=useRef(token);auth.current=token;const pending=useRef<{key:string;ids:Record<string,string>}|null>(null),previousHotel=useRef(hotel),alive=useRef(true),opened=useRef<string|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function read<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(path,{...init,headers:{Authorization:`Bearer ${auth.current}`,...init.headers}});if(!response.ok)throw Error(response.status===401||response.status===403?'Your session cannot access financial history.':'Financial history is unavailable. The last successful publication is retained.');return response.json() as Promise<T>;}
 useEffect(()=>{if(previousHotel.current!==hotel){previousHotel.current=hotel;setAccount('');setPage(0);}},[hotel]);
 useEffect(()=>{const controller=new AbortController();setOptionsError('');void(async()=>{const all:FinancialAccountOption[]=[];for(let page=0;;page++){const q=new URLSearchParams({page:String(page),limit:'200'});if(hotel!=='All')q.set('hotel',hotel);const result=await read<FinancialReport>('/api/financial/options?'+q,{signal:controller.signal});if(!Array.isArray(result.rows)||!Number.isSafeInteger(result.total)||!result.rows.length&&all.length<result.total)throw Error('Account options are incomplete.');all.push(...result.rows as FinancialAccountOption[]);if(all.length>=result.total)break;}if(!controller.signal.aborted)setOptions(all);})().catch(e=>{if(!controller.signal.aborted)setOptionsError(e instanceof Error?e.message:'Account options are unavailable.');});return()=>controller.abort();},[hotel,revision]);
 const sourceDateLabel=view==='payments'?'OPERA payment date':view==='coverage'?'source period':'OPERA invoice date';
 const invalid=!from||!to||from>to||(Date.parse(to)-Date.parse(from))/86400000>=366;
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');if(invalid)return()=>controller.abort();const q=new URLSearchParams({from,to,page:String(page),limit:'50'});if(hotel!=='All')q.set('hotel',hotel);if(type)q.set('type',type);if(account){try{const [h,a]=JSON.parse(account);if(hotel!=='All'&&h!==hotel)return()=>controller.abort();q.set('hotel',h);q.set('account',a);}catch{return()=>controller.abort();}}void read<FinancialReport>(`/api/financial/${view}?${q}`,{signal:controller.signal}).then(result=>{if(!Array.isArray(result.rows)||!result.summary||!result.coverage)throw Error('Financial response is incomplete.');if(!controller.signal.aborted)setData(result);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Financial history is unavailable.');});return()=>controller.abort();},[view,hotel,account,type,from,to,page,revision,invalid]);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;let lastRun='';const refresh=async()=>{try{const next=await read<{enabled:boolean;running:boolean;runs:Run[]}>('/api/financial/status',{signal:controller.signal});if(controller.signal.aborted)return;if(!Array.isArray(next.runs))throw Error();setStatus(next);const marker=next.runs.map(r=>r.id+':'+r.status).join('|');if(lastRun&&lastRun!==marker&&!next.running)setRevision(n=>n+1);lastRun=marker;if(next.running)timer=setTimeout(refresh,15000);}catch{if(!controller.signal.aborted)setStatus(null);}};void refresh();return()=>{controller.abort();clearTimeout(timer);};},[revision]);
 async function refreshSource(reason:'backfill'|'open'='backfill'){
  if(busy||invalid)return;const key=JSON.stringify([hotel,from,to,reason]);if(pending.current?.key!==key)pending.current={key,ids:{}};setBusy(true);setNotice('');setError('');
  try{for(const h of hotel==='All'?['KAT','TSK']:[hotel]){const commandId=pending.current.ids[h]??crypto.randomUUID();pending.current.ids[h]=commandId;await read('/api/financial/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId,hotel:h,reason,from,to})});}if(alive.current){pending.current=null;setNotice('History refresh requested. Previously verified data remains available while OPERA is read.');setRevision(n=>n+1);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Refresh could not be confirmed. Retry the same request.');}finally{if(alive.current)setBusy(false);}
 }
 useEffect(()=>{if(status?.enabled&&opened.current!==hotel&&!invalid){opened.current=hotel;void refreshSource('open');}},[status?.enabled,hotel]);
 function change(action:()=>void){action();setPage(0);}
 const summary=data?.summary,payments=summary?.paymentTotals;
 const metrics=view==='payments'?[
  ['Recorded OPERA payment credits',amount(payments?.creditPostings),'OPERA payment dates in this range'],['Currently applied',amount(payments?.currentlyApplied),'Allocation state of those payments'],['Currently unallocated',amount(payments?.currentlyUnallocated),'Remaining credit in those payments'],['Debit payment postings',amount(payments?.debitPostings),'Kept separate from credit postings']
 ]:view==='invoice_entries'?[
  ['Invoice records',data?.coverage.complete?String(summary?.invoiceCount??0):'—','Ordinary, verified source records'],['Original invoice amount',amount(summary?.amount),'Original value for this invoice-date range'],['Unknown amounts / status',data?String(summary?.unknownAmounts??0):'—','Excluded from a confirmed total'],['Not observed again',data?String(summary?.notObserved??0):'—','Previous amount is retained for review']
 ]:[['Current applied amount',amount(summary?.amount),'Current applications for this invoice-date range'],['Linked invoices',data?.coverage.complete?String(summary?.invoiceCount??0):'—','Distinct invoice identities'],['Linked payments',data?.coverage.complete?String(summary?.paymentCount??0):'—','Distinct payment identities'],['Unknown amount / status',data?String(summary?.unknownAmounts??0):'—','No invented application dates']];
 return <main className="page financial-reports"><button onClick={onBack}>Back to Reports</button><header className="financial-title"><div><h1>OPERA financial history</h1><p>Source dates, current allocations and publication coverage</p></div><div><button disabled={busy||invalid||!status?.enabled} onClick={()=>refreshSource()}>{busy?'Requesting…':'Refresh date range from OPERA'}</button><button onClick={()=>setRevision(n=>n+1)}>Reload saved history</button></div></header>
  <nav aria-label="Financial report views">{(Object.keys(labels) as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>change(()=>setView(v))}>{labels[v]}</button>)}</nav>
  <div className="financial-filters"><label>From · {sourceDateLabel}<input type="date" value={from} onChange={e=>change(()=>setFrom(e.target.value))}/></label><label>Through · {sourceDateLabel}<input type="date" value={to} onChange={e=>change(()=>setTo(e.target.value))}/></label><label>Account type<select aria-label="Account type" value={type} onChange={e=>change(()=>{setType(e.target.value);setAccount('');})}><option value="">All account types</option>{[...new Set(options.map(o=>o.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Account<select aria-label="Account" value={account} onChange={e=>change(()=>setAccount(e.target.value))}><option value="">All accounts</option>{options.filter(o=>!type||o.type===type).map(o=><option key={o.hotel+':'+o.accountId} value={JSON.stringify([o.hotel,o.accountId])}>{o.hotel} · {o.name}</option>)}</select></label></div>
  {invalid&&<p role="alert">Choose a source-date range of 1–366 days.</p>}{optionsError&&<p className="information-note">{optionsError}</p>}{status===null&&<p className="information-note">Refresh status is unavailable.</p>}{status&&!status.enabled&&<p className="information-note">Financial history ingestion is not enabled yet.</p>}{status?.running&&<p role="status">OPERA history refresh is running. Complete results will be published together.</p>}{notice&&<p role="status">{notice}</p>}{error&&<p className="error-message" role="alert">{error}</p>}
  {data&&!data.coverage.complete&&view!=='coverage'&&<p className="information-note" role="status">Coverage is incomplete for this range. Observed rows remain visible; an unverified total is shown as —.</p>}
  {view!=='coverage'&&<section className="financial-metrics">{metrics.map(([label,value,note])=><article className="panel" key={label}><small>{label}</small><strong>{value}</strong><p>{note}</p></article>)}</section>}
  {(view==='applications'||view==='invoice_entries')&&!!summary?.mappingUnverified&&<p className="information-note">Applications could not be verified for {summary.mappingUnverified} invoices. Their source invoice and payment records remain available. Review the status in Invoice entries; missing application data is not zero.</p>}
  <p className="financial-basis">{view==='payments'?'Credits display as positive in the summary. Detail rows retain OPERA signs. Applied and unallocated amounts are current balances for this payment-date cohort.':view==='applications'?'These are current applications for invoices dated in this range. The API does not provide an application event date.':view==='invoice_entries'?'Entry dates come from OPERA. Import time is not counted as a new invoice date.':'Each publication records its exact Hotel and source-date coverage.'}</p>
  {view==='payments'&&payments&&<p className="financial-basis">Transfer-flagged postings: {payments.transferRows} · Transfer status not supplied: {payments.unknownTransferRows}. Debit postings are not labelled as confirmed cancellations without a reversal link.</p>}
  {view==='invoice_entries'&&summary&&<p className="financial-basis">Compression children: {summary.compressedChildren} · Opening balances: {summary.openingBalances} · Credit records: {summary.credits}. These stay visible with their source classification.</p>}
  <section className="panel financial-list"><header><h2>{labels[view]}</h2><span>{data?`${data.total} saved rows`:error?'Source data unavailable':'Loading source data…'}</span></header><div className="financial-table-scroll" role="region" aria-label="Financial source records" tabIndex={0}><table><thead><tr>{(view==='coverage'?['Hotel','Source range','Published','Accounts','Records','Coverage']:['Source date','Hotel / Account','Identity','Source amounts','Observation / status']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data?.rows.map((raw,index)=>{
   if(view==='coverage'){const row=raw as FinancialCoverageRow;return <tr key={row.id}><td>{row.hotel}</td><td>{row.from} → {row.to}</td><td>{stamp(row.publishedAt)}</td><td>{row.accounts}</td><td>{row.invoices} invoices · {row.payments} payments</td><td>{row.periodComplete?'Complete':'Needs review'}{row.initialImport&&<small>Initial import</small>}</td></tr>;}
   const row=raw as FinancialInvoiceReportRow|FinancialPaymentReportRow|FinancialApplicationReportRow;
   const invoice=view==='invoice_entries'?row as FinancialInvoiceReportRow:null,payment=view==='payments'?row as FinancialPaymentReportRow:null,application=view==='applications'?row as FinancialApplicationReportRow:null;
   return <tr key={`${row.hotel}:${row.accountId}:${invoice?.transactionId??payment?.transactionId??application?.invoiceTransactionId}:${application?.paymentTransactionId??index}`}><td>{invoice?.transactionDate??payment?.transactionDate??application?.invoiceTransactionDate??'Date unavailable'}</td><td><b>{row.accountName}</b><small>{row.hotel} · {row.accountType} · {row.accountNo??row.accountId}</small></td><td>{invoice?<>Invoice {invoice.invoiceNo??invoice.transactionId}<small>Folio {invoice.folioNo??'Not supplied'} · {invoice.entryClassification}</small></>:payment?<>Payment {payment.transactionId}<small>Code {payment.transactionCode??'Not supplied'} · transfer: {payment.transfer}</small></>:<>Invoice {application?.invoiceNo??application?.invoiceTransactionId}<small>Payment {application?.paymentTransactionId}</small></>}</td><td>{invoice?<><b>Original {amount(invoice.originalAmount)}</b><small>Current open {amount(invoice.openAmount)}</small><small>{invoice.collectionRole}</small>{invoice.mappingError&&<small>Applications unavailable · {invoice.mappingError.replace('financial_mapping_','').replaceAll('_',' ')}</small>}</>:payment?<><b>Posted {amount(payment.amount)}</b><small>Applied {amount(payment.appliedAmount)}</small><small>Unallocated {amount(payment.unallocatedAmount)}</small></>:<><b>Applied {amount(application?.appliedAmount)}</b><small>Application date not supplied</small></>}</td><td><b>{row.sourceStatus==='observed'?'Observed':'Needs review · not observed'}</b><small>Checked {stamp(row.lastCheckedAt)}</small></td></tr>;
  })}</tbody></table></div>{data&&!data.rows.length&&<div className="financial-empty">{data.coverage.complete?'No source records match this range.':'No verified financial history is available for this range yet.'}</div>}{!data&&!error&&!invalid&&<p className="financial-empty" role="status">Loading financial history…</p>}{data&&<footer><span>Page {page+1} · Latest publication {stamp(data.coverage.lastSuccessAt)}</span><div><button disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous financial page</button><button disabled={(page+1)*50>=data.total} onClick={()=>setPage(n=>n+1)}>Next financial page</button></div></footer>}</section>
  {status&&<section className="panel financial-runs"><h2>Recent refreshes</h2>{status.runs.slice(0,4).map(run=><p key={run.id}>{run.hotel} · {run.from} → {run.to} · {run.status}{run.error?' · '+run.error.replaceAll('_',' '):''}</p>)}{!status.runs.length&&<p>No history refresh has been recorded.</p>}</section>}
 </main>;
}
