import {useEffect,useRef,useState} from 'react';
import {calendarAdd,thaiToday} from '../domain/collection';
import {formatAmount} from '../remittance/money';
import type {Account} from '../domain/portfolio';
import './observation-reports.css';
type View='daily_ar'|'balance_observations'|'timing';
export type ObservationContext={hotel:string;view:View;type:string;account:string;from:string;to:string;over60:boolean;page:number};
type Option={hotel:string;account_id:string;account_name:string;account_type:string};
type Row=Option&{id?:string|number;day?:string;invoice_id?:string;invoice_no?:string;folio_no?:string;net_open?:string|null;over90?:string|null;aging?:unknown;verified?:boolean;source_at?:string;publication_at?:string;kind?:string;observed_at?:string;previous_verified_at?:string|null;observed_open?:string;previous_open?:string|null;open?:string;opera_age?:number|null;unbilled_days?:number|null;first_billing_delay?:number|null;overdue_days?:number|null;since_reminder_days?:number|null;verification_state?:string};
type Result={rows:Row[];total:number;trackingStartedAt?:string;summary:{days?:number;daily?:{day:string;hotel:string;accounts:number;unverified:number;publication_at:string;net_open:string|null;over90:string|null}[];cleared?:number;reopened?:number;firstObservedZero?:number;invoices?:number;unbilled?:number;over60Unbilled?:number;over60Amount?:string|null;unknownAge?:number;sourceUnverified?:number}};
const labels:Record<View,string>={daily_ar:'AR balance history',balance_observations:'Balance check history',timing:'Billing & reminder timing'};
const money=(v:string|null|undefined)=>v==null?'—':formatAmount(v);
const time=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})+' ICT':'Not recorded';
export default function ObservationReports({token,hotel,accounts,onBack,onOpen,initialContext,onContextChange}:{token:string;hotel:string;accounts:Account[];onBack:()=>void;onOpen:(hotel:string,accountId:string,invoiceId?:string)=>void;initialContext?:ObservationContext;onContextChange?:(value:ObservationContext)=>void}){
 const initial=initialContext?.hotel===hotel?initialContext:undefined;
 const [view,setView]=useState<View>(initialContext?.view??'timing'),[type,setType]=useState(initialContext?.type??''),[account,setAccount]=useState(initial?.account??''),[from,setFrom]=useState(initialContext?.from??calendarAdd(thaiToday(),-30)),[to,setTo]=useState(initialContext?.to??thaiToday()),[over60,setOver60]=useState(initialContext?.over60??false),[page,setPage]=useState(initial?.page??0),[reload,setReload]=useState(0);
 const [options,setOptions]=useState<Option[]>([]),[data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[optionError,setOptionError]=useState(false);const auth=useRef(token);auth.current=token;
 async function read<T>(path:string,signal:AbortSignal){const r=await fetch(path,{headers:{Authorization:`Bearer ${auth.current}`},signal});if(!r.ok)throw Error();return await r.json() as T;}
 useEffect(()=>{onContextChange?.({hotel,view,type,account,from,to,over60,page});},[hotel,view,type,account,from,to,over60,page,onContextChange]);
 useEffect(()=>{const c=new AbortController();setOptionError(false);void(async()=>{const all:Option[]=[];for(let n=0;;n++){const q=new URLSearchParams({page:String(n)});if(hotel!=='All')q.set('hotel',hotel);const result=await read<{rows:Option[];total:number}>('/api/observations/options?'+q,c.signal);if(!Array.isArray(result.rows)||!Number.isSafeInteger(result.total)||!result.rows.length&&all.length<result.total)throw Error();all.push(...result.rows);if(all.length>=result.total)break;}if(!c.signal.aborted)setOptions(all);})().catch(()=>{if(!c.signal.aborted)setOptionError(true);});return()=>c.abort();},[hotel,token,reload]);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');if(view!=='timing'&&(!from||!to||from>to)){setError('Choose a valid observation date range.');return()=>c.abort();}const q=new URLSearchParams({page:String(page)});if(hotel!=='All')q.set('hotel',hotel);if(type)q.set('type',type);if(account){const [h,a]=JSON.parse(account);q.set('hotel',h);q.set('account',a);}if(view==='timing')q.set('over60',String(over60));else{q.set('from',from);q.set('to',to);}void read<Result>('/api/observations/'+view+'?'+q,c.signal).then(r=>{if(!Array.isArray(r.rows)||!r.summary||!Number.isSafeInteger(r.total))throw Error();if(!c.signal.aborted)setData(r);}).catch(()=>{if(!c.signal.aborted)setError('Source observations are unavailable. No zero balances or missing days have been inferred.');});return()=>c.abort();},[hotel,token,view,type,account,from,to,over60,page,reload]);
 const change=(fn:()=>void)=>{fn();setPage(0);},summary=data?.summary;
 const metrics=view==='timing'?[['Current positive invoices',summary?.invoices],['Not billed',summary?.unbilled],['Over 60 · not billed',summary?.over60Unbilled],['Over 60 · amount',summary?.over60Amount==null?'—':money(summary.over60Amount)]]:view==='balance_observations'?[['Verified zero observations',summary?.cleared],['Verified reopen observations',summary?.reopened],['First check already zero',summary?.firstObservedZero]]:[['Days with captured records',summary?.days],['Matching account snapshots',data?.total]];
 const choices=[...new Map(options.filter(o=>!type||o.account_type===type).map(o=>[JSON.stringify([o.hotel,o.account_id]),o])).entries()];
 return <main className="page observation-reports"><button onClick={onBack}>Back to Reports</button><header><h1>AR history & timing</h1><button onClick={()=>setReload(n=>n+1)}>Reload observations</button></header><nav aria-label="Observation report views">{(Object.keys(labels) as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>change(()=>setView(v))}>{labels[v]}</button>)}</nav><div className="observation-filters"><label>Account type<select aria-label="Observation account type" value={type} onChange={e=>change(()=>{setType(e.target.value);setAccount('');})}><option value="">All account types</option>{[...new Set(options.map(o=>o.account_type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Account<select aria-label="Observation account" value={account} onChange={e=>change(()=>setAccount(e.target.value))}><option value="">All accounts</option>{choices.map(([key,o])=><option key={key} value={key}>{o.hotel} · {o.account_name}</option>)}</select></label>{view==='timing'?<label className="observation-check"><input type="checkbox" checked={over60} onChange={e=>change(()=>setOver60(e.target.checked))}/>Only unbilled invoices with OPERA age over 60 days</label>:<><label>From · observed Thai date<input type="date" value={from} onChange={e=>change(()=>setFrom(e.target.value))}/></label><label>Through · observed Thai date<input type="date" value={to} onChange={e=>change(()=>setTo(e.target.value))}/></label></>}</div>{optionError&&<p className="information-note">Account filter options are unavailable. Reload to retry.</p>}{error&&<p className="error-message" role="alert">{error}</p>}<div className="observation-metrics">{metrics.map(([label,value])=><article className="panel" key={label}><small>{label}</small><strong>{value??'—'}</strong></article>)}</div><p>{view==='timing'?'Calendar-day durations use recorded invoice, billing and reminder dates. The over-60 filter uses OPERA invoice age, which is separate from days overdue.':view==='daily_ar'?'Each day shows the latest actual full-hotel publication captured that day. It is not an end-of-day balance. Uncaptured days are gaps; balances from different days are never added together.':'This is an audit of OPERA balance checks. These timestamps show when the app observed a change. Payment reports use the OPERA payment transaction date.'}</p>{data?.trackingStartedAt&&view!=='timing'&&<p className="information-note">Observation tracking began {time(data.trackingStartedAt)}. Earlier unrecorded activity is unknown.</p>}{!!summary?.unknownAge&&<p className="information-note">{summary.unknownAge} unbilled invoices have no verified OPERA age and cannot be classified as over 60.</p>}{!!summary?.sourceUnverified&&<p className="information-note">{summary.sourceUnverified} invoices need source verification; their displayed amounts are last known balances.</p>}
 {view==='daily_ar'&&!!summary?.daily?.length&&<section className="panel observation-daily"><h2>Daily captured balances</h2><div className="table-scroll"><table><thead><tr><th>Date</th><th>Hotel</th><th>Accounts</th><th>Net AR</th><th>Over 90</th><th>Source publication</th></tr></thead><tbody>{summary.daily.map(d=><tr key={d.day+d.hotel}><td>{d.day}</td><td>{d.hotel}</td><td>{d.accounts}{d.unverified>0&&<small>{d.unverified} need verification</small>}</td><td>{money(d.net_open)}</td><td>{money(d.over90)}</td><td>{time(d.publication_at)}</td></tr>)}</tbody></table></div></section>}
 <section className="panel observation-list"><h2>{labels[view]}</h2><div className="table-scroll" role="region" aria-label="Source observation records" tabIndex={0}><table><thead><tr><th>Hotel / Account</th><th>{view==='daily_ar'?'Captured date / amount':'Invoice / Folio'}</th><th>{view==='timing'?'OPERA age / unbilled days':view==='daily_ar'?'Aging / coverage':'Balance observation'}</th><th>{view==='timing'?'Recorded timing':'Source timestamps'}</th><th>Current account</th></tr></thead><tbody>{data?.rows.map((r,n)=><tr key={r.hotel+':'+r.account_id+':'+(r.invoice_id??r.day??r.id??n)}><td><b>{r.account_name}</b><small>{r.hotel} · {r.account_type}</small></td><td>{view==='daily_ar'?<>{r.day}<small>Net AR {money(r.net_open)}</small></>:<>{r.invoice_no??r.invoice_id}<small>{r.folio_no?'Folio '+r.folio_no:''}</small>{view==='timing'&&<small>Open {money(r.open)}</small>}</>}</td><td>{view==='timing'?<>OPERA age {r.opera_age??'Unknown'}<small>Unbilled {r.unbilled_days??'Not applicable'}</small></>:view==='daily_ar'?<>{r.verified?'Verified snapshot':'Needs verification'}<details><summary>Source aging buckets</summary><pre>{r.aging==null?'Source aging unavailable':JSON.stringify(r.aging,null,2)}</pre></details></>:<>{r.kind?.replaceAll('_',' ')}<small>{money(r.previous_open)} → {money(r.observed_open)}</small></>}</td><td>{view==='timing'?<>First-billing delay {r.first_billing_delay??'Not recorded'}<small>Overdue {r.overdue_days??'Unknown'}</small><small>Since recorded reminder {r.since_reminder_days??'Not recorded'}</small></>:view==='daily_ar'?time(r.source_at):<>Previous check {time(r.previous_verified_at)}<small>Observed {time(r.observed_at)}</small></>}</td><td><button disabled={!accounts.some(a=>a.hotel===r.hotel&&a.id===r.account_id)} onClick={()=>onOpen(r.hotel,r.account_id,r.invoice_id)}>Open account / invoice</button></td></tr>)}</tbody></table></div>{data&&!data.rows.length&&<p>{view==='daily_ar'?'No snapshots were captured for this selection. Missing days are not zero.':view==='balance_observations'?'No balance observations were recorded for this selection. This does not prove there were no payments.':'No current invoices match this selection.'}</p>}{!data&&!error&&<p role="status">Loading source observations…</p>}{data&&<footer><span>{data.total} records · Page {page+1}</span><button disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous observations</button><button disabled={(page+1)*50>=data.total} onClick={()=>setPage(n=>n+1)}>Next observations</button></footer>}</section></main>;
}
