import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,RefreshCw,X} from 'lucide-react';
import {money,type Account} from '../domain/portfolio';
import {stageLabel,thaiToday,calendarAdd} from '../domain/collection';
import './reports.css';

interface Option {hotel:string;account_id:string;account_name:string;account_type:string}
interface Row extends Option {id?:string;invoice_id?:string;invoice_no:string|null;folio_no:string|null;delivery_id?:string;sent_at?:string;sent_date?:string;kind?:string;amount?:number|null;open?:number;latest_stage?:string;last_sent_at?:string|null;verification_state?:string;workflow?:{billing_required:boolean|null;first_billing_date:string|null;due_date:string|null;last_reminder_stage?:string|null}}
interface Count {kind:string;invoices:number;amount:number|null}
interface Daily {sent_date:string;invoices:number;messages:number;amount:number|null}
interface Hotel {hotel:string;accounts:number;open:number;over90:number;oldest_sync:string;unverified_accounts:number}
interface Result {rows:Row[];total:number;summary:{invoices:number;amount:number|null;uniqueInvoices?:number;messages?:number;missingAmounts?:number;unverified?:number;unbilled?:number;urgent?:number;stages?:Count[];kinds?:Count[];daily?:Daily[];hotels?:Hotel[]}}
/** Navigation choices only. The app retains this in memory, scoped to the signed-in user. */
export interface ReportContext {hotel:string;mode:'current'|'activity';type:string;account:string;kind:string;from:string;to:string;page:number}
const dateLabel=(value?:string|null)=>value?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'short',year:'numeric'}).format(new Date(value.length===10?value+'T00:00:00+07:00':value)):'Not recorded';
const timeLabel=(value?:string|null)=>value?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))+' ICT':'';
const amountLabel=(value?:number|null,compact=true)=>typeof value==='number'&&Number.isFinite(value)?money(value,compact):'Unavailable';
async function get<T>(path:string,token:string,signal:AbortSignal):Promise<T>{const r=await fetch(path,{headers:{Authorization:`Bearer ${token}`},signal});if(!r.ok)throw Error('reports_unavailable');return r.json();}
function Pager({page,total,size=50,onChange,label='report'}:{page:number;total:number;size?:number;onChange:(page:number)=>void;label?:string}){return <div className="reports-pagination"><span>{total?`${page*size+1}–${Math.min((page+1)*size,total)} of ${total.toLocaleString()}`:'0 matching invoices'}</span><div><button aria-label={`Previous ${label} page`} disabled={!page} onClick={()=>onChange(page-1)}><ChevronLeft size={15}/></button><button aria-label={`Next ${label} page`} disabled={(page+1)*size>=total} onClick={()=>onChange(page+1)}><ChevronRight size={15}/></button></div></div>;}

function InvoiceHistory({row,token,accounts,onOpen,onClose}:{row:Row;token:string;accounts:Account[];onOpen:(account:Account)=>void;onClose:()=>void}){
 const [data,setData]=useState<Result|null>(null),[error,setError]=useState(false),[page,setPage]=useState(0),[retry,setRetry]=useState(0);
 const id=row.invoice_id??row.id??'';
 const historyPanel=useRef<HTMLElement>(null);
 useEffect(()=>{if(!matchMedia('(max-width: 900px)').matches)return;const frame=requestAnimationFrame(()=>historyPanel.current?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame);},[row.hotel,row.account_id,id]);
 useEffect(()=>{const controller=new AbortController();setData(null);setError(false);const q=new URLSearchParams({hotel:row.hotel,account:row.account_id,invoice:id,page:String(page),limit:'10'});get<Result>('/api/reports/activity?'+q,token,controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[token,row.hotel,row.account_id,id,page,retry]);
 const account=accounts.find(a=>a.hotel===row.hotel&&a.id===row.account_id);
 return <aside ref={historyPanel} className="panel reports-detail" aria-label="Invoice history details"><div className="reports-detail-title"><h2>Invoice send history</h2><button aria-label="Close invoice history" onClick={onClose}><X size={16}/></button></div><h3>{row.invoice_no??id}</h3><p>{row.hotel} · {row.account_name}</p><p>{row.folio_no??'Folio number not recorded'}</p><div className="reports-detail-context"><span>{row.sent_at?'Amount in selected message':'Current positive balance'}</span><strong>{amountLabel(row.sent_at?row.amount:row.open,false)}</strong></div><p className="reports-source">All verified sends for this invoice, across every date. A new payment changes current receivables; these message amounts remain as sent.</p>
 {error?<div role="alert" className="reports-empty">Invoice history is unavailable.<button onClick={()=>setRetry(n=>n+1)}>Retry history</button></div>:!data?<p className="reports-empty" role="status">Loading verified history…</p>:<><ol className="reports-history">{data.rows.map(r=><li key={r.delivery_id}><span className="reports-history-dot"/><div><strong>{stageLabel(r.kind??'Verified send')}</strong><span>{dateLabel(r.sent_at)} · {timeLabel(r.sent_at)}</span><b>{amountLabel(r.amount,false)}</b></div></li>)}</ol>{!data.rows.length&&<p className="reports-empty">No verified sends recorded for this invoice. Manual history edits and drafts are separate.</p>}<Pager page={page} total={data.total} size={10} label="history" onChange={setPage}/></>}
 {row.workflow&&<dl className="reports-workflow"><div><dt>Recorded first billing date</dt><dd>{dateLabel(row.workflow.first_billing_date)}</dd></div><div><dt>Current due date</dt><dd>{dateLabel(row.workflow.due_date)}</dd></div><div><dt>Recorded reminder stage</dt><dd>{stageLabel(row.workflow.last_reminder_stage??'None')}</dd></div></dl>}
 {account?<button className="reports-open-account" onClick={()=>onOpen(account)}>Open current account <ChevronRight size={14}/></button>:<p className="reports-source">This account is not in the loaded portfolio. Its verified send history remains available.</p>}</aside>;
}

/** Operate surface: extend the approved supporting-surfaces reference with source-backed invoice drilldown. */
export default function Reports({token,hotel,accounts,onOpen,initialContext,onContextChange}:{token:string;hotel:string;accounts:Account[];onOpen:(account:Account)=>void;initialContext?:ReportContext;onContextChange?:(context:ReportContext)=>void}){
 const [mode,setMode]=useState<ReportContext['mode']>(initialContext?.mode??'current'),[type,setType]=useState(initialContext?.type??''),[account,setAccount]=useState(initialContext?.hotel===hotel?initialContext.account:''),[kind,setKind]=useState(initialContext?.hotel===hotel?initialContext.kind:''),[from,setFrom]=useState(initialContext?.from??calendarAdd(thaiToday(),-29)),[to,setTo]=useState(initialContext?.to??thaiToday()),[page,setPage]=useState(initialContext?.hotel===hotel?initialContext.page:0),[retry,setRetry]=useState(0);
 const previousHotel=useRef(hotel),hotelChanged=previousHotel.current!==hotel;
 const [options,setOptions]=useState<Option[]>([]),[optionsError,setOptionsError]=useState(false),[data,setData]=useState<Result|null>(null),[error,setError]=useState(false),[selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>{const controller=new AbortController();setOptions([]);setOptionsError(false);(async()=>{const all:Option[]=[];for(let p=0;;p++){const q=new URLSearchParams({page:String(p),limit:'200'});if(hotel!=='All')q.set('hotel',hotel);const result=await get<{rows:Option[];total:number}>('/api/reports/options?'+q,token,controller.signal);if(!Array.isArray(result.rows)||!Number.isSafeInteger(result.total)||!result.rows.length&&all.length<result.total)throw Error('reports_invalid');all.push(...result.rows);if(all.length>=result.total)break;}if(!controller.signal.aborted)setOptions(all);})().catch(()=>{if(!controller.signal.aborted)setOptionsError(true);});return()=>controller.abort();},[token,hotel,retry]);
 useEffect(()=>{if(previousHotel.current===hotel)return;previousHotel.current=hotel;setAccount('');setKind('');setPage(0);setSelected(null);},[hotel]);
 useEffect(()=>{onContextChange?.({hotel,mode,type,account:hotelChanged?'':account,kind:hotelChanged?'':kind,from,to,page:hotelChanged?0:page});},[hotel,mode,type,account,kind,from,to,page,hotelChanged,onContextChange]);
 const invalidDates=mode==='activity'&&!!from&&!!to&&from>to;
 useEffect(()=>{
  const controller=new AbortController();setData(null);setError(false);if(invalidDates)return()=>controller.abort();
  const q=new URLSearchParams({page:String(page),limit:'50'});if(hotel!=='All')q.set('hotel',hotel);if(type)q.set('type',type);if(kind)q.set('kind',kind);
  if(account){const [accountHotel,accountId]=JSON.parse(account) as string[];if(hotel!=='All'&&accountHotel!==hotel)return()=>controller.abort();q.set('hotel',accountHotel);q.set('account',accountId);}
  if(mode==='activity'){if(from)q.set('from',from);if(to)q.set('to',to);}
  get<Result>('/api/reports/'+mode+'?'+q,token,controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();
 },[token,hotel,type,account,kind,from,to,page,mode,retry,invalidDates]);
 const change=(run:()=>void)=>{run();setPage(0);setSelected(null);};
 const accountOptions=[...new Map(options.filter(o=>!type||o.account_type===type).map(o=>[JSON.stringify([o.hotel,o.account_id]),o])).entries()].sort((a,b)=>a[1].account_name.localeCompare(b[1].account_name));
 const summary=data?.summary;
 const metrics=mode==='current'?[['Positive open invoices',summary?.invoices,'Each invoice counted once'],['Current invoice amount',data?amountLabel(summary?.amount):undefined,'Positive parent / standalone balances'],['Billing required · not billed',summary?.unbilled,'Current recorded billing state'],['After Final · still open',summary?.urgent,'Latest verified send is Final']]:[['Invoice send occurrences',summary?.invoices,`${summary?.uniqueInvoices??'—'} distinct invoices`],['Amount represented',data?amountLabel(summary?.amount):undefined,'Snapshot amount per invoice send'],['Verified messages',summary?.messages,'Actual Gmail sent evidence'],['Missing amount evidence',summary?.missingAmounts,'Unavailable amounts are never zero']];
 const stages=mode==='current'?summary?.stages:summary?.kinds;
 return <main className="page reports-page"><div className="reports-title"><div><h1>Reports & Activity</h1><p>Current receivables and verified work, with every invoice in view.</p></div><button onClick={()=>setRetry(n=>n+1)} disabled={!data&&!error}><RefreshCw size={14}/> Reload reports</button></div>
 <div className="reports-tabs" role="tablist" aria-label="Report view"><button role="tab" aria-selected={mode==='current'} onClick={()=>change(()=>{setMode('current');setKind('');})}>Current receivables</button><button role="tab" aria-selected={mode==='activity'} onClick={()=>change(()=>{setMode('activity');setKind('');})}>Verified sent activity</button><span>{mode==='activity'?'Actual sent dates · ICT (UTC+7)':'Latest OPERA balances · THB'}</span></div>
 <div className="reports-filters"><label>Account type<select aria-label="Report account type" value={type} onChange={e=>change(()=>{setType(e.target.value);setAccount('');})}><option value="">All account types</option>{[...new Set(options.map(o=>o.account_type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Account<select aria-label="Report account" value={account} onChange={e=>change(()=>setAccount(e.target.value))}><option value="">All accounts</option>{accountOptions.map(([key,o])=><option key={key} value={key}>{o.hotel} · {o.account_name}</option>)}</select></label><label>{mode==='current'?'Latest verified stage':'Activity kind'}<select aria-label="Report activity kind" value={kind} onChange={e=>change(()=>setKind(e.target.value))}><option value="">All {mode==='current'?'stages':'activity'}</option>{['First billing','Rebilling','Friendly','Follow 1','Follow 2','Follow 3','Final',...(mode==='current'?['No verified send']:['Billing classification unavailable'])].map(k=><option key={k} value={k}>{stageLabel(k)}</option>)}</select></label>{mode==='activity'&&<><label>From · Thai date<input type="date" aria-label="Report from date" value={from} onChange={e=>change(()=>setFrom(e.target.value))}/></label><label>Through · Thai date<input type="date" aria-label="Report through date" value={to} onChange={e=>change(()=>setTo(e.target.value))}/></label></>}<button onClick={()=>change(()=>{setType('');setAccount('');setKind('');if(mode==='activity'){setFrom('');setTo('');}})}>Clear filters</button></div>
 {optionsError&&<p className="reports-warning" role="status">Account filter options are unavailable. Reload reports to try again.</p>}{invalidDates&&<p className="reports-warning" role="alert">The start date must be on or before the end date.</p>}{error&&<p className="reports-warning" role="alert">Report data is unavailable. Reload reports to try again; no zero totals have been inferred.</p>}
 <div className="reports-metrics">{metrics.map(([label,value,note],i)=><div key={String(label)} className={i===0?'reports-metric-accent':''}><span>{label}</span><strong>{value??'—'}</strong><small>{note}</small></div>)}</div>
 <p className="reports-source">{mode==='activity'?'Counts and amounts describe verified invoice sends. An invoice sent twice appears twice; this is not cash collected. Drafts, diagnostics and manual history corrections are excluded. Account type is captured when send evidence is recorded; older uncaptured types remain “Not recorded”.':'Positive invoice backlog excludes compressed child rows. Latest stage comes only from verified sends; recorded billing and due dates may include reviewed manual corrections. Account totals below include OPERA credits and all stages.'}</p>
 {mode==='current'&&!!summary?.unverified&&<p className="reports-warning" role="status">{summary.unverified} positive invoices require source verification. Their last known balances remain visible until OPERA confirms them.</p>}
 {!!stages?.length&&<div className="reports-stage-strip" aria-label="Report stage breakdown">{stages.map(s=><button key={s.kind} onClick={()=>change(()=>setKind(kind===s.kind?'':s.kind))} aria-pressed={kind===s.kind}><span>{stageLabel(s.kind)}</span><strong>{s.invoices}</strong><small>{amountLabel(s.amount)}</small></button>)}</div>}
 <div className={`reports-layout ${selected?'has-detail':''}`}><section className="panel reports-list"><header><h2>{mode==='activity'?'Verified invoice sends':'Current positive invoices'}</h2><span>{data?`${data.total.toLocaleString()} matching ${mode==='activity'?'invoice sends':'invoices'}`:'Waiting for source data'}</span></header><div className="reports-table-scroll"><table className="reports-table"><thead><tr><th>{mode==='activity'?'Sent · Thai date':'Hotel'}</th><th>Account / Invoice</th><th>{mode==='activity'?'Activity':'Latest verified stage'}</th><th>{mode==='activity'?'Amount as sent':'Current open'}</th><th>Details</th></tr></thead><tbody>{data?.rows.map(row=><tr key={`${row.delivery_id??''}:${row.hotel}:${row.account_id}:${row.invoice_id??row.id}`}><td>{mode==='activity'?<>{dateLabel(row.sent_at)}<small>{timeLabel(row.sent_at)}</small></>:<span className={`reports-hotel ${row.hotel.toLowerCase()}`}>{row.hotel}</span>}</td><td><strong>{row.account_name}</strong><small>{mode==='activity'?row.hotel+' · ':''}{row.account_type} · {row.invoice_no??row.invoice_id??row.id}</small></td><td><span className={row.latest_stage==='Final'?'reports-urgent':''}>{stageLabel(mode==='activity'?row.kind??'Unknown':row.latest_stage??'No verified send')}</span>{mode==='current'&&<small>{row.last_sent_at?dateLabel(row.last_sent_at):'No actual send recorded'}</small>}</td><td className="reports-amount">{amountLabel(mode==='activity'?row.amount:row.open,false)}</td><td><button aria-label={`View history ${row.invoice_no??row.invoice_id??row.id}`} onClick={()=>setSelected(row)}>History <ChevronRight size={12}/></button></td></tr>)}</tbody></table></div>{!data?<div className="reports-empty" role="status">{error?'Verified source data is required to display this report.':invalidDates?'Choose a valid date range.':'Loading report data…'}</div>:!data.rows.length?<div className="reports-empty">{mode==='activity'?'No verified sends match these filters.':'No positive invoices match these filters.'}</div>:null}{data&&<Pager page={page} total={data.total} onChange={p=>{setPage(p);setSelected(null);}}/>}</section>{selected&&<InvoiceHistory key={`${selected.hotel}:${selected.account_id}:${selected.invoice_id??selected.id}`} row={selected} token={token} accounts={accounts} onOpen={onOpen} onClose={()=>setSelected(null)}/>}</div>
 <div className="reports-secondary">{mode==='current'?<section className="panel reports-source-summary"><header><h2>OPERA account balances by hotel</h2><span>Account filters apply · All stages</span></header><table><thead><tr><th>Hotel</th><th>Accounts</th><th>Net open</th><th>Over 90 days</th><th>Oldest snapshot</th></tr></thead><tbody>{summary?.hotels?.map(h=><tr key={h.hotel}><td>{h.hotel}</td><td>{h.accounts}</td><td>{amountLabel(h.open)}</td><td>{amountLabel(h.over90)}</td><td>{dateLabel(h.oldest_sync)} · {timeLabel(h.oldest_sync)}{h.unverified_accounts>0&&<small>{h.unverified_accounts} accounts need verification</small>}</td></tr>)}</tbody></table>{!summary?.hotels?.length&&<p className="reports-source">{data?'No account balance data matches these filters.':'Account balances unavailable while the report is loading.'}</p>}<p className="reports-source">Net open and over-90 amounts come directly from OPERA account snapshots. They can differ from positive invoice backlog because of credits and invoice relationships.</p></section>:<section className="panel reports-source-summary"><header><h2>Activity by actual sent day</h2><span>Thai calendar dates</span></header><div className="reports-daily-scroll"><table><thead><tr><th>Date</th><th>Invoice sends</th><th>Messages</th><th>Amount represented</th></tr></thead><tbody>{summary?.daily?.map(d=><tr key={d.sent_date}><td><button onClick={()=>change(()=>{setFrom(d.sent_date);setTo(d.sent_date);})}>{dateLabel(d.sent_date)}</button></td><td>{d.invoices}</td><td>{d.messages}</td><td>{amountLabel(d.amount)}</td></tr>)}</tbody></table></div>{!summary?.daily?.length&&<p className="reports-source">{data?'No verified sending days in this selection.':'Verified daily activity is unavailable while the report is loading.'}</p>}</section>}<aside className="reports-coverage"><h2>Available evidence</h2><p>Current balances: OPERA snapshots.<br/>Sent activity: verified Gmail send records.</p><h3>Not yet available</h3><p>Daily invoice arrivals, cash received, payment allocation and remittance statistics need their own verified source history. They are not inferred from balance changes or email replies.</p></aside></div>
 </main>;
}
