import {useEffect,useRef,useState} from 'react';
import {ShieldCheck,UserPlus,Pencil,Search} from 'lucide-react';
import {REGION_IDS,regionLabel,type RegionId} from '../domain/hotels';
import {parseAccess,type AccessList,type AccessMember} from './model';
import './users-access.css';
const messages:Record<string,string>={access_revision_conflict:'This user changed since you opened it. Reload the list and review the latest access.',access_command_conflict:'This request was already used for different changes. Reload before trying again.',access_administrator_locked:'The administrator must keep access to both regions.',access_invalid:'Enter a valid email and select at least one region.',access_forbidden:'Only the administrator can manage users.'};
async function api<T>(token:string,url:string,init:RequestInit={}):Promise<T>{const r=await fetch(url,{...init,headers:{Authorization:'Bearer '+token,...init.headers}});const v=await r.json();if(!r.ok){const code=v&&typeof v==='object'&&'error' in v?String(v.error):'';throw Error(messages[code]??'Access could not be saved or loaded. Keep your changes and try again.');}return v as T;}
const blank=()=>({email:'',regions:['phuket'] as RegionId[],active:true,revision:0});
export default function UsersAccess({token,onDirtyChange}:{token:string;onDirtyChange?:(dirty:boolean)=>void}){
 const [data,setData]=useState<AccessList|null>(null),[page,setPage]=useState(0),[search,setSearch]=useState(''),[draft,setDraft]=useState(blank),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[reload,setReload]=useState(0),[dirty,setDirty]=useState(false);
 const lifetime=useRef(0),pending=useRef<{key:string;id:string}|null>(null),emailField=useRef<HTMLInputElement>(null);
 useEffect(()=>{const version=++lifetime.current;let alive=true;setLoading(true);setError('');
  api<AccessList>(token,'/api/access/users?'+new URLSearchParams({page:String(page),search})).then(v=>{if(!Array.isArray(v.rows)||!Number.isSafeInteger(v.total)||v.total<0)throw Error('The user list is unavailable.');for(const row of v.rows){parseAccess(row);if(typeof row.active!=='boolean'||typeof row.registered!=='boolean')throw Error('The user list is unavailable.');}if(alive&&lifetime.current===version)setData(v);}).catch(e=>{if(alive&&lifetime.current===version){setData(null);setError(e.message);}}).finally(()=>{if(alive&&lifetime.current===version)setLoading(false);});return()=>{alive=false;};
 },[token,page,search,reload]);
 useEffect(()=>{onDirtyChange?.(dirty||busy);return()=>onDirtyChange?.(false);},[dirty,busy,onDirtyChange]);
 useEffect(()=>()=>{lifetime.current++;},[]);
 useEffect(()=>{setBusy(false);},[token]);
 const edit=(row:AccessMember)=>{if(busy)return;if(dirty&&!window.confirm('Discard unsaved access changes?'))return;setDraft({email:row.email,regions:[...row.regions],active:row.active,revision:row.revision});setDirty(false);setError('');setStatus('');pending.current=null;emailField.current?.focus();};
 const reset=()=>{if(busy)return;setDraft(blank());setDirty(false);pending.current=null;setError('');setStatus('');emailField.current?.focus();};
 const save=async()=>{if(busy||!draft.regions.length)return;const key=JSON.stringify({...draft,email:draft.email.trim().toLowerCase()});if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};const command=pending.current;setBusy(true);setError('');setStatus('');const version=lifetime.current;
  try{await api(token,'/api/access/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(key),commandId:command.id})});if(lifetime.current!==version)return;setStatus(draft.active?'Access saved. No invitation email was sent.':'Access suspended. Future requests from this user will be denied.');setDraft(blank());setDirty(false);pending.current=null;setReload(n=>n+1);}
  catch(e){if(lifetime.current===version)setError(e instanceof Error?e.message:'Access could not be saved.');}finally{if(lifetime.current===version)setBusy(false);}
 };
 return <main className="page user-access"><header className="access-heading"><div><h1>Users &amp; Access</h1><p>Approve staff emails and choose where they can work.</p></div><span className="access-admin"><ShieldCheck size={17}/> Administrator settings</span></header>
  <section className="access-mail-policy" aria-label="Email delivery by region"><p><strong>Phuket</strong><span>Email enabled · ar@katathani.com</span></p><p><strong>Khao Lak</strong><span>Email delivery is not enabled. Documents and external billing remain available.</span></p></section>
  <section className="panel access-form"><h2>{draft.revision?'Edit user access':'Add approved user'}</h2><form onSubmit={e=>{e.preventDefault();void save();}}><label className="access-email">Email<input ref={emailField} type="email" autoComplete="off" maxLength={254} required readOnly={draft.revision>0} disabled={busy} value={draft.email} onChange={e=>{setDraft({...draft,email:e.target.value});setDirty(true);}} placeholder="name@company.com"/></label><fieldset disabled={busy}><legend>Allowed regions</legend>{REGION_IDS.map(r=><label key={r}><input type="checkbox" checked={draft.regions.includes(r)} onChange={e=>{setDraft({...draft,regions:e.target.checked?REGION_IDS.filter(x=>x===r||draft.regions.includes(x)):draft.regions.filter(x=>x!==r)});setDirty(true);}}/>{regionLabel(r)}</label>)}</fieldset><label className="access-state">Status<select disabled={busy} value={draft.active?'active':'suspended'} onChange={e=>{setDraft({...draft,active:e.target.value==='active'});setDirty(true);}}><option value="active">Active</option><option value="suspended">Suspended</option></select></label><div className="access-form-actions"><button className="primary-button" disabled={busy||!draft.email.trim()||!draft.regions.length}><UserPlus size={15}/>{busy?'Saving…':draft.revision?'Save access':'Approve access'}</button>{(draft.revision>0||dirty)&&<button type="button" disabled={busy} onClick={reset}>Cancel</button>}</div></form><p className="access-help">Approved users can sign in with Google or create a web app password on the sign-in page. Each person uses their own login. Access does not change the sending mailbox.</p></section>
  {error&&<p role="alert" className="error-message">{error} <button disabled={busy} onClick={()=>setReload(n=>n+1)}>Reload list</button></p>}{status&&<p role="status" className="access-notice">{status}</p>}
  <section className="panel access-list"><header><h2>Approved users{data&&<small>{data.total}</small>}</h2><label className="access-search"><Search size={15}/><span className="sr-only">Search users</span><input type="search" aria-label="Search users" disabled={busy} placeholder="Search email" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></header>{loading?<p role="status" className="access-empty">Loading users…</p>:data&&<><div className="access-table-scroll"><table><thead><tr><th>Email</th><th>Regions</th><th>Status</th><th>Sign-in</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{data.rows.map(row=><tr key={row.email}><td><strong>{row.email}</strong>{row.administrator&&<small>Administrator · protected</small>}</td><td>{row.regions.map(regionLabel).join(' · ')}</td><td><span className={row.active?'access-active':'access-suspended'}>{row.active?'Active':'Suspended'}</span></td><td>{row.registered?'Account registered':'Awaiting first sign-in'}</td><td>{row.administrator?<span className="access-locked"><ShieldCheck size={16}/> Both regions</span>:<button aria-label={'Edit access for '+row.email} disabled={busy} onClick={()=>edit(row)}><Pencil size={14}/> Edit</button>}</td></tr>)}</tbody></table>{!data.rows.length&&<p className="access-empty">No users match this email.</p>}</div><footer><span>{data.total?`${page*25+1}–${Math.min((page+1)*25,data.total)} of ${data.total}`:'0 users'}</span><div><button disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={busy||(page+1)*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></footer></>}</section>
 </main>;
}
