import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,ArrowUpDown,Check,ChevronLeft,ChevronRight,Eye,EyeOff,History,Search,X} from 'lucide-react';
import {money,type Account} from '../domain/portfolio';
import {stageLabel} from '../domain/collection';
import {fieldLabels,RegisterInput} from './RegisterInput';
import {registerPath,registerRequest,saveRegister} from './client';
import {notifyRegisterChanged,registerError,registerSortKeys,registerValues,rowKey,trackingStatuses,type RegisterRow,type RegisterValues,type RegisterCommand,type RegisterResult,type RegisterSort} from './model';
import type {RegionId} from '../domain/hotels';
import './register.css';
type Column={key:RegisterSort;label:string;field?:keyof RegisterValues;width?:string};
const viewColumns:Record<string,Column[]>={
 Billing:[{key:'billing_required',label:'Billing',field:'billingRequired'},{key:'credit_term',label:'Term · days',field:'creditTerm',width:'7%'},{key:'first_billing_date',label:'First billing',field:'firstBillingDate'},{key:'due_date',label:'Due date'}],
 'Follow-up':[{key:'last_reminder_stage',label:'Latest reminder',field:'lastReminderStage'},{key:'last_reminder_date',label:'Date sent',field:'lastReminderDate'},{key:'promised_date',label:'Promised date',field:'promisedDate'},{key:'tracking_status',label:'Tracking',field:'trackingStatus'}],
 'Notes & receipts':[{key:'owner_name',label:'Owner',field:'ownerName'},{key:'reported_received',label:'Reported received',field:'reportedReceived'},{key:'note',label:'Invoice note',field:'note',width:'24%'}],
 'Invoice details':[{key:'folio_no',label:'Folio no.'},{key:'transaction_date',label:'Transaction date'},{key:'original',label:'Original · THB'},{key:'aging',label:'Aging'}],
};
const identityColumns:Column[]=[{key:'hotel',label:'Hotel',width:'50px'},{key:'invoice_no',label:'Invoice no.',width:'90px'},{key:'account_name',label:'Account',width:'15%'},{key:'guest',label:'Guest',width:'13%'},{key:'open',label:'Open · THB',width:'10%'}];
function display(row:RegisterRow,column:Column):string {const value=row[column.key as keyof RegisterRow];if(column.key==='billing_required')return value===true?'Required':value===false?'Not required':'Not configured';if(column.key==='last_reminder_stage')return value?stageLabel(String(value),undefined,row.workflow?.last_reminder_stage_snapshot):'No reminders';if(column.key==='tracking_status')return String(value||'Not started');if(column.key==='open'||column.key==='original'||column.key==='reported_received')return value===null?'—':money(Number(value),false).replace('THB ','');return value===null||value===undefined||value===''?'—':String(value);}
export function InvoiceRegister({token,region,hotel,accounts,params,update,onDirtyChange,onOpen,dataVersion=0}:{token:string;region:RegionId;hotel:string;accounts:Account[];params:URLSearchParams;update:(key:string,value:string)=>void;onDirtyChange:(v:boolean)=>void;onOpen:(account:Account,invoice?:string)=>void;dataVersion?:number}){
 const get=(key:string,fallback='')=>params.get('reg'+key)??fallback;
 const view=Object.hasOwn(viewColumns,get('View','Billing'))?get('View','Billing'):'Billing',sort=registerSortKeys.includes(get('Sort','account_name') as RegisterSort)?get('Sort','account_name'):'account_name',direction=get('Dir','asc')==='desc'?'desc':'asc',page=Math.max(0,Number(get('Page','0'))||0);
 const [search,setSearch]=useState(get('Search')),[querySearch,setQuerySearch]=useState(get('Search')),[data,setData]=useState<RegisterResult|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[refresh,setRefresh]=useState(0);
 const [focusField,setFocusField]=useState<keyof RegisterValues|null>(null);
 const [selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState<RegisterRow|null>(null),[draft,setDraft]=useState<RegisterValues|null>(null),[busy,setBusy]=useState(false),[pending,setPending]=useState<RegisterCommand|null>(null);
 const [historyRow,setHistoryRow]=useState<RegisterRow|null>(null),[historyPage,setHistoryPage]=useState(0),[historyData,setHistoryData]=useState<{rows:{id:number;actor:string;recorded_at:string;before_value:RegisterValues;after_value:RegisterValues}[];total:number}|null>(null),[historyError,setHistoryError]=useState(false);
 const auth=useRef(token);auth.current=token;const alive=useRef(true),writeLock=useRef(false),dirtyRef=useRef(false);const dirty=!!editing;dirtyRef.current=dirty;const dirtyCallback=useRef(onDirtyChange);dirtyCallback.current=onDirtyChange;
 useEffect(()=>{dirtyCallback.current(dirty||busy);},[dirty,busy]);useEffect(()=>{alive.current=true;return()=>{alive.current=false;dirtyCallback.current(false);};},[]);
 useEffect(()=>{const timer=setTimeout(()=>setQuerySearch(search),250);return()=>clearTimeout(timer);},[search]);
 const savedSearch=get('Search');useEffect(()=>setSearch(savedSearch),[savedSearch]);
 useEffect(()=>{const changed=()=>{if(!dirtyRef.current)setRefresh(n=>n+1);};window.addEventListener('focus',changed);return()=>window.removeEventListener('focus',changed);},[]);
 const accountKey=get('Account'),accountChoice=accounts.find(a=>JSON.stringify([a.hotel,a.id])===accountKey&&(hotel==='All'||a.hotel===hotel));
 const query=new URLSearchParams({region,sort,direction,page:String(page),limit:'50',balance:get('Balance','open'),visibility:get('Visibility','visible'),billing:get('Billing','all'),tracking:get('Tracking','all')});if(hotel!=='All')query.set('hotel',hotel);if(accountChoice){query.set('hotel',accountChoice.hotel);query.set('account',accountChoice.id);}if(get('Type'))query.set('type',get('Type'));if(querySearch)query.set('search',querySearch);
 const queryKey=query.toString();
 useEffect(()=>{if(dirtyRef.current)return;const controller=new AbortController();setLoading(true);setError('');registerRequest<RegisterResult>('/api/invoice-register?'+queryKey,auth.current,{signal:controller.signal}).then(v=>{if(!controller.signal.aborted){if(!Array.isArray(v.rows)||!Number.isSafeInteger(v.total))throw Error();setData(v);setSelected(new Set());if(page&&page*50>=v.total)update('regPage','');}}).catch(()=>{if(!controller.signal.aborted)setError('Invoice register is unavailable. Reload to retry; saved records have not changed.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[queryKey,refresh,dataVersion,token]);
 useEffect(()=>{if(!historyRow)return;const c=new AbortController();setHistoryData(null);setHistoryError(false);registerRequest<typeof historyData>(registerPath(historyRow)+'/history?page='+historyPage,auth.current,{signal:c.signal}).then(v=>{if(!c.signal.aborted)setHistoryData(v);}).catch(()=>{if(!c.signal.aborted)setHistoryError(true);});return()=>c.abort();},[historyRow,historyPage,refresh]);
 const changeFilter=(key:string,value:string)=>{update('reg'+key,value);update('regPage','');setStatus('');};
 const beginEdit=(row:RegisterRow,field?:keyof RegisterValues)=>{if(busy||editing)return;setFocusField(field??viewColumns[view].find(c=>c.field)?.field??null);setEditing(row);setDraft(registerValues(row));setPending(null);setError('');setStatus('');};
 const cancel=()=>{setEditing(null);setDraft(null);setPending(null);setError('');setRefresh(n=>n+1);};
 async function save(){if(!editing||!draft||writeLock.current)return;writeLock.current=true;setBusy(true);setError('');const command=pending??{commandId:crypto.randomUUID(),revision:editing.tracking_revision,workflowRevision:editing.workflow_revision,exceptionRevision:editing.exception_revision,values:draft};setPending(command);try{await saveRegister(editing,command,auth.current);if(alive.current){setEditing(null);setDraft(null);setPending(null);setStatus(`Invoice ${editing.invoice_no??editing.id} saved. Linked invoice status updated.`);setRefresh(n=>n+1);notifyRegisterChanged();}}catch(e){if(alive.current){const code=e instanceof Error?e.message:'';setError(registerError(code));if(code==='register_invalid')setPending(null);}}finally{writeLock.current=false;if(alive.current)setBusy(false);}}
 async function visibility(hidden:boolean){if(writeLock.current||dirty||!data)return;const rows=data.rows.filter(r=>selected.has(rowKey(r))).map(r=>({hotel:r.hotel,accountId:r.account_id,invoiceId:r.id}));if(!rows.length)return;writeLock.current=true;setBusy(true);setError('');try{await registerRequest('/api/invoice-register/visibility?region='+region,auth.current,{method:'POST',body:JSON.stringify({commandId:crypto.randomUUID(),hidden,rows})});if(alive.current){setStatus(`${rows.length} rows ${hidden?'hidden from your register':'restored'}.`);setRefresh(n=>n+1);}}catch{if(alive.current)setError('Visibility could not be confirmed. Reload to check your rows.');}finally{writeLock.current=false;if(alive.current)setBusy(false);}}
 const columns=[...identityColumns,...viewColumns[view]];const invoiceWidth=Math.max(90,...(data?.rows??[]).map(r=>(r.invoice_no?.length??0)*7+20));
 return <section className="invoice-register" aria-label="Invoice register"><div className="register-intro"><div><h2>Invoice Register</h2><p>Live invoice status and your team’s follow-up records.</p></div><button disabled={dirty||busy||loading} onClick={()=>setRefresh(n=>n+1)}>Reload register</button></div>
 <div className="register-filters"><label className="register-search"><span>Search</span><div><Search size={15}/><input aria-label="Search invoice register" value={search} onChange={e=>{setSearch(e.target.value);update('regSearch',e.target.value);update('regPage','');}} disabled={dirty||busy} placeholder="Invoice, folio, guest, account or note"/></div></label>
 <label>Account type<select aria-label="Register account type" value={get('Type')} disabled={dirty||busy} onChange={e=>changeFilter('Type',e.target.value)}><option value="">All types</option>{[...new Set(accounts.map(a=>a.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Account<select aria-label="Register account" value={accountChoice?accountKey:''} disabled={dirty||busy} onChange={e=>changeFilter('Account',e.target.value)}><option value="">All accounts</option>{accounts.filter(a=>(hotel==='All'||a.hotel===hotel)&&(!get('Type')||a.type===get('Type'))).map(a=><option key={a.hotel+a.id} value={JSON.stringify([a.hotel,a.id])}>{a.hotel} · {a.name}</option>)}</select></label>
 <label>Balance<select aria-label="Register balance" disabled={dirty||busy} value={get('Balance','open')} onChange={e=>changeFilter('Balance',e.target.value)}><option value="open">Open balances</option><option value="all">All saved invoices</option><option value="cleared">Verified zero balance</option><option value="credit">Credit balances</option></select></label>
 <label>Billing<select aria-label="Register billing filter" disabled={dirty||busy} value={get('Billing','all')} onChange={e=>changeFilter('Billing',e.target.value)}>{[['all','All billing states'],['required','Billing required'],['not_required','Not required'],['unconfigured','Not configured'],['unbilled','Not billed'],['billed','Billed']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Tracking<select aria-label="Register tracking filter" disabled={dirty||busy} value={get('Tracking','all')} onChange={e=>changeFilter('Tracking',e.target.value)}><option value="all">All tracking states</option>{trackingStatuses.map(s=><option key={s} value={s}>{s||'Not started'}</option>)}</select></label></div>
 <div className="register-summary"><span><b>{data?.total.toLocaleString()??'—'}</b> invoices</span><span>Open <b>{data?money(data.summary.open,false):'—'}</b></span>{!!data?.summary.unverified&&<span>{data.summary.unverified} need source verification</span>}<label>Rows<select aria-label="Register row visibility" disabled={dirty||busy} value={get('Visibility','visible')} onChange={e=>changeFilter('Visibility',e.target.value)}><option value="visible">Visible rows</option><option value="hidden">Hidden rows ({data?.hiddenTotal??0})</option><option value="all">All rows</option></select></label></div>
 <div className="register-mobile-sort"><label>Sort by<select aria-label="Register sort column" disabled={dirty||busy} value={sort} onChange={e=>{update('regSort',e.target.value);update('regPage','');}}>{columns.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label><button disabled={dirty||busy} onClick={()=>update('regDir',direction==='asc'?'desc':'asc')}>{direction==='asc'?'Ascending':'Descending'}</button></div><div className="register-tools"><nav aria-label="Register columns">{Object.keys(viewColumns).map(v=><button key={v} aria-pressed={view===v} onClick={()=>update('regView',v)}>{v}</button>)}</nav><div>{selected.size>0&&<><span>{selected.size} selected</span><button disabled={dirty||busy} onClick={()=>visibility(true)}><EyeOff size={14}/>Hide</button><button disabled={dirty||busy} onClick={()=>visibility(false)}><Eye size={14}/>Show</button></>}</div></div>
 {view==='Notes & receipts'&&<p className="register-help">Reported received records your team’s information. OPERA confirms the remaining balance.</p>}
 {error&&<p role="alert" className="register-error">{error}{pending&&<button disabled={busy} onClick={cancel}>Discard edits and reload</button>}</p>}{status&&<p role="status" className="register-status">{status}</p>}
 {editing&&<div className="register-editbar"><span>Editing invoice <b>{editing.invoice_no??editing.id}</b> · {editing.hotel}<small>Changes apply to this invoice. Account defaults stay unchanged.</small></span><button disabled={busy} onClick={cancel}>Cancel</button><button className="primary-button" disabled={busy} onClick={save}><Check size={15}/>{busy?'Saving…':pending?'Retry save':'Save row'}</button></div>}
 <div className="register-table-shell" aria-busy={loading}><table className="register-table"><colgroup><col style={{width:32}}/>{columns.map(c=><col key={c.key} style={{width:c.key==='invoice_no'?invoiceWidth:c.width}}/>)}<col style={{width:98}}/></colgroup><thead><tr><th><input aria-label="Select register page" type="checkbox" disabled={dirty||busy||!data?.rows.length} checked={!!data?.rows.length&&data.rows.every(r=>selected.has(rowKey(r)))} onChange={e=>setSelected(new Set(e.target.checked?data?.rows.map(rowKey):[]))}/></th>{columns.map(c=><th key={c.key} className={['open','original','reported_received'].includes(c.key)?'register-number-head':undefined} aria-sort={sort===c.key?direction==='asc'?'ascending':'descending':'none'}><button disabled={dirty||busy} onClick={()=>{update('regSort',c.key);update('regDir',sort===c.key&&direction==='asc'?'desc':'asc');update('regPage','');}}>{c.label}{sort===c.key?direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>:<ArrowUpDown size={12}/>}</button></th>)}<th>Actions</th></tr></thead><tbody>{data?.rows.map(row=>{const active=editing&&rowKey(editing)===rowKey(row);const account=accounts.find(a=>a.hotel===row.hotel&&a.id===row.account_id);return <tr key={rowKey(row)} className={active?'is-editing':row.hidden?'is-hidden':''}><td data-label="Select"><input type="checkbox" aria-label={`Select invoice ${row.hotel} ${row.invoice_no??row.id}`} disabled={dirty||busy} checked={selected.has(rowKey(row))} onChange={e=>setSelected(old=>{const n=new Set(old);e.target.checked?n.add(rowKey(row)):n.delete(rowKey(row));return n;})}/></td>{columns.map(c=><td key={c.key} data-label={c.label} className={['open','original','reported_received'].includes(c.key)?'register-amount':undefined}>{active&&draft&&c.field?<RegisterInput field={c.field} autoFocus={c.field===focusField} values={draft} disabled={busy||!!pending} onChange={patch=>setDraft({...draft,...patch})}/>:c.key==='invoice_no'&&account?<button className="register-invoice-link" disabled={dirty} onClick={()=>onOpen(account,row.id)}>{display(row,c)}</button>:c.field?<button className="register-cell" title={display(row,c)} disabled={dirty||busy} onClick={()=>beginEdit(row,c.field)}>{display(row,c)}</button>:<span title={display(row,c)}>{display(row,c)}</span>}</td>)}<td data-label="Actions"><div className="register-row-actions"><button disabled={dirty||busy} onClick={()=>beginEdit(row)} aria-label={`Edit invoice ${row.hotel} ${row.invoice_no??row.id}`}>Edit</button><button disabled={busy} aria-label={`History invoice ${row.hotel} ${row.invoice_no??row.id}`} onClick={()=>{setHistoryRow(row);setHistoryPage(0);}}><History size={15}/></button></div></td></tr>;})}</tbody></table>{!data?.rows.length&&<p className="register-empty">{loading?'Loading invoice register…':error?'Saved invoices are temporarily unavailable.':'No invoices match these filters.'}</p>}</div>
 <footer className="register-pagination"><span>{data?.total?`${page*50+1}–${Math.min(page*50+50,data.total)} of ${data.total}`:'0 rows'}{loading?' · Refreshing…':''}</span><div><button aria-label="Previous register page" disabled={dirty||busy||loading||page===0} onClick={()=>update('regPage',String(page-1))}><ChevronLeft size={16}/></button><span>Page {page+1}</span><button aria-label="Next register page" disabled={dirty||busy||loading||!data||page*50+50>=data.total} onClick={()=>update('regPage',String(page+1))}><ChevronRight size={16}/></button></div></footer>
 {historyRow&&<section className="register-history" aria-label="Register edit history"><header><h3>Edit history · {historyRow.invoice_no??historyRow.id}</h3><button aria-label="Close register history" onClick={()=>setHistoryRow(null)}><X size={16}/></button></header>{historyError?<p role="alert">History is unavailable. Close and reopen to retry.</p>:!historyData?<p>Loading history…</p>:<>{!historyData.rows.length&&<p>No edits from the register yet. Billing and reminder history remains available in Invoice details.</p>}{historyData.rows.map(h=><article key={h.id}><b>{new Date(h.recorded_at).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})} ICT</b><span>{h.actor}</span><ul>{(Object.keys(fieldLabels) as (keyof RegisterValues)[]).filter(k=>h.before_value[k]!==h.after_value[k]).map(k=><li key={k}>{fieldLabels[k]}: {String(h.before_value[k]??'—')} → {String(h.after_value[k]??'—')}</li>)}</ul></article>)}<div><button disabled={!historyPage} onClick={()=>setHistoryPage(n=>n-1)}>Previous history</button><button disabled={(historyPage+1)*20>=historyData.total} onClick={()=>setHistoryPage(n=>n+1)}>Next history</button></div></>}</section>}
 </section>;
}
