import {useEffect,useRef,useState} from 'react';
import {RegisterInput,fieldLabels} from './RegisterInput';
import {registerPath,registerRequest,saveRegister} from './client';
import {notifyRegisterChanged,registerError,registerValues,type RegisterCommand,type RegisterRow,type RegisterValues} from './model';
import type {HotelId} from '../domain/hotels';
import './register.css';
const fields: (keyof RegisterValues)[]=['trackingStatus','promisedDate','ownerName','reportedReceived'];
export function InvoiceTracking({hotel,accountId,invoiceId,token,onDirtyChange,onSaved}:{hotel:HotelId;accountId:string;invoiceId:string;token:string;onDirtyChange:(v:boolean)=>void;onSaved?:()=>void}){
 const [row,setRow]=useState<RegisterRow|null>(null),[draft,setDraft]=useState<RegisterValues|null>(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[version,setVersion]=useState(0);
 const pending=useRef<RegisterCommand|null>(null),lock=useRef(false),auth=useRef(token),dirtyRef=useRef(false),callback=useRef(onDirtyChange);auth.current=token;callback.current=onDirtyChange;
 const dirty=!!row&&!!draft&&JSON.stringify(registerValues(row))!==JSON.stringify(draft);dirtyRef.current=dirty;
 useEffect(()=>{callback.current(dirty||busy);},[dirty,busy]);useEffect(()=>()=>callback.current(false),[]);
 useEffect(()=>{const changed=()=>{if(!dirtyRef.current)setVersion(v=>v+1);};window.addEventListener('ar-invoice-changed',changed);window.addEventListener('focus',changed);return()=>{window.removeEventListener('ar-invoice-changed',changed);window.removeEventListener('focus',changed);};},[]);
 useEffect(()=>{if(!open||dirtyRef.current)return;const c=new AbortController();setError('');registerRequest<RegisterRow>(registerPath({hotel,account_id:accountId,id:invoiceId}),auth.current,{signal:c.signal}).then(v=>{if(!c.signal.aborted){setRow(v);setDraft(registerValues(v));}}).catch(()=>{if(!c.signal.aborted)setError('Tracking details are unavailable. Reopen this section to retry.');});return()=>c.abort();},[hotel,accountId,invoiceId,open,version]);
 async function save(){if(!row||!draft||lock.current)return;lock.current=true;setBusy(true);setError('');const command=pending.current??{commandId:crypto.randomUUID(),revision:row.tracking_revision,workflowRevision:row.workflow_revision,exceptionRevision:row.exception_revision,values:draft};pending.current=command;try{const result=await saveRegister(row,command,auth.current);pending.current=null;setRow(result.row);setDraft(registerValues(result.row));setStatus('Tracking saved. Invoice Register is updated.');onSaved?.();notifyRegisterChanged();}catch(e){const code=e instanceof Error?e.message:'';setError(registerError(code));if(code==='register_invalid')pending.current=null;}finally{lock.current=false;setBusy(false);}}
 return <details className="invoice-tracking" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Tracking & payment notes</summary><p>Shared with Reports → Invoice Register.</p>{draft&&fields.map(field=><label key={field}>{fieldLabels[field]}<RegisterInput field={field} values={draft} disabled={busy||!!pending.current} onChange={patch=>setDraft({...draft,...patch})}/></label>)}<p>Reported received is a manual note; the remaining balance comes from OPERA.</p>{error&&<p role="alert">{error}<button disabled={busy} onClick={()=>{pending.current=null;setDraft(row?registerValues(row):null);dirtyRef.current=false;setVersion(v=>v+1);}}>Discard edits and reload</button></p>}{status&&<p role="status">{status}</p>}{draft&&<button disabled={busy||!dirty&&!pending.current} onClick={save}>{busy?'Saving…':pending.current?'Retry tracking save':'Save tracking'}</button>}</details>;
}
