import {useEffect,useState} from 'react';
interface Status {active:boolean;id?:string;clockOffsetDays?:number;revision?:number;invoices?:{id:string;invoiceNo:string;original:number;open:number}[]}
export default function AcceptancePanel({token,setupId}:{token:string;setupId:string|null}){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[reload,setReload]=useState(0),[ready,setReady]=useState(false);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/acceptance/status',{headers:{Authorization:'Bearer '+token},signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<Status>;}).then(value=>{if(!controller.signal.aborted)setStatus(value);}).catch(()=>{if(!controller.signal.aborted)setStatus({active:false});});return()=>controller.abort();},[token,reload]);
 const id=status?.id??setupId,valid=!!id&&/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/.test(id);
 async function command(action:string,body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/acceptance/'+action,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json() as {error?:string;active?:boolean};if(!r.ok||value.error)throw Error(value.error??'acceptance_unavailable');if(action==='prepare'){setReady(true);setMessage('The isolated resources are prepared.');}else if(action==='enter'||action==='exit'){location.assign('/');return;}else {setMessage(action==='refresh'?'Synthetic source refresh requested.':'The isolated test action completed.');setReload(n=>n+1);}}catch(e){setError(e instanceof Error?e.message.replaceAll('_',' '):'Test action unavailable.');}finally{setBusy(false);}}
 return <main className="page operations-page"><h1>Isolated acceptance test</h1><p>This workspace contains one fictional Account and three synthetic Invoices. OPERA is simulated here. Email and Drive tests use real services and the authorized test destination.</p>{error&&<p className="error-message" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{status?.active?<><section className="panel operations-section"><h2>Synthetic source</h2><p>Changes below affect this isolated fixture only. Run its source refresh afterward to exercise the normal verification and publication flow.</p>{status.invoices?.map(invoice=><div className="operations-dates" key={invoice.id}><strong>Invoice {invoice.invoiceNo} · THB {invoice.open.toFixed(2)}</strong><button disabled={busy} onClick={()=>void command('source',{invoiceId:invoice.id,open:0,revision:status.revision})}>Set {invoice.invoiceNo} to zero</button><button disabled={busy} onClick={()=>void command('source',{invoiceId:invoice.id,open:invoice.original,revision:status.revision})}>Reopen {invoice.invoiceNo}</button></div>)}<button disabled={busy} onClick={()=>void command('refresh',{})}>Refresh synthetic source</button></section><section className="panel operations-section"><h2>Retention test clock</h2><p>Offset: {status.clockOffsetDays} days. Provider authentication, real send dates and the production budget keep the real clock.</p><div className="operations-actions"><button disabled={busy} onClick={()=>void command('clock',{days:31})}>Advance test clock by 31 days</button><button disabled={busy} onClick={()=>void command('clock',{days:0})}>Reset test clock</button><button disabled={busy} onClick={()=>void command('retention',{})}>Check eligible test files</button></div></section><button disabled={busy} onClick={()=>void command('exit',{})}>Exit test workspace</button></>:<section className="panel operations-section"><h2>Prepare registered scenario</h2><p>A pre-registered scenario and reserved resource allowance are required. Preparation creates only its private test bucket and restricted test folder; no real Account is copied.</p><div className="operations-actions"><button disabled={busy||!valid} onClick={()=>void command('prepare',{id})}>Prepare isolated workspace</button><button disabled={busy||!valid||!ready} onClick={()=>void command('enter',{id})}>Enter test workspace</button></div></section>}</main>;
}
