import {ExternalBillingHistory} from '../billing/ExternalBilling';
import {useEffect,useRef,useState} from 'react';
import {stageLabel} from '../domain/collection';
import {legacyStageSnapshot,type StageSnapshot} from '../domain/collection-policy';
import {money} from '../domain/portfolio';
import {SavedEmailReview} from './SavedEmailReview';
import './account-workspace.css';

type HistoryRow={stage_snapshot?:StageSnapshot|null;id:string;recorded_at:string;source:string;purpose:string;stage:string|null;actual_date:string|null;invoice_ids:string[];amount:number|null;job_id:string|null;revision:number|null;first_billing_date:string|null;reminder_date:string|null;message?:{subject:string;body:string;recipients:{to:string[];cc:string[];bcc:string[]}}|null};
type DocumentRow={lifecycle?:'legacy'|'transient';closed_at?:string|null;closed_reason?:'sent'|'discarded'|null;id:string;created_at:string;content:string;layout:string;purpose:string;state:string;revision:number;acknowledged:boolean;statement_source:string;invoice_count:number;draft_id:string|null;subject:string|null;delivery_state:string|null;delivery_reason:string|null;sent_at:string|null;has_thread:boolean};
type Result={rows:(HistoryRow|DocumentRow)[];total:number};
const at=(date:string)=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(date))+' ICT';
export function AccountWorkspace({hotel,accountId,section,token,onOpenDocument,onDirtyChange}:{onDirtyChange?:(dirty:boolean)=>void;hotel:string;accountId:string;section:'history'|'documents';token:string;onOpenDocument?:(id:string,compose?:boolean)=>void}){
 const [page,setPage]=useState(0),[reload,setReload]=useState(0),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [savedDraftId,setSavedDraftId]=useState<string|null>(null),heading=useRef<HTMLHeadingElement>(null);
 const auth=useRef(token);auth.current=token;
 const base=`/api/account-workspace/${encodeURIComponent(hotel)}/${encodeURIComponent(accountId)}/${section}`;
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setResult(null);
  void (async()=>{try{const r=await fetch(`${base}?page=${page}`,{headers:{Authorization:`Bearer ${auth.current}`},signal:controller.signal});if(!r.ok)throw Error();const data=await r.json() as Result;if(!Array.isArray(data.rows)||!Number.isSafeInteger(data.total))throw Error();if(!controller.signal.aborted)setResult(data);}catch{if(!controller.signal.aborted)setError('Account evidence is unavailable. Retry to read the saved records.');}finally{if(!controller.signal.aborted)setBusy(false);}})();
  return()=>controller.abort();
 },[base,page,reload]);
 if(savedDraftId)return <section className="panel account-evidence"><SavedEmailReview hotel={hotel} accountId={accountId} draftId={savedDraftId} token={token} onClose={()=>{setSavedDraftId(null);requestAnimationFrame(()=>heading.current?.focus());}}/></section>;
 return <section className="panel account-evidence" aria-label={section==='history'?'Account collection history':'Account documents and Gmail'}>
  <header><div><h2 ref={heading} tabIndex={-1}>{section==='history'?'Collection History':'Documents & Gmail'}</h2><p>{section==='history'?'Verified sends and manual corrections keep their own dates and source.':'Document preparation and email history for this account. New rounds use fresh PDFs.'}</p></div><button onClick={()=>setReload(n=>n+1)} disabled={busy}>Refresh records</button></header>
  {busy&&<p role="status">Loading account evidence…</p>}{error&&<p className="error-message" role="alert">{error}</p>}
  {result&&result.rows.length===0&&<div className="empty-state"><strong>{section==='history'?'No recorded collection history':'No document or email work yet'}</strong><p>{section==='history'?'Preparing a PDF or draft does not count as a verified send.':'Select invoices from the ledger to prepare a package.'}</p></div>}
  {!!result?.rows.length&&<div className="table-scroll" tabIndex={0} role="region" aria-label={section==='history'?'Collection history table':'Document history table'}><table>
   {section==='history'?<><thead><tr>{['Recorded','Source / action','Actual dates','Invoices','Open at send','Details'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{(result.rows as HistoryRow[]).map(row=><tr key={row.id}><td>{at(row.recorded_at)}</td><td><b>{row.source}</b><small>{row.purpose==='history'?'History revision '+row.revision:row.purpose}{row.stage?' · '+stageLabel(row.stage,undefined,row.stage_snapshot??legacyStageSnapshot(row.stage)):''}</small></td><td>{row.actual_date??<><small>First billing: {row.first_billing_date??'Not recorded'}</small><small>Reminder: {row.reminder_date??'Not recorded'}</small></>}</td><td>{row.invoice_ids.length}<small>{row.invoice_ids.join(', ')}</small></td><td>{row.amount===null?'—':money(row.amount)}</td><td>{row.message?<details><summary>Verified message</summary><b>{row.message.subject}</b><small>To: {row.message.recipients?.to?.join(', ')||'Not recorded'}</small><p className="account-message-body">{row.message.body}</p></details>:<small>Manual correction<br/>No new send event</small>}</td></tr>)}</tbody></>:<><thead><tr>{['Created','Package','PDF status','Email / Gmail status','Open'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{(result.rows as DocumentRow[]).map(row=><tr key={row.id}><td>{at(row.created_at)}</td><td><b>{row.invoice_count} invoices · {row.purpose}</b><small>{row.content} · {row.layout.replaceAll('_',' ')}</small></td><td><b>{row.closed_at?(row.closed_reason==='sent'?'Sent · preparation closed':'Discarded'):row.state}</b><small>{row.closed_at?'History retained':row.lifecycle==='transient'?(row.acknowledged?'Reviewed for this attempt':'Review required'):`Revision ${row.revision} · ${row.acknowledged?'Reviewed':'Review required'}`}</small></td><td><b>{row.delivery_state?.replaceAll('_',' ')??(row.draft_id?'Workspace draft':'Not prepared')}</b>{row.subject&&<small>{row.subject}</small>}{row.sent_at&&<small>Sent {at(row.sent_at)}</small>}{row.delivery_reason&&<small>{row.delivery_reason.replaceAll('_',' ')}</small>}{row.has_thread&&<small>Linked conversation available in email work</small>}</td><td><button onClick={()=>onOpenDocument?.(row.id)}>{row.closed_at?'View preparation record':row.lifecycle==='transient'?'Continue preparation':'Open earlier preparation'}</button>{row.draft_id&&<button onClick={()=>setSavedDraftId(row.draft_id)}>Open email & conversation</button>}</td></tr>)}</tbody></>}
  </table></div>}
  {result&&<footer><span>{result.total} records · {hotel}</span><div><button disabled={busy||page===0} onClick={()=>setPage(n=>n-1)}>Previous records</button><span>Page {page+1}</span><button disabled={busy||(page+1)*20>=result.total} onClick={()=>setPage(n=>n+1)}>Next records</button></div></footer>}
  {section==='history'&&<ExternalBillingHistory hotel={hotel} accountId={accountId} token={token} onDirtyChange={onDirtyChange}/>}
  <p className="account-evidence-note">{section==='history'?'Manual corrections preserve entered history; they are not counted as verified Gmail sending activity.':'Gmail status and replies do not clear balances. Use the existing review and sent-status checks before another handoff.'}</p>
 </section>;
}
