import {useEffect,useRef,useState} from 'react';
import {checkedException,type InvoiceException,type ExceptionInput,type ExceptionAction,type ExceptionHistory} from '../../worker/collection/exceptions';
import './invoice-exceptions.css';
const messages:Record<string,string>={exception_revision_conflict:'This invoice status changed. Refresh its status before preparing another command.',exception_command_conflict:'The pending command has different details. Keep its original request and check its result.',exception_source_unverified:'Refresh OPERA and verify this invoice before acknowledging its reopening.',exception_state_conflict:'The action no longer matches the current invoice status. Refresh the status.'};
export function InvoiceExceptions({hotel,accountId,invoiceId,token,onSaved,onDirtyChange}:{hotel:'KAT'|'TSK';accountId:string;invoiceId:string;token:string;onSaved?:()=>void;onDirtyChange?:(dirty:boolean)=>void}){
 const [saved,setSaved]=useState<InvoiceException|null>(null),[note,setNote]=useState(''),[dispute,setDispute]=useState(''),[reason,setReason]=useState(''),[reviewDate,setReviewDate]=useState('');
 const [preview,setPreview]=useState<ExceptionInput|null>(null),[pending,setPending]=useState<ExceptionInput|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[history,setHistory]=useState<ExceptionHistory|null>(null),[historyPage,setHistoryPage]=useState(0);
 const auth=useRef(token);auth.current=token;const alive=useRef(true),lock=useRef(false),callbacks=useRef({onSaved,onDirtyChange});callbacks.current={onSaved,onDirtyChange};
 const base=`/api/invoice-exceptions/${encodeURIComponent(hotel)}/${encodeURIComponent(accountId)}/${encodeURIComponent(invoiceId)}`;
 const dirty=!!saved&&(note!==saved.note||dispute!==saved.dispute||!!reason.trim()||reviewDate!==(saved.holdReviewDate??''))||!!preview||!!pending;
 useEffect(()=>{callbacks.current.onDirtyChange?.(dirty);},[dirty]);
 async function request<T>(path:string,init:RequestInit={}):Promise<T>{const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${auth.current}`,...init.headers}});const v=await r.json();if(!r.ok)throw Error(v&&typeof v==='object'&&'error'in v&&typeof v.error==='string'?v.error:'exception_unavailable');return v as T;}
 function apply(v:InvoiceException){setSaved(v);setNote(v.note);setDispute(v.dispute);setReason('');setReviewDate(v.holdReviewDate??'');setHistory(null);}
 async function refresh(){if(lock.current)return;if(dirty&&!window.confirm('Discard unsaved invoice notes and reload status?'))return;setBusy(true);setError('');try{const v=checkedException(await request(base),{hotel,accountId,invoiceId});if(alive.current){apply(v);setStatus('Saved invoice status loaded.');}}catch{if(alive.current)setError('Invoice status is unavailable. Your edits are retained.');}finally{if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;const controller=new AbortController();setBusy(true);void request(base,{signal:controller.signal}).then(v=>{if(alive.current)apply(checkedException(v,{hotel,accountId,invoiceId}));}).catch(()=>{if(alive.current)setError('Invoice status is unavailable. Refresh status to retry.');}).finally(()=>{if(alive.current)setBusy(false);});return()=>{alive.current=false;controller.abort();callbacks.current.onDirtyChange?.(false);};},[base]);
 function prepare(action:ExceptionAction){if(!saved||busy||pending)return;if(action!=='set_notes'&&(note!==saved.note||dispute!==saved.dispute)){setError('Save or discard note and dispute changes before another action.');return;}if(!reason.trim()){setError('Enter a reason for this change.');return;}setError('');setConfirmed(false);setPreview({commandId:crypto.randomUUID(),revision:saved.revision,confirmed:true,action,reason:reason.trim(),...(action==='set_notes'?{note,dispute}:action==='hold'?{reviewDate:reviewDate||null}:{})});}
 async function submit(command:ExceptionInput){if(lock.current)return;lock.current=true;setBusy(true);setPending(command);setError('');setPreview(null);try{await request(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});if(!alive.current)return;setPending(null);setStatus('Change recorded. No email was sent.');callbacks.current.onSaved?.();try{apply(checkedException(await request(base),{hotel,accountId,invoiceId}));}catch{setError('Change was recorded, but the latest status could not be loaded. Refresh status before another action.');setSaved(null);}}catch(e){if(alive.current){const code=e instanceof Error?e.message:'';setError(messages[code]??'The result is not confirmed. Retry the same command; do not prepare a second one.');if(['exception_revision_conflict','exception_source_unverified','exception_state_conflict','exception_invalid','exception_reason_required','exception_forbidden'].includes(code))setPending(null);}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function readHistory(page:number){setBusy(true);setError('');try{const v=await request<ExceptionHistory>(`${base}/history?page=${page}&limit=10`);if(alive.current){setHistory(v);setHistoryPage(page);}}catch{if(alive.current)setError('Status history is unavailable. Retry the read.');}finally{if(alive.current)setBusy(false);}}
 return <details className="invoice-exceptions"><summary>Notes, holds & review</summary>
  <p>Notes and disputes do not pause collection automatically. A hold requires an explicit action.</p>
  {saved&&<><div className="exception-badges">{saved.held&&<b>On hold</b>}{saved.needsReview&&<b>Needs review · reopened</b>}{!saved.held&&!saved.needsReview&&<span>No manual hold or reopen review</span>}</div>{saved.holdReason&&<p>Hold: {saved.holdReason}</p>}{saved.reopenedAt&&<p>Reopened observation: {new Date(saved.reopenedAt).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})} ICT</p>}
  <label>Invoice note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={4000} rows={3} disabled={busy||!!pending||!!preview}/></label><label>Dispute details<textarea value={dispute} onChange={e=>setDispute(e.target.value)} maxLength={4000} rows={3} disabled={busy||!!pending||!!preview}/></label><label>Reason for status change<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} rows={2} disabled={busy||!!pending||!!preview}/></label>
  {!saved.held&&<label>Hold review date (optional)<input type="date" value={reviewDate} onChange={e=>setReviewDate(e.target.value)} disabled={busy||!!pending||!!preview}/></label>}
  <p>A review date does not release a hold. Reopen acknowledgement preserves billing dates and reminder history.</p>
  {!preview&&!pending&&<div className="exception-actions"><button disabled={busy} onClick={()=>prepare('set_notes')}>Review note changes</button><button disabled={busy} onClick={()=>prepare(saved.held?'release':'hold')}>{saved.held?'Review release':'Review hold'}</button>{saved.needsReview&&<button disabled={busy} onClick={()=>prepare('acknowledge_reopen')}>Review reopened invoice</button>}</div>}
  </>}
  {preview&&<section className="exception-confirm" aria-label="Confirm invoice status change"><h3>Review {preview.action.replaceAll('_',' ')}</h3><p>{preview.reason}</p>{preview.action==='set_notes'&&<><p>Note: {preview.note||'Clear note'}</p><p>Dispute: {preview.dispute||'Clear dispute'}</p></>}{preview.action==='hold'&&<p>Review date: {preview.reviewDate??'Not specified'}</p>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this invoice and the change</label><button onClick={()=>setPreview(null)}>Cancel status change</button><button disabled={!confirmed||busy} onClick={()=>submit(preview)}>Confirm status change</button></section>}
  {pending&&<button disabled={busy} onClick={()=>submit(pending)}>Retry same status command</button>}
  {error&&<p role="alert" className="error-message">{error}</p>}{status&&<p role="status">{status}</p>}{busy&&<p role="status">Loading invoice status…</p>}
  <div className="exception-actions"><button disabled={busy||!!pending||!!preview} onClick={refresh}>Refresh invoice status</button><button disabled={busy||!saved||!!pending||!!preview} onClick={()=>readHistory(0)}>View status history</button></div>
  {history&&<section aria-label="Invoice status history">{history.rows.map(row=><article key={row.revision}><b>{row.action.replaceAll('_',' ')}</b><p>{row.reason}</p><small>Revision {row.revision} · {new Date(row.recordedAt).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})} ICT</small></article>)}{!history.rows.length&&<p>No status changes recorded.</p>}<button disabled={busy||!historyPage} onClick={()=>readHistory(historyPage-1)}>Previous status changes</button><button disabled={busy||(historyPage+1)*10>=history.total} onClick={()=>readHistory(historyPage+1)}>More status changes</button></section>}
 </details>;
}
