import {useEffect,useRef,useState} from 'react';
import {parseSettings,type Recipients} from '../../worker/settings/validation';
import './account-settings.css';
type Saved={revision:number;billing_required:boolean|null;credit_term:number|null;billing_recipients:Recipients;collection_recipients:Recipients};
const fields=['to','cc','bcc'] as const;
async function responseValue(r:Response):Promise<Saved>{const value:unknown=await r.json();if(!value||typeof value!=='object')throw Error('settings_unavailable');const v=value as Record<string,unknown>;if(!r.ok)throw Error(typeof v.error==='string'?v.error:'settings_unavailable');const checked=parseSettings({revision:v.revision,billingRequired:v.billing_required,creditTerm:v.credit_term,billingRecipients:v.billing_recipients,collectionRecipients:v.collection_recipients});return {revision:checked.revision,billing_required:checked.billingRequired,credit_term:checked.creditTerm,billing_recipients:checked.billingRecipients,collection_recipients:checked.collectionRecipients};}
const message=(e:string)=>e.includes('conflict')?'Settings changed in another session. Reload the saved version before saving again.':e==='settings_invalid'?'Check the credit term and email addresses. Use each address only once per recipient profile.':'Settings could not be saved. Your edits are still here.';
export function AccountSettings({hotel,accountId,token,onSaved}:{hotel:string;accountId:string;token:string;onSaved?:()=>void}){
 const auth=useRef(token);auth.current=token;const saving=useRef(false);const [saved,setSaved]=useState<Saved|null>(null),[mode,setMode]=useState('unset'),[term,setTerm]=useState(''),[recipients,setRecipients]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Loading account settings…');
 const [section,setSection]=useState('Billing rules');
 const url=`/api/account-settings/${encodeURIComponent(hotel)}/${encodeURIComponent(accountId)}`;
 const apply=(v:Saved)=>{setSaved(v);setMode(v.billing_required===null?'unset':v.billing_required?'required':'not_required');setTerm(v.credit_term===null?'':String(v.credit_term));setRecipients(Object.fromEntries(['billing','collection'].flatMap(p=>fields.map(k=>[`${p}_${k}`,v[p==='billing'?'billing_recipients':'collection_recipients'][k].join(', ')]))));};
 useEffect(()=>{let live=true;const c=new AbortController();setSaved(null);setError('');setStatus('Loading account settings…');fetch(url,{headers:{Authorization:`Bearer ${auth.current}`},signal:c.signal}).then(async r=>{return responseValue(r);}).then(v=>{if(live){apply(v);setStatus('');}}).catch(()=>{if(live){setError('Account settings are unavailable. Reload this account to retry.');setStatus('');}});return()=>{live=false;c.abort();};},[url]);
 async function reload(){setBusy(true);try{const r=await fetch(url,{headers:{Authorization:`Bearer ${auth.current}`}});apply(await responseValue(r));setError('');setStatus('Saved settings loaded.');}catch{setError('Saved settings are unavailable. Your edits are retained.');}finally{setBusy(false);}}
 async function save(){if(saving.current||!saved)return;saving.current=true;setBusy(true);setError('');setStatus('');try{
  const profile=(purpose:string)=>Object.fromEntries(fields.map(k=>[k,(recipients[`${purpose}_${k}`]??'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)]));
  const body=parseSettings({revision:saved.revision,billingRequired:mode==='unset'?null:mode==='required',creditTerm:term.trim()===''?null:Number(term),billingRecipients:profile('billing'),collectionRecipients:profile('collection')});
  const r=await fetch(url,{method:'PUT',headers:{Authorization:`Bearer ${auth.current}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await responseValue(r);apply(v);setStatus('Account settings saved. Initial rules apply to existing open invoices and new arrivals.');onSaved?.();
 }catch(e){setError(message(e instanceof Error?e.message:''));}finally{saving.current=false;setBusy(false);}}
 if(!saved)return <section className="panel account-config"><h2>Account settings</h2><p role="status">{status}</p>{error&&<p role="alert">{error}</p>}</section>;
 return <section className="panel account-config"><header><div><h2>Account settings</h2><p>{hotel} · Billing rules and purpose-specific recipients</p></div><span>Revision {saved.revision}</span></header><div className="account-config-body"><nav aria-label="Settings sections">{['Billing rules','Billing recipients','Collection recipients'].map(s=><button type="button" className={section===s?'selected':''} key={s} onClick={()=>setSection(s)}>{s}</button>)}</nav><div className="account-config-form">
 {section==='Billing rules'?<><h3>Billing rules</h3><div className="settings-pair"><label>Billing requirement<select value={mode} onChange={e=>setMode(e.target.value)} disabled={busy}><option value="unset">Not configured</option><option value="required">Billing required</option><option value="not_required">Billing not required</option></select></label><label>Credit term (calendar days)<input type="number" min="0" step="1" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Not configured" disabled={busy}/></label></div><p className="settings-help">Initial rules apply to existing open invoices and new arrivals. Later changes apply to invoices without assigned rules; established terms and history are retained.</p><p className="settings-help">Billing required: due date starts from the actual first billing date. Billing not required: due date uses the OPERA bill date. Missing terms remain unconfigured; zero means zero days.</p><p className="settings-help">Initial history is Not billed / No reminders sent. Correct earlier billing or reminders from the invoice detail panel.</p></>:<><h3>{section}</h3><p>Enter email addresses only, separated by commas or new lines. No OPERA email fallback is used.</p>{fields.map(k=>{const p=section==='Billing recipients'?'billing':'collection',key=`${p}_${k}`;return <label key={key}>{k==='to'?'To':k.toUpperCase()}<textarea rows={2} aria-label={`${p==='billing'?'Billing':'Collection'} ${k==='to'?'To':k.toUpperCase()}`} value={recipients[key]??''} onChange={e=>setRecipients({...recipients,[key]:e.target.value})} placeholder="name@example.com" disabled={busy}/></label>;})}</>}
 {error&&<p className="error-message" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}<footer><button type="button" onClick={reload} disabled={busy}>Discard edits and reload</button><button type="button" className="primary-button" onClick={save} disabled={busy}>{busy?'Saving…':'Save account settings'}</button></footer></div></div></section>;
}
