import {useEffect,useMemo,useRef,useState} from 'react';
import {Search,RefreshCw,Check,ArrowLeft} from 'lucide-react';
import {useWorkspaceMember} from '../access/context';
import {regionHotels,type HotelId} from '../domain/hotels';
import {notifyRegisterChanged} from '../register/model';
import {bulkFields,parseSettingsPatch,type BulkField,type BulkPreview,type SettingsAccount,type SettingsCatalog,type SettingsPatch} from './bulk-model';
import {SortButton,compareValues} from '../table-sort';
import {filterSettingsAccounts,sortSettingsAccounts,type AccountSortKey} from './account-list';
import './bulk-settings.css';
const names:Record<BulkField,string>={billingRequired:'Billing requirement',creditTerm:'Credit term',billingMethod:'Billing type',billingPortal:'Billing portal',billingInstructions:'Billing instructions',collectionInstructions:'Collection instructions',billingRecipients:'Billing recipients',collectionRecipients:'Collection recipients'};
const identity=(a:{hotel:string;accountId:string})=>JSON.stringify([a.hotel,a.accountId]);
const requirement=(v:boolean|null)=>v===null?'Not configured':v?'Required':'Not required';
const errorText=(code:string)=>code==='access_forbidden'?'Some accounts are outside your access. Reload the account list.':code==='bulk_settings_limit'?'Select up to 500 accounts per save.':code==='bulk_settings_conflict'||code==='settings_revision_conflict'||code==='bulk_settings_membership_changed'?'Accounts or settings changed. Reload and review the selection again.':code==='settings_billing_handoff_pending'?'An account has a billing email awaiting verification. Resolve that handoff before applying these changes.':code==='bulk_settings_invalid'||code==='settings_invalid'?'Check the selected values and email addresses. Credit term must be a whole number from 0 to 3,650.':'The request could not be confirmed. Retry with the same selection.';
type Review=Omit<BulkPreview,'rows'>&{rows:(SettingsAccount&{changed:boolean;protected:boolean;after:Pick<SettingsAccount,'billingRequired'|'creditTerm'|'billingMethod'>})[]};
async function request<T>(token:string,path:string,body?:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch('/api/account-settings/bulk'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...body?{'Content-Type':'application/json'}:{}},...body?{body:JSON.stringify(body)}:{},signal:AbortSignal.any([...(signal?[signal]:[]),AbortSignal.timeout(30000)])});
 const value=await response.json();if(!value||typeof value!=='object'||Array.isArray(value))throw Error('bulk_settings_unavailable');const result=value as Record<string,unknown>;if(!response.ok||result.error)throw Error(typeof result.error==='string'?result.error:'bulk_settings_unavailable');return value as T;
}
export default function BulkAccountSettings({token,onDirtyChange}:{token:string;onDirtyChange:(value:boolean)=>void}){
 const access=useWorkspaceMember(),allowed=useMemo(()=>[...new Set((access?.regions??[]).flatMap(regionHotels))],[access?.regions.join('|')]);
 const [catalog,setCatalog]=useState<SettingsCatalog|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[reload,setReload]=useState(0);
 const [mode,setMode]=useState<'accounts'|'types'>('accounts'),[hotels,setHotels]=useState<HotelId[]>(allowed),[types,setTypes]=useState<string[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set());
 const [sort,setSort]=useState<{key:AccountSortKey;descending:boolean}>({key:'name',descending:false}),[reviewSort,setReviewSort]=useState<{key:AccountSortKey;descending:boolean}>({key:'name',descending:false});
 const [defaultSort,setDefaultSort]=useState<{key:'hotel'|'type'|'fields';descending:boolean}>({key:'hotel',descending:false});
 const [billingFilter,setBillingFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[termFilter,setTermFilter]=useState('all'),[invoiceFilter,setInvoiceFilter]=useState('all');
 const [enabled,setEnabled]=useState<Set<BulkField>>(new Set()),[values,setValues]=useState<Record<string,string>>({billingRequired:'true',creditTerm:'30',billingMethod:'email'});
 const [preview,setPreview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[uncertain,setUncertain]=useState(false);
 const [fieldErrors,setFieldErrors]=useState<Partial<Record<BulkField,string>>>({});
 const fieldHosts=useRef<Partial<Record<BulkField,HTMLDivElement|null>>>({});
 const feedback=(key:BulkField)=>({'aria-invalid':fieldErrors[key]?true:undefined,'aria-describedby':fieldErrors[key]?'bulk-error-'+key:undefined});
 const command=useRef<string|null>(null),lock=useRef(false),dirty=useRef(onDirtyChange),reviewRef=useRef<HTMLElement>(null);dirty.current=onDirtyChange;
 useEffect(()=>{dirty.current(enabled.size>0||busy||!!preview);},[enabled,busy,preview]);useEffect(()=>()=>dirty.current(false),[]);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setLoadError(false);
  void request<SettingsCatalog>(token,'',undefined,controller.signal).then(data=>{
   if(!Array.isArray(data.rows)||!Array.isArray(data.defaults)||!Number.isSafeInteger(data.total)||data.rows.length!==data.total||data.rows.some(r=>!allowed.includes(r.hotel)||typeof r.accountId!=='string'||typeof r.name!=='string'||typeof r.type!=='string'||!Number.isSafeInteger(r.revision)||!Number.isSafeInteger(r.invoices))||new Set(data.rows.map(identity)).size!==data.rows.length)throw Error('invalid_catalog');
   if(!controller.signal.aborted){setCatalog(data);setSelected(old=>new Set([...old].filter(key=>data.rows.some(r=>identity(r)===key))));}
  }).catch(()=>{if(!controller.signal.aborted)setLoadError(true);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
 },[token,reload,allowed]);
 useEffect(()=>{if(preview)reviewRef.current?.scrollIntoView({block:'start'});},[preview]);
 const allTypes=[...new Set([...(catalog?.rows.map(a=>a.type)??[]),...(catalog?.defaults.map(d=>d.type)??[])])].sort();
 const matching=(catalog?.rows??[]).filter(a=>hotels.includes(a.hotel)&&(!types.length||types.includes(a.type)));
 const shown=sortSettingsAccounts(filterSettingsAccounts(matching,{query,billing:billingFilter,status:statusFilter,term:termFilter,invoices:invoiceFilter}),sort.key,sort.descending,selected);
 const reviewRows=sortSettingsAccounts(preview?.rows??[],reviewSort.key,reviewSort.descending,selected,true);
 const defaultRows=[...(catalog?.defaults??[])].sort((a,b)=>compareValues(defaultSort.key==='fields'?Object.keys(a.patch).map(k=>names[k as BulkField]).sort().join(', '):a[defaultSort.key],defaultSort.key==='fields'?Object.keys(b.patch).map(k=>names[k as BulkField]).sort().join(', '):b[defaultSort.key],defaultSort.descending)||compareValues(a.hotel,b.hotel)||compareValues(a.type,b.type));
 const heading=(key:AccountSortKey,label:string,review=false)=>{const current=review?reviewSort:sort;return <th scope="col" aria-sort={current.key===key?current.descending?'descending':'ascending':'none'}><SortButton label={label} active={current.key===key} descending={current.descending} onClick={()=>{const setter=review?setReviewSort:setSort;setter(old=>({key,descending:old.key===key?!old.descending:['invoices','selected'].includes(key)}));}}/></th>;};
 const defaultHeading=(key:'hotel'|'type'|'fields',label:string)=><th scope="col" aria-sort={defaultSort.key===key?defaultSort.descending?'descending':'ascending':'none'}><SortButton label={label} active={defaultSort.key===key} descending={defaultSort.descending} onClick={()=>setDefaultSort(old=>({key,descending:old.key===key?!old.descending:false}))}/></th>;
 const clearListFilters=()=>{setQuery('');setBillingFilter('all');setStatusFilter('all');setTermFilter('all');setInvoiceFilter('all');};
 const chosen=mode==='types'?(types.length?matching:[]):(catalog?.rows??[]).filter(a=>selected.has(identity(a)));
 const resetPreview=()=>{setPreview(null);setError('');command.current=null;setUncertain(false);};
 const changeValue=(key:string,value:string)=>{setValues(old=>({...old,[key]:value}));const field=bulkFields.find(f=>key===f||key.startsWith(f+'_'));if(field)setFieldErrors(old=>({...old,[field]:undefined}));};
 const toggleField=(key:BulkField)=>setEnabled(old=>{const next=new Set(old);if(next.has(key))next.delete(key);else next.add(key);return next;});
 const patch=():SettingsPatch|null=>{
  const raw:Record<string,unknown>={};for(const key of enabled){
   if(key==='billingRequired')raw[key]=values[key]==='null'?null:values[key]==='true';
   else if(key==='creditTerm')raw[key]=values[key]?.trim()?Number(values[key]):null;
   else if(key==='billingRecipients'||key==='collectionRecipients')raw[key]=Object.fromEntries(['to','cc','bcc'].map(part=>[part,(values[key+'_'+part]??'').split(/[,;\n]/).map(v=>v.trim()).filter(Boolean)]));
   else raw[key]=values[key]?.trim()||(key==='billingPortal'?null:'');
  }
  const issues:Partial<Record<BulkField,string>>={};for(const key of enabled){try{parseSettingsPatch({[key]:raw[key]});}catch{issues[key]=key==='creditTerm'?'Enter a whole number from 0 to 3,650, or leave blank for Not configured.':key.endsWith('Recipients')?'Enter valid email addresses. Remove duplicates across To, Cc and Bcc.':key==='billingPortal'?'Enter an HTTPS URL, or leave blank to clear.':'Check this value and try again.';}}
  setFieldErrors(issues);const first=bulkFields.find(key=>issues[key]);if(first){requestAnimationFrame(()=>fieldHosts.current[first]?.querySelector<HTMLElement>('input,select,textarea')?.focus());return null;}return parseSettingsPatch(raw);
 };
 async function review(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');try{
  const selectedPatch=patch();if(!selectedPatch)return;
  const body={mode,accounts:chosen.map(({hotel,accountId,revision})=>({hotel,accountId,revision})),types:mode==='types'?hotels.flatMap(hotel=>types.map(type=>({hotel,type,revision:catalog?.defaults.find(d=>d.hotel===hotel&&d.type===type)?.revision??0}))):[],patch:selectedPatch};
  const result=await request<Review>(token,'/preview',body);if(!Array.isArray(result.rows)||result.rows.length!==result.accountCount||!Array.isArray(result.accounts)||!Array.isArray(result.types))throw Error('bulk_settings_unavailable');
  setPreview(result);command.current=crypto.randomUUID();
 }catch(e){setError(errorText(e instanceof Error?e.message:''));}finally{lock.current=false;setBusy(false);}}
 async function apply(){if(!preview||lock.current||!command.current)return;lock.current=true;setBusy(true);setError('');try{
  const {mode,accounts,types,patch}=preview;
  const result=await request<{saved:boolean;changed:number;invoices:number;defaults:number}>(token,'/apply',{mode,accounts,types,patch,commandId:command.current});
  if(result.saved!==true)throw Error('bulk_settings_unavailable');
  setSuccess(`Saved ${result.changed} accounts${result.defaults?` and ${result.defaults} hotel / type defaults`:''}.`);setPreview(null);setEnabled(new Set());setSelected(new Set());setUncertain(false);command.current=null;setReload(n=>n+1);notifyRegisterChanged();
 }catch(e){const code=e instanceof Error?e.message:'';setError(errorText(code));setUncertain(!['bulk_settings_conflict','bulk_settings_membership_changed','settings_revision_conflict','settings_billing_handoff_pending','access_forbidden','bulk_settings_invalid','settings_invalid'].includes(code));}finally{lock.current=false;setBusy(false);}}
 return <main className="page bulk-settings"><header className="bulk-heading"><div><h1>Account settings</h1></div><button disabled={busy||uncertain} onClick={()=>{resetPreview();setReload(n=>n+1);}}><RefreshCw size={15}/>Reload accounts</button></header>
  {success&&<p className="bulk-success" role="status"><Check size={16}/>{success}</p>}{error&&<p className="error-message" role="alert">{error}</p>}
  {preview?<section ref={reviewRef} className="bulk-review" aria-label="Review account settings"><header><h2>Review changes</h2><button disabled={busy||uncertain} onClick={resetPreview}><ArrowLeft size={14}/>Edit selection</button></header><p><strong>{preview.accountCount} accounts</strong> · {preview.changedCount} will change · {preview.invoiceCount} invoice rules will update{preview.defaultsCount?` · ${preview.defaultsCount} type defaults · explicit Account settings stay unchanged`:''}</p>
   <dl className="bulk-patch-summary">{Object.entries(preview.patch).map(([key,value])=><div key={key}><dt>{names[key as BulkField]}</dt><dd>{key==='billingRequired'?requirement(value as boolean|null):value===null||value===''?'Clear / not configured':typeof value==='object'?Object.entries(value).map(([part,list])=>`${part.toUpperCase()}: ${(list as string[]).join(', ')||'None'}`).join(' · '):String(value)}</dd></div>)}</dl>
   {!!preview.types.length&&<p className="bulk-default-summary">New-account defaults: {preview.types.map(t=>t.hotel+' · '+t.type).join(', ')}</p>}
   <div className="bulk-table-scroll" role="region" aria-label="Accounts receiving changes" tabIndex={0}><table><thead><tr>{heading('hotel','Hotel',true)}{heading('name','Account',true)}{heading('type','Type',true)}{heading('billingRequired','Billing requirement',true)}{heading('creditTerm','Credit term',true)}{heading('result','Result',true)}</tr></thead><tbody>{reviewRows.map(r=><tr key={identity(r)}><td>{r.hotel}</td><td>{r.name}</td><td>{r.type}</td><td>{requirement(r.billingRequired)} → {requirement(r.after.billingRequired)}</td><td>{r.creditTerm??'—'} → {r.after.creditTerm??'—'}</td><td>{r.protected?'Keeps Account settings':r.changed?'Will update':'Unchanged'}</td></tr>)}</tbody></table></div>
   <footer className="bulk-actions"><span>{uncertain?'Retry keeps the same save request.':'Actual billing and reminder history will be kept.'}</span><button className="primary-button" disabled={busy} onClick={()=>void apply()}>{busy?'Saving…':uncertain?'Retry save':'Apply changes'}</button></footer>
  </section>:<fieldset className="bulk-work-form" disabled={busy}>
   {!!catalog?.defaults.length&&<details className="bulk-saved-defaults"><summary>Saved Account Type defaults · {catalog.defaults.length}</summary><div className="bulk-table-scroll"><table><thead><tr>{defaultHeading('hotel','Hotel')}{defaultHeading('type','Account type')}{defaultHeading('fields','Default fields')}<th></th></tr></thead><tbody>{defaultRows.map(d=><tr key={JSON.stringify([d.hotel,d.type])}><td>{d.hotel}</td><td>{d.type}</td><td>{Object.keys(d.patch).map(k=>names[k as BulkField]).join(', ')}</td><td><button onClick={()=>{const next:Record<string,string>={};for(const [key,value] of Object.entries(d.patch)){if(key.endsWith('Recipients'))for(const [part,list] of Object.entries(value as NonNullable<SettingsPatch['billingRecipients']>))next[key+'_'+part]=list.join(', ');else next[key]=value===null?(key==='billingRequired'?'null':''):String(value);}setMode('types');setHotels([d.hotel]);setTypes([d.type]);setSelected(new Set());setValues(next);setEnabled(new Set(Object.keys(d.patch) as BulkField[]));}}>Edit {d.hotel} · {d.type}</button></td></tr>)}</tbody></table></div></details>}
   <section className="bulk-scope" aria-label="Choose account scope"><fieldset className="bulk-mode"><legend>Set by</legend>{(['accounts','types'] as const).map(value=><label key={value}><input type="radio" name="bulk-mode" value={value} checked={mode===value} onChange={()=>{setMode(value);setSelected(new Set());}}/>{value==='accounts'?'Selected accounts':'Account types · fallback defaults'}</label>)}</fieldset>
    <fieldset><legend>Hotels</legend><div className="bulk-options">{allowed.map(h=><label key={h}><input type="checkbox" checked={hotels.includes(h)} onChange={()=>{setHotels(old=>old.includes(h)?old.filter(v=>v!==h):[...old,h]);setSelected(new Set());}}/>{h}</label>)}</div></fieldset>
    <fieldset><legend>Account types {mode==='accounts'&&<small>· optional filter</small>}</legend><div className="bulk-options">{allTypes.map(type=><label key={type}><input type="checkbox" checked={types.includes(type)} onChange={()=>{setTypes(old=>old.includes(type)?old.filter(t=>t!==type):[...old,type]);setSelected(new Set());}}/>{type}</label>)}</div></fieldset>
   </section>
   <section aria-label="Choose accounts" className="bulk-selection"><div className="bulk-list-tools"><label className="bulk-search"><Search size={16}/><input type="search" placeholder="Account, number, hotel, type or status" aria-label="Search account settings" value={query} onChange={e=>setQuery(e.target.value)}/></label><strong>{chosen.length} selected</strong><span className="bulk-shown-count">{shown.length} shown / {matching.length}</span>{mode==='accounts'&&<><button disabled={!shown.length||loading} onClick={()=>setSelected(old=>new Set([...old,...shown.map(identity)]))}>Select all shown</button><button disabled={!selected.size} onClick={()=>setSelected(new Set())}>Clear selection</button></>}</div>
    <div className="bulk-list-filters" role="group" aria-label="Account list filters"><label>Billing<select aria-label="Filter billing requirement" value={billingFilter} onChange={e=>setBillingFilter(e.target.value)}><option value="all">All billing requirements</option><option value="required">Billing required</option><option value="not_required">Billing not required</option><option value="unset">Not configured</option></select></label><label>Setting status<select aria-label="Filter setting status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All setting statuses</option><option value="account">Own Account settings</option><option value="type">Using Type defaults</option><option value="none">No saved settings</option><option value="setup">Setup needed</option></select></label><label>Credit term<select aria-label="Filter credit term" value={termFilter} onChange={e=>setTermFilter(e.target.value)}><option value="all">All credit terms</option><option value="unset">Not configured</option><option value="short">Under 7 days</option><option value="standard">7–30 days</option><option value="long">Over 30 days</option></select></label><label>Invoices<select aria-label="Filter invoice count" value={invoiceFilter} onChange={e=>setInvoiceFilter(e.target.value)}><option value="all">All accounts</option><option value="with">With invoices</option><option value="without">Without invoices</option></select></label><button disabled={!query&&[billingFilter,statusFilter,termFilter,invoiceFilter].every(v=>v==='all')} onClick={clearListFilters}>Clear list filters</button></div>
    {mode==='types'&&<p className="bulk-scope-count">Type scope: all {chosen.length} accounts in the selected Hotel / Type groups.</p>}
    {loading?<p role="status">Loading accounts…</p>:loadError?<p role="alert">Account settings could not be loaded. <button onClick={()=>setReload(n=>n+1)}>Retry</button></p>:<div className="bulk-table-scroll bulk-account-list" role="region" aria-label="Account settings selection" tabIndex={0}><table><thead><tr>{heading('selected','Select')}{heading('name','Account')}{heading('hotel','Hotel')}{heading('type','Type')}{heading('billingRequired','Billing')}{heading('creditTerm','Term · days')}{heading('invoices','Invoices')}</tr></thead><tbody>{shown.map(a=><tr key={identity(a)} className={chosen.some(r=>identity(r)===identity(a))?'is-selected':''}><td><input type="checkbox" aria-label={`Select ${a.hotel} account ${a.name}`} checked={mode==='types'?types.length>0:selected.has(identity(a))} disabled={mode==='types'} onChange={()=>setSelected(old=>{const next=new Set(old);if(next.has(identity(a)))next.delete(identity(a));else next.add(identity(a));return next;})}/></td><td><strong>{a.name}</strong><small>{a.accountNo??a.accountId}{a.source==='type'?' · Type default':a.source==='none'?' · Setup needed':''}</small></td><td>{a.hotel}</td><td>{a.type}</td><td>{requirement(a.billingRequired)}</td><td>{a.creditTerm??'—'}</td><td>{a.invoices}</td></tr>)}</tbody></table>{!shown.length&&<p>No accounts match these filters.</p>}</div>}
   </section>
   <section className="bulk-editor" aria-label="Choose settings to change"><h2>Fields to change</h2><p>Unchecked fields keep their current values.</p><div className="bulk-fields">{bulkFields.map(key=><div className={'bulk-field'+(enabled.has(key)?' is-enabled':'')} key={key}><label className="bulk-field-switch"><input type="checkbox" checked={enabled.has(key)} onChange={()=>toggleField(key)}/>{names[key]}</label>{enabled.has(key)&&<div className="bulk-field-value" ref={el=>{fieldHosts.current[key]=el;}}>
    {key==='billingRequired'?<select {...feedback(key)} aria-label="New billing requirement" value={values[key]??'true'} onChange={e=>changeValue(key,e.target.value)}><option value="true">Billing required</option><option value="false">Billing not required</option><option value="null">Not configured</option></select>:key==='creditTerm'?<input {...feedback(key)} type="number" aria-label="New credit term" min="0" max="3650" step="1" placeholder="Not configured" value={values[key]??''} onChange={e=>changeValue(key,e.target.value)}/>:key==='billingMethod'?<select {...feedback(key)} aria-label="New billing type" value={values[key]??'email'} onChange={e=>changeValue(key,e.target.value)}><option value="email">By Email</option><option value="system">By System</option></select>:key==='billingPortal'?<input {...feedback(key)} type="url" aria-label="New billing portal" placeholder="Leave blank to clear" value={values[key]??''} onChange={e=>changeValue(key,e.target.value)}/>:key.endsWith('Recipients')?<>{['to','cc','bcc'].map(part=><label key={part}>{part.toUpperCase()}<textarea {...feedback(key)} rows={2} aria-label={`${names[key]} ${part.toUpperCase()}`} placeholder="Addresses separated by commas; blank clears this list" value={values[key+'_'+part]??''} onChange={e=>changeValue(key+'_'+part,e.target.value)}/></label>)}</>:<textarea {...feedback(key)} rows={3} maxLength={4000} aria-label={'New '+names[key].toLowerCase()} placeholder="Leave blank to clear" value={values[key]??''} onChange={e=>changeValue(key,e.target.value)}/>}
   {fieldErrors[key]&&<p id={"bulk-error-"+key} className="error-message" role="alert">{fieldErrors[key]}</p>}</div>}</div>)}</div><footer className="bulk-actions"><span>{chosen.length} accounts{mode==='types'?` · ${hotels.length*types.length} hotel / type defaults`:''}</span><button className="primary-button" disabled={busy||loading||loadError||!enabled.size||!hotels.length||mode==='accounts'&&!chosen.length||mode==='types'&&!types.length} onClick={()=>void review()}>{busy?'Preparing review…':'Review changes'}</button></footer></section>
  </fieldset>}
 </main>;
}
