import {useRef,useState} from 'react';
import type {Invoice} from '../domain/portfolio';
import './account-settings.css';
export function HistoryEditor({invoice,token,onSaved}:{invoice:Invoice;token:string;onSaved?:()=>void}){
 const initial=invoice.workflow!;const auth=useRef(token);auth.current=token;const lock=useRef(false);
 const [revision,setRevision]=useState(initial.revision),[billing,setBilling]=useState(initial.first_billing_date??''),[stage,setStage]=useState(initial.last_reminder_stage??''),[sent,setSent]=useState(initial.last_reminder_date??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setStatus('');try{const r=await fetch(`/api/invoice-history/${encodeURIComponent(invoice.hotel)}/${encodeURIComponent(invoice.accountId)}/${encodeURIComponent(invoice.id)}`,{method:'PUT',headers:{Authorization:`Bearer ${auth.current}`,'Content-Type':'application/json'},body:JSON.stringify({revision,firstBillingDate:billing||null,lastReminderStage:stage||null,lastReminderDate:stage?(sent||null):null})});const value:unknown=await r.json();if(!value||typeof value!=='object')throw Error();const v=value as {error?:string;revision?:number};if(!r.ok)throw Error(v.error);if(!Number.isSafeInteger(v.revision))throw Error();setRevision(v.revision!);setStatus('History saved. No email was sent.');onSaved?.();}catch(e){setError(e instanceof Error&&e.message.includes('conflict')?'History changed elsewhere. Reload this invoice before saving.':'Check the dates and reminder stage. Future actual dates are not allowed. Your edits are retained.');}finally{lock.current=false;setBusy(false);}}
 return <details className="history-editor"><summary>Billing & reminder history</summary><p>Initial history is Not billed / No reminders sent. Enter actual historical dates to correct it. This does not send an email or create a send event for today.</p><label>First actual billing date<input type="date" value={billing} onChange={e=>setBilling(e.target.value)} disabled={busy}/></label><label>Latest reminder sent<select value={stage} onChange={e=>{setStage(e.target.value);if(!e.target.value)setSent('');}} disabled={busy}><option value="">No reminders sent</option>{['Friendly','Follow 1','Follow 2','Follow 3','Final'].map(v=><option key={v}>{v}</option>)}</select></label>{stage&&<label>Actual reminder date<input type="date" value={sent} onChange={e=>setSent(e.target.value)} disabled={busy}/></label>}{error&&<p role="alert" className="error-message">{error}</p>}{status&&<p role="status">{status}</p>}<button className="primary-button" onClick={save} disabled={busy||!!stage&&!sent}>{busy?'Saving…':'Save history'}</button></details>;
}
