import {useEffect,useRef,useState} from 'react';
import {parseCollectionPolicy,parsePolicyCommand,type CollectionPolicy,type CollectionRound,type PolicyCommand} from '../domain/collection-policy';
import {useCollectionPolicy} from './PolicyContext';
import './collection-policy.css';
export default function CollectionPolicySettings({token,onBack,onDirtyChange}:{token:string;onBack:()=>void;onDirtyChange?:(value:boolean)=>void}){
 const current=useCollectionPolicy(),[saved,setSaved]=useState<CollectionPolicy|null>(null),[rounds,setRounds]=useState<CollectionRound[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<PolicyCommand|null>(null),[pending,setPending]=useState<PolicyCommand|null>(null),[confirmed,setConfirmed]=useState(false);
 const [dayEdits,setDayEdits]=useState<Record<string,string>>({});
 const [history,setHistory]=useState<{rows:(CollectionPolicy&{reason:string;recordedAt:string})[];total:number}|null>(null),[historyPage,setHistoryPage]=useState(0);
 const auth=useRef(token);auth.current=token;const callbacks=useRef({onDirtyChange});callbacks.current={onDirtyChange};const lock=useRef(false),alive=useRef(true);
 const dirty=!!saved&&(JSON.stringify(saved.rounds)!==JSON.stringify(rounds)||Object.entries(dayEdits).some(([key,value])=>value!==String(rounds.find(r=>r.key===key)?.offsetDays))||!!reason.trim())||!!preview||!!pending;
 useEffect(()=>{callbacks.current.onDirtyChange?.(dirty);},[dirty]);useEffect(()=>{alive.current=true;return()=>{alive.current=false;callbacks.current.onDirtyChange?.(false);};},[]);
 useEffect(()=>{if(!saved&&current.policy){setSaved(current.policy);setRounds(current.policy.rounds);setDayEdits({});}},[current.policy]);
 function change(index:number,patch:Partial<CollectionRound>){setRounds(rows=>rows.map((r,i)=>i===index?{...r,...patch}:r));setStatus('');}
 function move(index:number,step:number){const next=[...rounds],other=index+step;if(other<0||other>=next.length)return;[next[index],next[other]]=[next[other],next[index]];setRounds(next);}
 function add(){const next=[...rounds],terminal=next.findIndex(r=>r.active&&r.terminal),round:CollectionRound={key:`round_${crypto.randomUUID()}`,label:'New follow-up',anchor:'previous_sent',offsetDays:7,terminal:false,active:true};next.splice(terminal<0?next.length:terminal,0,round);setRounds(next);}
 function review(){if(!saved)return;try{const edited=rounds.map(r=>{const raw=dayEdits[r.key]??String(r.offsetDays);if(!/^-?[0-9]+$/.test(raw))throw Error('invalid days');return {...r,offsetDays:Number(raw)};});parseCollectionPolicy({version:saved.version,rounds:edited},saved);setPreview(parsePolicyCommand({commandId:crypto.randomUUID(),revision:saved.version,confirmed:true,reason,rounds:edited}));setConfirmed(false);setError('');}catch{setError('Give each active round a unique label, keep due-date offsets increasing before follow-ups, and mark only the last active round as terminal. Enter a reason. Retire a round instead of removing its history.');}}
 async function publish(command:PolicyCommand){if(lock.current)return;lock.current=true;setBusy(true);setPending(command);setPreview(null);setError('');try{const r=await fetch('/api/collection-policy',{method:'PUT',headers:{Authorization:`Bearer ${auth.current}`,'Content-Type':'application/json'},body:JSON.stringify(command)});const value=await r.json();if(!r.ok){const code=value&&typeof value==='object'&&'error'in value?value.error:null;if(code==='policy_revision_conflict'||code==='policy_invalid'||code==='policy_retirement_required'){setPending(null);throw Error('Rules changed or need correction. Reload the current version before publishing. Your edits are retained.');}throw Error('The publish result is uncertain. Retry the same command.');}const next=parseCollectionPolicy(value);if(alive.current){setSaved(next);setRounds(next.rounds);setDayEdits({});setReason('');setPending(null);setStatus(`Collection rules version ${next.version} saved. Existing sent history is retained.`);await current.refresh();}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Rules could not be published.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function loadHistory(page:number){setBusy(true);setError('');try{const r=await fetch(`/api/collection-policy/history?page=${page}&limit=10`,{headers:{Authorization:`Bearer ${auth.current}`}});if(!r.ok)throw Error();const v=await r.json() as {rows:(CollectionPolicy&{reason:string;recordedAt:string})[];total:number};if(alive.current){setHistory(v);setHistoryPage(page);}}catch{if(alive.current)setError('Rule history is unavailable. Retry the read.');}finally{if(alive.current)setBusy(false);}}
 return <main className="page collection-policy"><button onClick={onBack}>Back to Collections</button><header><div><h1>Collection rules</h1><p>One versioned sequence for KAT and TSK. People choose when to send.</p></div>{saved&&<span>Editing version {saved.version}</span>}</header>
  {!saved?<section className="panel policy-panel"><p role="status">{current.loading?'Loading collection rules…':current.error||'Collection rules unavailable.'}</p><button onClick={current.refresh}>Retry loading rules</button></section>:<section className="panel policy-panel"><p>Offsets use calendar days. After an actual terminal reminder, any remaining open balance is urgent immediately. A hold or review can block new handoff while urgent remains visible.</p>
  <div className="policy-table-scroll" role="region" aria-label="Collection round editor" tabIndex={0}><table><thead><tr>{['Order','Round label','Timing from','Days','Active','Terminal','Move'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rounds.map((round,i)=><tr key={round.key} className={round.active?'':'retired'}><td>{i+1}</td><td><input aria-label={`Round ${i+1} label`} value={round.label} maxLength={80} onChange={e=>change(i,{label:e.target.value})} disabled={busy||!!pending||!!preview}/>{!round.active&&<small>Retired · history retained</small>}</td><td><select aria-label={`Round ${i+1} timing`} value={round.anchor} onChange={e=>change(i,{anchor:e.target.value as CollectionRound['anchor']})} disabled={busy||!!pending||!!preview}><option value="due">Due date</option><option value="previous_sent">Previous actual send</option></select></td><td><input aria-label={`Round ${i+1} days`} type="text" inputMode="numeric" value={dayEdits[round.key]??String(round.offsetDays)} onChange={e=>setDayEdits(values=>({...values,[round.key]:e.target.value}))} disabled={busy||!!pending||!!preview}/></td><td><input type="checkbox" aria-label={`Round ${i+1} active`} checked={round.active} onChange={e=>change(i,{active:e.target.checked})} disabled={busy||!!pending||!!preview}/></td><td><input type="radio" name="terminal-round" aria-label={`Round ${i+1} terminal`} checked={round.terminal} onChange={()=>setRounds(rows=>rows.map((r,n)=>({...r,terminal:n===i})))} disabled={busy||!!pending||!!preview||!round.active}/></td><td><button aria-label={`Move round ${i+1} earlier`} disabled={!i||busy||!!pending||!!preview} onClick={()=>move(i,-1)}>↑</button><button aria-label={`Move round ${i+1} later`} disabled={i===rounds.length-1||busy||!!pending||!!preview} onClick={()=>move(i,1)}>↓</button></td></tr>)}</tbody></table></div>
  <button disabled={busy||!!pending||!!preview||rounds.length>=100} onClick={add}>Add collection round</button><label>Reason for rule change<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2} maxLength={1000} disabled={busy||!!pending||!!preview}/></label>
  <footer><button disabled={busy||!!pending} onClick={async()=>{if(dirty&&!window.confirm('Discard rule edits and load the current version?'))return;setSaved(null);setRounds([]);setDayEdits({});setReason('');setPreview(null);await current.refresh();}}>Discard edits and reload rules</button><button disabled={busy||!!pending||!!preview} onClick={review}>Review rule changes</button><button disabled={busy||!!pending||!!preview} onClick={()=>loadHistory(0)}>View rule history</button></footer></section>}
  {preview&&<section className="panel policy-confirm" aria-label="Review collection rule changes"><h2>Review new rule version</h2><p>{preview.reason}</p><ol>{preview.rounds.filter(r=>r.active).map(r=><li key={r.key}><b>{r.label}</b> · {r.offsetDays>=0?'+':''}{r.offsetDays} days from {r.anchor==='due'?'due date':'previous actual send'}{r.terminal?' · Terminal → Urgent if unpaid':''}</li>)}</ol><p>Pending and sent messages retain their captured rule version. This does not create drafts or send email.</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this collection sequence</label><button onClick={()=>setPreview(null)}>Cancel rule review</button><button disabled={!confirmed||busy} onClick={()=>publish(preview)}>Publish collection rules</button></section>}
  {pending&&<button disabled={busy} onClick={()=>publish(pending)}>Retry same rule command</button>}{error&&<p className="error-message" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}
  {history&&<section className="panel policy-panel"><h2>Rule history</h2>{history.rows.map(v=><details key={v.version}><summary>Version {v.version} · {v.reason}</summary><ol>{v.rounds.map(r=><li key={r.key}>{r.label} · {r.active?'Active':'Retired'} · {r.offsetDays} days</li>)}</ol></details>)}<button disabled={busy||!historyPage} onClick={()=>loadHistory(historyPage-1)}>Previous rule versions</button><button disabled={busy||(historyPage+1)*10>=history.total} onClick={()=>loadHistory(historyPage+1)}>More rule versions</button></section>}
 </main>;
}
