import {useState} from 'react';
import {ArrowUpRight,Check,ChevronRight,FileText,Search} from 'lucide-react';
import type {Group} from '../CollectionQueue';
import {stageLabel as sentLabel} from '../domain/collection';
import {legacyStageSnapshot} from '../domain/collection-policy';
import {money} from '../domain/portfolio';
export function QueueWorkPanel({group,label,stages,stageLabel,onStage,selected,onToggle,onSelect,onClear,onPrepare,onAccount}:{group:Group;label:string;stages:Group[];stageLabel:(g:Group)=>string;onStage:(key:string)=>void;selected:ReadonlySet<string>;onToggle:(id:string)=>void;onSelect:(ids:string[])=>void;onClear:()=>void;onPrepare:()=>void;onAccount:()=>void}){
 const [query,setQuery]=useState(''),[selectedOnly,setSelectedOnly]=useState(false);
 const canPrepare=!['Needs review','On hold'].includes(group.stage);
 const eligible=group.rows.filter(r=>r.collection_selectable&&r.verification_state==='verified'),picked=eligible.filter(r=>selected.has(r.id));
 const shown=group.rows.filter(r=>(!selectedOnly||selected.has(r.id))&&`${r.invoice_no??''} ${r.folio_no??''} ${r.guest}`.toLowerCase().includes(query.trim().toLowerCase()));
 const shownEligible=shown.filter(r=>r.collection_selectable&&r.verification_state==='verified');
 const selectedAmount=picked.reduce((n,r)=>n+Math.round(r.open*100),0)/100;
 return <>
  <header className="queue-detail-heading"><div className="queue-detail-context"><span className={'queue-hotel '+group.hotel.toLowerCase()}>{group.hotel}</span><span>{group.type}</span><strong title={`Open amount for ${label}`}><small>{stages.length>1?'This stage':'Open'}</small>{money(group.amount)}</strong></div><div className="queue-detail-title"><h2>{group.name}</h2>{stages.length===1&&<span className="queue-action-badge">{label}</span>}<button onClick={onAccount} aria-label="Open account details" title="Open account details"><ArrowUpRight size={18}/></button></div>
   {stages.length>1?<nav className="queue-work-stages" aria-label="Work stages for selected account">{stages.map(g=><button key={g.key} aria-pressed={g.key===group.key} onClick={()=>onStage(g.key)}>{stageLabel(g)}<b>{g.rows.length}</b></button>)}</nav>:null}
  </header>
  <div className="queue-invoice-tools"><div className="queue-invoice-toolbar"><label className="queue-find"><Search size={16} aria-hidden="true"/><input type="search" aria-label="Search selected account invoices" placeholder="Find invoice, folio or guest" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="queue-selected-filter" aria-pressed={selectedOnly} onClick={()=>setSelectedOnly(v=>!v)}><Check size={14}/>Selected {picked.length}</button></div><div className="queue-list-actions"><span>{shown.length} shown <small>· {group.purpose==='Review'?label:`${shown.filter(r=>r.action.ready).length} ready / ${shown.filter(r=>!r.action.ready).length} upcoming`}</small></span><div><button disabled={!canPrepare||!shownEligible.length||shownEligible.every(r=>selected.has(r.id))} onClick={()=>onSelect(shownEligible.map(r=>r.id))}>Select all shown</button><button disabled={!picked.length} onClick={onClear}>Clear selection</button></div></div></div>
  <div className="queue-invoice-list" role="group" aria-label="Invoices in selected work"><table className="queue-invoices"><thead><tr><th aria-label="Selection"></th><th>Invoice / Folio</th><th>Guest</th><th>Action date</th><th>Latest sent</th><th className="queue-invoice-amount">Open · THB</th></tr></thead><tbody>{shown.map(r=>{const disabled=!canPrepare||!r.collection_selectable||r.verification_state!=='verified';return <tr key={r.id} className={selected.has(r.id)?'selected':''} onClick={event=>{if(disabled||(event.target as HTMLElement).closest('input')||window.getSelection()?.type==='Range')return;onToggle(r.id);}}><td className="queue-invoice-check"><input type="checkbox" aria-label={`Queue select ${r.invoice_no??r.id}`} checked={selected.has(r.id)} disabled={disabled} onChange={()=>onToggle(r.id)}/></td><td className="queue-invoice-number"><b>{r.invoice_no??'Unavailable'}</b>{r.folio_no&&<small>Folio {r.folio_no}</small>}</td><td className="queue-invoice-guest">{r.guest||'—'}{r.action.reason&&<small className="queue-warning">{r.action.reason}</small>}</td><td className="queue-invoice-date"><span>{r.action.date??'—'}</span><small className={'queue-invoice-timing '+(group.purpose==='Review'?'attention':r.action.ready?'ready':'upcoming')}>{group.purpose==='Review'?label:r.action.ready?'Ready':'Upcoming'}</small></td><td className="queue-invoice-latest">{sentLabel(r.action.latest,undefined,r.workflow?.last_reminder_stage_snapshot??legacyStageSnapshot(r.action.latest))}</td><td className="queue-invoice-amount">{money(r.open,false).replace('THB ','')}</td></tr>;})}</tbody></table>{!shown.length&&<div className="queue-invoice-empty">{selectedOnly?'No selected invoices in this view.':'No invoices match this search.'}{selectedOnly&&<button onClick={()=>setSelectedOnly(false)}>Show all invoices</button>}</div>}</div>
  <footer className="queue-selection-footer"><div aria-live="polite" aria-atomic="true"><span>{picked.length} selected</span><strong>THB {selectedAmount.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong></div>{canPrepare?<button className="primary-button" disabled={!picked.length} onClick={onPrepare}><FileText size={17}/>Prepare documents<ChevronRight size={17}/></button>:<button onClick={onAccount}>Review account<ArrowUpRight size={16}/></button>}</footer>
 </>;
}
