import { useState } from 'react';
import { ArrowLeft, FileText, X, ChevronRight } from 'lucide-react';
import { type Account, type Invoice, money, sortRows, selectionTotal } from './domain/portfolio';
import { agingLabels } from './demo';
import { Metric, Freshness, SearchBox, SortHead } from './ui';
export function AccountDetail({account, invoices, review, back}:{account:Account; invoices:Invoice[]; review:boolean; back:()=>void}) {
  const [selected,setSelected]=useState<Set<string>>(new Set());
  const [focused,setFocused]=useState<Invoice|null>(invoices[0]??null);
  const [drawer,setDrawer]=useState(false), [aging,setAging]=useState(true);
  const [search,setSearch]=useState(''), [sort,setSort]=useState<keyof Invoice>('guest'), [direction,setDirection]=useState<'asc'|'desc'>('asc');
  const [tab,setTab]=useState('Invoice / Folio');
  const rows=sortRows(invoices.filter(i=>`${i.guest} ${i.invoiceNo} ${i.folioNo}`.toLowerCase().includes(search.toLowerCase())),sort,direction);
  const columns:[string,keyof Invoice][]=[['Guest Name','guest'],['Invoice No.','invoiceNo'],['Folio No.','folioNo'],['Bill date','date'],['Due date','due'],['Original','original'],['Open','open'],['Aging','aging'],['Latest sent','stage']];
  const changeSort=(key:keyof Invoice)=>{setSort(key);setDirection(sort===key&&direction==='asc'?'desc':'asc');};
  const toggle=(id:string)=>setSelected(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next;});
  const detail=<><div className="detail-head"><small>Selected guest / item</small><h2>{focused?.guest??'Choose an invoice'}</h2><button className="drawer-close icon-button" aria-label="Close invoice details" onClick={()=>setDrawer(false)}><X size={18}/></button></div>{focused&&<><div className="detail-balance"><small>Open balance</small><strong>{money(focused.open)}</strong></div><dl className="detail-fields"><div><dt>Hotel</dt><dd>{account.hotel}</dd></div><div><dt>Account</dt><dd>{account.name}</dd></div><div><dt>Invoice no.</dt><dd>{focused.invoiceNo}</dd></div><div><dt>Folio no.</dt><dd>{focused.folioNo}</dd></div><div><dt>Latest sent stage</dt><dd>{focused.stage}</dd></div><div><dt>Due date</dt><dd>{focused.due??'Not billed'}</dd></div></dl>{focused.stage==='Final'&&focused.open>0&&<p className="urgent-note">Urgent · Final sent, balance remains open</p>}<h3>Available documents</h3><div className="document-placeholder"><FileText size={22}/><div><b>{review?'Document preview only':'No verified documents'}</b><small>OPERA document connection is not enabled.</small></div></div><div className="information-note">{review?'Synthetic review — these values are not customer data.':'Balances are read from OPERA. PDF changes never alter accounting values.'}</div></>}</>;
  return <main className="page account-page"><button className="breadcrumb" onClick={back}><ArrowLeft size={12}/> Portfolio / {account.type} / <b>{account.name}</b></button><div className="page-title"><div><h1>{account.name}</h1><p>Exact Hotel + Account workspace · Invoice / Folio selection stays inside {account.hotel}</p></div><div className="account-context"><span className="selected-hotel"><small>{account.hotel} · Selected</small><b>{money(account.open)}</b></span><Freshness review={review}/></div></div>
    <section className="account-metrics"><Metric label={`Total open · ${account.hotel}`} value={money(account.open)} note={`${invoices.length} displayed Invoice / Folio items`} accent="blue"/><Metric label="Credit limit / LOC" value={account.creditLimit?money(account.creditLimit):'Not set'} note={account.creditLimit?`${(account.open/account.creditLimit*100).toFixed(0)}% utilized`:undefined}/><Metric label="Over 90 days" value={money(account.over90)} accent="red-value"/><Metric label="Oldest open" value={account.oldest?`${account.oldest} days`:'—'} note="OPERA aging, separate from overdue"/><Metric label="Next action" value="Review account" note={review?'Synthetic review only':'OPERA connection pending'}/></section>
    <section className="panel account-aging"><b>Aging · {account.hotel}<small>{aging?'Expanded source buckets':'Source aging summary'}</small></b>{aging&&agingLabels.map((label,i)=><div className={`aging-value bucket-${i}`} key={label}><small>{label}</small><strong>{account.aging?money(account.aging[i]??0):review?money(account.open*[.164,.102,.156,.188,.219,.171][i]):'—'}</strong></div>)}<button className="small-button" onClick={()=>setAging(!aging)}>{aging?'Collapse':'Expand'} Aging</button></section>
    <nav className="account-tabs" aria-label="Account sections">{['Overview','Invoice / Folio'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}<span>Collection History</span><span>Documents & Gmail</span></nav>
    {tab==='Overview'?<section className="panel overview-info"><h2>Account overview</h2><dl><dt>Hotel</dt><dd>{account.hotel}</dd><dt>Account type</dt><dd>{account.type}</dd><dt>Account identity</dt><dd>{account.id}</dd><dt>Billing configuration</dt><dd>Not configured</dd></dl><p>Credit term and billing recipients will be configured per hotel and account. No OPERA email fallback is used.</p><button onClick={()=>setTab('Invoice / Folio')}>Open Invoice / Folio ledger</button></section>:<div className="account-workspace"><section className="panel ledger-panel"><div className="panel-heading"><h2>Guest Invoice / Folio <span className="badge">{account.hotel} · {invoices.length} items</span></h2><SearchBox value={search} onChange={setSearch} placeholder="Search guest / invoice / folio"/></div><div className="table-scroll"><table className="ledger"><thead><tr><th><input type="checkbox" aria-label="Select all visible invoices" checked={rows.length>0&&rows.every(i=>selected.has(i.id))} onChange={e=>setSelected(old=>{const n=new Set(old);rows.forEach(i=>e.target.checked?n.add(i.id):n.delete(i.id));return n;})}/></th>{columns.map(([l,k])=><SortHead key={k} label={l} active={sort===k} direction={direction} onClick={()=>changeSort(k)}/>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className={selected.has(row.id)?'selected-row':''}><td><input type="checkbox" aria-label={`Select ${row.invoiceNo}`} checked={selected.has(row.id)} onChange={()=>toggle(row.id)}/></td><td><button className="name-link" onClick={()=>{setFocused(row);setDrawer(true);}}>{row.guest}</button></td><td>{row.invoiceNo}</td><td>{row.folioNo}</td><td>{row.date}</td><td>{row.due??'Not billed'}</td><td>{money(row.original)}</td><td><b>{money(row.open)}</b></td><td><span className="aging-badge">{row.aging}</span></td><td><span className={`badge ${row.stage==='Final'?'danger':''}`}>{row.stage==='Final'?'Final · Urgent':row.stage}</span></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty-state"><strong>No matching invoices</strong><p>{invoices.length?'Try a different guest or document number.':'No verified OPERA invoice data is available for this account.'}</p></div>}<div className="selection-bar"><div><strong>{selected.size} items selected</strong><small>{account.hotel} · {account.name}</small></div><div><small>Selected open balance</small><strong>{money(selectionTotal(invoices,selected,account.hotel,account.id))}</strong></div><button onClick={()=>setSelected(new Set())} disabled={!selected.size}>Clear selection</button><span className="selection-hint">Document workflow is not enabled yet</span></div></section><aside className={`panel invoice-detail ${drawer?'drawer-open':''}`}>{detail}</aside>{drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}/>}</div>}
    <button className="back-bottom" onClick={back}><ArrowLeft size={13}/> Back to portfolio <ChevronRight size={12}/></button>
  </main>;
}
