import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,ChevronRight,RefreshCw,X} from 'lucide-react';
import {actionStages,nextCollectionAction,stageLabel,thaiToday,type QueueInvoice,type CollectionAction} from './domain/collection';
import {money,type Account} from './domain/portfolio';
import type {DocumentSelection} from './DocumentRoute';
import './collection-queue.css';
export interface QueueRow extends QueueInvoice {account_name:string;account_type:string}
interface Work extends QueueRow {action:CollectionAction}
interface Group {key:string;hotel:string;accountId:string;name:string;type:string;stage:string;purpose:string;rows:Work[];amount:number;date:string|null;ready:number;priority:number}
interface ReconcileStatus {enabled:boolean;intervalMinutes:number;waiting:number;needsReview:number;last?:{trigger:string;state:string;created_at:string;finished_at:string|null;checked:number;verified:number;needs_review:number;unavailable:number}|null}
const priority:Record<string,number>={'Urgent':0,'Needs review':1,'Final':2,'Follow 3':3,'Follow 2':4,'Follow 1':5,'Billing':6,'Friendly':7,'Setup needed':8};
async function read<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!r.ok)throw Error('Queue service unavailable');return r.json() as Promise<T>;}
export default function CollectionQueue({token,hotel,accounts,params,update,onOpen,onPrepare}:{token:string;hotel:string;accounts:Account[];params:URLSearchParams;update:(key:string,value:string)=>void;onOpen:(account:Account)=>void;onPrepare:(selection:DocumentSelection)=>void}){
 const [data,setData]=useState<QueueRow[]|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0),[sync,setSync]=useState<ReconcileStatus|null>(null),[syncBusy,setSyncBusy]=useState(false),[syncError,setSyncError]=useState(''),[drawer,setDrawer]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[today,setToday]=useState(thaiToday);
 const auth=useRef(token);auth.current=token;
 useEffect(()=>{let current=true;const controller=new AbortController();setLoading(true);setError('');void read<{rows:QueueRow[]}>('/api/collection-queue',auth.current,{signal:controller.signal}).then(r=>{if(!Array.isArray(r.rows))throw Error();if(current){setData(r.rows.map(row=>({...row,account_name:row.account_name??'Account metadata unavailable',account_type:row.account_type??'Type unavailable'})));setLoading(false);}}).catch(()=>{if(current){setLoading(false);setError('Collection data is unavailable. No replacement data has been shown.');}});void read<ReconcileStatus>('/api/mail-reconciliation',auth.current,{signal:controller.signal}).then(s=>{if(current)setSync(s);}).catch(()=>{if(current)setSyncError('Sent-check status unavailable.');});return()=>{current=false;controller.abort();};},[version]);
 useEffect(()=>{const timer=setInterval(()=>setToday(thaiToday()),60000);return()=>clearInterval(timer);},[]);
 const type=params.get('qtype')??'All',account=params.get('qaccount')??'All',stage=params.get('qstage')??'All',purpose=params.get('qpurpose')??'All',when=params.get('qwhen')??'All',search=params.get('qsearch')??'',sort=params.get('qsort')??'priority',dir=params.get('qdir')??'asc';
 const allWork=useMemo(()=>{return (data??[]).flatMap(r=>{const action=nextCollectionAction(r,today);return action?[{...r,action}]:[];});},[data,today]);
 const base=allWork.filter(r=>(hotel==='All'||r.hotel===hotel)&&(type==='All'||r.account_type===type)&&(account==='All'||`${r.hotel}:${r.account_id}`===account)&&`${r.account_name} ${r.guest} ${r.invoice_no??''} ${r.folio_no??''}`.toLowerCase().includes(search.toLowerCase()));
 const latestFilter=params.get('qsent')??'All';
 const visible=base.filter(r=>(latestFilter==='All'||r.action.latest===latestFilter)&&(stage==='All'||stage==='Collection due'&&!['Billing','Urgent','Setup needed','Needs review'].includes(r.action.stage)||r.action.stage===stage)&&(purpose==='All'||(purpose==='Billing'?r.action.stage==='Billing':!['Billing','Setup needed','Needs review'].includes(r.action.stage)))&&(when==='All'||(when==='Ready'?r.action.ready:!r.action.ready)));
 const groups=useMemo(()=>{const values=new Map<string,Group>();for(const r of visible){const key=`${r.hotel}:${r.account_id}:${r.action.stage}`;const g=values.get(key)??{key,hotel:r.hotel,accountId:r.account_id,name:r.account_name,type:r.account_type,stage:r.action.stage,purpose:r.action.stage==='Billing'?'Billing':['Setup needed','Needs review'].includes(r.action.stage)?'Review':'Collection',rows:[],amount:0,date:r.action.date,ready:0,priority:priority[r.action.stage]};g.rows.push(r);g.amount+=Math.round(r.open*100);if(r.action.date&&(!g.date||r.action.date<g.date))g.date=r.action.date;if(r.action.ready)g.ready++;values.set(key,g);}return [...values.values()].map(g=>({...g,amount:g.amount/100,priority:priority[g.stage]+(g.ready?0:20)})).sort((a,b)=>{const get=(g:Group)=>sort==='count'?g.rows.length:sort==='amount'?g.amount:sort==='date'?g.date??'9999':sort==='hotel'?g.hotel:sort==='name'?g.name:sort==='stage'?g.stage:sort==='purpose'?g.purpose:g.priority;const x=get(a),y=get(b);return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'en',{numeric:true}))*(dir==='asc'?1:-1)||b.amount-a.amount||a.key.localeCompare(b.key);});},[visible,sort,dir]);
 const focused=groups.find(g=>g.key===params.get('qfocus'))??groups[0];const focusKey=focused?.key;
 useEffect(()=>{setSelected(new Set());},[focusKey]);
 const scopedSelected=focused?.rows.filter(r=>selected.has(r.id)&&r.collection_selectable&&r.verification_state==='verified')??[];
 const tiles=[{label:'Billing due',test:(r:Work)=>r.action.stage==='Billing'&&r.action.ready,filter:'Billing'},{label:'Collection due',test:(r:Work)=>!['Billing','Setup needed','Needs review','Urgent'].includes(r.action.stage)&&r.action.ready,filter:'collection'},{label:'Urgent',test:(r:Work)=>r.action.stage==='Urgent',filter:'Urgent'},{label:'Upcoming',test:(r:Work)=>!r.action.ready,filter:'upcoming'},{label:'Setup needed',test:(r:Work)=>r.action.stage==='Setup needed',filter:'Setup needed'},{label:'Needs review',test:(r:Work)=>r.action.stage==='Needs review',filter:'Needs review'}];
 function tileFilter(filter:string){update('qstage',filter==='collection'?'Collection due':filter==='upcoming'?'All':filter);update('qpurpose',filter==='collection'?'Collection':'All');update('qwhen',filter==='upcoming'?'Upcoming':filter==='collection'||filter==='Billing'?'Ready':'All');}
 function sorting(key:string){update('qdir',sort===key&&dir==='asc'?'desc':'asc');update('qsort',key);}
 function openAccount(){if(!focused)return;const row=accounts.find(a=>a.hotel===focused.hotel&&a.id===focused.accountId);if(row)onOpen(row);}
 async function checkMail(){setSyncBusy(true);setSyncError('');try{await read('/api/mail-reconciliation',auth.current,{method:'POST'});setSync(await read<ReconcileStatus>('/api/mail-reconciliation',auth.current));setVersion(n=>n+1);}catch{setSyncError('Sent check could not start. No email was sent.');}finally{setSyncBusy(false);}}
 return <main className="page collection-page"><div className="queue-title"><div><h1>Billing & Collection Queue</h1><p>Latest sent stage and next action remain separate · Calendar dates in Thailand</p></div><button onClick={()=>setVersion(n=>n+1)} disabled={loading}><RefreshCw size={14}/>{loading?'Loading…':'Reload queue'}</button></div>
 {error&&<p className="error-message" role="alert">{error}{data?' Showing the last successfully loaded queue.':''}</p>}
 <div className="queue-metrics">{tiles.map((tile,i)=>{const rows=base.filter(tile.test);return <button key={tile.label} className={i===0?'billing-metric':''} onClick={()=>tileFilter(tile.filter)} disabled={!data}><small>{tile.label}</small><strong>{data?rows.length:'—'}</strong><span>{data?`${new Set(rows.map(r=>r.hotel+':'+r.account_id)).size} accounts · ${money(rows.reduce((n,r)=>n+Math.round(r.open*100),0)/100)}`:'Waiting for source data'}</span></button>;})}</div>
 <div className="queue-purpose-note"><strong>TWO PURPOSES</strong><span>BILLING · invoice presentation</span><span>COLLECTION · debt follow-up</span><b>Drafts never advance invoice stages</b></div>
 <div className="queue-filters"><label>Purpose<select aria-label="Queue purpose" value={purpose} onChange={e=>update('qpurpose',e.target.value)}>{['All','Billing','Collection'].map(s=><option key={s}>{s}</option>)}</select></label><label>Account type<select aria-label="Queue account type" value={type} onChange={e=>update('qtype',e.target.value)}><option>All</option>{[...new Set((data??[]).map(r=>r.account_type))].sort().map(s=><option key={s}>{s}</option>)}</select></label><label>Account<select aria-label="Queue account" value={account} onChange={e=>update('qaccount',e.target.value)}><option>All</option>{[...new Map((data??[]).filter(r=>hotel==='All'||r.hotel===hotel).map(r=>[`${r.hotel}:${r.account_id}`,r])).entries()].sort((a,b)=>a[1].account_name.localeCompare(b[1].account_name)).map(([key,r])=><option key={key} value={key}>{r.hotel} · {r.account_name}</option>)}</select></label><label>Next action<select aria-label="Queue stage" value={stage} onChange={e=>update('qstage',e.target.value)}><option>All</option><option>Collection due</option>{actionStages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select></label><label>Latest sent<select aria-label="Queue latest sent stage" value={latestFilter} onChange={e=>update('qsent',e.target.value)}><option>All</option>{['No reminders sent','Billed','Friendly','Follow 1','Follow 2','Follow 3','Final'].map(s=><option key={s} value={s}>{stageLabel(s)} · {base.filter(r=>r.action.latest===s).length}</option>)}</select></label><label>When<select aria-label="Queue timing" value={when} onChange={e=>update('qwhen',e.target.value)}>{['All','Ready','Upcoming'].map(s=><option key={s}>{s}</option>)}</select></label><input type="search" aria-label="Search collection queue" placeholder="Search account / guest / invoice" value={search} onChange={e=>update('qsearch',e.target.value)}/><button onClick={()=>{for(const k of ['qtype','qaccount','qstage','qpurpose','qwhen','qsearch','qsent'])update(k,'');}}>Clear filters</button></div>
 <div className="queue-layout"><section className="panel queue-work"><header><h2>Prioritized work <small>{groups.length} account / action groups · {visible.length} invoices</small></h2><span>KAT <i/> TSK</span></header><div className="queue-table-scroll"><table><thead><tr>{[['priority','Priority'],['hotel','Hotel'],['purpose','Purpose'],['name','Account'],['stage','Next action'],['count','Open invoices'],['amount','Open amount'],['date','Action date']].map(([key,label])=><th key={key}><button onClick={()=>sorting(key)}>{label}{sort===key?(dir==='asc'?<ArrowUp size={10}/>:<ArrowDown size={10}/>):null}</button></th>)}</tr></thead><tbody>{groups.map((g,index)=><tr key={g.key} className={focused?.key===g.key?'focused':''} onClick={()=>{update('qfocus',g.key);setDrawer(true);}}><td><span className="queue-priority">{String(index+1).padStart(2,'0')}</span></td><td><span className={`queue-hotel ${g.hotel.toLowerCase()}`}>{g.hotel}</span></td><td><span className={`queue-purpose ${g.purpose.toLowerCase()}`}>{g.purpose}</span></td><td><button className="queue-account" onClick={e=>{e.stopPropagation();update('qfocus',g.key);setDrawer(true);}}>{g.name}</button><small>{g.type}</small></td><td><span className={g.stage==='Urgent'?'urgent-text':''}>{stageLabel(g.stage)}</span></td><td>{g.rows.length}</td><td><strong>{money(g.amount)}</strong></td><td>{g.date??'Needs attention'}<small>{g.ready?`${g.ready} ready`:'Upcoming'}</small></td></tr>)}</tbody></table>{!groups.length&&<div className="queue-empty"><strong>{loading?'Loading invoice work…':error?'Queue unavailable':'No work matches these filters'}</strong><p>{!loading&&!error?'All matching positive open invoices are included. Try another stage or timing filter.':'Verified data is required to show this queue.'}</p></div>}</div><footer>{(data??[]).filter(r=>r.collection_role==='child'&&(hotel==='All'||r.hotel===hotel)).length} child invoice rows are represented by their parent and are not collected separately.</footer></section>
 <aside className={`panel queue-detail ${drawer?'open':''}`}><button className="queue-close" aria-label="Close queue details" onClick={()=>setDrawer(false)}><X size={18}/></button>{focused?<><small>SELECTED WORK · {focused.purpose.toUpperCase()}</small><h2>{focused.name}</h2><span className="badge">{stageLabel(focused.stage)}</span><div className="queue-detail-balance"><small>CURRENT OPEN · THIS ACTION</small><strong>{money(focused.amount)}</strong></div><dl><div><dt>Hotel</dt><dd>{focused.hotel}</dd></div><div><dt>Account type</dt><dd>{focused.type}</dd></div><div><dt>Ready / upcoming</dt><dd>{focused.ready} / {focused.rows.length-focused.ready}</dd></div><div><dt>Selected</dt><dd>{scopedSelected.length} invoices</dd></div></dl><h3>Invoices and latest sent stage</h3><div className="queue-invoice-list">{focused.rows.map(r=><label key={r.id}><input type="checkbox" aria-label={`Queue select ${r.invoice_no??r.id}`} checked={selected.has(r.id)} disabled={!r.collection_selectable||r.verification_state!=='verified'} onChange={()=>setSelected(old=>{const next=new Set(old);if(next.has(r.id))next.delete(r.id);else next.add(r.id);return next;})}/><span><b>{r.invoice_no??'Invoice unavailable'} · {r.folio_no??'Folio unavailable'}</b><small>{r.guest}</small><small>Latest: {stageLabel(r.action.latest)} · {money(r.open)}</small>{r.action.reason&&<small className="queue-warning">{r.action.reason}</small>}</span></label>)}</div><button className="queue-account-open" onClick={openAccount}>Open account details <ChevronRight size={14}/></button>{!['Setup needed','Needs review'].includes(focused.stage)&&<button className="primary-button" disabled={!scopedSelected.length} onClick={()=>onPrepare({hotel:focused.hotel,accountId:focused.accountId,accountName:focused.name,ids:scopedSelected.map(r=>r.id),purpose:focused.stage==='Billing'?'billing':'collection'})}>Prepare {focused.stage==='Billing'?'billing':'collection'} documents</button>}<p className="queue-safety-note">Document preparation does not create a Gmail draft or send email.</p></>:<p>Choose a work row to review its invoices.</p>}</aside></div>{drawer&&<div className="queue-backdrop" onClick={()=>setDrawer(false)}/>}
 <section className="queue-sync"><div><strong>Sent status checks</strong><p>{sync?.enabled?`Read-only Gmail checks every ${sync.intervalMinutes} minutes`:'Scheduled checks are not enabled.'}{sync?.last?` · Last ${sync.last.trigger} run: ${sync.last.state} · ${new Date(sync.last.finished_at??sync.last.created_at).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})} ICT`:''}</p>{sync?.last&&<small>{sync.last.checked} checked · {sync.last.verified} verified · {sync.last.needs_review} require review · {sync.last.unavailable} unavailable</small>}{syncError&&<p role="alert">{syncError}</p>}</div><button disabled={syncBusy} onClick={checkMail}>{syncBusy?'Starting check…':'Check sent status now'}</button></section>
 </main>;
}
