import {useWorkspaceMember} from './access/context';
import {hotelInRegion,resolveRegion} from './domain/hotels';
import {useCollectionPolicy} from './collection/PolicyContext';
import {QueueWorkPanel} from './collection/QueueWorkPanel';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,RefreshCw,Search,Settings2,SlidersHorizontal,X} from 'lucide-react';
import {actionStagesForPolicy,nextCollectionAction,stageLabel,thaiToday,type QueueInvoice,type CollectionAction} from './domain/collection';
import {money,type Account} from './domain/portfolio';
import type {DocumentSelection} from './DocumentRoute';
import './collection-queue.css';
export interface QueueRow extends QueueInvoice {account_name:string;account_type:string}
interface Work extends QueueRow {action:CollectionAction}
export interface Group {key:string;hotel:string;accountId:string;name:string;type:string;stage:string;purpose:string;rows:Work[];amount:number;date:string|null;ready:number;priority:number}
interface ReconcileStatus {enabled:boolean;intervalMinutes:number;waiting:number;needsReview:number;last?:{trigger:string;state:string;created_at:string;finished_at:string|null;checked:number;verified:number;needs_review:number;unavailable:number}|null}
const priority:Record<string,number>={'Urgent':0,'Needs review':1,'Final':2,'Follow 3':3,'Follow 2':4,'Follow 1':5,'Billing':6,'Friendly':7,'Setup needed':8};
async function read<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!r.ok)throw Error('Queue service unavailable');return r.json() as Promise<T>;}
export default function CollectionQueue({token,hotel,accounts,params,update,onOpen,onPrepare,onEditPolicy}:{onEditPolicy?:()=>void;token:string;hotel:string;accounts:Account[];params:URLSearchParams;update:(key:string,value:string)=>void;onOpen:(account:Account)=>void;onPrepare:(selection:DocumentSelection)=>void}){
 const {policy,error:policyError,refresh:refreshPolicy}=useCollectionPolicy();const actionStages=policy?actionStagesForPolicy(policy):['Billing','Urgent','Setup needed','Needs review','On hold'];
 const [data,setData]=useState<QueueRow[]|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0),[sync,setSync]=useState<ReconcileStatus|null>(null),[syncBusy,setSyncBusy]=useState(false),[syncError,setSyncError]=useState(''),[drawer,setDrawer]=useState(false),[selection,setSelection]=useState<{scope:string;ids:Set<string>}>({scope:'',ids:new Set()}),[today,setToday]=useState(thaiToday);
 const syncMarker=useRef('');
 const [filtersOpen,setFiltersOpen]=useState(false);
 const detailDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const panel=detailDialog.current;if(!panel)return;const observer=new ResizeObserver(()=>{const height=panel.getBoundingClientRect().height;if(height>0)panel.style.setProperty('--queue-detail-height',height+'px');});observer.observe(panel);return()=>observer.disconnect();},[]);
 const [compact,setCompact]=useState(()=>typeof matchMedia!=='undefined'&&matchMedia('(max-width:1100px)').matches);
 useEffect(()=>{const media=matchMedia('(max-width:1100px)');const changed=()=>setCompact(media.matches);media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed);},[]);
 useEffect(()=>{
   const dialog=detailDialog.current;if(!dialog)return;
   if(dialog.open&&(compact!==dialog.matches(':modal')||compact&&!drawer))dialog.close();
   if(!dialog.open&&(!compact||drawer)){if(compact)dialog.showModal();else dialog.show();}
 },[compact,drawer]);
 const canCheckMail=(useWorkspaceMember()?.administrator??true)&&resolveRegion(params)==='phuket';
 const auth=useRef(token);auth.current=token;
 useEffect(()=>{let current=true;const controller=new AbortController();setLoading(true);setError('');void read<{rows:QueueRow[]}>('/api/collection-queue'+(resolveRegion(params)==='khao-lak'?'?region=khao-lak':''),auth.current,{signal:controller.signal}).then(r=>{if(!Array.isArray(r.rows))throw Error();if(current){setData(r.rows.filter(row=>hotelInRegion(row.hotel,resolveRegion(params))).map(row=>({...row,account_name:row.account_name??'Account metadata unavailable',account_type:row.account_type??'Type unavailable'})));setLoading(false);}}).catch(()=>{if(current){setLoading(false);setError('Collection data is unavailable. No replacement data has been shown.');}});if(canCheckMail)void read<ReconcileStatus>('/api/mail-reconciliation',auth.current,{signal:controller.signal}).then(s=>{if(current){setSync(s);syncMarker.current=s.last?.finished_at??'';}}).catch(()=>{if(current)setSyncError('Sent-check status unavailable.');});return()=>{current=false;controller.abort();};},[version,accounts,token,canCheckMail]);
 useEffect(()=>{const timer=setInterval(()=>setToday(thaiToday()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!canCheckMail)return;let alive=true;const poll=async()=>{if(document.visibilityState==='hidden')return;try{const s=await read<ReconcileStatus>('/api/mail-reconciliation',auth.current);if(!alive)return;setSync(s);setSyncError('');if(s.last?.verified&&s.last.finished_at&&s.last.finished_at!==syncMarker.current)setVersion(n=>n+1);syncMarker.current=s.last?.finished_at??'';}catch{if(alive)setSyncError('Sent-check status unavailable.');}};const timer=setInterval(poll,60000);document.addEventListener('visibilitychange',poll);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',poll);};},[canCheckMail]);
 const type=params.get('qtype')??'All',account=params.get('qaccount')??'All',stage=params.get('qstage')??'All',purpose=params.get('qpurpose')??'All',when=params.get('qwhen')??'All',search=params.get('qsearch')??'',sort=params.get('qsort')??'priority',dir=params.get('qdir')??'asc';
 const allWork=useMemo(()=>{return (data??[]).flatMap(r=>{const action=nextCollectionAction(r,today,policy);return action?[{...r,action}]:[];});},[data,today,policy]);
 const base=allWork.filter(r=>(hotel==='All'||r.hotel===hotel)&&(type==='All'||r.account_type===type)&&(account==='All'||`${r.hotel}:${r.account_id}`===account)&&`${r.account_name} ${r.guest} ${r.invoice_no??''} ${r.folio_no??''}`.toLowerCase().includes(search.toLowerCase()));
 const latestFilter=params.get('qsent')??'All';
 const visible=base.filter(r=>(latestFilter==='All'||r.action.latest===latestFilter)&&(stage==='All'||stage==='Collection due'&&!['Billing','Urgent','Setup needed','Needs review','On hold'].includes(r.action.stage)||r.action.stage===stage||stage==='Urgent'&&r.action.urgent)&&(purpose==='All'||(purpose==='Billing'?r.action.stage==='Billing':!['Billing','Setup needed','Needs review','On hold'].includes(r.action.stage)))&&(when==='All'||(when==='Ready'?r.action.ready:!r.action.ready)));
 const groups=useMemo(()=>{const values=new Map<string,Group>();for(const r of visible){const key=`${r.hotel}:${r.account_id}:${r.action.stage}`;const g=values.get(key)??{key,hotel:r.hotel,accountId:r.account_id,name:r.account_name,type:r.account_type,stage:r.action.stage,purpose:r.action.stage==='Billing'?'Billing':['Setup needed','Needs review','On hold'].includes(r.action.stage)?'Review':'Collection',rows:[],amount:0,date:r.action.date,ready:0,priority:priority[r.action.stage]??10};g.rows.push(r);g.amount+=Math.round(r.open*100);if(r.action.date&&(!g.date||r.action.date<g.date))g.date=r.action.date;if(r.action.ready)g.ready++;values.set(key,g);}return [...values.values()].map(g=>({...g,amount:g.amount/100,priority:(g.rows.some(r=>r.action.urgent)?0:priority[g.stage]??(policy?policy.rounds.length-policy.rounds.findIndex(r=>r.key===g.stage)+2:10))+(g.ready?0:20)})).sort((a,b)=>{const get=(g:Group)=>sort==='count'?g.rows.length:sort==='amount'?g.amount:sort==='date'?g.date??'9999':sort==='hotel'?g.hotel:sort==='name'?g.name:sort==='stage'?g.stage:sort==='purpose'?g.purpose:g.priority;const x=get(a),y=get(b);return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'en',{numeric:true}))*(dir==='asc'?1:-1)||b.amount-a.amount||a.key.localeCompare(b.key);});},[visible,sort,dir,policy]);
 const groupStageLabel=(g:Group)=>g.stage==='Setup needed'&&g.rows.every(r=>r.workflow?.billing_required!=null&&r.workflow.credit_term===null)?'Credit term needed':stageLabel(g.stage,policy);
 const focused=groups.find(g=>g.key===params.get('qfocus'))??groups[0];const focusKey=focused?.key;
 const selected=selection.scope===focusKey?selection.ids:new Set<string>();
 useEffect(()=>{setSelection({scope:focusKey??'',ids:new Set()});},[focusKey]);
 useEffect(()=>{setSelection(previous=>{if(previous.scope!==focusKey)return previous;const next=new Set([...previous.ids].filter(id=>focused?.rows.some(r=>r.id===id&&r.collection_selectable&&r.verification_state==='verified')));return next.size===previous.ids.size?previous:{scope:previous.scope,ids:next};});},[data,focusKey]);
 const scopedSelected=focused?.rows.filter(r=>selected.has(r.id)&&r.collection_selectable&&r.verification_state==='verified')??[];
 const tiles=[{label:'All work',test:(_r:Work)=>true,filter:'all'},{label:'Billing due',test:(r:Work)=>r.action.stage==='Billing'&&r.action.ready,filter:'Billing'},{label:'Collection due',test:(r:Work)=>!['Billing','Setup needed','Needs review','On hold','Urgent'].includes(r.action.stage)&&r.action.ready,filter:'collection'},{label:'Urgent',test:(r:Work)=>r.action.urgent,filter:'Urgent'},{label:'Upcoming',test:(r:Work)=>!r.action.ready,filter:'upcoming'},{label:'Setup needed',test:(r:Work)=>r.action.stage==='Setup needed',filter:'Setup needed'},{label:'On hold',test:(r:Work)=>r.action.stage==='On hold',filter:'On hold'},{label:'Needs review',test:(r:Work)=>r.action.stage==='Needs review',filter:'Needs review'}];
 function tileFilter(filter:string){update('qstage',filter==='collection'?'Collection due':filter==='upcoming'||filter==='all'?'All':filter);update('qpurpose',filter==='collection'?'Collection':'All');update('qwhen',filter==='upcoming'?'Upcoming':filter==='collection'||filter==='Billing'?'Ready':'All');update('qsent','');}
 function sorting(key:string){update('qdir',sort===key&&dir==='asc'?'desc':'asc');update('qsort',key);}
 function openAccount(){if(!focused)return;const row=accounts.find(a=>a.hotel===focused.hotel&&a.id===focused.accountId);if(row)onOpen(row);}
 async function checkMail(){if(!canCheckMail)return;setSyncBusy(true);setSyncError('');try{await read('/api/mail-reconciliation',auth.current,{method:'POST'});setSync(await read<ReconcileStatus>('/api/mail-reconciliation',auth.current));setVersion(n=>n+1);}catch{setSyncError('Sent check could not start. No email was sent.');}finally{setSyncBusy(false);}}

 function clearFilters(){for(const k of ['qtype','qaccount','qstage','qpurpose','qwhen','qsearch','qsent'])update(k,'');}
 function activeView(filter:string){const target=filter==='collection'?'Collection due':filter==='upcoming'||filter==='all'?'All':filter;return stage===target&&purpose===(filter==='collection'?'Collection':'All')&&when===(filter==='upcoming'?'Upcoming':filter==='collection'||filter==='Billing'?'Ready':'All')&&latestFilter==='All';}
 const filters=[{key:'qtype',label:'Type',value:type},{key:'qaccount',label:'Account',value:account,text:data?.find(r=>`${r.hotel}:${r.account_id}`===account)?.account_name??account},{key:'qpurpose',label:'Purpose',value:purpose},{key:'qstage',label:'Next action',value:stage,text:stageLabel(stage,policy)},{key:'qsent',label:'Latest sent',value:latestFilter,text:stageLabel(latestFilter,policy)},{key:'qwhen',label:'When',value:when}].filter(f=>f.value!=='All');
 const visibleAmount=visible.reduce((n,r)=>n+Math.round(r.open*100),0)/100;
 function prepareSelected(){if(!focused||!scopedSelected.length)return;onPrepare({hotel:focused.hotel,accountId:focused.accountId,accountName:focused.name,ids:scopedSelected.map(r=>r.id),purpose:focused.stage==='Billing'||focused.stage==='Setup needed'&&!scopedSelected.every(r=>r.workflow?.billing_required===false)?'billing':'collection'});}
 return <main className="page collection-page"><header className="queue-title"><div><h1>Collections</h1></div><div className="queue-heading-actions">{onEditPolicy&&<button className="queue-rules" onClick={onEditPolicy}><Settings2 size={15}/>Edit collection rules</button>}<button onClick={()=>{setVersion(n=>n+1);void refreshPolicy();}} disabled={loading}><RefreshCw size={15}/>{loading?'Loading…':'Reload queue'}</button></div></header>
 {policyError&&<p className="information-note" role="status">{policyError}</p>}{error&&<p className="error-message" role="alert">{error}{data?' Showing the last successfully loaded queue.':''}</p>}
 <nav className="queue-views" aria-label="Collection work views">{tiles.map(tile=>{const rows=base.filter(tile.test);return <button key={tile.label} aria-pressed={activeView(tile.filter)} className={tile.filter==='Urgent'&&rows.length?'has-urgent':''} onClick={()=>tileFilter(tile.filter)} disabled={!data} title={`${new Set(rows.map(r=>r.hotel+':'+r.account_id)).size} accounts · ${money(rows.reduce((n,r)=>n+Math.round(r.open*100),0)/100)}`}><span>{tile.label}</span><b>{data?rows.length:'—'}</b></button>;})}</nav>
 <div className="queue-toolbar"><label className="queue-find"><Search size={17} aria-hidden="true"/><input type="search" aria-label="Search collection queue" placeholder="Find account, guest or invoice" value={search} onChange={e=>update('qsearch',e.target.value)}/></label><button className="queue-filter-toggle" aria-label="Collection filters" aria-expanded={filtersOpen} aria-controls="collection-filter-fields" onClick={()=>setFiltersOpen(v=>!v)}><SlidersHorizontal size={15}/>Filters{filters.length>0&&<b>{filters.length}</b>}</button><div className="queue-sort"><select aria-label="Sort collection work" value={sort} onChange={e=>{update('qsort',e.target.value);update('qdir','asc');}}>{[['priority','Priority'],['name','Account'],['hotel','Hotel'],['purpose','Purpose'],['stage','Next action'],['count','Invoice count'],['amount','Open amount'],['date','Action date']].map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><button aria-label={dir==='asc'?'Sort descending':'Sort ascending'} onClick={()=>update('qdir',dir==='asc'?'desc':'asc')}>{dir==='asc'?<ArrowUp size={15}/>:<ArrowDown size={15}/>}</button></div></div>
  <div className="queue-filters" id="collection-filter-fields" hidden={!filtersOpen}><label>Purpose<select aria-label="Queue purpose" value={purpose} onChange={e=>update('qpurpose',e.target.value)}>{['All','Billing','Collection'].map(s=><option key={s}>{s}</option>)}</select></label><label>Account type<select aria-label="Queue account type" value={type} onChange={e=>update('qtype',e.target.value)}><option>All</option>{[...new Set((data??[]).map(r=>r.account_type))].sort().map(s=><option key={s}>{s}</option>)}</select></label><label>Account<select aria-label="Queue account" value={account} onChange={e=>update('qaccount',e.target.value)}><option>All</option>{[...new Map((data??[]).filter(r=>hotel==='All'||r.hotel===hotel).map(r=>[`${r.hotel}:${r.account_id}`,r])).entries()].sort((a,b)=>a[1].account_name.localeCompare(b[1].account_name)).map(([key,r])=><option key={key} value={key}>{r.hotel} · {r.account_name}</option>)}</select></label><label>Next action<select aria-label="Queue stage" value={stage} onChange={e=>update('qstage',e.target.value)}><option>All</option><option>Collection due</option>{actionStages.map(s=><option key={s} value={s}>{stageLabel(s,policy)}</option>)}</select></label><label>Latest sent<select aria-label="Queue latest sent stage" value={latestFilter} onChange={e=>update('qsent',e.target.value)}><option>All</option>{[...new Set(['No reminders sent','Billed',...(policy?.rounds.map(r=>r.key)??[]),...base.map(r=>r.action.latest)])].map(s=><option key={s} value={s}>{stageLabel(s,policy)} · {base.filter(r=>r.action.latest===s).length}</option>)}</select></label><label>When<select aria-label="Queue timing" value={when} onChange={e=>update('qwhen',e.target.value)}>{['All','Ready','Upcoming'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 {(filters.length>0||search)&&<div className="queue-filter-chips" aria-label="Active collection filters">{filters.map(f=><button key={f.key} onClick={()=>update(f.key,'')} aria-label={`Remove ${f.label} filter`}>{f.label}: {f.text??f.value}<X size={12}/></button>)}<button className="queue-clear-filters" onClick={clearFilters}>Clear filters</button></div>}
 <div className="queue-layout"><section className="panel queue-work"><header><div><h2>Work queue</h2><p>{data?`${groups.length} work items · ${visible.length} invoices`:'Loading work…'}</p></div><strong>{data?money(visibleAmount):'—'}</strong></header><div className="queue-table-scroll" role="region" aria-label="Prioritized collection work" tabIndex={0}><table><thead><tr>{[['name','Account'],['stage','Next action'],['count','Invoices'],['amount','Open amount'],['date','Action date']].map(([key,label])=><th key={key} aria-sort={sort===key?(dir==='asc'?'ascending':'descending'):'none'}><button onClick={()=>sorting(key)}>{label}{sort===key?(dir==='asc'?<ArrowUp size={11}/>:<ArrowDown size={11}/>):null}</button></th>)}</tr></thead><tbody>{groups.map(g=><tr key={g.key} className={focused?.key===g.key?'focused':''} aria-selected={focused?.key===g.key} onClick={()=>{update('qfocus',g.key);setDrawer(true);}}><td className="queue-account-cell"><button className="queue-account" onClick={e=>{e.stopPropagation();update('qfocus',g.key);setDrawer(true);}}>{g.name}</button><div className="queue-row-context"><span className={`queue-hotel ${g.hotel.toLowerCase()}`}>{g.hotel}</span><small>{g.type}</small></div></td><td data-label="Next action"><span className={'queue-stage '+(g.stage==='Urgent'?'urgent-text':'')}>{groupStageLabel(g)}</span>{g.rows.some(r=>r.action.urgent)&&g.stage!=='Urgent'&&<small className="urgent-text">Urgent</small>}</td><td data-label="Invoices" className="queue-number">{g.rows.length}</td><td data-label="Open amount" className="queue-number"><strong>{money(g.amount)}</strong></td><td data-label="Action date"><span>{g.date??'Needs attention'}</span><small className={g.purpose==='Review'?'queue-attention':g.ready?'queue-ready':'queue-upcoming'}>{g.purpose==='Review'?(g.stage==='On hold'?'On hold':'Needs attention'):g.ready?`${g.ready} ready`:'Upcoming'}</small></td></tr>)}</tbody></table>{!groups.length&&<div className="queue-empty"><strong>{loading?'Loading invoice work…':error?'Queue unavailable':'No work matches these filters'}</strong>{!loading&&!error&&<button onClick={clearFilters}>Reset view</button>}</div>}</div></section>
 <dialog ref={detailDialog} open={!compact||undefined} className={`panel queue-detail ${drawer?'open':''}`} role={compact?'dialog':'complementary'} aria-label="Collection work details" onCancel={e=>{e.preventDefault();setDrawer(false);}} onClick={e=>{const box=e.currentTarget.getBoundingClientRect();if(compact&&e.target===e.currentTarget&&(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom))setDrawer(false);}}><button className="queue-close" aria-label="Close queue details" onClick={()=>setDrawer(false)}><X size={18}/></button>{focused?<QueueWorkPanel key={focused.key} group={focused} label={groupStageLabel(focused)} selected={selected} onToggle={id=>setSelection(old=>{const next=new Set(old.scope===focused.key?old.ids:[]);if(next.has(id))next.delete(id);else next.add(id);return {scope:focused.key,ids:next};})} onSelect={ids=>setSelection(old=>({scope:focused.key,ids:new Set([...(old.scope===focused.key?old.ids:[]),...ids])}))} onClear={()=>setSelection({scope:focused.key,ids:new Set()})} onPrepare={prepareSelected} onAccount={openAccount}/>:<div className="queue-detail-empty"><h2>Select an account</h2><p>Its invoices and document actions will appear here.</p></div>}</dialog></div>
 {canCheckMail&&<details className="queue-sync"><summary>Sent status checks{(sync?.needsReview??0)>0?' · Needs review':''}</summary><div><p>{sync===null?'Sent-check status unavailable.':sync.enabled?`Gmail checks every ${sync.intervalMinutes} minutes`:'Scheduled checks are not enabled.'}{sync?.last?` · Last ${sync.last.state} · ${new Date(sync.last.finished_at??sync.last.created_at).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})} ICT`:''}</p>{sync?.last&&<small>{sync.last.checked} checked · {sync.last.verified} verified · {sync.last.needs_review} require review · {sync.last.unavailable} unavailable</small>}{syncError&&<p role="alert">{syncError}</p>}<button disabled={syncBusy} onClick={checkMail}>{syncBusy?'Starting check…':'Check sent status now'}</button></div></details>}
 </main>;
}
