import {createReviewHandoff} from './pdf/review-handoff';
import {operationMessages} from '../worker/operations/messages';
import {PrivatePdfPreview} from './pdf/PrivatePdfPreview';
import {DriveArchive} from './drive/DriveStorage';
import {useEffect,useRef,useState} from 'react';
import {PdfWorkspace,type PdfSourceDocument,type PdfExportFile,type PdfProject} from './pdf/PdfWorkspace';
import type {DocumentJob,DocumentExport} from '../worker/documents/jobs';
import './document-route.css';
import EmailComposer from './EmailComposer';
const uuid=()=>crypto.randomUUID();
const message=(code:string)=>(operationMessages[code]??({native_statement_transport_unverified:'This earlier request used the retired native Statement source. Create a new Statement in AR Workspace.',document_statement_source_retired:'Statement uses AR Workspace. Create a new document job with the current source.',non_reservation_document_unavailable:'This invoice needs a non-reservation document source that has not been verified yet.',folio_window_ambiguous:'Several historical folios share this window. Exact document selection needs verification.',document_source_changed:'OPERA changed since selection. Refresh the account before starting a new document request.',document_revision_conflict:'This preparation changed in another session. Reload it before reviewing again.',document_closed:'This preparation is closed. Select invoices in the account to start a new round.',document_discard_blocked:'This package is still used by document processing or an email attempt. Resolve that work before discarding it.',document_generation_pending:'Document processing is still running or needs verification. Wait for its result before discarding.',document_mail_pending:'This preparation is used by a Draft or an unconfirmed email attempt. Resolve the email work before discarding or changing the reviewed files.',document_upload_pending:'A file upload is still being verified. Keep this preparation and retry once the upload result is known.',document_project_retired:'PDF edits stay in this tab. New preparations do not save editor projects.',document_archive_retired:'These files are temporary for this preparation and are not archived to Drive.',document_upload_too_large:'This file exceeds the configured upload memory limit. Your edits remain open.'}[code]??code.replaceAll('_',' ')));
async function requestJson<T>(url:string,token:string,init:RequestInit={}):Promise<T>{const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});const data=await r.json();if(!r.ok)throw new Error(data&&typeof data==='object'&&'error'in data?message(String(data.error)):'Document service unavailable');return data as T;}
export interface DocumentSelection {hotel:string;accountId:string;accountName:string;ids:string[];purpose?:'billing'|'collection'}
export function CreateDocumentDialog({selection,token,onClose,onCreated}:{selection:DocumentSelection;token:string;onClose:()=>void;onCreated:(id:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),alive=useRef(true);const [content,setContent]=useState('invoices'),[layout,setLayout]=useState('combined'),[purpose,setPurpose]=useState<string>(selection.purpose??'billing'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{alive.current=true;dialog.current?.showModal();return()=>{alive.current=false;};},[]);
 async function create(){setBusy(true);setError('');try{
  const payload={hotel:selection.hotel,accountId:selection.accountId,ids:selection.ids,content,layout,purpose,statementSource:content==='invoices'?'native':'workspace'};
  const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(payload)));const key='ar-document-command:'+Array.from(new Uint8Array(digest)).map(n=>n.toString(16).padStart(2,'0')).join('');
  const commandKey=sessionStorage.getItem(key)??uuid();sessionStorage.setItem(key,commandKey);
  const job=await requestJson<DocumentJob>('/api/documents',token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,commandKey})});
  if(alive.current){sessionStorage.removeItem(key);onCreated(job.id);}
 }catch(e){if(alive.current)setError(e instanceof Error?e.message:'Document request failed');}finally{if(alive.current)setBusy(false);}}
 return <dialog className="document-dialog" ref={dialog} onCancel={onClose}><h2>Prepare documents</h2><p>{selection.hotel} · {selection.accountName} · {selection.ids.length} selected invoices</p><label>Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)} disabled={busy}><option value="billing">Billing</option><option value="collection">Collection</option></select></label><label>Document content<select value={content} onChange={e=>setContent(e.target.value)} disabled={busy}><option value="invoices">Invoices / Folios only</option><option value="statement">Statement only</option><option value="both">Statement and Invoices / Folios</option></select></label>{content!=='invoices'&&<p className="information-note">Statement: Generate in AR Workspace. Includes only selected invoices. Aging Summary covers the account. Review the PDF before use.</p>}<label>Delivery layout<select value={layout} onChange={e=>setLayout(e.target.value)} disabled={busy}><option value="combined">One combined PDF</option><option value="statement_bundle">Statement + invoice bundle</option><option value="separate">Statement + each invoice separately</option></select></label><p>Invoice / Folio retrieval may record OPERA print history. This does not send email or change AR balances.</p>{error&&<p role="alert" className="error-message">{error}</p>}<footer><button onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" onClick={create} disabled={busy}>{busy?'Preparing request…':'Create document job'}</button></footer></dialog>;
}
export default function DocumentRoute({token,jobId,onClose,onDirtyChange,backLabel='Back to portfolio',maxBytes=64*1024*1024}:{token:string;jobId?:string;onClose:()=>void;onDirtyChange?:(dirty:boolean)=>void;backLabel?:string;maxBytes?:number}){
 const [compact,setCompact]=useState(()=>matchMedia('(max-width:899px)').matches),[previewSource,setPreviewSource]=useState<string|null>(null);
 useEffect(()=>{const media=matchMedia('(max-width:899px)'),change=()=>setCompact(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 const [job,setJob]=useState<DocumentJob|null>(null),[loadRevision,setLoadRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sources,setSources]=useState<PdfSourceDocument[]|null>(null),[initialProject,setInitialProject]=useState<PdfProject|undefined>();
 const [compose,setCompose]=useState(()=>new URLSearchParams(location.search).get('compose')==='1');
 const [editorReviewed,setEditorReviewed]=useState(false);
 const handoff=useRef(createReviewHandoff());
 const tokenRef=useRef(token);tokenRef.current=token;const generation=useRef(0),opening=useRef(0);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const transient=job?.lifecycle==='transient',closed=!!job?.closed_at;
 useEffect(()=>{generation.current++;let current=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;setJob(null);setSources(null);setInitialProject(undefined);setError('');
  async function load(){if(!jobId)return;try{const next=await requestJson<DocumentJob>(`/api/documents/${jobId}`,tokenRef.current,{signal:controller.signal});if(!current)return;setJob(next);if(!next.closed_at&&next.files.some(f=>['pending','generating'].includes(f.state)))timer=setTimeout(load,3000);}catch(e){if(current)setError(e instanceof Error?e.message:'Document service unavailable');}}
  void load();return()=>{current=false;generation.current++;controller.abort();clearTimeout(timer);};
 },[jobId,loadRevision]);
 function openEmail(){setSources(null);setInitialProject(undefined);setCompose(true);const url=new URL(location.href);url.searchParams.set('compose','1');history.replaceState(null,'',url);}
 async function openEditor(restore=true){if(!job||compact||closed)return;const life=generation.current,attempt=++opening.current;setBusy(true);setError('');try{
  const ready=job.files.filter(f=>f.state==='ready');if(!ready.length)throw new Error('No source PDF is ready.');
  if(ready.reduce((sum,f)=>sum+(f.byte_count??0),0)>maxBytes)throw new Error('Package exceeds the configured editor memory budget. Use a smaller selection.');
  const docs:PdfSourceDocument[]=[];for(const file of ready){const r=await fetch(`/api/documents/${job.id}/files/${file.id}`,{headers:{Authorization:`Bearer ${tokenRef.current}`}});if(!r.ok){if(r.status===410)throw Error(operationMessages.storage_file_expired);throw new Error('A private source file could not be loaded. No partial package was opened.');}const bytes=new Uint8Array(await r.arrayBuffer());docs.push({id:file.id,name:file.kind==='statement'?'Statement.pdf':`Invoice ${job.manifest.find(i=>i.id===file.invoice_id)?.invoice_no??file.ordinal}.pdf`,kind:file.kind,invoiceId:file.invoice_id??undefined,bytes});}
  let project:PdfProject|undefined;if(!transient&&restore&&job.project_key)project=await requestJson<PdfProject>(`/api/documents/${job.id}/project`,tokenRef.current);
  if(alive.current&&generation.current===life&&opening.current===attempt){setInitialProject(project);setEditorReviewed(!!project&&job.acknowledged&&job.exports.length>0);handoff.current=createReviewHandoff();setSources(docs);}
 }catch(e){if(alive.current&&generation.current===life&&opening.current===attempt)setError(e instanceof Error?e.message:'Unable to open editor');}finally{if(alive.current&&generation.current===life&&opening.current===attempt)setBusy(false);}}
 async function uploadExport(file:PdfExportFile){if(!job)throw Error('Document preparation unavailable');return requestJson<Omit<DocumentExport,'name'>>(`/api/documents/${job.id}/upload?kind=export`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/pdf'},body:new Uint8Array(file.bytes).buffer});}
 async function review(files:PdfExportFile[],next:'email'|'download'){
  if(!job||closed)throw Error('This preparation is unavailable.');if(next==='email'&&job.state!=='ready')throw Error('Some requested documents are missing. Prepare a complete package before continuing to email.');
  const reviewed=await handoff.current(files,job.revision,uploadExport,(revision,exports)=>requestJson<DocumentJob>(`/api/documents/${job.id}/review`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,exports,acknowledged:true})}));
  if(!alive.current)return;setJob(reviewed);
  if(next==='email')return openEmail;
  return ()=>{for(const file of files){const url=URL.createObjectURL(new Blob([new Uint8Array(file.bytes).buffer],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}};
 }
 async function save(files:PdfExportFile[],project:PdfProject){if(!job)throw new Error('Document preparation unavailable');const exports:DocumentExport[]=[];
  for(const file of files)exports.push({...await uploadExport(file),name:file.name});
  const receipt=await requestJson<Omit<DocumentExport,'name'>>(`/api/documents/${job.id}/upload?kind=project`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});
  const saved=await requestJson<DocumentJob>(`/api/documents/${job.id}/save`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:job.revision,projectKey:receipt.storage_key,exports,acknowledged:true})});if(alive.current)setJob(saved);
 }
 async function saveDraft(project:PdfProject){if(!job)throw new Error('Document preparation unavailable');const receipt=await requestJson<Omit<DocumentExport,'name'>>(`/api/documents/${job.id}/upload?kind=project`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});const saved=await requestJson<DocumentJob>(`/api/documents/${job.id}/save`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:job.revision,projectKey:receipt.storage_key,exports:[],acknowledged:false})});if(alive.current)setJob(saved);}
 async function download(index:number){if(!job)return;setError('');try{const r=await fetch(`/api/documents/${job.id}/exports/${index}`,{headers:{Authorization:`Bearer ${tokenRef.current}`}});if(!r.ok)throw new Error(r.status===410?operationMessages.storage_file_expired:'Download unavailable. Retry to check the temporary file.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=job.exports[index].name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setError(e instanceof Error?e.message:'Download unavailable.');}}
 async function discard(){if(!job||!window.confirm('Discard this preparation and its temporary files? PDF edits cannot be reopened. Billing and email history will remain.'))return;setBusy(true);setError('');try{setJob(await requestJson<DocumentJob>(`/api/documents/${job.id}/discard`,tokenRef.current,{method:'POST'}));}catch(e){setError(e instanceof Error?e.message:'Unable to discard this preparation.');}finally{setBusy(false);}}
 if(compose&&job&&!closed&&job.acknowledged&&job.exports.length)return <EmailComposer job={job} token={token} onClose={()=>{setCompose(false);const u=new URL(location.href);u.searchParams.delete('compose');u.searchParams.delete('gmail');history.replaceState(null,'',u);setLoadRevision(n=>n+1);}}/>;
 if(sources&&job&&!closed)return <PdfWorkspace onDirtyChange={onDirtyChange} documents={sources} initialProject={initialProject} transient={transient} onReview={transient?review:undefined} initialReviewed={editorReviewed&&job.acknowledged&&job.exports.length>0} onContinueToEmail={job.state==='ready'?()=>{if(!job.acknowledged||!job.exports.length)return;openEmail();}:undefined} initialDelivery={job.layout==='statement_bundle'?'split':job.layout==='separate'?'separate':'combined'} accountName={job.account_name} hotel={job.hotel} selectedCount={sources.some(s=>s.kind==='statement')?job.invoice_ids.length:sources.filter(s=>s.kind==='invoice').length} onClose={()=>setSources(null)} onSave={transient?undefined:save} onSaveDraft={transient?undefined:saveDraft}/>;
 return <main className="page document-jobs">
  <button className="back-bottom" onClick={onClose}>{backLabel}</button><h1>Document preparation</h1>
  {compact&&jobId&&!closed&&<p className="document-companion-note">Continue PDF editing and final review on a larger screen.</p>}
  {previewSource&&job&&!closed&&<PrivatePdfPreview jobId={job.id} fileId={previewSource} token={token} maxBytes={Math.min(maxBytes,20*1024*1024)} onClose={()=>setPreviewSource(null)}/>}
  {error&&<><p role="alert" className="error-message">{error}</p><button onClick={()=>setLoadRevision(n=>n+1)}>Retry loading documents</button></>}
  {!jobId?<p>Select invoices in an account or Collections to prepare a new package.</p>:!job?<p>{error?'Document preparation unavailable.':'Loading document preparation…'}</p>:<>
   <p>{job.hotel} · {job.account_name} · {job.invoice_ids.length} selected invoices · {closed?'Closed':job.state}</p>
   {closed?<section className="panel document-manifest"><h2>{job.closed_reason==='sent'?'Email sent':'Preparation discarded'}</h2><p>This preparation is closed. Its temporary files are scheduled for deletion. Billing and email history remain in the account.</p><p>Select invoices in the account to prepare fresh documents for a new round.</p><button onClick={onClose}>{backLabel}</button></section>:<>
    {transient&&<p className="information-note">Prepare fresh documents for this round. PDF edits stay in this tab. Reviewed files are held privately for the current email or download, then removed after confirmed sending or explicit discard.</p>}
    {job.state==='queued'&&<p className="information-note" role="status">Waiting for document processing to start. This request continues in the background; progress updates here automatically.</p>}
    {job.files.some(f=>f.state==='generating')&&<p role="status">Preparing requested PDFs · {job.files.filter(f=>f.state==='ready').length} of {job.files.length} ready.</p>}
    <section className="panel document-manifest"><h2>Requested source PDFs</h2>{job.files.map(f=><div key={f.id}><strong>{f.kind==='statement'?'Statement':`Invoice ${job.manifest.find(i=>i.id===f.invoice_id)?.invoice_no??f.ordinal}`}</strong><span>{f.state}</span>{f.state==='ready'&&<button className="source-preview-button" onClick={()=>setPreviewSource(f.id)}>Preview source PDF</button>}{f.error_code&&<p>{message(f.error_code)}{f.state==='uncertain'?' The provider may have processed the request. It will not be repeated automatically.':''}</p>}</div>)}</section>
    {job.state==='queued'&&<button disabled={busy} onClick={async()=>{setBusy(true);try{setJob(await requestJson<DocumentJob>(`/api/documents/${job.id}/dispatch`,tokenRef.current,{method:'POST'}));}catch(e){setError(e instanceof Error?e.message:'Dispatch unavailable');}finally{setBusy(false);}}}>Retry pending dispatch</button>}
    {job.files.some(f=>f.state==='ready')&&(!transient||!job.acknowledged)&&<><p>{job.state!=='ready'?'Some requested files are unavailable. Opening available files is a subset review; missing sources are not replaced.':'All requested source files are ready for review.'}</p><button className="primary-button" disabled={compact||busy||job.files.some(f=>['pending','generating'].includes(f.state))} onClick={()=>openEditor()}>{busy?'Loading original PDFs…':!transient&&job.project_key?'Reopen saved PDF project':job.state==='ready'?'Open PDF Workspace':'Open available native files only'}</button>{!transient&&job.project_key&&<button className="back-bottom" disabled={compact||busy} onClick={()=>openEditor(false)}>Start from original PDFs</button>}</>}
    {job.exports.length>0&&<section className="panel document-manifest"><h2>{transient?'Reviewed files for this attempt':`Reviewed files · revision ${job.revision}`}</h2>{job.acknowledged&&job.state==='ready'&&<button className="primary-button" onClick={openEmail}>{transient?'Continue to email':'Prepare email'}</button>}{job.exports.map((f,i)=><button key={f.storage_key} onClick={()=>download(i)}>{f.name} · Download</button>)}{transient&&<p>Retries use these reviewed files. To change the PDFs after leaving the editor, start a new preparation from the account.</p>}</section>}
    {!transient&&job.acknowledged&&job.state==='ready'&&job.exports.length>0&&<DriveArchive key={job.id+':'+job.revision} token={token} job={job}/>}
    {transient&&<div className="document-discard"><button disabled={busy||['queued','running'].includes(job.state)} onClick={()=>void discard()}>Discard preparation</button><p>For By System, download the reviewed PDFs and submit them in the account’s system. Record actual billing separately, then discard this temporary preparation when finished.</p></div>}
    <p>Document preparation does not send email. PDF editing never changes OPERA or AR balances.</p>
   </>}
  </>}
 </main>;
}
