import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,FileText,Mail,ShieldCheck} from 'lucide-react';
import type {EmailDraft} from '../worker/email/shared';
import type {DocumentJob} from '../worker/documents/jobs';
import './email-composer.css';

async function api<T>(path:string,token:string,init:RequestInit={}):Promise<T>{
 const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});const data=await r.json() as Record<string,unknown>;
 if(!r.ok)throw Error(({email_package_changed:'The reviewed PDF package changed. Return to PDF review before continuing.',email_revision_conflict:'This draft changed in another session. Your edits are retained; reopen the draft to review the latest version.',email_package_not_reviewed:'Review and save the final PDF package before preparing email.',email_invalid:'Check recipient addresses and message fields.',gmail_not_configured:'Gmail OAuth configuration is incomplete.',email_source_changed:'OPERA balances or invoice relationships changed. Refresh the account and prepare a new reviewed package.',email_too_large:'The complete attachment package exceeds this Worker’s Gmail memory budget. No files were removed.',gmail_reconnect_required:'Gmail access needs authorization again.',gmail_read_permission_required:'Authorize Gmail read access to verify Sent evidence before continuing.',email_incomplete:'Add a To recipient, subject and message before sending.',email_stage_required:'Select the collection stage for this message.',email_rules_missing:'Set Billing requirement and Credit Term for the selected invoices before sending. Billing applies only to Billing Required invoices.',email_handoff_pending:'A Gmail draft request is still pending or uncertain. Check Gmail before any new request.'} as Record<string,string>)[String(data.error)]??'The email service is unavailable. Your edits remain here.');
 return data as T;
}
const fields=['to','cc','bcc'] as const;
type GmailState={configured:boolean;connected:boolean;canRead?:boolean;email?:string;maxAttachmentBytes?:number};
export default function EmailComposer({job,token,onClose}:{job:DocumentJob;token:string;onClose:()=>void}){
 const [draft,setDraft]=useState<EmailDraft|null>(null),[purpose,setPurpose]=useState<'billing'|'collection'>('billing'),[recipients,setRecipients]=useState({to:'',cc:'',bcc:''}),[subject,setSubject]=useState(''),[body,setBody]=useState('');
 const [gmail,setGmail]=useState<GmailState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[dirty,setDirty]=useState(false),[retry,setRetry]=useState(0);
 const [handoff,setHandoff]=useState(''),[stage,setStage]=useState(''),[confirming,setConfirming]=useState(false),[ack,setAck]=useState(false),[delivery,setDelivery]=useState<{id:string;state:string;mode:string;recorded?:boolean}|null>(null);
 const [testOpen,setTestOpen]=useState(false),[testRecipient,setTestRecipient]=useState(''),[testId]=useState(()=>sessionStorage.getItem('ar-mail-test-command')??crypto.randomUUID()),[testResult,setTestResult]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);
 const live=useRef(true),tokenRef=useRef(token);tokenRef.current=token;
 function restore(d:EmailDraft){setDraft(d);setPurpose(d.purpose);setRecipients({to:d.recipients.to.join(', '),cc:d.recipients.cc.join(', '),bcc:d.recipients.bcc.join(', ')});setSubject(d.subject);setBody(d.body);setDirty(false);setHandoff(d.gmail_handoff??'');setDelivery(d.delivery??null);}
 useEffect(()=>{live.current=true;const controller=new AbortController();setError('');
  void api<EmailDraft>('/api/email/open',tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.id,documentRevision:job.revision}),signal:controller.signal}).then(d=>{if(live.current)restore(d);}).catch(e=>{if(live.current)setError(e.message);});
  void api<GmailState>('/api/gmail/status',tokenRef.current,{signal:controller.signal}).then(s=>{if(live.current)setGmail(s);}).catch(()=>{if(live.current)setGmail(null);});
  return()=>{live.current=false;controller.abort();};
 },[job.id,job.revision,retry]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const changed=()=>{setDirty(true);setStatus('');};
 async function save(){if(!draft)return;setBusy(true);setError('');try{
  const parsed=Object.fromEntries(fields.map(f=>[f,recipients[f].split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)]));
  const saved=await api<EmailDraft>(`/api/email/${draft.id}`,tokenRef.current,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:draft.revision,purpose,recipients:parsed,subject,body})});
  if(live.current){restore(saved);setStatus('Workspace draft saved. This save did not create or send a Gmail message.');}
 }catch(e){if(live.current)setError(e instanceof Error?e.message:'Save unavailable.');}finally{if(live.current)setBusy(false);}}
 async function connect(){if(!draft)return;setBusy(true);setError('');try{const result=await api<{url:string}>('/api/gmail/connect',tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:job.id})});const u=new URL(result.url);if(u.origin!=='https://accounts.google.com')throw Error('Unexpected authorization destination.');location.assign(u.href);}catch(e){setError(e instanceof Error?e.message:'Gmail unavailable.');setBusy(false);}}
 async function createDraft(){if(!draft)return;setBusy(true);setError('');try{const result=await api<{id:string;state:string;created:boolean;mode:string}>(`/api/email/${draft.id}/gmail-draft`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:draft.revision,stage:purpose==='collection'?stage:null})});if(live.current){setHandoff(result.state);setDelivery(result);setStatus(result.state==='created'?'Gmail confirmed draft creation. AR Workspace did not send it.':'Gmail draft outcome is uncertain. Check Gmail; this request will not be repeated automatically.');}}catch(e){if(live.current)setError(e instanceof Error?e.message:'Gmail draft unavailable.');}finally{if(live.current)setBusy(false);}}
 async function download(index:number){if(!draft)return;setError('');try{const r=await fetch(`/api/email/${draft.id}/exports/${index}`,{headers:{Authorization:`Bearer ${tokenRef.current}`}});if(!r.ok)throw Error();const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=draft.exports[index].name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}catch{setError('Private attachment download is unavailable.');}}
 async function sendNow(){if(!draft||!ack)return;setBusy(true);setError('');try{const r=await api<{id:string;state:string;mode:string;recorded?:boolean}>(`/api/email/${draft.id}/send`,tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:draft.revision,stage:purpose==='collection'?stage:null,confirmed:true})});setDelivery(r);setHandoff(r.state);setConfirming(false);setStatus(r.state==='sent'?'Gmail sent evidence verified. Billing / collection history recorded.':'Send outcome needs verification. Use Check sent status; do not send again.');}catch(e){setError(e instanceof Error?e.message:'Send unavailable.');}finally{setBusy(false);}}
 async function checkSent(){if(!delivery)return;setBusy(true);setError('');try{const r=await api<{id:string;state:string;mode:string;recorded?:boolean}>(`/api/email/deliveries/${delivery.id}/check`,tokenRef.current,{method:'POST'});setDelivery(r);setHandoff(r.state);setStatus(r.state==='sent'?'Gmail sent evidence verified. Billing / collection history recorded.':r.state==='review_required'?'The sent message or workflow needs review. No invoice history was updated.':'No verified sent message yet. A missing draft is not proof of sending.');}catch(e){setError(e instanceof Error?e.message:'Verification unavailable.');}finally{setBusy(false);}}
 async function testSend(){sessionStorage.setItem('ar-mail-test-command',testId);setBusy(true);setError('');try{const r=await api<{state:string;id:string}>('/api/email/test-send',tokenRef.current,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:testId,recipient:testRecipient,confirmed:true})});setTestRecipient('');setTestResult(r.state==='sent'?'Test email sent and verified. No business history was changed.':'Test outcome unconfirmed. Check the original request before any retry.');}catch(e){setError(e instanceof Error?e.message:'Test unavailable.');}finally{setBusy(false);}}
 async function checkTest(){setBusy(true);try{const r=await api<{state:string}>(`/api/email/deliveries/${testId}/check`,tokenRef.current,{method:'POST'});setTestResult(r.state==='sent'?'Test email sent and verified. No business history was changed.':'Test still needs verification. Do not send again.');}catch{setTestResult('Verification unavailable. Do not send again.');}finally{setBusy(false);}}
 function close(){if(!dirty||window.confirm('Leave without saving these message edits?'))onClose();}
 return <dialog ref={dialog} className="email-workspace" aria-label="Email workspace" onCancel={e=>{e.preventDefault();if(!busy)close();}}>
  <header className="email-heading" inert={confirming}><div><Mail size={24}/><div><h1>Email preparation</h1><p>{job.hotel} · {job.account_name} · {job.invoice_ids.length} selected invoices</p></div></div><span className="email-ready"><ShieldCheck size={15}/> Reviewed PDF · revision {job.revision}</span><button aria-label="Back to document preparation" onClick={close} disabled={busy}><ArrowLeft size={18}/></button></header>
  <ol className="email-steps" inert={confirming}>{['Scope & purpose','Documents','PDF review','Email','Gmail handoff'].map((label,i)=><li key={label} className={i===3?'current':i<3?'complete':''}><span>{i<3?<Check size={16}/>:i+1}</span><div>{label}<small>{['Selected invoices','Source files ready','Reviewed and saved','Message & attachments','Draft or send'][i]}</small></div></li>)}</ol>
  {!draft?<section className="email-loading">{error?<><p role="alert">{error}</p><button onClick={()=>setRetry(n=>n+1)}>Retry loading draft</button></>:<p role="status">Loading saved email workspace…</p>}</section>:<div className="email-columns" inert={confirming}>
   <aside className="email-context"><h2>Message context</h2><p className="email-muted">Purpose and recipient profile</p><div className="email-purpose">{(['billing','collection'] as const).map(p=><button key={p} disabled={busy||confirming} aria-pressed={purpose===p} onClick={()=>{setPurpose(p);changed();}}>{p}</button>)}</div>{purpose==='collection'&&<label className="email-stage">Collection stage<select aria-label="Collection stage" disabled={busy||confirming||!!handoff} value={stage} onChange={e=>setStage(e.target.value)}><option value="">Choose stage</option>{['Friendly','Follow 1','Follow 2','Follow 3','Final'].map(v=><option key={v}>{v}</option>)}</select></label>}<section><h3>Recipient profile</h3><strong>Current message</strong><p>Initial recipients use this account’s saved {draft.purpose} profile. Editing this message does not change account defaults.</p><p className="email-note">No recipient fallback from OPERA.</p></section><section><h3>Message format</h3><strong>Plain text</strong><p>Edit the subject and wording for this email.</p></section><section><h3>Thread choice</h3><div className="email-thread">Start a new email<small>Existing-thread selection is not enabled yet.</small></div></section></aside>
   <section className="email-message"><div className="email-message-title"><h2>Message draft</h2><span>{purpose}</span></div><fieldset disabled={busy||confirming||draft.package_changed}><legend className="sr-only">Email fields</legend>{fields.map(f=><label className="email-address" key={f}><span>{f.toUpperCase()}</span><input aria-label={`Email ${f.toUpperCase()}`} value={recipients[f]} placeholder={f==='to'?'Add recipient addresses':'Optional'} onChange={e=>{setRecipients({...recipients,[f]:e.target.value});changed();}}/></label>)}<label className="email-address"><span>Subject</span><input aria-label="Email subject" maxLength={998} value={subject} onChange={e=>{setSubject(e.target.value);changed();}}/></label><label className="email-body-label"><span>Message</span><textarea aria-label="Email message" value={body} maxLength={100000} onChange={e=>{setBody(e.target.value);changed();}}/></label></fieldset><footer><span>{dirty?'Unsaved changes':`Saved revision ${draft.revision}`}</span><button className="primary-button" onClick={save} disabled={busy||draft.package_changed||!dirty}>{busy?'Working…':'Save workspace draft'}</button></footer>{status&&<p role="status" className="email-feedback">{status}</p>}{(error||draft.package_changed)&&<p role="alert" className="error-message">{error||'The PDF package changed. Return to document preparation.'}</p>}</section>
   <aside className="email-attachments"><h2>Attachments</h2><p className="email-muted">Exact files from the reviewed package</p><div className="email-size"><strong>{draft.exports.length} files</strong><span>{(draft.exports.reduce((n,f)=>n+f.byte_count,0)/1048576).toFixed(2)} MiB</span></div><h3>Generated package</h3>{draft.exports.map((f,index)=><div className="email-file" key={f.storage_key}><FileText size={22}/><div><button className="email-file-link" onClick={()=>download(index)}>{f.name}</button><small>Reviewed PDF · {(f.byte_count/1024).toFixed(0)} KiB</small></div><Check size={14}/></div>)}<h3>Supplemental attachments</h3><p className="email-note">Supplemental upload is not enabled in this increment.</p><section className="email-handoff"><h3>Gmail connection</h3><p>{gmail===null?'Connection status unavailable.':gmail.connected?`Connected as ${gmail.email}`:gmail.configured?'Authorize Gmail to enable draft handoff.':'Gmail configuration is incomplete.'}</p>{(!gmail?.connected||!gmail.canRead)&&<button className="primary-button" disabled={busy||dirty||!gmail?.configured} onClick={connect}>{gmail?.connected?'Authorize sent verification':'Connect Gmail'}</button>}{dirty&&<small>Save your message before connecting Gmail.</small>}<button className="primary-button" onClick={createDraft} disabled={busy||dirty||!gmail?.connected||!gmail.canRead||draft.package_changed||!!handoff||(purpose==='collection'&&!stage)}>{busy?'Checking package…':'Create Gmail draft'}</button><button disabled={busy||dirty||!gmail?.connected||!gmail.canRead||draft.package_changed||!!handoff||(purpose==='collection'&&!stage)} onClick={()=>{setAck(false);setConfirming(true);}}>Review & send now</button>{delivery&&<><p role="status">Delivery: {delivery.state.replaceAll('_',' ')}</p><button disabled={busy||delivery.state==='sent'} onClick={checkSent}>Check sent status</button></>}{gmail?.maxAttachmentBytes&&<small>Attachment budget: {(gmail.maxAttachmentBytes/1048576).toFixed(0)} MiB. Complete package only.</small>}{handoff&&<a href="https://mail.google.com/mail/u/?authuser=ar%40katathani.com#drafts" target="_blank" rel="noreferrer">Open Gmail drafts →</a>}<p className="email-note">Saving a draft does not record billing / collection activity. Only verified Sent evidence does.</p><button disabled={busy||!gmail?.canRead} onClick={()=>{setTestOpen(!testOpen);}}>Connection test</button>{testOpen&&<div className="email-test"><label>One-time test recipient<input type="email" aria-label="One-time test recipient" autoComplete="off" value={testRecipient} onChange={e=>setTestRecipient(e.target.value)}/></label><p>Sends one generic message with a synthetic PDF. Recipient is not saved as an account default. No invoice history or KPI changes.</p><button disabled={busy||!testRecipient||!!testResult} onClick={testSend}>Send one test email</button>{testResult&&<><p role="status">{testResult}</p><button disabled={busy} onClick={checkTest}>Check test status</button></>}</div>}</section></aside>
  </div>}{confirming&&draft&&<section className="email-send-confirm" aria-label="Confirm email send"><h2>Review before sending</h2><p>{job.hotel} · {job.account_name} · {purpose==='billing'?'Billing':stage}</p>{fields.map(f=><p key={f}><strong>{f.toUpperCase()}: </strong>{recipients[f]||'None'}</p>)}<p><strong>{subject}</strong></p><pre>{body}</pre><h3>Selected invoices</h3><p>{job.manifest?.map(i=>`Invoice ${i.invoice_no??'unavailable'} · Folio ${i.folio_no??'unavailable'}`).join('; ')??`${job.invoice_ids.length} selected invoices`}</p><h3>Attachments</h3><ul>{draft.exports.map(f=><li key={f.storage_key}>{f.name}</li>)}</ul><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the recipients, message and final PDF files.</label><footer><button disabled={busy} onClick={()=>setConfirming(false)}>Back to editing</button><button className="primary-button" disabled={!ack||busy} onClick={sendNow}>{busy?'Sending and verifying…':'Confirm send now'}</button></footer>{error&&<p role="alert">{error}</p>}</section>}
 </dialog>;
}
