import { useState } from 'react';
import { ChevronRight, ChevronDown } from 'lucide-react';
import { aggregateAccounts, filterAccounts, sortRows, money, type Account, type Comparison } from './domain/portfolio';
import { agingLabels } from './demo';
import { Freshness, SearchBox, SortHead } from './ui';
export function Portfolio({ accounts, hotel, review, params, update, openAccount }: { accounts: Account[]; hotel: string; review: boolean; params: URLSearchParams; update: (k:string,v:string)=>void; openAccount:(a:Account)=>void }) {
  const [expanded, setExpanded] = useState(false);
  const [group, setGroup] = useState<Comparison|null>(null);
  const type = params.get('type') || 'All', search = params.get('search') || '';
  const sort = (params.get('sort') || 'total') as keyof Comparison, direction = params.get('dir') === 'asc' ? 'asc' : 'desc';
  const filtered = filterAccounts(accounts, { hotel, type, search });
  const propertyRows = filterAccounts(accounts, {hotel, type: 'All', search: ''});
  const total = propertyRows.reduce((s,a)=>s+a.open,0);
  const sumHotel = (h:string) => propertyRows.filter(a=>a.hotel===h).reduce((s,a)=>s+a.open,0);
  const typeRows = sortRows(aggregateAccounts(propertyRows, true), sort, direction);
  const accountRows = sortRows(aggregateAccounts(filtered), sort, direction);
  const onSort = (key:keyof Comparison) => { update('sort',key); update('dir',sort === key && direction === 'desc' ? 'asc':'desc'); };
  const headings: [string,keyof Comparison][] = [['TSK','tsk'],['KAT','kat'],['Total open','total'],['Over 90 days','over90'],['Accounts','accounts'],['Items','items']];
  const table = (rows:Comparison[], isType:boolean) => <div className="table-scroll"><table className="comparison"><thead><tr><SortHead label={isType?'Account type':'Account'} active={sort==='name'} direction={direction} onClick={()=>onSort('name')}/>{headings.map(([label,key])=><SortHead key={key} label={label} active={sort===key} direction={direction} onClick={()=>onSort(key)}/>)}<th>% {isType?'Portfolio':'Filtered'}</th></tr></thead><tbody>{rows.map(row=><tr key={row.key} className={isType && type===row.name?'selected-row':''}>
    <td><button className="name-link" onClick={()=>isType?update('type',type===row.name?'All':row.name):row.members.length===1?openAccount(row.members[0]):setGroup(row)}>{row.name}{!isType&&<ChevronRight size={12}/>}</button></td>
    {(['tsk','kat'] as const).map(key=><td className={key} key={key}>{isType ? money(row[key]) : row.members.find(a=>a.hotel===key.toUpperCase()) ? <button className="amount-link" onClick={()=>openAccount(row.members.find(a=>a.hotel===key.toUpperCase())!)}>{money(row[key])}</button> : <span className="muted">—</span>}</td>)}
    <td className="total-cell"><span className="value-bar" style={{width:`${Math.max(0,row.total/Math.max(...rows.map(r=>r.total),1)*96)}%`}}/><strong>{money(row.total)}</strong></td><td className="overdue">{money(row.over90)}</td><td>{row.accounts}</td><td>{row.items}</td><td className="percentage">{(row.total/Math.max(rows.reduce((s,r)=>s+r.total,0),1)*100).toFixed(1)}%</td>
  </tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><strong>{accounts.length?'No matching accounts':'No OPERA data yet'}</strong><p>{accounts.length?'Try another account type or search.':'The workspace will show verified balances after OPERA is connected and refreshed.'}</p></div>}</div>;
  return <main className="page portfolio"><div className="page-title"><div><h1>Receivables portfolio</h1><p>All Hotels comparison with exact property contribution and account-level drill-down.</p></div><Freshness review={review}/></div>
    <section className="portfolio-overview"><div className="panel total-summary"><span className="metric-label">Total open AR {review?'· Synthetic':''}</span><strong>{accounts.length?money(total):'—'}</strong><small>{propertyRows.length} accounts · {propertyRows.reduce((s,a)=>s+a.items,0)} Invoice / Folio items</small><div className="orb"/></div>
      <div className="panel contributions"><h2>Hotel contribution <span>{hotel==='All'?'All Hotels':hotel}</span></h2><div className="property-pair">{['KAT','TSK'].map(h=><div key={h}><small>{h} · {total?(sumHotel(h)/total*100).toFixed(0):'—'}%</small><strong>{accounts.length?money(sumHotel(h)):'—'}</strong><div className="mini-track"><i style={{width:`${total?sumHotel(h)/total*100:0}%`,background:h==='KAT'?'#4169ff':'#13b7ac'}}/></div></div>)}</div></div>
      <div className="panel aging-summary"><h2>Aging exposure <span>Separate source buckets · values stay visible</span></h2>{['KAT','TSK'].map(h=><div className="aging-row" key={h}><b>{h}</b><div className="aging-track">{[.43,.14,.08,.10,.12,.13].map((v,i)=><span key={i} className={`bucket-${i}`} style={{width:accounts.length?`${v*100}%`:'0%'}}/>)}</div><b>{accounts.length?money(sumHotel(h)):'—'}</b></div>)}<div className="aging-legend">{agingLabels.map(x=><span key={x}>{x}</span>)}</div><button className="text-button aging-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'Collapse':'Expand'} Aging <ChevronDown size={11}/></button></div>
    </section>
    {expanded&&<section className="panel expanded-aging"><strong>Aging by hotel</strong><p>{review?'Illustrative distribution for visual review. Live aging will use each hotel’s source buckets.':'No verified OPERA aging buckets available.'}</p>{['KAT','TSK'].map(h=><div className="aging-values" key={h}><b>{h}</b>{agingLabels.map((l,i)=><span key={l}><small>{l}</small>{review?money(sumHotel(h)*[.43,.14,.08,.10,.12,.13][i]):'—'}</span>)}</div>)}</section>}
    <div className="filters"><label className="filter">Account Type<select aria-label="Account Type" value={type} onChange={e=>update('type',e.target.value)}><option value="All">All</option>{[...new Set(accounts.map(a=>a.type))].map(t=><option key={t}>{t}</option>)}</select></label><button className="filter" onClick={()=>{update('type','All');update('search','');}}>Clear filters</button><span className="filter-count">{accountRows.length} matching accounts</span><SearchBox value={search} onChange={v=>update('search',v)} placeholder="Search Account / Account ID"/></div>
    <section className="panel table-panel"><div className="panel-heading"><h2>Account Type overview <small>All {typeRows.length} types · no top-N cutoff</small></h2><div className="property-key"><i className="kat-dot"/>KAT<i className="tsk-dot"/>TSK</div></div>{table(typeRows,true)}</section>
    <section className="panel table-panel accounts-panel"><div className="panel-heading"><h2>Accounts <span className="badge">{type==='All'?'All types':type}</span></h2><small>Both hotels shown · {sort==='total'?'Sorted by Total Open':`Sorted by ${sort}`}</small></div>{table(accountRows,false)}<div className="table-foot">{review?'All values and account labels are synthetic. ':''}Every matching account is accessible. Select a property amount to open its ledger.</div></section>
    {group&&<div className="modal-backdrop" onClick={()=>setGroup(null)}><section className="group-dialog panel" role="dialog" aria-modal="true" aria-label="Choose account hotel" onClick={e=>e.stopPropagation()}><h2>{group.name}</h2><p>Select a hotel to open its separate account ledger.</p>{group.members.map(a=><button key={a.hotel+a.id} className="hotel-choice" onClick={()=>openAccount(a)}><b>{a.hotel}</b><strong>{money(a.open)}</strong><ChevronRight size={16}/></button>)}<button onClick={()=>setGroup(null)}>Cancel</button></section></div>}
  </main>;
}
