import { useEffect, useRef, useState } from 'react';
import { ChevronRight, ChevronDown } from 'lucide-react';
import { sourceAging, type RefreshState, aggregateAccounts, filterAccounts, sortRows, money, type Account, type Comparison } from './domain/portfolio';
import { agingLabels } from './demo';
import { SourceWarning, Freshness, SearchBox, SortHead } from './ui';
export function Portfolio({ accounts, hotel, review, refresh, params, update, openAccount }: { accounts: Account[]; hotel: string; review: boolean; refresh?: RefreshState; params: URLSearchParams; update: (k:string,v:string)=>void; openAccount:(a:Account)=>void }) {
  const [expanded, setExpanded] = useState(false);
  const [group, setGroup] = useState<Comparison|null>(null);
  const groupDialog = useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(group)groupDialog.current?.showModal();},[group]);
  const type = params.get('type') || 'All', search = params.get('search') || '';
  const sort = (params.get('sort') || 'total') as keyof Comparison, direction = params.get('dir') === 'asc' ? 'asc' : 'desc';
  const filtered = filterAccounts(accounts, { hotel, type, search }).filter(a => (!params.get('accountFilter') || a.name===params.get('accountFilter')) && (params.get('aging')!=='over90' || a.over90>0));
  const propertyRows = filterAccounts(accounts, {hotel, type: 'All', search: ''});
  const total = propertyRows.reduce((s,a)=>s+a.open,0);
  const sumHotel = (h:string) => propertyRows.filter(a=>a.hotel===h).reduce((s,a)=>s+a.open,0);
  const typeRows = sortRows(aggregateAccounts(propertyRows, true), sort, direction);
  const accountRows = sortRows(aggregateAccounts(filtered), sort, direction);
  const onSort = (key:keyof Comparison) => { update('sort',key); update('dir',sort === key && direction === 'desc' ? 'asc':'desc'); };
  const headings: [string,keyof Comparison][] = [['TSK','tsk'],['KAT','kat'],['Total open','total'],['Over 90 days','over90'],['% share','share'],['Accounts','accounts'],['Items','items']];
  const table = (rows:Comparison[], isType:boolean) => <div className="table-scroll" role="region" aria-label={isType?'Account type comparison':'Accounts comparison'} tabIndex={0}><table className="comparison"><thead><tr><SortHead label={isType?'Account type':'Account'} active={sort==='name'} direction={direction} onClick={()=>onSort('name')}/>{headings.map(([label,key])=><SortHead key={key} label={label} active={sort===key} direction={direction} onClick={()=>onSort(key)}/>)}</tr></thead><tbody>{rows.map(row=><tr key={row.key} className={isType && type===row.name?'selected-row':''}>
    <td><button className="name-link" onClick={()=>isType?update('type',type===row.name?'All':row.name):row.members.length===1?openAccount(row.members[0]):setGroup(row)}>{row.name}{!isType&&<ChevronRight size={12}/>}</button></td>
    {(['tsk','kat'] as const).map(key=><td className={key} key={key}>{isType ? money(row[key]) : row.members.find(a=>a.hotel===key.toUpperCase()) ? <button className="amount-link" onClick={()=>openAccount(row.members.find(a=>a.hotel===key.toUpperCase())!)}>{money(row[key])}</button> : <span className="muted">—</span>}</td>)}
    <td className="total-cell"><span className="value-bar" style={{width:`${Math.max(0,row.total/Math.max(...rows.map(r=>r.total),1)*96)}%`}}/><strong>{money(row.total)}</strong></td><td className="overdue">{money(row.over90)}</td><td className="percentage">{row.share.toFixed(1)}%</td><td>{row.accounts}</td><td>{row.items}</td>
  </tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><strong>{accounts.length?'No matching accounts':'No OPERA data yet'}</strong><p>{accounts.length?'Try another account type or search.':'The workspace will show verified balances after OPERA is connected and refreshed.'}</p></div>}</div>;
  return <main className="page portfolio"><div className="page-title"><div><h1>Receivables portfolio</h1><p>All Hotels comparison with exact property contribution and account-level drill-down.</p></div><Freshness review={review} refresh={refresh} hotel={hotel}/></div>
    <section className="portfolio-overview"><div className="panel total-summary"><span className="metric-label">Total open AR {review?'· Synthetic':''}</span><strong>{accounts.length?money(total):'—'}</strong><small>{propertyRows.length} accounts · {propertyRows.reduce((s,a)=>s+a.items,0)} Invoice / Folio items</small><div className="orb"/></div>
      <div className="panel contributions"><h2>Hotel contribution <span>{hotel==='All'?'All Hotels':hotel}</span></h2><div className="property-pair">{['KAT','TSK'].map(h=><div key={h}><small>{h} · {total?(sumHotel(h)/total*100).toFixed(0):'—'}%</small><strong>{accounts.length?money(sumHotel(h)):'—'}</strong><div className="mini-track"><i style={{width:`${total?sumHotel(h)/total*100:0}%`,background:h==='KAT'?'#4169ff':'#13b7ac'}}/></div></div>)}</div></div>
      <div className="panel aging-summary"><h2>Aging exposure <span>Separate source buckets · values stay visible</span></h2>{['KAT','TSK'].map(h=>{const buckets=sourceAging(propertyRows,h);const positive=buckets.reduce((sum,b)=>sum+Math.max(0,b.amount),0);return <div key={h}><div className="aging-row"><b>{h}</b><div className="aging-track">{review?[.43,.14,.08,.10,.12,.13].map((v,i)=><span key={i} className={`bucket-${i}`} style={{width:accounts.length?`${v*100}%`:'0%'}}/>):buckets.map((b,i)=><span key={i} title={`${b.label}: ${money(b.amount,false)}`} className={`bucket-${i%6}`} style={{width:positive?`${Math.max(0,b.amount)/positive*100}%`:'0%'}}/>)}</div><b>{accounts.length?money(sumHotel(h)):'—'}</b></div>{!review&&<small>{buckets.length?buckets.map(b=>`${b.label}: ${money(b.amount)}`).join(' · '):'Aging unavailable or source ranges differ across accounts'}</small>}</div>})}{review&&<div className="aging-legend">{agingLabels.map(x=><span key={x}>{x}</span>)}</div>}<button className="text-button aging-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'Collapse':'Expand'} Aging <ChevronDown size={11}/></button></div>
    </section>
    {!review&&<SourceWarning accounts={propertyRows}/>}
    {expanded&&<section className="panel expanded-aging"><strong>Aging by hotel</strong><p>{review?'Illustrative distribution for visual review. Live aging will use each hotel’s source buckets.':'Source ranges remain separate for each hotel. Negative balances are shown as credits.'}</p>{['KAT','TSK'].map(h=><div className="aging-values" key={h}><b>{h}</b>{review?agingLabels.map((l,i)=><span key={l}><small>{l}</small>{money(sumHotel(h)*[.43,.14,.08,.10,.12,.13][i])}</span>):sourceAging(propertyRows,h).map((b,i)=><span key={i}><small>{b.label}</small>{money(b.amount)}<small>Debit {money(b.debit)} · Credit {money(b.credit)}</small></span>)}</div>)}</section>}
    <div className="filters"><label className="filter">Account Type<select aria-label="Account Type" value={type} onChange={e=>update('type',e.target.value)}><option value="All">All</option>{[...new Set(accounts.map(a=>a.type))].map(t=><option key={t}>{t}</option>)}</select></label><label className="filter">Account<select aria-label="Account filter" value={params.get('accountFilter')||''} onChange={e=>update('accountFilter',e.target.value)}><option value="">All</option>{[...new Set(accounts.map(a=>a.name))].map(n=><option key={n}>{n}</option>)}</select></label><label className="filter">Aging<select aria-label="Aging filter" value={params.get('aging')||'All'} onChange={e=>update('aging',e.target.value)}><option>All</option><option value="over90">Over 90 exposure</option></select></label><button className="filter" onClick={()=>{update('type','All');update('search','');update('accountFilter','');update('aging','');}}>Clear filters</button><span className="filter-count">{accountRows.length} matching accounts</span><SearchBox value={search} onChange={v=>update('search',v)} placeholder="Search Account / Account ID"/></div>
    <section className="panel table-panel"><div className="panel-heading"><h2>Account Type overview <small>All {typeRows.length} types · no top-N cutoff</small></h2><div className="property-key"><i className="kat-dot"/>KAT<i className="tsk-dot"/>TSK</div></div><p className="table-scroll-hint">Scroll across to compare TSK, KAT and Total.</p>{table(typeRows,true)}</section>
    <section className="panel table-panel accounts-panel"><div className="panel-heading"><h2>Accounts <span className="badge">{type==='All'?'All types':type}</span></h2><small>Both hotels shown · {sort==='total'?'Sorted by Total Open':`Sorted by ${sort}`}</small></div><p className="table-scroll-hint">All {accountRows.length} matching accounts · scroll across for every column.</p>{table(accountRows,false)}<div className="table-foot">{review?'All values and account labels are synthetic. ':''}Every matching account is accessible. Select a property amount to open its ledger.</div></section>
    {group&&<dialog ref={groupDialog} className="group-dialog panel" aria-label="Choose account hotel" onClose={()=>setGroup(null)} onClick={e=>{const box=e.currentTarget.getBoundingClientRect();if(e.target===e.currentTarget&&(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom))e.currentTarget.close();}}><h2>{group.name}</h2><p>Select a hotel to open its separate account ledger.</p>{group.members.map(a=><button key={a.hotel+a.id} className="hotel-choice" onClick={()=>openAccount(a)}><b>{a.hotel}</b><strong>{money(a.open)}</strong><ChevronRight size={16}/></button>)}<button onClick={()=>groupDialog.current?.close()}>Cancel</button></dialog>}
  </main>;
}
