-- Explicit self-test only. Its synthetic source/notice/file metadata subtransaction NEVER commits.
create function public.ar_remittance_diagnostic_check(p_actor uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare
 scope text:='SYNTHETIC-REMIT-'||gen_random_uuid()::text;day date:=(clock_timestamp() at time zone 'Asia/Bangkok')::date;
 rid uuid:=gen_random_uuid();rid2 uuid:=gen_random_uuid();rid3 uuid:=gen_random_uuid();bad_rid uuid:=gen_random_uuid();fid uuid:=gen_random_uuid();
 cmd uuid:=gen_random_uuid();void_cmd uuid:=gen_random_uuid();remove_cmd uuid:=gen_random_uuid();
 input jsonb;second_input jsonb;edit_input jsonb;r jsonb;filters jsonb;file jsonb;limits jsonb;
 checks integer:=0;rolled_back boolean:=false;
begin
 if not ar_private.remittance_actor(p_actor) then return jsonb_build_object('error','remittance_forbidden');end if;
 perform pg_advisory_xact_lock(hashtextextended(p_actor::text,946));
 begin
  insert into public.ar_accounts(hotel,id,name,type,open,over90,items,verification_state,account_no)
  values('KAT',scope,'Synthetic remittance Account','SYNTHETIC_REMIT',30000,0,3,'verified','SYNTHETIC'),('TSK',scope,'Synthetic other hotel','SYNTHETIC_REMIT',100,0,1,'verified','SYNTHETIC');
  insert into public.ar_invoices(hotel,account_id,id,guest,invoice_no,folio_no,transaction_date,original,open,verification_state,collection_role,compressed,synced_at)
  select 'KAT',scope,x.id,'Synthetic guest '||x.id,'INV-'||x.id,'FOL-'||x.id,day-10,10000,x.amount,x.verification,'standalone',false,clock_timestamp()
  from(values('A',10000::numeric,'verified'),('B',10000,'verified'),('C',10000,'verified'),('Z',0,'cleared'),('U',1000,'unknown'),('N',-100,'verified'))x(id,amount,verification);
  insert into public.ar_invoices(hotel,account_id,id,guest,invoice_no,folio_no,transaction_date,original,open,verification_state,collection_role,compressed,parent_invoice_no,parent_invoice_id,parent_open,synced_at)
  values('KAT',scope,'CHILD','Synthetic child','INV-CHILD','FOL-CHILD',day-10,100,100,'verified','child',false,'INV-A','A',10000,clock_timestamp());
  insert into public.ar_invoices(hotel,account_id,id,guest,invoice_no,folio_no,transaction_date,original,open,verification_state,collection_role,compressed,synced_at)
  values('TSK',scope,'TSKONLY','Synthetic other hotel','INV-TSK','FOL-TSK',day-10,100,100,'verified','standalone',false,clock_timestamp());
  input:=jsonb_build_object('commandId',cmd,'revision',0,'confirmed',true,'hotel','KAT','accountId',scope,'receivedDate',day,'reference','Synthetic notice 1','sourceNote','Synthetic test only','notes','No customer data','reportedAmount','30000.00','lines','[{"invoiceId":"A","reportedAmount":null},{"invoiceId":"B","reportedAmount":null},{"invoiceId":"C","reportedAmount":null}]'::jsonb,'changeReason','');
  filters:=jsonb_build_object('view','pending','hotel','KAT','accountId',scope,'offset',0,'limit',50);
  r:=public.ar_remittance_save(gen_random_uuid(),rid,input);if r->>'error' is distinct from 'remittance_forbidden' then raise exception 'remittance diagnostic owner guard';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,input);if r->>'revision' is distinct from '1' or r->>'reportedAmount' is distinct from '30000.00' or r->>'invoiceCount' is distinct from '3' or r->>'allocatedAmount' is distinct from '0.00' or r->>'linkedOpen' is distinct from '30000.00' then raise exception 'remittance diagnostic create: %',r->>'error';end if;checks:=checks+1;
  if exists(select 1 from jsonb_array_elements(r->'lines') l where l->'reportedAmount' is distinct from 'null'::jsonb) then raise exception 'remittance diagnostic fabricated allocation';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,input);if r->>'revision' is distinct from '1' or (select count(*) from public.ar_remittances where account_id=scope)<>1 then raise exception 'remittance diagnostic duplicate command';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,jsonb_set(input,'{reportedAmount}','"35000.00"'));if r->>'error' is distinct from 'remittance_command_conflict' then raise exception 'remittance diagnostic changed command';end if;checks:=checks+1;
  r:=public.ar_remittance_command_get(p_actor,cmd);if r->>'complete' is distinct from 'true' or r->>'recordId' is distinct from rid::text then raise exception 'remittance diagnostic receipt';end if;checks:=checks+1;
  r:=public.ar_remittance_list(p_actor,filters);if r->'summary'->>'documents' is distinct from '1' or r->'summary'->>'invoices' is distinct from '3' or r->'summary'->>'reportedAmount' is distinct from '30000.00' then raise exception 'remittance diagnostic triple count';end if;checks:=checks+1;
  second_input:=input||jsonb_build_object('commandId',gen_random_uuid(),'reference','Synthetic notice 2','reportedAmount','5000.00','lines','[{"invoiceId":"A","reportedAmount":"5000.00"}]'::jsonb);
  r:=public.ar_remittance_save(p_actor,rid2,second_input);if r?'error' then raise exception 'remittance diagnostic overlapping notice';end if;
  r:=public.ar_remittance_list(p_actor,filters);if r->'summary'->>'documents' is distinct from '2' or r->'summary'->>'invoices' is distinct from '3' or r->'summary'->>'reportedAmount' is distinct from '35000.00' or r->'summary'->>'linkedOpen' is distinct from '30000.00' then raise exception 'remittance diagnostic overlapping open counted twice';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid3,input||jsonb_build_object('commandId',gen_random_uuid(),'reference','Synthetic unknown total','reportedAmount',null,'lines','[{"invoiceId":"Z","reportedAmount":null}]'::jsonb));
  if r->'reportedAmount' is distinct from 'null'::jsonb or r->>'resolution' is distinct from 'linked_zero' then raise exception 'remittance diagnostic verified zero or unknown amount';end if;checks:=checks+1;
  r:=public.ar_remittance_list(p_actor,filters||jsonb_build_object('view','activity','from',day,'to',day));if r->'summary'->>'documents' is distinct from '3' or r->'summary'->'reportedAmount' is distinct from 'null'::jsonb or r->'summary'->>'knownReportedAmount' is distinct from '35000.00' or r->'summary'->>'unspecifiedAmounts' is distinct from '1' then raise exception 'remittance diagnostic unknown total became zero';end if;checks:=checks+1;
  r:=public.ar_remittance_list(p_actor,filters||jsonb_build_object('view','activity','from',day-2,'to',day-1));if r->>'total' is distinct from '0' then raise exception 'remittance diagnostic received date filter';end if;checks:=checks+1;
  r:=public.ar_remittance_list(p_actor,filters||jsonb_build_object('from',day-2,'to',day-1));if r->>'total' is distinct from '2' then raise exception 'remittance diagnostic pending date incorrectly filtered';end if;checks:=checks+1;
  r:=public.ar_remittance_invoices(p_actor,'KAT',scope,'',0,2);if r->>'total' is distinct from '7' or jsonb_array_length(r->'rows')<>2 then raise exception 'remittance diagnostic invoice pagination';end if;checks:=checks+1;
  r:=public.ar_remittance_invoices(p_actor,'KAT',scope,'INV-CHILD',0,50);if r->'rows'->0->>'eligible' is distinct from 'false' then raise exception 'remittance diagnostic child allowed';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'lines','[{"invoiceId":"A","reportedAmount":null},{"invoiceId":"A","reportedAmount":null}]'::jsonb));if r->>'error' is distinct from 'remittance_invalid' then raise exception 'remittance diagnostic duplicate invoice';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'lines','[{"invoiceId":"A","reportedAmount":"40000.00"}]'::jsonb));if r->>'error' is distinct from 'remittance_allocation_overflow' then raise exception 'remittance diagnostic allocation overflow';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'receivedDate',day+1));if r->>'error' is distinct from 'remittance_future_received_date' then raise exception 'remittance diagnostic future date';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'lines','[{"invoiceId":"TSKONLY","reportedAmount":null}]'::jsonb));if r->>'error' is distinct from 'remittance_invoice_invalid' then raise exception 'remittance diagnostic cross hotel';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'lines','[{"invoiceId":"U","reportedAmount":null}]'::jsonb));if r->>'error' is distinct from 'remittance_invoice_invalid' then raise exception 'remittance diagnostic unverified new link';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,bad_rid,input||jsonb_build_object('commandId',gen_random_uuid(),'lines','[{"invoiceId":"CHILD","reportedAmount":null}]'::jsonb));if r->>'error' is distinct from 'remittance_invoice_invalid' then raise exception 'remittance diagnostic child new link';end if;checks:=checks+1;
  update public.ar_invoices set open=3000 where hotel='KAT' and account_id=scope and id='A';
  r:=public.ar_remittance_get(p_actor,rid);if r->>'reportedAmount' is distinct from '30000.00' or r->>'linkedOpen' is distinct from '23000.00' then raise exception 'remittance diagnostic inferred remaining reported cash';end if;checks:=checks+1;
  update public.ar_invoices set verification_state='missing' where hotel='KAT' and account_id=scope and id='B';
  r:=public.ar_remittance_list(p_actor,filters);if r->'summary'->'linkedOpen' is distinct from 'null'::jsonb or r->'summary'->>'knownLinkedOpen' is distinct from '13000.00' or r->'summary'->>'unverifiedInvoices' is distinct from '1' then raise exception 'remittance diagnostic missing source became zero';end if;checks:=checks+1;
  update public.ar_invoices set verification_state='verified' where hotel='KAT' and account_id=scope and id='B';
  delete from public.ar_invoices where hotel='KAT' and account_id=scope and id='C';
  r:=public.ar_remittance_get(p_actor,rid);if r->>'resolution' is distinct from 'needs_review' or not exists(select 1 from jsonb_array_elements(r->'lines') l where l->>'invoiceId'='C' and l->>'currentStatus'='missing' and l->>'invoiceNo'='INV-C') then raise exception 'remittance diagnostic lost historical identity';end if;checks:=checks+1;
  edit_input:=input||jsonb_build_object('commandId',gen_random_uuid(),'revision',1,'notes','Synthetic correction','changeReason','Correct recorded notice');
  r:=public.ar_remittance_save(p_actor,rid,edit_input||'{"changeReason":""}');if r->>'error' is distinct from 'remittance_change_reason_required' then raise exception 'remittance diagnostic correction reason';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,edit_input||'{"hotel":"TSK"}');if r->>'error' is distinct from 'remittance_scope_immutable' then raise exception 'remittance diagnostic moved scope';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,edit_input);if r->>'revision' is distinct from '2' or r->>'invoiceCount' is distinct from '3' then raise exception 'remittance diagnostic correcting old missing link';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,edit_input||jsonb_build_object('commandId',gen_random_uuid()));if r->>'error' is distinct from 'remittance_revision_conflict' then raise exception 'remittance diagnostic stale edit';end if;checks:=checks+1;
  update public.ar_accounts set type='SYNTHETIC_CHANGED' where hotel='KAT' and id=scope;
  r:=public.ar_remittance_get(p_actor,rid);if r->>'accountType' is distinct from 'SYNTHETIC_REMIT' then raise exception 'remittance diagnostic historical type changed';end if;checks:=checks+1;
  file:=jsonb_build_object('id',fid,'name','Synthetic-proof.pdf','mime','application/pdf','byteCount',100,'sha256',repeat('a',64),'inspection','{"version":1,"pages":1}'::jsonb);limits:='{"maxFileBytes":10485760,"maxFiles":50,"maxTotalFileBytes":104857600}';
  r:=public.ar_remittance_file_begin(p_actor,rid,2,file,limits);if r->'file'->>'state' is distinct from 'pending' or r->'file'->>'storageKey' is distinct from 'remittances/'||rid::text||'/'||fid::text then raise exception 'remittance diagnostic file reservation';end if;checks:=checks+1;
  r:=public.ar_remittance_save(p_actor,rid,edit_input||jsonb_build_object('commandId',gen_random_uuid(),'revision',2));if r->>'error' is distinct from 'remittance_pending_upload' then raise exception 'remittance diagnostic edit during upload';end if;checks:=checks+1;
  r:=public.ar_remittance_set_status(p_actor,rid,gen_random_uuid(),2,'voided','Synthetic void');if r->>'error' is distinct from 'remittance_pending_upload' then raise exception 'remittance diagnostic void during upload';end if;checks:=checks+1;
  r:=public.ar_remittance_file_begin(p_actor,rid,2,jsonb_set(file,'{sha256}',to_jsonb(repeat('b',64))),limits);if r->>'error' is distinct from 'remittance_file_conflict' then raise exception 'remittance diagnostic conflicting file';end if;checks:=checks+1;
  r:=public.ar_remittance_file_finish(p_actor,rid,fid,repeat('b',64));if r->>'error' is distinct from 'remittance_file_conflict' then raise exception 'remittance diagnostic wrong file digest';end if;checks:=checks+1;
  r:=public.ar_remittance_file_finish(p_actor,rid,fid,repeat('a',64));if r->>'revision' is distinct from '3' or r->>'pendingFiles' is distinct from '0' or r->>'fileCount' is distinct from '1' then raise exception 'remittance diagnostic file finish';end if;checks:=checks+1;
  r:=public.ar_remittance_file_finish(p_actor,rid,fid,repeat('a',64));if r->>'revision' is distinct from '3' then raise exception 'remittance diagnostic file finish duplicate';end if;checks:=checks+1;
  r:=public.ar_remittance_file_begin(p_actor,rid,0,file,limits);if r->'record'->>'revision' is distinct from '3' then raise exception 'remittance diagnostic exact upload retry';end if;checks:=checks+1;
  r:=public.ar_remittance_set_status(p_actor,rid,void_cmd,3,'voided','Synthetic duplicate notice');if r->>'revision' is distinct from '4' or r->>'resolution' is distinct from 'voided' then raise exception 'remittance diagnostic void';end if;checks:=checks+1;
  r:=public.ar_remittance_list(p_actor,filters||'{"view":"all","includeVoided":true}');if r->>'total' is distinct from '3' or r->'summary'->>'documents' is distinct from '2' or r->'summary'->>'knownReportedAmount' is distinct from '5000.00' then raise exception 'remittance diagnostic void inflated totals';end if;checks:=checks+1;
  r:=public.ar_remittance_set_status(p_actor,rid,gen_random_uuid(),4,'active','Synthetic restore');if r->>'revision' is distinct from '5' or r->>'state' is distinct from 'active' then raise exception 'remittance diagnostic restore';end if;checks:=checks+1;
  r:=public.ar_remittance_set_status(p_actor,rid,void_cmd,3,'voided','Synthetic duplicate notice');if r->>'revision' is distinct from '4' or public.ar_remittance_get(p_actor,rid)->>'revision' is distinct from '5' then raise exception 'remittance diagnostic replay changed newer record';end if;checks:=checks+1;
  r:=public.ar_remittance_file_status(p_actor,rid,fid,remove_cmd,5,false,'Synthetic removal',limits);if r->>'revision' is distinct from '6' or r->>'fileCount' is distinct from '0' then raise exception 'remittance diagnostic file removal';end if;checks:=checks+1;
  r:=public.ar_remittance_file_begin(p_actor,rid,6,jsonb_set(file,'{id}',to_jsonb(gen_random_uuid()::text)),jsonb_set(limits,'{maxTotalFileBytes}','100'));if r->>'error' is distinct from 'remittance_file_limit' then raise exception 'remittance diagnostic removed bytes escaped retained quota';end if;checks:=checks+1;
  r:=public.ar_remittance_file_status(p_actor,rid,fid,gen_random_uuid(),6,true,'Synthetic restore',jsonb_set(limits,'{maxFileBytes}','50'));if r->>'error' is distinct from 'remittance_file_limit' then raise exception 'remittance diagnostic restore budget';end if;checks:=checks+1;
  r:=public.ar_remittance_file_status(p_actor,rid,fid,gen_random_uuid(),6,true,'Synthetic restore',jsonb_set(limits,'{maxTotalFileBytes}','100'));if r->>'revision' is distinct from '7' or r->>'fileCount' is distinct from '1' then raise exception 'remittance diagnostic file restoration counted bytes twice';end if;checks:=checks+1;
  r:=public.ar_remittance_file_get(gen_random_uuid(),rid,fid);if r->>'error' is distinct from 'remittance_forbidden' then raise exception 'remittance diagnostic evidence owner';end if;checks:=checks+1;
  r:=public.ar_remittance_history(p_actor,rid,0,2);if r->>'total' is distinct from '7' or jsonb_array_length(r->'rows')<>2 then raise exception 'remittance diagnostic revision history';end if;checks:=checks+1;
  if exists(select 1 from public.ar_invoice_workflow where account_id=scope and (first_billing_date is not null or due_date is not null or last_reminder_stage is not null)) or exists(select 1 from public.ar_sent_events where account_id=scope) then raise exception 'remittance diagnostic mutated business workflow';end if;checks:=checks+1;
  -- Catch only this exact marker. Any failed assertion propagates and rolls back as an error.
  raise exception using errcode='ZR001',message='rollback synthetic remittance diagnostic';
 exception when sqlstate 'ZR001' then rolled_back:=true;
 end;
 if not rolled_back or exists(select 1 from public.ar_remittances where account_id=scope or id in(rid,rid2,rid3,bad_rid)) or exists(select 1 from public.ar_sent_events where account_id=scope) or exists(select 1 from public.ar_accounts where id=scope) or exists(select 1 from public.ar_invoice_workflow where account_id=scope) then raise exception 'remittance diagnostic rollback failed';end if;
 return jsonb_build_object('passed',true,'rolledBack',true,'checks',checks);
end $$;
revoke all on function public.ar_remittance_diagnostic_check(uuid) from public,anon,authenticated;
grant execute on function public.ar_remittance_diagnostic_check(uuid) to service_role;
