import {useRef,useState} from 'react';
import type {Session,SupabaseClient} from '@supabase/supabase-js';
export function PasswordRecovery({client,session,ready,onClose}:{client:SupabaseClient|null;session:Session|null;ready:boolean;onClose:()=>void}){
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[done,setDone]=useState(false);const locked=useRef(false);
 const approved=session?.user.email?.toLowerCase()==='ar@katathani.com'&&!!session.user.email_confirmed_at;
 async function requestLink(){if(!client||locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');try{const result=await client.auth.resetPasswordForEmail('ar@katathani.com',{redirectTo:location.origin+'/?recover=1'});if(result.error)throw Error();setNotice('If recovery is available for this account, a link has been sent to ar@katathani.com. Open it in this browser.');}catch{setError('The recovery email could not be requested. Wait a moment and try again, or use Google sign-in.');}finally{locked.current=false;setBusy(false);}}
 async function update(){if(!client||!approved||locked.current)return;if(password.length<12){setError('Use at least 12 characters for your web app password.');return;}if(password!==confirm){setError('The two passwords do not match.');return;}locked.current=true;setBusy(true);setError('');try{const result=await client.auth.updateUser({password});if(result.error)throw Error();setPassword('');setConfirm('');setDone(true);setNotice('Your web app password has been updated. Your Google account password is unchanged.');}catch{setError('The password could not be updated. Use a strong new password, or request a fresh recovery link.');}finally{locked.current=false;setBusy(false);}}
 return <section className="login-panel panel" aria-label="Web app password recovery"><h1>{done?'Password updated':'Reset your web app password'}</h1><p>This changes the password for Katathani AR. It does not change your Gmail or Google password.</p>{ready&&!client&&<p className="error-message" role="alert">Authentication service is unavailable. Please try again later.</p>}{!ready?<p role="status">Checking your recovery session…</p>:approved&&!done?<form onSubmit={e=>{e.preventDefault();void update();}}><label>New web app password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy}/></label><button className="primary-button" disabled={busy}>{busy?'Updating…':'Update web app password'}</button></form>:!done?<><p>A valid recovery link is needed before choosing a new password.</p><button className="primary-button" disabled={!client||busy} onClick={()=>void requestLink()}>{busy?'Requesting…':'Send recovery link'}</button><small>Open the link in the same browser where you requested it. Expired or already used links require a new request.</small></>:null}{error&&<p className="error-message" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button style={{marginTop:20}} disabled={busy} onClick={onClose}>{done?'Continue to workspace':'Back to sign in'}</button></section>;
}
