import type {RefreshEnv} from '../refresh/backend';
import {parseSettings} from './validation';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function input(request:Request){if(!request.headers.get('Content-Type')?.includes('application/json'))throw Error('settings_invalid');let size=0;const chunks:Uint8Array[]=[];const reader=request.body?.getReader();if(!reader)throw Error('settings_invalid');try{while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>65536){await reader.cancel();throw Error('settings_invalid');}chunks.push(p.value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length;}return JSON.parse(new TextDecoder().decode(bytes));}
async function rpc(env:RefreshEnv,name:string,args:unknown){if(!env.SUPABASE_URL||!env.SUPABASE_SECRET_KEY)throw Error('settings_unavailable');const r=await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(args),redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok){await r.body?.cancel();throw Error('settings_unavailable');}const v:unknown=await r.json();if(!v||typeof v!=='object'||Array.isArray(v))throw Error('settings_unavailable');return v as Record<string,unknown>;}
export async function settingsApi(request:Request,env:RefreshEnv,actor:string){try{
 const u=new URL(request.url),parts=u.pathname.split('/');const hotel=decodeURIComponent(parts[3]??''),accountId=decodeURIComponent(parts[4]??'');if(!['KAT','TSK'].includes(hotel)||!accountId||accountId.length>200)return json({error:'settings_invalid'},400);
 if(!['GET','PUT'].includes(request.method))return json({error:'method_not_allowed'},405);
 if(request.method==='PUT'&&request.headers.get('Origin')&&request.headers.get('Origin')!==u.origin)return json({error:'forbidden'},403);
 let result;if(parts[2]==='account-settings'&&parts.length===5){
  if(request.method==='GET')result=await rpc(env,'ar_settings_get',{p_hotel:hotel,p_account_id:accountId});
  else{const v=parseSettings(await input(request));result=await rpc(env,'ar_settings_save_v2',{p_actor:actor,p_hotel:hotel,p_account_id:accountId,p_revision:v.revision,p_billing_required:v.billingRequired,p_credit_term:v.creditTerm,p_billing_recipients:v.billingRecipients,p_collection_recipients:v.collectionRecipients,p_delivery:Object.fromEntries(['billingMethod','billingPortal','billingInstructions','collectionInstructions'].filter(k=>k in v).map(k=>[k,v[k as keyof typeof v]]))});}
 }else if(parts[2]==='invoice-history'&&parts.length===6&&request.method==='PUT'){
  const v=await input(request),invoiceId=decodeURIComponent(parts[5]);const date=(d:unknown)=>d===null||typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d;
  if(!Number.isSafeInteger(v.revision)||v.revision<0||!date(v.firstBillingDate)||!date(v.lastReminderDate)||!(v.lastReminderStage===null||['Friendly','Follow 1','Follow 2','Follow 3','Final'].includes(v.lastReminderStage))||!invoiceId||invoiceId.length>200)return json({error:'history_invalid'},400);
  result=await rpc(env,'ar_workflow_history_save',{p_actor:actor,p_hotel:hotel,p_account_id:accountId,p_invoice_id:invoiceId,p_revision:v.revision,p_first_billing_date:v.firstBillingDate,p_stage:v.lastReminderStage,p_stage_date:v.lastReminderDate});
 }else return json({error:'not_found'},404);
 if(typeof result?.error==='string')return json(result,/conflict|pending/.test(result.error)?409:/forbidden/.test(result.error)?403:/missing/.test(result.error)?404:400);return json(result);
 }catch(e){const code=e instanceof Error&&e.message==='settings_invalid'?'settings_invalid':'settings_unavailable';return json({error:code},code==='settings_invalid'?400:503);}}
